openapi: 3.0.0
info:
  description: Get name and website-URL for airports by ICAO code. Covered airports are
    mostly in Germany.
  title: airportsapi
  version: v1
  x-apisguru-categories:
    - transport
  x-logo:
    url: https://user-images.githubusercontent.com/21603/37955263-098e5b38-31a0-11e8-96fd-5755b16341e3.png
  x-origin:
    - format: swagger
      url: https://airport-web.appspot.com/api/docs/swagger.json
      version: "2.0"
  x-providerName: airport-web.appspot.com
paths:
  "/airportsapi/v1/airports/{icao_code}":
    get:
      operationId: AirportApi_getAirport
      parameters:
        - in: path
          name: icao_code
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiEndpointsAirportResponse"
servers:
  - url: https://airport-web.appspot.com/_ah/api
components:
  securitySchemes:
    google_id_token:
      type: oauth2
      x-google-issuer: accounts.google.com
      x-google-jwks_uri: https://www.googleapis.com/oauth2/v1/certs
      flows:
        implicit:
          authorizationUrl: /
          scopes: {}
  schemas:
    ApiEndpointsAirportResponse:
      properties:
        ICAO:
          type: string
        last_update:
          type: string
        name:
          type: string
        url:
          type: string
      type: object
