openapi: 3.0.0
info:
  version: 2018-02-27
  x-release: v4
  title: AWS Performance Insights
  description: <p>AWS Performance Insights enables you to monitor and explore different
    dimensions of database load based on data captured from a running RDS
    instance. The guide provides detailed information about Performance Insights
    data types, parameters and errors. For more information about Performance
    Insights capabilities see <a
    href="http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_PerfInsights.html">Using
    Amazon RDS Performance Insights </a> in the <i>Amazon RDS User
    Guide</i>.</p> <p> The AWS Performance Insights API provides visibility into
    the performance of your RDS instance, when Performance Insights is enabled
    for supported engine types. While Amazon CloudWatch provides the
    authoritative source for AWS service vended monitoring metrics, AWS
    Performance Insights offers a domain-specific view of database load measured
    as Average Active Sessions and provided to API consumers as a 2-dimensional
    time-series dataset. The time dimension of the data provides DB load data
    for each time point in the queried time range, and each time point
    decomposes overall load in relation to the requested dimensions, such as
    SQL, Wait-event, User or Host, measured at that time point.</p>
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: "#FFFFFF"
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: pi
  x-origin:
    - contentType: application/json
      url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/pi-2018-02-27.normal.json
      converter:
        url: https://github.com/mermade/aws2openapi
        version: 1.0.0
      x-apisguru-direct: true
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
    - cloud
  x-preferred: true
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/pi/
x-hasEquivalentPaths: true
security:
  - hmac: []
paths:
  /#X-Amz-Target=PerformanceInsightsv20180227.DescribeDimensionKeys:
    post:
      operationId: DescribeDimensionKeys
      description: For a specific time period, retrieve the top <code>N</code> dimension
        keys for a metric.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DescribeDimensionKeysResponse"
        "480":
          description: InvalidArgumentException
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InvalidArgumentException"
        "481":
          description: InternalServiceError
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServiceError"
        "482":
          description: NotAuthorizedException
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotAuthorizedException"
      parameters:
        - name: X-Amz-Target
          in: header
          required: true
          schema:
            type: string
            enum:
              - PerformanceInsightsv20180227.DescribeDimensionKeys
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DescribeDimensionKeysRequest"
        required: true
    parameters:
      - $ref: "#/components/parameters/X-Amz-Content-Sha256"
      - $ref: "#/components/parameters/X-Amz-Date"
      - $ref: "#/components/parameters/X-Amz-Algorithm"
      - $ref: "#/components/parameters/X-Amz-Credential"
      - $ref: "#/components/parameters/X-Amz-Security-Token"
      - $ref: "#/components/parameters/X-Amz-Signature"
      - $ref: "#/components/parameters/X-Amz-SignedHeaders"
  /#X-Amz-Target=PerformanceInsightsv20180227.GetResourceMetrics:
    post:
      operationId: GetResourceMetrics
      description: Retrieve Performance Insights metrics for a set of data sources, over a
        time period. You can provide specific dimension groups and dimensions,
        and provide aggregation and filtering criteria for each group.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetResourceMetricsResponse"
        "480":
          description: InvalidArgumentException
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InvalidArgumentException"
        "481":
          description: InternalServiceError
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServiceError"
        "482":
          description: NotAuthorizedException
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotAuthorizedException"
      parameters:
        - name: X-Amz-Target
          in: header
          required: true
          schema:
            type: string
            enum:
              - PerformanceInsightsv20180227.GetResourceMetrics
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetResourceMetricsRequest"
        required: true
    parameters:
      - $ref: "#/components/parameters/X-Amz-Content-Sha256"
      - $ref: "#/components/parameters/X-Amz-Date"
      - $ref: "#/components/parameters/X-Amz-Algorithm"
      - $ref: "#/components/parameters/X-Amz-Credential"
      - $ref: "#/components/parameters/X-Amz-Security-Token"
      - $ref: "#/components/parameters/X-Amz-Signature"
      - $ref: "#/components/parameters/X-Amz-SignedHeaders"
servers:
  - url: http://pi.{region}.amazonaws.com
    variables:
      region:
        description: The AWS region
        enum:
          - us-east-1
          - us-east-2
          - us-west-1
          - us-west-2
          - us-gov-west-1
          - us-gov-east-1
          - ca-central-1
          - eu-north-1
          - eu-west-1
          - eu-west-2
          - eu-west-3
          - eu-central-1
          - ap-northeast-1
          - ap-northeast-2
          - ap-northeast-3
          - ap-southeast-1
          - ap-southeast-2
          - ap-south-1
          - sa-east-1
        default: us-east-1
    description: The AWS PI multi-region endpoint
  - url: https://pi.{region}.amazonaws.com
    variables:
      region:
        description: The AWS region
        enum:
          - us-east-1
          - us-east-2
          - us-west-1
          - us-west-2
          - us-gov-west-1
          - us-gov-east-1
          - ca-central-1
          - eu-north-1
          - eu-west-1
          - eu-west-2
          - eu-west-3
          - eu-central-1
          - ap-northeast-1
          - ap-northeast-2
          - ap-northeast-3
          - ap-southeast-1
          - ap-southeast-2
          - ap-south-1
          - sa-east-1
        default: us-east-1
    description: The AWS PI multi-region endpoint
  - url: http://pi.{region}.amazonaws.com.cn
    variables:
      region:
        description: The AWS region
        enum:
          - cn-north-1
          - cn-northwest-1
        default: cn-north-1
    description: The AWS PI endpoint for China (Beijing) and China (Ningxia)
  - url: https://pi.{region}.amazonaws.com.cn
    variables:
      region:
        description: The AWS region
        enum:
          - cn-north-1
          - cn-northwest-1
        default: cn-north-1
    description: The AWS PI endpoint for China (Beijing) and China (Ningxia)
components:
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      required: false
      schema:
        type: string
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      required: false
      schema:
        type: string
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      required: false
      schema:
        type: string
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      required: false
      schema:
        type: string
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      required: false
      schema:
        type: string
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      required: false
      schema:
        type: string
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      required: false
      schema:
        type: string
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
  schemas:
    DescribeDimensionKeysResponse:
      type: object
      properties:
        AlignedStartTime:
          $ref: "#/components/schemas/ISOTimestamp"
        AlignedEndTime:
          $ref: "#/components/schemas/ISOTimestamp"
        PartitionKeys:
          $ref: "#/components/schemas/ResponsePartitionKeyList"
        Keys:
          $ref: "#/components/schemas/DimensionKeyDescriptionList"
        NextToken:
          $ref: "#/components/schemas/String"
    DescribeDimensionKeysRequest:
      type: object
      required:
        - ServiceType
        - Identifier
        - StartTime
        - EndTime
        - Metric
        - GroupBy
      properties:
        ServiceType:
          $ref: "#/components/schemas/ServiceType"
        Identifier:
          $ref: "#/components/schemas/String"
        StartTime:
          $ref: "#/components/schemas/ISOTimestamp"
        EndTime:
          $ref: "#/components/schemas/ISOTimestamp"
        Metric:
          $ref: "#/components/schemas/String"
        PeriodInSeconds:
          $ref: "#/components/schemas/Integer"
        GroupBy:
          $ref: "#/components/schemas/DimensionGroup"
        PartitionBy:
          $ref: "#/components/schemas/DimensionGroup"
        Filter:
          $ref: "#/components/schemas/MetricQueryFilterMap"
        MaxResults:
          $ref: "#/components/schemas/MaxResults"
        NextToken:
          $ref: "#/components/schemas/String"
    InvalidArgumentException:
      type: object
      properties:
        Message:
          $ref: "#/components/schemas/String"
      description: One of the arguments provided is invalid for this request.
    InternalServiceError:
      type: object
      properties:
        Message:
          $ref: "#/components/schemas/String"
      description: The request failed due to an unknown error.
    NotAuthorizedException:
      type: object
      properties:
        Message:
          $ref: "#/components/schemas/String"
      description: The user is not authorized to perform this request.
    GetResourceMetricsResponse:
      type: object
      properties:
        AlignedStartTime:
          $ref: "#/components/schemas/ISOTimestamp"
        AlignedEndTime:
          $ref: "#/components/schemas/ISOTimestamp"
        Identifier:
          $ref: "#/components/schemas/String"
        MetricList:
          $ref: "#/components/schemas/MetricKeyDataPointsList"
        NextToken:
          $ref: "#/components/schemas/String"
    GetResourceMetricsRequest:
      type: object
      required:
        - ServiceType
        - Identifier
        - MetricQueries
        - StartTime
        - EndTime
      properties:
        ServiceType:
          $ref: "#/components/schemas/ServiceType"
        Identifier:
          $ref: "#/components/schemas/String"
        MetricQueries:
          $ref: "#/components/schemas/MetricQueryList"
        StartTime:
          $ref: "#/components/schemas/ISOTimestamp"
        EndTime:
          $ref: "#/components/schemas/ISOTimestamp"
        PeriodInSeconds:
          $ref: "#/components/schemas/Integer"
        MaxResults:
          $ref: "#/components/schemas/MaxResults"
        NextToken:
          $ref: "#/components/schemas/String"
    ISOTimestamp:
      type: string
      format: date-time
    Double:
      type: number
      format: double
    DataPoint:
      type: object
      required:
        - Timestamp
        - Value
      properties:
        Timestamp:
          $ref: "#/components/schemas/ISOTimestamp"
        Value:
          $ref: "#/components/schemas/Double"
      description: A timestamp, and a single numerical value, which together represent a
        measurement at a particular point in time.
    DataPointsList:
      type: array
      items:
        $ref: "#/components/schemas/DataPoint"
    ServiceType:
      type: string
      enum:
        - RDS
    String:
      type: string
    Integer:
      type: integer
    DimensionGroup:
      type: object
      required:
        - Group
      properties:
        Group:
          $ref: "#/components/schemas/String"
        Dimensions:
          $ref: "#/components/schemas/StringList"
        Limit:
          $ref: "#/components/schemas/Limit"
      description: "A logical grouping of Performance Insights metrics for a related
        subject area. For example, the <code>db.sql</code> dimension group
        consists of the following dimensions: <code>db.sql.id</code>,
        <code>db.sql.db_id</code>, <code>db.sql.statement</code>, and
        <code>db.sql.tokenized_id</code>."
    MetricQueryFilterMap:
      type: object
      additionalProperties:
        $ref: "#/components/schemas/String"
    MaxResults:
      type: integer
      minimum: 0
      maximum: 20
    ResponsePartitionKeyList:
      type: array
      items:
        $ref: "#/components/schemas/ResponsePartitionKey"
    DimensionKeyDescriptionList:
      type: array
      items:
        $ref: "#/components/schemas/DimensionKeyDescription"
    StringList:
      type: array
      items:
        $ref: "#/components/schemas/String"
      minItems: 1
      maxItems: 10
    Limit:
      type: integer
      minimum: 1
      maximum: 10
    DimensionMap:
      type: object
      additionalProperties:
        $ref: "#/components/schemas/String"
    MetricValuesList:
      type: array
      items:
        $ref: "#/components/schemas/Double"
    DimensionKeyDescription:
      type: object
      properties:
        Dimensions:
          $ref: "#/components/schemas/DimensionMap"
        Total:
          $ref: "#/components/schemas/Double"
        Partitions:
          $ref: "#/components/schemas/MetricValuesList"
      description: An array of descriptions and aggregated values for each dimension within
        a dimension group.
    MetricQueryList:
      type: array
      items:
        $ref: "#/components/schemas/MetricQuery"
      minItems: 1
      maxItems: 15
    MetricKeyDataPointsList:
      type: array
      items:
        $ref: "#/components/schemas/MetricKeyDataPoints"
    ResponseResourceMetricKey:
      type: object
      required:
        - Metric
      properties:
        Metric:
          $ref: "#/components/schemas/String"
        Dimensions:
          $ref: "#/components/schemas/DimensionMap"
      description: An object describing a Performance Insights metric and one or more
        dimensions for that metric.
    MetricKeyDataPoints:
      type: object
      properties:
        Key:
          $ref: "#/components/schemas/ResponseResourceMetricKey"
        DataPoints:
          $ref: "#/components/schemas/DataPointsList"
      description: A time-ordered series of data points, correpsonding to a dimension of a
        Performance Insights metric.
    MetricQuery:
      type: object
      required:
        - Metric
      properties:
        Metric:
          $ref: "#/components/schemas/String"
        GroupBy:
          $ref: "#/components/schemas/DimensionGroup"
        Filter:
          $ref: "#/components/schemas/MetricQueryFilterMap"
      description: A single query to be processed. You must provide the metric to query. If
        no other parameters are specified, Performance Insights returns all of
        the data points for that metric. You can optionally request that the
        data points be aggregated by dimension group ( <code>GroupBy</code>),
        and return only those data points that match your criteria
        (<code>Filter</code>).
    ResponsePartitionKey:
      type: object
      required:
        - Dimensions
      properties:
        Dimensions:
          $ref: "#/components/schemas/DimensionMap"
      description: "If <code>PartitionBy</code> was specified in a
        <code>DescribeDimensionKeys</code> request, the dimensions are returned
        in an array. Each element in the array specifies one dimension. "
