openapi: 3.0.0
info:
  version: 2018-11-29
  x-release: v4
  title: AmazonApiGatewayManagementApi
  description: The Amazon API Gateway Management API allows you to directly manage runtime
    aspects of your deployed APIs. To use it, you must explicitly set the SDK's
    endpoint to point to the endpoint of your deployed API. The endpoint will be
    of the form https://{api-id}.execute-api.{region}.amazonaws.com/{stage}, or
    will be the endpoint corresponding to your API's custom domain and base
    path, if applicable.
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: "#FFFFFF"
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigatewaymanagementapi
  x-origin:
    - contentType: application/json
      url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigatewaymanagementapi-2018-11-29.normal.json
      converter:
        url: https://github.com/mermade/aws2openapi
        version: 1.0.0
      x-apisguru-direct: true
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
    - cloud
  x-preferred: true
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/execute-api/
security:
  - hmac: []
paths:
  "/@connections/{connectionId}":
    delete:
      operationId: DeleteConnection
      description: Delete the connection with the provided id.
      responses:
        "204":
          description: Success
        "480":
          description: GoneException
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GoneException"
        "481":
          description: LimitExceededException
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LimitExceededException"
        "482":
          description: ForbiddenException
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ForbiddenException"
      parameters:
        - name: connectionId
          in: path
          required: true
          description: ""
          schema:
            type: string
    parameters:
      - $ref: "#/components/parameters/X-Amz-Content-Sha256"
      - $ref: "#/components/parameters/X-Amz-Date"
      - $ref: "#/components/parameters/X-Amz-Algorithm"
      - $ref: "#/components/parameters/X-Amz-Credential"
      - $ref: "#/components/parameters/X-Amz-Security-Token"
      - $ref: "#/components/parameters/X-Amz-Signature"
      - $ref: "#/components/parameters/X-Amz-SignedHeaders"
    get:
      operationId: GetConnection
      description: Get information about the connection with the provided id.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetConnectionResponse"
        "480":
          description: GoneException
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GoneException"
        "481":
          description: LimitExceededException
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LimitExceededException"
        "482":
          description: ForbiddenException
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ForbiddenException"
      parameters:
        - name: connectionId
          in: path
          required: true
          description: ""
          schema:
            type: string
    post:
      operationId: PostToConnection
      description: Sends the provided data to the specified connection.
      responses:
        "200":
          description: Success
        "480":
          description: GoneException
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GoneException"
        "481":
          description: LimitExceededException
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LimitExceededException"
        "482":
          description: PayloadTooLargeException
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PayloadTooLargeException"
        "483":
          description: ForbiddenException
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ForbiddenException"
      parameters:
        - name: connectionId
          in: path
          required: true
          description: The identifier of the connection that a specific client is using.
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - Data
              properties:
                Data:
                  description: The data to be sent to the client specified by its
                    connection id.
                  type: string
                  maxLength: 131072
        required: true
servers:
  - url: http://execute-api.{region}.amazonaws.com
    variables:
      region:
        description: The AWS region
        enum:
          - us-east-1
          - us-east-2
          - us-west-1
          - us-west-2
          - us-gov-west-1
          - us-gov-east-1
          - ca-central-1
          - eu-north-1
          - eu-west-1
          - eu-west-2
          - eu-west-3
          - eu-central-1
          - ap-northeast-1
          - ap-northeast-2
          - ap-northeast-3
          - ap-southeast-1
          - ap-southeast-2
          - ap-south-1
          - sa-east-1
        default: us-east-1
    description: The AmazonApiGatewayManagementApi multi-region endpoint
  - url: https://execute-api.{region}.amazonaws.com
    variables:
      region:
        description: The AWS region
        enum:
          - us-east-1
          - us-east-2
          - us-west-1
          - us-west-2
          - us-gov-west-1
          - us-gov-east-1
          - ca-central-1
          - eu-north-1
          - eu-west-1
          - eu-west-2
          - eu-west-3
          - eu-central-1
          - ap-northeast-1
          - ap-northeast-2
          - ap-northeast-3
          - ap-southeast-1
          - ap-southeast-2
          - ap-south-1
          - sa-east-1
        default: us-east-1
    description: The AmazonApiGatewayManagementApi multi-region endpoint
  - url: http://execute-api.{region}.amazonaws.com.cn
    variables:
      region:
        description: The AWS region
        enum:
          - cn-north-1
          - cn-northwest-1
        default: cn-north-1
    description: The AmazonApiGatewayManagementApi endpoint for China (Beijing) and China
      (Ningxia)
  - url: https://execute-api.{region}.amazonaws.com.cn
    variables:
      region:
        description: The AWS region
        enum:
          - cn-north-1
          - cn-northwest-1
        default: cn-north-1
    description: The AmazonApiGatewayManagementApi endpoint for China (Beijing) and China
      (Ningxia)
components:
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      required: false
      schema:
        type: string
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      required: false
      schema:
        type: string
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      required: false
      schema:
        type: string
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      required: false
      schema:
        type: string
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      required: false
      schema:
        type: string
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      required: false
      schema:
        type: string
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      required: false
      schema:
        type: string
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
  schemas:
    GoneException: {}
    LimitExceededException: {}
    ForbiddenException: {}
    GetConnectionResponse:
      type: object
      properties:
        ConnectedAt:
          $ref: "#/components/schemas/__timestampIso8601"
        Identity:
          $ref: "#/components/schemas/Identity"
        LastActiveAt:
          $ref: "#/components/schemas/__timestampIso8601"
    PayloadTooLargeException: {}
    Data:
      type: string
      description: The data to be sent to the client specified by its connection id.
      maxLength: 131072
    __string:
      type: string
    DeleteConnectionRequest:
      type: object
      properties: {}
    GetConnectionRequest:
      type: object
      properties: {}
    __timestampIso8601:
      type: string
      format: date-time
    Identity:
      type: object
      required:
        - SourceIp
        - UserAgent
      properties:
        SourceIp:
          $ref: "#/components/schemas/__string"
        UserAgent:
          $ref: "#/components/schemas/__string"
    PostToConnectionRequest:
      type: object
      required:
        - Data
      properties:
        Data:
          $ref: "#/components/schemas/Data"
