openapi: 3.0.0
info:
  version: 2017-05-13
  x-release: v4
  title: Amazon SageMaker Runtime
  description: " The Amazon SageMaker runtime API. "
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: "#FFFFFF"
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: runtime.sagemaker
  x-origin:
    - contentType: application/json
      url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/runtime.sagemaker-2017-05-13.normal.json
      converter:
        url: https://github.com/mermade/aws2openapi
        version: 1.0.0
      x-apisguru-direct: true
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
    - cloud
  x-preferred: true
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/sagemaker/
security:
  - hmac: []
paths:
  "/endpoints/{EndpointName}/invocations":
    post:
      operationId: InvokeEndpoint
      description: <p>After you deploy a model into production using Amazon SageMaker
        hosting services, your client applications use this API to get
        inferences from the model hosted at the specified endpoint. </p> <p>For
        an overview of Amazon SageMaker, see <a
        href="http://docs.aws.amazon.com/sagemaker/latest/dg/how-it-works.html">How
        It Works</a>. </p> <p>Amazon SageMaker strips all POST headers except
        those supported by the API. Amazon SageMaker might add additional
        headers. You should not rely on the behavior of headers outside those
        enumerated in the request syntax. </p> <p>Cals to
        <code>InvokeEndpoint</code> are authenticated by using AWS Signature
        Version 4. For information, see <a
        href="http://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html">Authenticating
        Requests (AWS Signature Version 4)</a> in the <i>Amazon S3 API
        Reference</i>.</p> <note> <p>Endpoints are scoped to an individual
        account, and are not public. The URL does not contain the account ID,
        but Amazon SageMaker determines the account ID from the authentication
        token that is supplied by the caller.</p> </note>
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InvokeEndpointOutput"
        "480":
          description: InternalFailure
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalFailure"
        "481":
          description: ServiceUnavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServiceUnavailable"
        "482":
          description: ValidationError
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationError"
        "483":
          description: ModelError
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ModelError"
      parameters:
        - name: EndpointName
          in: path
          required: true
          description: 'The name of the endpoint that you specified when you created the
            endpoint using the <a
            href="http://docs.aws.amazon.com/sagemaker/latest/dg/API_CreateEndpoint.html">CreateEndpoint</a>
            API. '
          schema:
            type: string
            maxLength: 63
            pattern: ^[a-zA-Z0-9](-*[a-zA-Z0-9])*
        - name: Content-Type
          in: header
          required: false
          description: The MIME type of the input data in the request body.
          schema:
            type: string
            maxLength: 1024
        - name: Accept
          in: header
          required: false
          description: The desired MIME type of the inference in the response.
          schema:
            type: string
            maxLength: 1024
        - name: X-Amzn-SageMaker-Custom-Attributes
          in: header
          required: false
          description: <p/>
          schema:
            type: string
            format: password
            maxLength: 1024
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - Body
              properties:
                Body:
                  description: <p>Provides input data, in the format specified in the
                    <code>ContentType</code> request header. Amazon SageMaker
                    passes all of the data in the body to the model. </p> <p>For
                    information about the format of the request body, see <a
                    href="http://docs.aws.amazon.com/sagemaker/latest/dg/cdf-inference.html">Common
                    Data Formats—Inference</a>.</p>
                  type: string
                  maxLength: 5242880
                  format: password
        required: true
    parameters:
      - $ref: "#/components/parameters/X-Amz-Content-Sha256"
      - $ref: "#/components/parameters/X-Amz-Date"
      - $ref: "#/components/parameters/X-Amz-Algorithm"
      - $ref: "#/components/parameters/X-Amz-Credential"
      - $ref: "#/components/parameters/X-Amz-Security-Token"
      - $ref: "#/components/parameters/X-Amz-Signature"
      - $ref: "#/components/parameters/X-Amz-SignedHeaders"
servers:
  - url: http://runtime.sagemaker.{region}.amazonaws.com
    variables:
      region:
        description: The AWS region
        enum:
          - us-east-1
          - us-east-2
          - us-west-1
          - us-west-2
          - us-gov-west-1
          - us-gov-east-1
          - ca-central-1
          - eu-north-1
          - eu-west-1
          - eu-west-2
          - eu-west-3
          - eu-central-1
          - ap-northeast-1
          - ap-northeast-2
          - ap-northeast-3
          - ap-southeast-1
          - ap-southeast-2
          - ap-south-1
          - sa-east-1
        default: us-east-1
    description: The Amazon SageMaker Runtime multi-region endpoint
  - url: https://runtime.sagemaker.{region}.amazonaws.com
    variables:
      region:
        description: The AWS region
        enum:
          - us-east-1
          - us-east-2
          - us-west-1
          - us-west-2
          - us-gov-west-1
          - us-gov-east-1
          - ca-central-1
          - eu-north-1
          - eu-west-1
          - eu-west-2
          - eu-west-3
          - eu-central-1
          - ap-northeast-1
          - ap-northeast-2
          - ap-northeast-3
          - ap-southeast-1
          - ap-southeast-2
          - ap-south-1
          - sa-east-1
        default: us-east-1
    description: The Amazon SageMaker Runtime multi-region endpoint
  - url: http://runtime.sagemaker.{region}.amazonaws.com.cn
    variables:
      region:
        description: The AWS region
        enum:
          - cn-north-1
          - cn-northwest-1
        default: cn-north-1
    description: The Amazon SageMaker Runtime endpoint for China (Beijing) and China
      (Ningxia)
  - url: https://runtime.sagemaker.{region}.amazonaws.com.cn
    variables:
      region:
        description: The AWS region
        enum:
          - cn-north-1
          - cn-northwest-1
        default: cn-north-1
    description: The Amazon SageMaker Runtime endpoint for China (Beijing) and China
      (Ningxia)
components:
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      required: false
      schema:
        type: string
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      required: false
      schema:
        type: string
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      required: false
      schema:
        type: string
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      required: false
      schema:
        type: string
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      required: false
      schema:
        type: string
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      required: false
      schema:
        type: string
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      required: false
      schema:
        type: string
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
  schemas:
    InvokeEndpointOutput:
      type: object
      required:
        - Body
      properties:
        Body:
          $ref: "#/components/schemas/BodyBlob"
    InternalFailure: {}
    ServiceUnavailable: {}
    ValidationError: {}
    ModelError: {}
    BodyBlob:
      type: string
      maxLength: 5242880
      format: password
    CustomAttributesHeader:
      type: string
      maxLength: 1024
      format: password
    EndpointName:
      type: string
      pattern: ^[a-zA-Z0-9](-*[a-zA-Z0-9])*
      maxLength: 63
    Header:
      type: string
      maxLength: 1024
    InvokeEndpointInput:
      type: object
      required:
        - Body
      properties:
        Body:
          $ref: "#/components/schemas/BodyBlob"
