openapi: 3.0.0
info:
  version: 2017-01-06
  x-release: v4
  title: AWS Cost and Usage Report Service
  description: <p>The AWS Cost and Usage Report API enables you to programmatically create,
    query, and delete AWS Cost and Usage report definitions.</p> <p>AWS Cost and
    Usage reports track the monthly AWS costs and usage associated with your AWS
    account. The report contains line items for each unique combination of AWS
    product, usage type, and operation that your AWS account uses. You can
    configure the AWS Cost and Usage report to show only the data that you want,
    using the AWS Cost and Usage API.</p> <p>Service Endpoint</p> <p>The AWS
    Cost and Usage Report API provides the following endpoint:</p> <ul> <li>
    <p>cur.us-east-1.amazonaws.com</p> </li> </ul>
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: "#FFFFFF"
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: cur
  x-origin:
    - contentType: application/json
      url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/cur-2017-01-06.normal.json
      converter:
        url: https://github.com/mermade/aws2openapi
        version: 1.0.0
      x-apisguru-direct: true
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
    - cloud
  x-preferred: true
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/cur/
x-hasEquivalentPaths: true
security:
  - hmac: []
paths:
  /#X-Amz-Target=AWSOrigamiServiceGatewayService.DeleteReportDefinition:
    post:
      operationId: DeleteReportDefinition
      description: Deletes the specified report.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeleteReportDefinitionResponse"
        "480":
          description: InternalErrorException
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalErrorException"
        "481":
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationException"
      parameters:
        - name: X-Amz-Target
          in: header
          required: true
          schema:
            type: string
            enum:
              - AWSOrigamiServiceGatewayService.DeleteReportDefinition
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeleteReportDefinitionRequest"
        required: true
    parameters:
      - $ref: "#/components/parameters/X-Amz-Content-Sha256"
      - $ref: "#/components/parameters/X-Amz-Date"
      - $ref: "#/components/parameters/X-Amz-Algorithm"
      - $ref: "#/components/parameters/X-Amz-Credential"
      - $ref: "#/components/parameters/X-Amz-Security-Token"
      - $ref: "#/components/parameters/X-Amz-Signature"
      - $ref: "#/components/parameters/X-Amz-SignedHeaders"
  /#X-Amz-Target=AWSOrigamiServiceGatewayService.DescribeReportDefinitions:
    post:
      operationId: DescribeReportDefinitions
      description: Lists the AWS Cost and Usage reports available to this account.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DescribeReportDefinitionsResponse"
        "480":
          description: InternalErrorException
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalErrorException"
      parameters:
        - name: MaxResults
          in: query
          description: Pagination limit
          required: false
          schema:
            type: string
        - name: NextToken
          in: query
          description: Pagination token
          required: false
          schema:
            type: string
        - name: X-Amz-Target
          in: header
          required: true
          schema:
            type: string
            enum:
              - AWSOrigamiServiceGatewayService.DescribeReportDefinitions
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DescribeReportDefinitionsRequest"
        required: true
    parameters:
      - $ref: "#/components/parameters/X-Amz-Content-Sha256"
      - $ref: "#/components/parameters/X-Amz-Date"
      - $ref: "#/components/parameters/X-Amz-Algorithm"
      - $ref: "#/components/parameters/X-Amz-Credential"
      - $ref: "#/components/parameters/X-Amz-Security-Token"
      - $ref: "#/components/parameters/X-Amz-Signature"
      - $ref: "#/components/parameters/X-Amz-SignedHeaders"
  /#X-Amz-Target=AWSOrigamiServiceGatewayService.ModifyReportDefinition:
    post:
      operationId: ModifyReportDefinition
      description: Allows you to programatically update your report preferences.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ModifyReportDefinitionResponse"
        "480":
          description: InternalErrorException
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalErrorException"
        "481":
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationException"
      parameters:
        - name: X-Amz-Target
          in: header
          required: true
          schema:
            type: string
            enum:
              - AWSOrigamiServiceGatewayService.ModifyReportDefinition
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ModifyReportDefinitionRequest"
        required: true
    parameters:
      - $ref: "#/components/parameters/X-Amz-Content-Sha256"
      - $ref: "#/components/parameters/X-Amz-Date"
      - $ref: "#/components/parameters/X-Amz-Algorithm"
      - $ref: "#/components/parameters/X-Amz-Credential"
      - $ref: "#/components/parameters/X-Amz-Security-Token"
      - $ref: "#/components/parameters/X-Amz-Signature"
      - $ref: "#/components/parameters/X-Amz-SignedHeaders"
  /#X-Amz-Target=AWSOrigamiServiceGatewayService.PutReportDefinition:
    post:
      operationId: PutReportDefinition
      description: Creates a new report using the description that you provide.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PutReportDefinitionResponse"
        "480":
          description: DuplicateReportNameException
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DuplicateReportNameException"
        "481":
          description: ReportLimitReachedException
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReportLimitReachedException"
        "482":
          description: InternalErrorException
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalErrorException"
        "483":
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationException"
      parameters:
        - name: X-Amz-Target
          in: header
          required: true
          schema:
            type: string
            enum:
              - AWSOrigamiServiceGatewayService.PutReportDefinition
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PutReportDefinitionRequest"
        required: true
    parameters:
      - $ref: "#/components/parameters/X-Amz-Content-Sha256"
      - $ref: "#/components/parameters/X-Amz-Date"
      - $ref: "#/components/parameters/X-Amz-Algorithm"
      - $ref: "#/components/parameters/X-Amz-Credential"
      - $ref: "#/components/parameters/X-Amz-Security-Token"
      - $ref: "#/components/parameters/X-Amz-Signature"
      - $ref: "#/components/parameters/X-Amz-SignedHeaders"
servers:
  - url: http://cur.{region}.amazonaws.com
    variables:
      region:
        description: The AWS region
        enum:
          - us-east-1
          - us-east-2
          - us-west-1
          - us-west-2
          - us-gov-west-1
          - us-gov-east-1
          - ca-central-1
          - eu-north-1
          - eu-west-1
          - eu-west-2
          - eu-west-3
          - eu-central-1
          - ap-northeast-1
          - ap-northeast-2
          - ap-northeast-3
          - ap-southeast-1
          - ap-southeast-2
          - ap-south-1
          - sa-east-1
        default: us-east-1
    description: The AWS Cost and Usage Report Service multi-region endpoint
  - url: https://cur.{region}.amazonaws.com
    variables:
      region:
        description: The AWS region
        enum:
          - us-east-1
          - us-east-2
          - us-west-1
          - us-west-2
          - us-gov-west-1
          - us-gov-east-1
          - ca-central-1
          - eu-north-1
          - eu-west-1
          - eu-west-2
          - eu-west-3
          - eu-central-1
          - ap-northeast-1
          - ap-northeast-2
          - ap-northeast-3
          - ap-southeast-1
          - ap-southeast-2
          - ap-south-1
          - sa-east-1
        default: us-east-1
    description: The AWS Cost and Usage Report Service multi-region endpoint
  - url: http://cur.{region}.amazonaws.com.cn
    variables:
      region:
        description: The AWS region
        enum:
          - cn-north-1
          - cn-northwest-1
        default: cn-north-1
    description: The AWS Cost and Usage Report Service endpoint for China (Beijing) and
      China (Ningxia)
  - url: https://cur.{region}.amazonaws.com.cn
    variables:
      region:
        description: The AWS region
        enum:
          - cn-north-1
          - cn-northwest-1
        default: cn-north-1
    description: The AWS Cost and Usage Report Service endpoint for China (Beijing) and
      China (Ningxia)
components:
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      required: false
      schema:
        type: string
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      required: false
      schema:
        type: string
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      required: false
      schema:
        type: string
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      required: false
      schema:
        type: string
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      required: false
      schema:
        type: string
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      required: false
      schema:
        type: string
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      required: false
      schema:
        type: string
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
  schemas:
    DeleteReportDefinitionResponse:
      type: object
      properties:
        ResponseMessage:
          $ref: "#/components/schemas/DeleteResponseMessage"
      description: If the action is successful, the service sends back an HTTP 200 response.
    DeleteReportDefinitionRequest:
      type: object
      properties:
        ReportName:
          $ref: "#/components/schemas/ReportName"
      description: Deletes the specified report.
    InternalErrorException: {}
    ValidationException: {}
    DescribeReportDefinitionsResponse:
      type: object
      example:
        ReportDefinitions:
          - AdditionalArtifacts:
              - QUICKSIGHT
            AdditionalSchemaElements:
              - RESOURCES
            Compression: GZIP
            Format: textORcsv
            ReportName: ExampleReport
            S3Bucket: example-s3-bucket
            S3Prefix: exampleprefix
            S3Region: us-east-1
            TimeUnit: HOURLY
          - AdditionalArtifacts:
              - QUICKSIGHT
            AdditionalSchemaElements:
              - RESOURCES
            Compression: GZIP
            Format: textORcsv
            ReportName: ExampleReport2
            S3Bucket: example-s3-bucket
            S3Prefix: exampleprefix
            S3Region: us-east-1
            TimeUnit: HOURLY
      properties:
        ReportDefinitions:
          $ref: "#/components/schemas/ReportDefinitionList"
        NextToken:
          $ref: "#/components/schemas/GenericString"
      description: If the action is successful, the service sends back an HTTP 200 response.
    DescribeReportDefinitionsRequest:
      type: object
      properties:
        MaxResults:
          $ref: "#/components/schemas/MaxResults"
        NextToken:
          $ref: "#/components/schemas/GenericString"
      description: Requests a list of AWS Cost and Usage reports owned by the account.
    ModifyReportDefinitionResponse:
      type: object
      properties: {}
    ModifyReportDefinitionRequest:
      type: object
      required:
        - ReportName
        - ReportDefinition
      properties:
        ReportName:
          $ref: "#/components/schemas/ReportName"
        ReportDefinition:
          $ref: "#/components/schemas/ReportDefinition"
    PutReportDefinitionResponse:
      type: object
      properties: {}
      description: If the action is successful, the service sends back an HTTP 200 response
        with an empty HTTP body.
    PutReportDefinitionRequest:
      type: object
      required:
        - ReportDefinition
      properties:
        ReportDefinition:
          $ref: "#/components/schemas/ReportDefinition"
      description: Creates a Cost and Usage Report.
    DuplicateReportNameException: {}
    ReportLimitReachedException: {}
    AWSRegion:
      type: string
      enum:
        - us-east-1
        - us-west-1
        - us-west-2
        - eu-central-1
        - eu-west-1
        - ap-southeast-1
        - ap-southeast-2
        - ap-northeast-1
        - eu-north-1
        - ap-northeast-3
        - ap-east-1
      description: The region of the S3 bucket that AWS delivers the report into.
    AdditionalArtifact:
      type: string
      enum:
        - REDSHIFT
        - QUICKSIGHT
        - ATHENA
      description: The types of manifest that you want AWS to create for this report.
    AdditionalArtifactList:
      type: array
      description: A list of additional artifacts.
      items:
        $ref: "#/components/schemas/AdditionalArtifact"
    CompressionFormat:
      type: string
      enum:
        - ZIP
        - GZIP
        - Parquet
      description: The compression format that AWS uses for the report.
    ReportName:
      type: string
      pattern: "[0-9A-Za-z!\\-_.*\\'()]+"
      description: "The name of the report that you want to create. The name must be
        unique, is case sensitive, and can't include spaces. "
      maxLength: 256
    DeleteResponseMessage:
      type: string
      description: Whether the deletion was successful or not.
    MaxResults:
      type: integer
      description: The maximum number of results that AWS returns for the operation.
      minimum: 5
      maximum: 5
    GenericString:
      type: string
      description: A generic string.
    ReportDefinitionList:
      type: array
      description: A list of report definitions.
      items:
        $ref: "#/components/schemas/ReportDefinition"
    ReportDefinition:
      type: object
      required:
        - ReportName
        - TimeUnit
        - Format
        - Compression
        - AdditionalSchemaElements
        - S3Bucket
        - S3Prefix
        - S3Region
      properties:
        ReportName:
          $ref: "#/components/schemas/ReportName"
        TimeUnit:
          $ref: "#/components/schemas/TimeUnit"
        Format:
          $ref: "#/components/schemas/ReportFormat"
        Compression:
          $ref: "#/components/schemas/CompressionFormat"
        AdditionalSchemaElements:
          $ref: "#/components/schemas/SchemaElementList"
        S3Bucket:
          $ref: "#/components/schemas/S3Bucket"
        S3Prefix:
          $ref: "#/components/schemas/S3Prefix"
        S3Region:
          $ref: "#/components/schemas/AWSRegion"
        AdditionalArtifacts:
          $ref: "#/components/schemas/AdditionalArtifactList"
        RefreshClosedReports:
          $ref: "#/components/schemas/RefreshClosedReports"
        ReportVersioning:
          $ref: "#/components/schemas/ReportVersioning"
      description: "The definition of AWS Cost and Usage Report. You can specify the report
        name, time unit, report format, compression format, S3 bucket,
        additional artifacts, and schema elements in the definition. "
    RefreshClosedReports:
      type: boolean
    TimeUnit:
      type: string
      enum:
        - HOURLY
        - DAILY
      description: "The length of time covered by the report. "
    ReportFormat:
      type: string
      enum:
        - textORcsv
        - Parquet
      description: The format that AWS saves the report in.
    SchemaElementList:
      type: array
      description: A list of strings that indicate the content that is included in the
        report, such as service or usage type.
      items:
        $ref: "#/components/schemas/SchemaElement"
    S3Bucket:
      type: string
      description: The S3 bucket where AWS delivers the report.
      maxLength: 256
    S3Prefix:
      type: string
      pattern: "[0-9A-Za-z!\\-_.*\\'()/]*"
      description: The prefix that AWS adds to the report name when AWS delivers the
        report. Your prefix can't include spaces.
      maxLength: 256
    ReportVersioning:
      type: string
      enum:
        - CREATE_NEW_REPORT
        - OVERWRITE_REPORT
    SchemaElement:
      type: string
      enum:
        - RESOURCES
      description: "Whether or not AWS includes resource IDs in the report. "
