openapi: 3.0.0
info:
  version: 2018-06-26
  x-release: v4
  title: Amazon Forecast Query Service
  description: Provides APIs for creating and managing Amazon Forecast resources.
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: "#FFFFFF"
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: forecastquery
  x-origin:
    - contentType: application/json
      url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/forecastquery-2018-06-26.normal.json
      converter:
        url: https://github.com/mermade/aws2openapi
        version: 1.0.0
      x-apisguru-direct: true
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
    - cloud
  x-preferred: true
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/forecastquery/
security:
  - hmac: []
paths:
  /#X-Amz-Target=AmazonForecastRuntime.QueryForecast:
    post:
      operationId: QueryForecast
      description: <p>Retrieves a forecast filtered by the supplied criteria.</p> <p>The
        criteria is a key-value pair. The key is either <code>item_id</code> (or
        the equivalent non-timestamp, non-target field) from the
        <code>TARGET_TIME_SERIES</code> dataset, or one of the forecast
        dimensions specified as part of the <code>FeaturizationConfig</code>
        object.</p> <p>By default, the complete date range of the filtered
        forecast is returned. Optionally, you can request a specific date range
        within the forecast.</p> <note> <p>The forecasts generated by Amazon
        Forecast are in the same timezone as the dataset that was used to create
        the predictor.</p> </note>
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QueryForecastResponse"
        "480":
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResourceNotFoundException"
        "481":
          description: ResourceInUseException
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResourceInUseException"
        "482":
          description: InvalidInputException
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InvalidInputException"
        "483":
          description: LimitExceededException
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LimitExceededException"
        "484":
          description: InvalidNextTokenException
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InvalidNextTokenException"
      parameters:
        - name: X-Amz-Target
          in: header
          required: true
          schema:
            type: string
            enum:
              - AmazonForecastRuntime.QueryForecast
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/QueryForecastRequest"
        required: true
    parameters:
      - $ref: "#/components/parameters/X-Amz-Content-Sha256"
      - $ref: "#/components/parameters/X-Amz-Date"
      - $ref: "#/components/parameters/X-Amz-Algorithm"
      - $ref: "#/components/parameters/X-Amz-Credential"
      - $ref: "#/components/parameters/X-Amz-Security-Token"
      - $ref: "#/components/parameters/X-Amz-Signature"
      - $ref: "#/components/parameters/X-Amz-SignedHeaders"
servers:
  - url: http://forecastquery.{region}.amazonaws.com
    variables:
      region:
        description: The AWS region
        enum:
          - us-east-1
          - us-east-2
          - us-west-1
          - us-west-2
          - us-gov-west-1
          - us-gov-east-1
          - ca-central-1
          - eu-north-1
          - eu-west-1
          - eu-west-2
          - eu-west-3
          - eu-central-1
          - ap-northeast-1
          - ap-northeast-2
          - ap-northeast-3
          - ap-southeast-1
          - ap-southeast-2
          - ap-south-1
          - sa-east-1
        default: us-east-1
    description: The Amazon Forecast Query Service multi-region endpoint
  - url: https://forecastquery.{region}.amazonaws.com
    variables:
      region:
        description: The AWS region
        enum:
          - us-east-1
          - us-east-2
          - us-west-1
          - us-west-2
          - us-gov-west-1
          - us-gov-east-1
          - ca-central-1
          - eu-north-1
          - eu-west-1
          - eu-west-2
          - eu-west-3
          - eu-central-1
          - ap-northeast-1
          - ap-northeast-2
          - ap-northeast-3
          - ap-southeast-1
          - ap-southeast-2
          - ap-south-1
          - sa-east-1
        default: us-east-1
    description: The Amazon Forecast Query Service multi-region endpoint
  - url: http://forecastquery.{region}.amazonaws.com.cn
    variables:
      region:
        description: The AWS region
        enum:
          - cn-north-1
          - cn-northwest-1
        default: cn-north-1
    description: The Amazon Forecast Query Service endpoint for China (Beijing) and China
      (Ningxia)
  - url: https://forecastquery.{region}.amazonaws.com.cn
    variables:
      region:
        description: The AWS region
        enum:
          - cn-north-1
          - cn-northwest-1
        default: cn-north-1
    description: The Amazon Forecast Query Service endpoint for China (Beijing) and China
      (Ningxia)
components:
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      required: false
      schema:
        type: string
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      required: false
      schema:
        type: string
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      required: false
      schema:
        type: string
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      required: false
      schema:
        type: string
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      required: false
      schema:
        type: string
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      required: false
      schema:
        type: string
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      required: false
      schema:
        type: string
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
  schemas:
    QueryForecastResponse:
      type: object
      properties:
        Forecast:
          $ref: "#/components/schemas/Forecast"
    QueryForecastRequest:
      type: object
      required:
        - ForecastArn
        - Filters
      properties:
        ForecastArn:
          $ref: "#/components/schemas/Arn"
        StartDate:
          $ref: "#/components/schemas/DateTime"
        EndDate:
          $ref: "#/components/schemas/DateTime"
        Filters:
          $ref: "#/components/schemas/Filters"
        NextToken:
          $ref: "#/components/schemas/NextToken"
    ResourceNotFoundException: {}
    ResourceInUseException: {}
    InvalidInputException: {}
    LimitExceededException: {}
    InvalidNextTokenException: {}
    Arn:
      type: string
      pattern: arn:([a-z\d-]+):forecast:.*:.*:.+
      maxLength: 256
    AttributeName:
      type: string
      pattern: ^[a-zA-Z0-9\_\-]+$
      maxLength: 256
    AttributeValue:
      type: string
      maxLength: 256
    Timestamp:
      type: string
      pattern: ^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$
      maxLength: 20
    Double:
      type: number
      format: double
    DataPoint:
      type: object
      properties:
        Timestamp:
          $ref: "#/components/schemas/Timestamp"
        Value:
          $ref: "#/components/schemas/Double"
      description: The forecast value for a specific date. Part of the <a>Forecast</a>
        object.
    DateTime:
      type: string
      pattern: ^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$
      maxLength: 20
    Filters:
      type: object
      minProperties: 1
      maxProperties: 50
      additionalProperties:
        $ref: "#/components/schemas/AttributeValue"
    Predictions:
      type: object
      additionalProperties:
        $ref: "#/components/schemas/TimeSeries"
    Forecast:
      type: object
      properties:
        Predictions:
          $ref: "#/components/schemas/Predictions"
      description: Provides information about a forecast. Returned as part of the
        <a>QueryForecast</a> response.
    NextToken:
      type: string
      minLength: 1
      maxLength: 3000
    TimeSeries:
      type: array
      items:
        $ref: "#/components/schemas/DataPoint"
    Statistic:
      type: string
      maxLength: 4
