openapi: 3.0.0
info:
  version: 2018-05-22
  x-release: v4
  title: Amazon Personalize Runtime
  description: <p/>
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: "#FFFFFF"
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: personalize-runtime
  x-origin:
    - contentType: application/json
      url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/personalize-runtime-2018-05-22.normal.json
      converter:
        url: https://github.com/mermade/aws2openapi
        version: 1.0.0
      x-apisguru-direct: true
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
    - cloud
  x-preferred: true
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/personalize-runtime/
security:
  - hmac: []
paths:
  /personalize-ranking:
    post:
      operationId: GetPersonalizedRanking
      description: <p>Re-ranks a list of recommended items for the given user. The first
        item in the list is deemed the most likely item to be of interest to the
        user.</p> <note> <p>The solution backing the campaign must have been
        created using a recipe of type PERSONALIZED_RANKING.</p> </note>
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetPersonalizedRankingResponse"
        "480":
          description: InvalidInputException
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InvalidInputException"
        "481":
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResourceNotFoundException"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - campaignArn
                - inputList
                - userId
              properties:
                campaignArn:
                  description: The Amazon Resource Name (ARN) of the campaign to use for
                    generating the personalized ranking.
                  type: string
                  pattern: arn:([a-z\d-]+):personalize:.*:.*:.+
                  maxLength: 256
                inputList:
                  description: A list of items (itemId's) to rank. If an item was not
                    included in the training dataset, the item is appended to
                    the end of the reranked list.
                  type: array
                  items:
                    $ref: "#/components/schemas/ItemID"
                userId:
                  description: The user for which you want the campaign to provide a
                    personalized ranking.
                  type: string
                  maxLength: 256
        required: true
    parameters:
      - $ref: "#/components/parameters/X-Amz-Content-Sha256"
      - $ref: "#/components/parameters/X-Amz-Date"
      - $ref: "#/components/parameters/X-Amz-Algorithm"
      - $ref: "#/components/parameters/X-Amz-Credential"
      - $ref: "#/components/parameters/X-Amz-Security-Token"
      - $ref: "#/components/parameters/X-Amz-Signature"
      - $ref: "#/components/parameters/X-Amz-SignedHeaders"
  /recommendations:
    post:
      operationId: GetRecommendations
      description: <p>Returns a list of recommended items. The required input depends on
        the recipe type used to create the solution backing the campaign, as
        follows:</p> <ul> <li> <p>RELATED_ITEMS - <code>itemId</code> required,
        <code>userId</code> not used</p> </li> <li> <p>USER_PERSONALIZATION -
        <code>itemId</code> optional, <code>userId</code> required</p> </li>
        </ul> <note> <p>Campaigns that are backed by a solution created using a
        recipe of type PERSONALIZED_RANKING use the API.</p> </note>
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetRecommendationsResponse"
        "480":
          description: InvalidInputException
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InvalidInputException"
        "481":
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResourceNotFoundException"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - campaignArn
              properties:
                campaignArn:
                  description: The Amazon Resource Name (ARN) of the campaign to use for
                    getting recommendations.
                  type: string
                  pattern: arn:([a-z\d-]+):personalize:.*:.*:.+
                  maxLength: 256
                itemId:
                  description: <p>The item ID to provide recommendations for.</p>
                    <p>Required for <code>RELATED_ITEMS</code> recipe type.</p>
                  type: string
                  maxLength: 256
                userId:
                  description: <p>The user ID to provide recommendations for.</p>
                    <p>Required for <code>USER_PERSONALIZATION</code> recipe
                    type.</p>
                  type: string
                  maxLength: 256
                numResults:
                  description: The number of results to return. The default is 25. The
                    maximum is 100.
                  type: integer
                  minimum: 0
        required: true
    parameters:
      - $ref: "#/components/parameters/X-Amz-Content-Sha256"
      - $ref: "#/components/parameters/X-Amz-Date"
      - $ref: "#/components/parameters/X-Amz-Algorithm"
      - $ref: "#/components/parameters/X-Amz-Credential"
      - $ref: "#/components/parameters/X-Amz-Security-Token"
      - $ref: "#/components/parameters/X-Amz-Signature"
      - $ref: "#/components/parameters/X-Amz-SignedHeaders"
servers:
  - url: http://personalize-runtime.{region}.amazonaws.com
    variables:
      region:
        description: The AWS region
        enum:
          - us-east-1
          - us-east-2
          - us-west-1
          - us-west-2
          - us-gov-west-1
          - us-gov-east-1
          - ca-central-1
          - eu-north-1
          - eu-west-1
          - eu-west-2
          - eu-west-3
          - eu-central-1
          - ap-northeast-1
          - ap-northeast-2
          - ap-northeast-3
          - ap-southeast-1
          - ap-southeast-2
          - ap-south-1
          - sa-east-1
        default: us-east-1
    description: The Amazon Personalize Runtime multi-region endpoint
  - url: https://personalize-runtime.{region}.amazonaws.com
    variables:
      region:
        description: The AWS region
        enum:
          - us-east-1
          - us-east-2
          - us-west-1
          - us-west-2
          - us-gov-west-1
          - us-gov-east-1
          - ca-central-1
          - eu-north-1
          - eu-west-1
          - eu-west-2
          - eu-west-3
          - eu-central-1
          - ap-northeast-1
          - ap-northeast-2
          - ap-northeast-3
          - ap-southeast-1
          - ap-southeast-2
          - ap-south-1
          - sa-east-1
        default: us-east-1
    description: The Amazon Personalize Runtime multi-region endpoint
  - url: http://personalize-runtime.{region}.amazonaws.com.cn
    variables:
      region:
        description: The AWS region
        enum:
          - cn-north-1
          - cn-northwest-1
        default: cn-north-1
    description: The Amazon Personalize Runtime endpoint for China (Beijing) and China
      (Ningxia)
  - url: https://personalize-runtime.{region}.amazonaws.com.cn
    variables:
      region:
        description: The AWS region
        enum:
          - cn-north-1
          - cn-northwest-1
        default: cn-north-1
    description: The Amazon Personalize Runtime endpoint for China (Beijing) and China
      (Ningxia)
components:
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      required: false
      schema:
        type: string
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      required: false
      schema:
        type: string
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      required: false
      schema:
        type: string
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      required: false
      schema:
        type: string
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      required: false
      schema:
        type: string
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      required: false
      schema:
        type: string
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      required: false
      schema:
        type: string
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
  schemas:
    GetPersonalizedRankingResponse:
      type: object
      properties:
        personalizedRanking:
          $ref: "#/components/schemas/ItemList"
    ItemID:
      type: string
      maxLength: 256
    InvalidInputException: {}
    ResourceNotFoundException: {}
    GetRecommendationsResponse:
      type: object
      properties:
        itemList:
          $ref: "#/components/schemas/ItemList"
    Arn:
      type: string
      pattern: arn:([a-z\d-]+):personalize:.*:.*:.+
      maxLength: 256
    InputList:
      type: array
      items:
        $ref: "#/components/schemas/ItemID"
    UserID:
      type: string
      maxLength: 256
    GetPersonalizedRankingRequest:
      type: object
      required:
        - campaignArn
        - inputList
        - userId
      properties:
        campaignArn:
          $ref: "#/components/schemas/Arn"
        inputList:
          $ref: "#/components/schemas/InputList"
        userId:
          $ref: "#/components/schemas/UserID"
    ItemList:
      type: array
      items:
        $ref: "#/components/schemas/PredictedItem"
    NumResults:
      type: integer
      minimum: 0
    GetRecommendationsRequest:
      type: object
      required:
        - campaignArn
      properties:
        campaignArn:
          $ref: "#/components/schemas/Arn"
        itemId:
          $ref: "#/components/schemas/ItemID"
        userId:
          $ref: "#/components/schemas/UserID"
        numResults:
          $ref: "#/components/schemas/NumResults"
    PredictedItem:
      type: object
      properties:
        itemId:
          $ref: "#/components/schemas/ItemID"
      description: <p>An object that identifies an item.</p> <p>The and APIs return a list
        of <code>PredictedItem</code>s.</p>
