openapi: 3.0.0
info:
  contact:
    x-twitter: amentumspace
  description: >
    
    The World Magnetic Model calculates the intensity and direction of the Earth's magnetic field on a specific date-time, geodetic altitude, latitude, and longitude. It is relied upon throughout the world for navigation, mineral exploration, atmospheric and space science, and is installed on billions of devices.  <br><br>

    A comprehensive description of the World Magnetic Model, including its limitations, can be found <a href='https://www.ngdc.noaa.gov/geomag/WMM/back.shtml'>here</a>.  <br><br>

    We provide a RESTful API for free access to the out-of-cycle  Wolrd Magnetic Model (WMM2015v2) valid for years 2015.0 - 2020.0. <br><br>

    The Global Magnet API wraps the original WMM code which is available  <a href='https://www.ngdc.noaa.gov/geomag/WMM/soft.shtml'>here</a>.  <br><br>

    Amentum Pty Ltd is not responsible nor liable for any loss or damage of any sort incurred as the result of the use of the API. <br><br>

    The API is rate limited to 1000 calls per day. Contact <a href="mailto:team@amentum.space">team@amentum.space</a> to discuss high volume annd enterprise support options. <br><br>

    Copyright <a href='https://amentum.space'>Amentum Pty Ltd</a> 2019.
  title: Global Magnet API - calculate main components of the geomagnetic field at or
    near Earth's surface
  version: 1.0.1
  x-apisguru-categories:
    - location
  x-logo:
    url: https://twitter.com/amentumspace/profile_image?size=original
  x-origin:
    - format: swagger
      url: https://globalmagnet.amentum.space/api/swagger.json
      version: "2.0"
  x-providerName: amentum.space
  x-serviceName: global-magnet
paths:
  /calculate_magnetic_field:
    get:
      description: >
        <b>Declination (degrees)</b> - angle in the horizontal plane between
        magnetic north and true north. Declination is positive when magnetic
        north is east of true north. <br> <b>Magnetic inclination, or dip
        (degrees)</b>  - angle made between the horizontal plane and the
        magnetic field vector at some position. Positive inclination corresponds
        to a downward pointing  magnetic field. <br> <b>Geomagnetic Total
        Intensity (nano Teslas)</b>  <br> <b>GV - Geomagnetic grid variation
        (deg)</b>  referenced to grid north. Grid  north reference to 0 deg
        meridian of a polar stereographic projection. Only defined for latitudes
        greater than 55 degrees  and less than -55 degrees (arctic and
        antarctic). <br>
      operationId: app.api.endpoints.GeoMag.calculate_magnetic_field
      parameters:
        - $ref: "#/components/parameters/Altitude"
        - $ref: "#/components/parameters/Latitude"
        - $ref: "#/components/parameters/Longitude"
        - $ref: "#/components/parameters/Year"
      responses:
        "200":
          description: Successful magnetic field intensity calculation
          content:
            application/json:
              schema:
                properties:
                  declination:
                    properties:
                      data:
                        type: number
                      units:
                        type: string
                    type: object
                  grid_variation:
                    properties:
                      data:
                        type: number
                      units:
                        type: string
                    type: object
                  inclination:
                    properties:
                      data:
                        type: number
                      units:
                        type: string
                    type: object
                  total_intensity:
                    properties:
                      data:
                        type: number
                      units:
                        type: string
                    type: object
                type: object
      summary: >
        Calculates the declination, inclination, total intensity, and grid
        variation at a point.
      tags:
        - Click to view documentation for API endpoints
servers:
  - url: https://globalmagnet.amentum.space/api
components:
  parameters:
    Altitude:
      description: Geodetic Altitude 0 to 600 (km).
      in: query
      name: altitude
      required: true
      schema:
        type: number
    Latitude:
      description: Geodetic Latitude. -90 (S) to 90 (N).
      in: query
      name: latitude
      required: true
      schema:
        type: number
    Longitude:
      description: Geodetic Longitude. -180 (W) to 180 (E).
      in: query
      name: longitude
      required: true
      schema:
        type: number
    Year:
      description: Year as a decimal in the range 2015-2020 (2017.5 would be half way
        through 2017)
      in: query
      name: year
      required: true
      schema:
        type: number
