openapi: 3.0.0
info:
  contact:
    email: transform@apimatic.io
    name: API Transformer
    url: https://apimatic.io/transformer
  description: Transform API Descriptions from/to various formats
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: https://apimatic.io/transformer
  title: APIMATIC API Transformer
  version: "1.0"
  x-apisguru-categories:
    - developer_tools
    - tools
  x-logo:
    backgroundColor: "#2a313a"
    url: https://apimatic.io/img/theme/Convertron.svg
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Mermade/open_api_specifications/master/APIMATIC%20API%20Transformer/swagger.json
      version: "2.0"
  x-providerName: apimatic.io
  x-tags:
    - API
    - API descriptions
    - API definition
    - swagger
    - RAML
    - WADL
    - API blueprint
    - OpenAPI
  x-unofficialSpec: true
externalDocs:
  description: API Transformer Website
  url: https://apimatic.io/transformer
security: []
paths:
  /transform:
    post:
      description: >-
        Transform API Descriptions from/to various formats e.g., Swagger, API
        Blueprint, RAML, WADL, Google Discovery, I/O Docs.


        ### INPUTS

        * API Blueprint

        * Swagger 1.0 - 1.2

        * Swagger 2.0 JSON

        * Swagger 2.0 YAML

        * WADL - W3C 2009

        * Google Discovery

        * RAML 0.8

        * I/O Docs - Mashery

        * HAR 1.2

        * Postman Collection 1.0 - 2.0

        * APIMATIC Format

        * Mashape


        ### OUTPUTS

        * API Blueprint

        * Swagger 1.2

        * Swagger 2.0 JSON

        * Swagger 2.0 YAML

        * WADL - W3C 2009

        * RAML 0.8 - 1.0

        * APIMATIC Format
      operationId: ConvertAPI
      parameters:
        - in: query
          name: format
          required: true
          schema:
            type: string
            enum:
              - swagger10
              - swagger20
              - swaggeryaml
              - apiblueprint
              - wadl2009
              - raml
              - apimatic
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                url:
                  type: string
      responses:
        "200":
          description: The converted API specification
          content:
            application/json:
              schema:
                type: object
            application/x-yaml:
              schema:
                type: object
        "429":
          description: Rate-limit exceeded
      security: []
      summary: Transform API Descriptions from/to various formats
servers:
  - url: https://apimatic.io/api/transform
components:
  securitySchemes:
    api-key:
      in: query
      name: apikey
      type: apiKey
    basic:
      type: http
      scheme: basic
