openapi: 3.0.0
info:
  title: StreamAnalyticsManagementClient
  version: 2016-03-01
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/streamanalytics/resource-manager/Microsoft.StreamAnalytics/stable/2016-03-01/transformations.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: streamanalytics-transformations
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.StreamAnalytics/streamingjobs/{jobName}/transformations/{transformationName}":
    get:
      description: Gets details about the specified transformation.
      operationId: Transformations_Get
      parameters:
        - $ref: "#/components/parameters/ApiVersionParameter"
        - $ref: "#/components/parameters/SubscriptionIdParameter"
        - $ref: "#/components/parameters/ResourceGroupNameParameter"
        - $ref: "#/components/parameters/StreamingJobNameParameter"
        - $ref: "#/components/parameters/TransformationNameParameter"
      responses:
        "200":
          description: Successfully retrieved the specified transformation.
          headers:
            ETag:
              description: The current entity tag for the transformation. This is an opaque
                string. You can use it to detect whether the resource has
                changed between requests. You can also use it in the If-Match or
                If-None-Match headers for write operations for optimistic
                concurrency.
              schema:
                type: string
              example: be3cfaa2-3d02-4624-92d7-a26766306c8b
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transformation"
              examples:
                Get a transformation:
                  $ref: "#/components/examples/Get_a_transformation"
      tags:
        - Transformations
    patch:
      description: Updates an existing transformation under an existing streaming job. This
        can be used to partially update (ie. update one or two properties) a
        transformation without affecting the rest the job or transformation
        definition.
      operationId: Transformations_Update
      parameters:
        - description: The ETag of the transformation. Omit this value to always overwrite
            the current transformation. Specify the last-seen ETag value to
            prevent accidentally overwriting concurrent changes.
          in: header
          name: If-Match
          required: false
          x-ms-client-name: IfMatch
          schema:
            type: string
        - $ref: "#/components/parameters/ApiVersionParameter"
        - $ref: "#/components/parameters/SubscriptionIdParameter"
        - $ref: "#/components/parameters/ResourceGroupNameParameter"
        - $ref: "#/components/parameters/StreamingJobNameParameter"
        - $ref: "#/components/parameters/TransformationNameParameter"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Transformation"
        description: A Transformation object. The properties specified here will overwrite
          the corresponding properties in the existing transformation (ie. Those
          properties will be updated). Any properties that are set to null here
          will mean that the corresponding property in the existing
          transformation will remain the same and not change as a result of this
          PATCH operation.
        required: true
      responses:
        "200":
          description: The transformation was successfully updated.
          headers:
            ETag:
              description: The current entity tag for the transformation. This is an opaque
                string. You can use it to detect whether the resource has
                changed between requests. You can also use it in the If-Match or
                If-None-Match headers for write operations for optimistic
                concurrency.
              schema:
                type: string
              example: fc6f7a9b-3eea-4589-8265-cc854ec25f5a
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transformation"
              examples:
                Update a transformation:
                  $ref: "#/components/examples/Update_a_transformation"
      tags:
        - Transformations
    put:
      description: Creates a transformation or replaces an already existing transformation
        under an existing streaming job.
      operationId: Transformations_CreateOrReplace
      parameters:
        - description: The ETag of the transformation. Omit this value to always overwrite
            the current transformation. Specify the last-seen ETag value to
            prevent accidentally overwriting concurrent changes.
          in: header
          name: If-Match
          required: false
          x-ms-client-name: IfMatch
          schema:
            type: string
        - description: Set to '*' to allow a new transformation to be created, but to
            prevent updating an existing transformation. Other values will
            result in a 412 Pre-condition Failed response.
          in: header
          name: If-None-Match
          required: false
          x-ms-client-name: IfNoneMatch
          schema:
            type: string
        - $ref: "#/components/parameters/ApiVersionParameter"
        - $ref: "#/components/parameters/SubscriptionIdParameter"
        - $ref: "#/components/parameters/ResourceGroupNameParameter"
        - $ref: "#/components/parameters/StreamingJobNameParameter"
        - $ref: "#/components/parameters/TransformationNameParameter"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Transformation"
        description: The definition of the transformation that will be used to create a new
          transformation or replace the existing one under the streaming job.
        required: true
      responses:
        "200":
          description: The transformation was successfully created or replaced.
          headers:
            ETag:
              description: The current entity tag for the transformation. This is an opaque
                string. You can use it to detect whether the resource has
                changed between requests. You can also use it in the If-Match or
                If-None-Match headers for write operations for optimistic
                concurrency.
              schema:
                type: string
              example: be3cfaa2-3d02-4624-92d7-a26766306c8b
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transformation"
              examples:
                Create a transformation:
                  $ref: "#/components/examples/Create_a_transformation"
        "201":
          description: The transformation was successfully created or replaced.
          headers:
            ETag:
              description: The current entity tag for the transformation. This is an opaque
                string. You can use it to detect whether the resource has
                changed between requests. You can also use it in the If-Match or
                If-None-Match headers for write operations for optimistic
                concurrency.
              schema:
                type: string
              example: be3cfaa2-3d02-4624-92d7-a26766306c8b
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transformation"
              examples:
                Create a transformation:
                  $ref: "#/components/examples/Create_a_transformation"
      tags:
        - Transformations
servers:
  - url: https://management.azure.com
components:
  examples:
    Get_a_transformation:
      value:
        id: /subscriptions/56b5e0a9-b645-407d-99b0-c64f86013e3d/resourceGroups/sjrg4423/providers/Microsoft.StreamAnalytics/streamingjobs/sj8374/transformations/transformation952
        name: transformation952
        properties:
          query: Select Id, Name from inputtest
          streamingUnits: 6
        type: Microsoft.StreamAnalytics/streamingjobs/transformations
    Update_a_transformation:
      value:
        id: /subscriptions/56b5e0a9-b645-407d-99b0-c64f86013e3d/resourceGroups/sjrg4423/providers/Microsoft.StreamAnalytics/streamingjobs/sj8374/transformations/transformation952
        name: transformation952
        properties:
          query: New query
          streamingUnits: 6
        type: Microsoft.StreamAnalytics/streamingjobs/transformations
    Create_a_transformation:
      value:
        id: /subscriptions/56b5e0a9-b645-407d-99b0-c64f86013e3d/resourceGroups/sjrg4423/providers/Microsoft.StreamAnalytics/streamingjobs/sj8374/transformations/transformation952
        name: transformation952
        properties:
          query: Select Id, Name from inputtest
          streamingUnits: 6
        type: Microsoft.StreamAnalytics/streamingjobs/transformations
  parameters:
    ApiVersionParameter:
      description: Client Api Version.
      in: query
      name: api-version
      required: true
      schema:
        type: string
      examples:
        Get a transformation:
          value: 2016-03-01
        Update a transformation:
          value: 2016-03-01
        Create a transformation:
          value: 2016-03-01
    ResourceGroupNameParameter:
      description: The name of the resource group that contains the resource. You can
        obtain this value from the Azure Resource Manager API or the portal.
      in: path
      name: resourceGroupName
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
      examples:
        Get a transformation:
          value: sjrg4423
        Update a transformation:
          value: sjrg4423
        Create a transformation:
          value: sjrg4423
    StreamingJobNameParameter:
      description: The name of the streaming job.
      in: path
      name: jobName
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
      examples:
        Get a transformation:
          value: sj8374
        Update a transformation:
          value: sj8374
        Create a transformation:
          value: sj8374
    SubscriptionIdParameter:
      description: GUID which uniquely identify Microsoft Azure subscription. The
        subscription ID forms part of the URI for every service call.
      in: path
      name: subscriptionId
      required: true
      schema:
        type: string
      examples:
        Get a transformation:
          value: 56b5e0a9-b645-407d-99b0-c64f86013e3d
        Update a transformation:
          value: 56b5e0a9-b645-407d-99b0-c64f86013e3d
        Create a transformation:
          value: 56b5e0a9-b645-407d-99b0-c64f86013e3d
    TransformationNameParameter:
      description: The name of the transformation.
      in: path
      name: transformationName
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
      examples:
        Get a transformation:
          value: transformation952
        Update a transformation:
          value: transformation952
        Create a transformation:
          value: transformation952
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    SubResource:
      description: The base sub-resource model definition.
      properties:
        id:
          description: Resource Id
          readOnly: true
          type: string
        name:
          description: Resource name
          type: string
        type:
          description: Resource type
          readOnly: true
          type: string
      x-ms-azure-resource: true
    Transformation:
      allOf:
        - $ref: "#/components/schemas/SubResource"
      description: A transformation object, containing all information associated with the
        named transformation. All transformations are contained under a
        streaming job.
      properties:
        properties:
          $ref: "#/components/schemas/TransformationProperties"
    TransformationProperties:
      description: The properties that are associated with a transformation.
      properties:
        etag:
          description: The current entity tag for the transformation. This is an opaque
            string. You can use it to detect whether the resource has changed
            between requests. You can also use it in the If-Match or
            If-None-Match headers for write operations for optimistic
            concurrency.
          readOnly: true
          type: string
        query:
          description: "Specifies the query that will be run in the streaming job. You can
            learn more about the Stream Analytics Query Language (SAQL) here:
            https://msdn.microsoft.com/library/azure/dn834998 . Required on PUT
            (CreateOrReplace) requests."
          type: string
        streamingUnits:
          description: Specifies the number of streaming units that the streaming job uses.
          format: int32
          type: integer
