openapi: 3.0.0
info:
  description: The HDInsight Management Client.
  title: HDInsightManagementClient
  version: 2015-03-01-preview
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/hdinsight/resource-manager/Microsoft.HDInsight/preview/2015-03-01-preview/extensions.json
      version: "2.0"
  x-preferred: false
  x-providerName: azure.com
  x-serviceName: hdinsight-extensions
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.HDInsight/clusters/{clusterName}/extensions/clustermonitoring":
    delete:
      description: Disables the Operations Management Suite (OMS) on the HDInsight cluster.
      operationId: Extension_DisableMonitoring
      parameters:
        - $ref: "#/components/parameters/SubscriptionIdParameter"
        - $ref: "#/components/parameters/ResourceGroupNameParameter"
        - $ref: "#/components/parameters/ClusterNameParameter"
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: Ok response definition.
        "202":
          description: OK response definition.
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Describes the format of Error response.
                properties:
                  code:
                    description: Error code
                    type: string
                  message:
                    description: Error message indicating why the operation failed.
                    type: string
                type: object
      tags:
        - Extensions
      x-ms-long-running-operation: true
    get:
      description: Gets the status of Operations Management Suite (OMS) on the HDInsight
        cluster.
      operationId: Extension_GetMonitoringStatus
      parameters:
        - $ref: "#/components/parameters/SubscriptionIdParameter"
        - $ref: "#/components/parameters/ResourceGroupNameParameter"
        - $ref: "#/components/parameters/ClusterNameParameter"
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: OK. The request has succeeded.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClusterMonitoringResponse"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Describes the format of Error response.
                properties:
                  code:
                    description: Error code
                    type: string
                  message:
                    description: Error message indicating why the operation failed.
                    type: string
                type: object
      tags:
        - Extensions
    put:
      description: Enables the Operations Management Suite (OMS) on the HDInsight cluster.
      operationId: Extension_EnableMonitoring
      parameters:
        - $ref: "#/components/parameters/SubscriptionIdParameter"
        - $ref: "#/components/parameters/ResourceGroupNameParameter"
        - $ref: "#/components/parameters/ClusterNameParameter"
        - $ref: "#/components/parameters/ApiVersionParameter"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ClusterMonitoringRequest"
        description: The Operations Management Suite (OMS) workspace parameters.
        required: true
      responses:
        "200":
          description: Ok response definition.
        "202":
          description: Accepted response definition.
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Describes the format of Error response.
                properties:
                  code:
                    description: Error code
                    type: string
                  message:
                    description: Error message indicating why the operation failed.
                    type: string
                type: object
      tags:
        - Extensions
      x-ms-long-running-operation: true
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.HDInsight/clusters/{clusterName}/extensions/{extensionName}":
    delete:
      description: Deletes the specified extension for HDInsight cluster.
      operationId: Extension_Delete
      parameters:
        - $ref: "#/components/parameters/SubscriptionIdParameter"
        - $ref: "#/components/parameters/ResourceGroupNameParameter"
        - $ref: "#/components/parameters/ClusterNameParameter"
        - $ref: "#/components/parameters/ExtensionNameParameter"
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: Ok response definition.
        "202":
          description: OK response definition.
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Describes the format of Error response.
                properties:
                  code:
                    description: Error code
                    type: string
                  message:
                    description: Error message indicating why the operation failed.
                    type: string
                type: object
      tags:
        - Extensions
    get:
      description: Gets the extension properties for the specified HDInsight cluster
        extension.
      operationId: Extension_Get
      parameters:
        - $ref: "#/components/parameters/SubscriptionIdParameter"
        - $ref: "#/components/parameters/ResourceGroupNameParameter"
        - $ref: "#/components/parameters/ClusterNameParameter"
        - $ref: "#/components/parameters/ExtensionNameParameter"
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: OK. The request has succeeded.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Extension"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Describes the format of Error response.
                properties:
                  code:
                    description: Error code
                    type: string
                  message:
                    description: Error message indicating why the operation failed.
                    type: string
                type: object
      tags:
        - Extensions
    put:
      description: Creates an HDInsight cluster extension.
      operationId: Extension_Create
      parameters:
        - $ref: "#/components/parameters/SubscriptionIdParameter"
        - $ref: "#/components/parameters/ResourceGroupNameParameter"
        - $ref: "#/components/parameters/ClusterNameParameter"
        - $ref: "#/components/parameters/ExtensionNameParameter"
        - $ref: "#/components/parameters/ApiVersionParameter"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Extension"
        description: The cluster extensions create request.
        required: true
      responses:
        "200":
          description: OK. The request has succeeded.
        "202":
          description: OK. The request has succeeded.
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Describes the format of Error response.
                properties:
                  code:
                    description: Error code
                    type: string
                  message:
                    description: Error message indicating why the operation failed.
                    type: string
                type: object
      tags:
        - Extensions
servers:
  - url: https://management.azure.com
components:
  parameters:
    ApiVersionParameter:
      description: The HDInsight client API Version.
      in: query
      name: api-version
      required: true
      schema:
        type: string
      examples:
        Enable cluster monitoring:
          value: 2015-03-01-preview
        Delete an extension:
          value: 2015-03-01-preview
        Get an extension:
          value: 2015-03-01-preview
        Create a monitoring extension on Hadoop Linux cluster:
          value: 2015-03-01-preview
    ClusterNameParameter:
      description: The name of the cluster.
      in: path
      name: clusterName
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
      examples:
        Enable cluster monitoring:
          value: cluster1
        Delete an extension:
          value: cluster1
        Get an extension:
          value: cluster1
        Create a monitoring extension on Hadoop Linux cluster:
          value: cluster1
    ExtensionNameParameter:
      description: The name of the cluster extension.
      in: path
      name: extensionName
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
      examples:
        Delete an extension:
          value: clustermonitoring
        Get an extension:
          value: clustermonitoring
        Create a monitoring extension on Hadoop Linux cluster:
          value: clustermonitoring
    ResourceGroupNameParameter:
      description: The name of the resource group.
      in: path
      name: resourceGroupName
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
      examples:
        Enable cluster monitoring:
          value: rg1
        Delete an extension:
          value: rg1
        Get an extension:
          value: rg1
        Create a monitoring extension on Hadoop Linux cluster:
          value: rg1
    SubscriptionIdParameter:
      description: The subscription credentials which uniquely identify Microsoft Azure
        subscription. The subscription ID forms part of the URI for every
        service call.
      in: path
      name: subscriptionId
      required: true
      schema:
        type: string
      examples:
        Enable cluster monitoring:
          value: subid
        Delete an extension:
          value: subid
        Get an extension:
          value: subid
        Create a monitoring extension on Hadoop Linux cluster:
          value: subid
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    ClusterMonitoringRequest:
      description: The Operations Management Suite (OMS) parameters.
      properties:
        primaryKey:
          description: The Operations Management Suite (OMS) workspace key.
          type: string
        workspaceId:
          description: The Operations Management Suite (OMS) workspace ID.
          type: string
    ClusterMonitoringResponse:
      description: The Operations Management Suite (OMS) status response
      properties:
        clusterMonitoringEnabled:
          description: The status of the Operations Management Suite (OMS) on the HDInsight
            cluster.
          type: boolean
        workspaceId:
          description: The workspace ID of the Operations Management Suite (OMS) on the
            HDInsight cluster.
          type: string
    Extension:
      description: Cluster monitoring extensions
      properties:
        primaryKey:
          description: The certificate for the cluster monitoring extensions.
          type: string
        workspaceId:
          description: The workspace ID for the cluster monitoring extension.
          type: string
