openapi: 3.0.0
info:
  description: The Microsoft Azure Network management API provides a RESTful set of web
    services that interact with Microsoft Azure Networks service to manage your
    network resources. The API has entities that capture the relationship
    between an end user and the Microsoft Azure Networks service.
  title: NetworkManagementClient
  version: 2019-07-01
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/network/resource-manager/Microsoft.Network/stable/2019-07-01/network.json
      version: "2.0"
  x-preferred: false
  x-providerName: azure.com
  x-serviceName: network
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths: {}
servers:
  - url: https://management.azure.com
components:
  parameters:
    ApiVersionParameter:
      description: Client API version.
      in: query
      name: api-version
      required: true
      schema:
        type: string
    ApiVersionVmssParameter:
      description: Client API version.
      in: query
      name: api-version
      required: true
      x-ms-enum:
        modelAsString: true
        name: ApiVersion
      schema:
        type: string
        enum:
          - 2017-03-30
    SubscriptionIdParameter:
      description: The subscription credentials which uniquely identify the Microsoft Azure
        subscription. The subscription ID forms part of the URI for every
        service call.
      in: path
      name: subscriptionId
      required: true
      schema:
        type: string
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    Access:
      description: Access to be allowed or denied.
      enum:
        - Allow
        - Deny
      type: string
      x-ms-enum:
        modelAsString: true
        name: Access
    AuthenticationMethod:
      description: VPN client authentication method.
      enum:
        - EAPTLS
        - EAPMSCHAPv2
      type: string
      x-ms-enum:
        modelAsString: true
        name: AuthenticationMethod
    AzureAsyncOperationResult:
      description: The response body contains the status of the specified asynchronous
        operation, indicating whether it has succeeded, is in progress, or has
        failed. Note that this status is distinct from the HTTP status code
        returned for the Get Operation Status operation itself. If the
        asynchronous operation succeeded, the response body includes the HTTP
        status code for the successful request. If the asynchronous operation
        failed, the response body includes the HTTP status code for the failed
        request and error information regarding the failure.
      properties:
        error:
          $ref: "#/components/schemas/Error"
        status:
          description: Status of the Azure async operation.
          enum:
            - InProgress
            - Succeeded
            - Failed
          type: string
          x-ms-enum:
            modelAsString: true
            name: NetworkOperationStatus
    Error:
      description: Common error representation.
      properties:
        code:
          description: Error code.
          type: string
        details:
          description: Error details.
          items:
            $ref: "#/components/schemas/ErrorDetails"
          type: array
        innerError:
          description: Inner error message.
          type: string
        message:
          description: Error message.
          type: string
        target:
          description: Error target.
          type: string
    ErrorDetails:
      description: Common error details representation.
      properties:
        code:
          description: Error code.
          type: string
        message:
          description: Error message.
          type: string
        target:
          description: Error target.
          type: string
    IPAllocationMethod:
      description: IP address allocation method.
      enum:
        - Static
        - Dynamic
      type: string
      x-ms-enum:
        modelAsString: true
        name: IPAllocationMethod
    IPVersion:
      description: IP address version.
      enum:
        - IPv4
        - IPv6
      type: string
      x-ms-enum:
        modelAsString: true
        name: IPVersion
    ManagedServiceIdentity:
      description: Identity for the resource.
      properties:
        principalId:
          description: The principal id of the system assigned identity. This property will
            only be provided for a system assigned identity.
          readOnly: true
          type: string
        tenantId:
          description: The tenant id of the system assigned identity. This property will
            only be provided for a system assigned identity.
          readOnly: true
          type: string
        type:
          description: The type of identity used for the resource. The type
            'SystemAssigned, UserAssigned' includes both an implicitly created
            identity and a set of user assigned identities. The type 'None' will
            remove any identities from the virtual machine.
          enum:
            - SystemAssigned
            - UserAssigned
            - SystemAssigned, UserAssigned
            - None
          type: string
          x-ms-enum:
            modelAsString: false
            name: ResourceIdentityType
        userAssignedIdentities:
          additionalProperties:
            properties:
              clientId:
                description: The client id of user assigned identity.
                readOnly: true
                type: string
              principalId:
                description: The principal id of user assigned identity.
                readOnly: true
                type: string
            type: object
          description: "The list of user identities associated with resource. The user
            identity dictionary key references will be ARM resource ids in the
            form:
            '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}\
            /providers/Microsoft.ManagedIdentity/userAssignedIdentities/{identi\
            tyName}'."
          type: object
    ProvisioningState:
      description: The current provisioning state.
      enum:
        - Succeeded
        - Updating
        - Deleting
        - Failed
      readOnly: true
      type: string
      x-ms-enum:
        modelAsString: true
        name: ProvisioningState
    Resource:
      description: Common resource representation.
      properties:
        id:
          description: Resource ID.
          type: string
        location:
          description: Resource location.
          type: string
        name:
          description: Resource name.
          readOnly: true
          type: string
        tags:
          additionalProperties:
            type: string
          description: Resource tags.
          type: object
        type:
          description: Resource type.
          readOnly: true
          type: string
      x-ms-azure-resource: true
    SubResource:
      description: Reference to another subresource.
      properties:
        id:
          description: Resource ID.
          type: string
      x-ms-azure-resource: true
    TagsObject:
      description: Tags object for patch operations.
      properties:
        tags:
          additionalProperties:
            type: string
          description: Resource tags.
          type: object
