openapi: 3.0.0
info:
  description: All resource groups and resources exist within subscriptions. These
    operation enable you get information about your subscriptions and tenants. A
    tenant is a dedicated instance of Azure Active Directory (Azure AD) for your
    organization.
  title: SubscriptionClient
  version: 2016-06-01
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/subscription/resource-manager/Microsoft.Subscription/stable/2016-06-01/subscriptions.json
      version: "2.0"
  x-preferred: false
  x-providerName: azure.com
  x-serviceName: subscription-subscriptions
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  /subscriptions:
    get:
      description: Gets all subscriptions for a tenant.
      operationId: Subscriptions_List
      parameters:
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: OK - Returns an array of subscriptions.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SubscriptionListResult"
      tags:
        - Subscriptions
      x-ms-pageable:
        nextLinkName: nextLink
  "/subscriptions/{subscriptionId}":
    get:
      description: Gets details about a specified subscription.
      operationId: Subscriptions_Get
      parameters:
        - $ref: "#/components/parameters/SubscriptionIdParameter"
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: OK - Returns information about the subscription.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Subscription"
      tags:
        - Subscriptions
  "/subscriptions/{subscriptionId}/locations":
    get:
      description: This operation provides all the locations that are available for
        resource providers; however, each resource provider may support a subset
        of this list.
      operationId: Subscriptions_ListLocations
      parameters:
        - $ref: "#/components/parameters/SubscriptionIdParameter"
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: OK - Returns an array of locations.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LocationListResult"
      summary: Gets all available geo-locations.
      tags:
        - Subscriptions
      x-ms-pageable: {}
  /tenants:
    get:
      description: Gets the tenants for your account.
      operationId: Tenants_List
      parameters:
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: OK - Returns an array of tenants.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TenantListResult"
      tags:
        - Tenants
      x-ms-pageable:
        nextLinkName: nextLink
servers:
  - url: https://management.azure.com
components:
  parameters:
    ApiVersionParameter:
      description: The API version to use for the operation.
      in: query
      name: api-version
      required: true
      x-ms-parameter-location: client
      schema:
        type: string
    SubscriptionIdParameter:
      description: The ID of the target subscription.
      in: path
      name: subscriptionId
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    Location:
      description: Location information.
      properties:
        displayName:
          description: The display name of the location.
          readOnly: true
          type: string
        id:
          description: The fully qualified ID of the location. For example,
            /subscriptions/00000000-0000-0000-0000-000000000000/locations/westus.
          readOnly: true
          type: string
        latitude:
          description: The latitude of the location.
          readOnly: true
          type: string
        longitude:
          description: The longitude of the location.
          readOnly: true
          type: string
        name:
          description: The location name.
          readOnly: true
          type: string
        subscriptionId:
          description: The subscription ID.
          readOnly: true
          type: string
    LocationListResult:
      description: Location list operation response.
      properties:
        value:
          description: An array of locations.
          items:
            $ref: "#/components/schemas/Location"
          type: array
    Subscription:
      description: Subscription information.
      properties:
        authorizationSource:
          description: The authorization source of the request. Valid values are one or
            more combinations of Legacy, RoleBased, Bypassed, Direct and
            Management. For example, 'Legacy, RoleBased'.
          type: string
        displayName:
          description: The subscription display name.
          readOnly: true
          type: string
        id:
          description: The fully qualified ID for the subscription. For example,
            /subscriptions/00000000-0000-0000-0000-000000000000.
          readOnly: true
          type: string
        state:
          description: The subscription state. Possible values are Enabled, Warned,
            PastDue, Disabled, and Deleted.
          enum:
            - Enabled
            - Warned
            - PastDue
            - Disabled
            - Deleted
          readOnly: true
          type: string
          x-ms-enum:
            modelAsString: false
            name: SubscriptionState
        subscriptionId:
          description: The subscription ID.
          readOnly: true
          type: string
        subscriptionPolicies:
          $ref: "#/components/schemas/SubscriptionPolicies"
    SubscriptionListResult:
      description: Subscription list operation response.
      properties:
        nextLink:
          description: The URL to get the next set of results.
          type: string
        value:
          description: An array of subscriptions.
          items:
            $ref: "#/components/schemas/Subscription"
          type: array
      required:
        - nextLink
    SubscriptionPolicies:
      description: Subscription policies.
      properties:
        locationPlacementId:
          description: The subscription location placement ID. The ID indicates which
            regions are visible for a subscription. For example, a subscription
            with a location placement Id of Public_2014-09-01 has access to
            Azure public regions.
          readOnly: true
          type: string
        quotaId:
          description: The subscription quota ID.
          readOnly: true
          type: string
        spendingLimit:
          description: The subscription spending limit.
          enum:
            - On
            - Off
            - CurrentPeriodOff
          readOnly: true
          type: string
          x-ms-enum:
            modelAsString: false
            name: spendingLimit
    TenantIdDescription:
      description: Tenant Id information.
      properties:
        id:
          description: The fully qualified ID of the tenant. For example,
            /tenants/00000000-0000-0000-0000-000000000000.
          readOnly: true
          type: string
        tenantId:
          description: The tenant ID. For example, 00000000-0000-0000-0000-000000000000.
          readOnly: true
          type: string
    TenantListResult:
      description: Tenant Ids information.
      properties:
        nextLink:
          description: The URL to use for getting the next set of results.
          type: string
        value:
          description: An array of tenants.
          items:
            $ref: "#/components/schemas/TenantIdDescription"
          type: array
      required:
        - nextLink
