openapi: 3.0.0
info:
  title: DeletedWebApps API Client
  version: 2018-02-01
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/web/resource-manager/Microsoft.Web/stable/2018-02-01/DeletedWebApps.json
      version: "2.0"
  x-preferred: true
  x-providerName: azure.com
  x-serviceName: web-DeletedWebApps
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  "/subscriptions/{subscriptionId}/providers/Microsoft.Web/deletedSites":
    get:
      description: Get all deleted apps for a subscription.
      operationId: DeletedWebApps_List
      parameters:
        - $ref: "#/components/parameters/subscriptionIdParameter"
        - $ref: "#/components/parameters/apiVersionParameter"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeletedWebAppCollection"
        default:
          description: App Service error response.
          content:
            application/json:
              schema:
                description: App Service error response.
                properties:
                  error:
                    description: Error model.
                    properties:
                      code:
                        description: Standardized string to programmatically identify the
                          error.
                        readOnly: true
                        type: string
                      details:
                        items:
                          description: Detailed errors.
                          properties:
                            code:
                              description: Standardized string to programmatically identify
                                the error.
                              readOnly: true
                              type: string
                            message:
                              description: Detailed error description and debugging
                                information.
                              readOnly: true
                              type: string
                            target:
                              description: Detailed error description and debugging
                                information.
                              readOnly: true
                              type: string
                          readOnly: true
                        type: array
                      innererror:
                        description: More information to debug error.
                        readOnly: true
                        type: string
                      message:
                        description: Detailed error description and debugging information.
                        readOnly: true
                        type: string
                      target:
                        description: Detailed error description and debugging information.
                        readOnly: true
                        type: string
                    readOnly: true
                    type: object
                type: object
      summary: Get all deleted apps for a subscription.
      tags:
        - DeletedWebApps
      x-ms-pageable:
        nextLinkName: nextLink
  "/subscriptions/{subscriptionId}/providers/Microsoft.Web/locations/{location}/deletedSites":
    get:
      description: Get all deleted apps for a subscription at location
      operationId: DeletedWebApps_ListByLocation
      parameters:
        - in: path
          name: location
          required: true
          schema:
            type: string
          examples:
            List Deleted Web App by Location:
              value: West US 2
        - $ref: "#/components/parameters/subscriptionIdParameter"
        - $ref: "#/components/parameters/apiVersionParameter"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeletedWebAppCollection"
              examples:
                List Deleted Web App by Location:
                  $ref: "#/components/examples/List_Deleted_Web_App_by_Location"
        default:
          description: App Service error response.
          content:
            application/json:
              schema:
                description: App Service error response.
                properties:
                  error:
                    description: Error model.
                    properties:
                      code:
                        description: Standardized string to programmatically identify the
                          error.
                        readOnly: true
                        type: string
                      details:
                        items:
                          description: Detailed errors.
                          properties:
                            code:
                              description: Standardized string to programmatically identify
                                the error.
                              readOnly: true
                              type: string
                            message:
                              description: Detailed error description and debugging
                                information.
                              readOnly: true
                              type: string
                            target:
                              description: Detailed error description and debugging
                                information.
                              readOnly: true
                              type: string
                          readOnly: true
                        type: array
                      innererror:
                        description: More information to debug error.
                        readOnly: true
                        type: string
                      message:
                        description: Detailed error description and debugging information.
                        readOnly: true
                        type: string
                      target:
                        description: Detailed error description and debugging information.
                        readOnly: true
                        type: string
                    readOnly: true
                    type: object
                type: object
      summary: Get all deleted apps for a subscription at location
      tags:
        - DeletedWebApps
      x-ms-pageable:
        nextLinkName: nextLink
  "/subscriptions/{subscriptionId}/providers/Microsoft.Web/locations/{location}/deletedSites/{deletedSiteId}":
    get:
      description: Get deleted app for a subscription at location.
      operationId: DeletedWebApps_GetDeletedWebAppByLocation
      parameters:
        - in: path
          name: location
          required: true
          schema:
            type: string
          examples:
            Get Deleted Web App by Location:
              value: West US 2
        - description: The numeric ID of the deleted app, e.g. 12345
          in: path
          name: deletedSiteId
          required: true
          schema:
            type: string
          examples:
            Get Deleted Web App by Location:
              value: "9"
        - $ref: "#/components/parameters/subscriptionIdParameter"
        - $ref: "#/components/parameters/apiVersionParameter"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - description: Azure proxy only resource. This resource is not tracked by
                      Azure Resource Manager.
                    properties:
                      id:
                        description: Resource Id.
                        readOnly: true
                        type: string
                      kind:
                        description: Kind of resource.
                        type: string
                      name:
                        description: Resource Name.
                        readOnly: true
                        type: string
                      type:
                        description: Resource type.
                        readOnly: true
                        type: string
                    x-ms-azure-resource: true
                description: A deleted app.
                properties:
                  properties:
                    description: DeletedSite resource specific properties
                    properties:
                      deletedSiteId:
                        description: Numeric id for the deleted site
                        format: int32
                        readOnly: true
                        type: integer
                      deletedSiteName:
                        description: Name of the deleted site
                        readOnly: true
                        type: string
                      deletedTimestamp:
                        description: Time in UTC when the app was deleted.
                        readOnly: true
                        type: string
                      geoRegionName:
                        description: Geo Region of the deleted site
                        readOnly: true
                        type: string
                      kind:
                        description: Kind of site that was deleted
                        readOnly: true
                        type: string
                      resourceGroup:
                        description: ResourceGroup that contained the deleted site
                        readOnly: true
                        type: string
                      slot:
                        description: Slot of the deleted site
                        readOnly: true
                        type: string
                      subscription:
                        description: Subscription containing the deleted site
                        readOnly: true
                        type: string
                    x-ms-client-flatten: true
                type: object
              examples:
                Get Deleted Web App by Location:
                  $ref: "#/components/examples/Get_Deleted_Web_App_by_Location"
        default:
          description: App Service error response.
          content:
            application/json:
              schema:
                description: App Service error response.
                properties:
                  error:
                    description: Error model.
                    properties:
                      code:
                        description: Standardized string to programmatically identify the
                          error.
                        readOnly: true
                        type: string
                      details:
                        items:
                          description: Detailed errors.
                          properties:
                            code:
                              description: Standardized string to programmatically identify
                                the error.
                              readOnly: true
                              type: string
                            message:
                              description: Detailed error description and debugging
                                information.
                              readOnly: true
                              type: string
                            target:
                              description: Detailed error description and debugging
                                information.
                              readOnly: true
                              type: string
                          readOnly: true
                        type: array
                      innererror:
                        description: More information to debug error.
                        readOnly: true
                        type: string
                      message:
                        description: Detailed error description and debugging information.
                        readOnly: true
                        type: string
                      target:
                        description: Detailed error description and debugging information.
                        readOnly: true
                        type: string
                    readOnly: true
                    type: object
                type: object
      summary: Get deleted app for a subscription at location.
      tags:
        - DeletedWebApps
servers:
  - url: https://management.azure.com
components:
  examples:
    List_Deleted_Web_App_by_Location:
      value:
        value:
          - name: wussite6
            properties:
              deletedSiteId: 9
              deletedSiteName: wussite6
              deletedTimestamp: 2019-05-09T22:29:05.1337007
              geoRegionName: West US 2
              kind: app
              resourceGroup: rg1
              slot: Production
              subscription: 34adfa4f-cedf-4dc0-ba29-b6d1a69ab345
            type: Microsoft.Web/locations/deletedSites
    Get_Deleted_Web_App_by_Location:
      value:
        name: wussite6
        properties:
          deletedSiteId: 9
          deletedSiteName: wussite6
          deletedTimestamp: 2019-05-09T22:29:05.1337007
          geoRegionName: West US 2
          kind: app
          resourceGroup: rg1
          slot: Production
          subscription: 34adfa4f-cedf-4dc0-ba29-b6d1a69ab345
        type: Microsoft.Web/locations/deletedSites
  parameters:
    apiVersionParameter:
      description: API Version
      in: query
      name: api-version
      required: true
      schema:
        type: string
      examples:
        List Deleted Web App by Location:
          value: 2018-02-01
        Get Deleted Web App by Location:
          value: 2018-02-01
    subscriptionIdParameter:
      description: Your Azure subscription ID. This is a GUID-formatted string (e.g.
        00000000-0000-0000-0000-000000000000).
      in: path
      name: subscriptionId
      required: true
      schema:
        type: string
      examples:
        List Deleted Web App by Location:
          value: 34adfa4f-cedf-4dc0-ba29-b6d1a69ab345
        Get Deleted Web App by Location:
          value: 34adfa4f-cedf-4dc0-ba29-b6d1a69ab345
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    DeletedWebAppCollection:
      description: Collection of deleted apps.
      properties:
        nextLink:
          description: Link to next page of resources.
          readOnly: true
          type: string
        value:
          description: Collection of resources.
          items:
            allOf:
              - description: Azure proxy only resource. This resource is not tracked by
                  Azure Resource Manager.
                properties:
                  id:
                    description: Resource Id.
                    readOnly: true
                    type: string
                  kind:
                    description: Kind of resource.
                    type: string
                  name:
                    description: Resource Name.
                    readOnly: true
                    type: string
                  type:
                    description: Resource type.
                    readOnly: true
                    type: string
                x-ms-azure-resource: true
            description: A deleted app.
            properties:
              properties:
                description: DeletedSite resource specific properties
                properties:
                  deletedSiteId:
                    description: Numeric id for the deleted site
                    format: int32
                    readOnly: true
                    type: integer
                  deletedSiteName:
                    description: Name of the deleted site
                    readOnly: true
                    type: string
                  deletedTimestamp:
                    description: Time in UTC when the app was deleted.
                    readOnly: true
                    type: string
                  geoRegionName:
                    description: Geo Region of the deleted site
                    readOnly: true
                    type: string
                  kind:
                    description: Kind of site that was deleted
                    readOnly: true
                    type: string
                  resourceGroup:
                    description: ResourceGroup that contained the deleted site
                    readOnly: true
                    type: string
                  slot:
                    description: Slot of the deleted site
                    readOnly: true
                    type: string
                  subscription:
                    description: Subscription containing the deleted site
                    readOnly: true
                    type: string
                x-ms-client-flatten: true
            type: object
          type: array
      required:
        - value
      type: object
