openapi: 3.0.0
info:
  description: Provides create, read, update and delete functionality Azure SQL server
    communication links.
  title: Azure SQL Database
  version: 2014-04-01
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/sql/resource-manager/Microsoft.Sql/stable/2014-04-01/serverCommunicationLinks.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: sql-serverCommunicationLinks
  x-tags:
    - Azure
    - Microsoft
paths:
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}/communicationLinks":
    get:
      description: Gets a list of server communication links.
      operationId: ServerCommunicationLinks_ListByServer
      parameters:
        - description: The API version to use for the request.
          in: query
          name: api-version
          required: true
          x-ms-parameter-location: client
          schema:
            type: string
          examples:
            List server communication links:
              value: 2014-04-01
        - description: The subscription ID that identifies an Azure subscription.
          in: path
          name: subscriptionId
          required: true
          x-ms-parameter-location: client
          schema:
            type: string
          examples:
            List server communication links:
              value: 00000000-1111-2222-3333-444444444444
        - description: The name of the resource group that contains the resource. You can
            obtain this value from the Azure Resource Manager API or the portal.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            List server communication links:
              value: sqlcrudtest-7398
        - $ref: "#/components/parameters/ServerNameParameter"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerCommunicationLinkListResult"
              examples:
                List server communication links:
                  $ref: "#/components/examples/List_server_communication_links"
      tags:
        - ServerCommunicationLinks
      x-ms-pageable: {}
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}/communicationLinks/{communicationLinkName}":
    delete:
      description: Deletes a server communication link.
      operationId: ServerCommunicationLinks_Delete
      parameters:
        - description: The API version to use for the request.
          in: query
          name: api-version
          required: true
          x-ms-parameter-location: client
          schema:
            type: string
          examples:
            Delete a server communication link:
              value: 2014-04-01
        - description: The subscription ID that identifies an Azure subscription.
          in: path
          name: subscriptionId
          required: true
          x-ms-parameter-location: client
          schema:
            type: string
          examples:
            Delete a server communication link:
              value: 00000000-1111-2222-3333-444444444444
        - description: The name of the resource group that contains the resource. You can
            obtain this value from the Azure Resource Manager API or the portal.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Delete a server communication link:
              value: sqlcrudtest-7398
        - $ref: "#/components/parameters/ServerNameParameter"
        - description: The name of the server communication link.
          in: path
          name: communicationLinkName
          required: true
          schema:
            type: string
          examples:
            Delete a server communication link:
              value: link1
      responses:
        "200":
          description: OK
      tags:
        - ServerCommunicationLinks
    get:
      description: Returns a server communication link.
      operationId: ServerCommunicationLinks_Get
      parameters:
        - description: The API version to use for the request.
          in: query
          name: api-version
          required: true
          x-ms-parameter-location: client
          schema:
            type: string
          examples:
            Get a server communication link:
              value: 2014-04-01
        - description: The subscription ID that identifies an Azure subscription.
          in: path
          name: subscriptionId
          required: true
          x-ms-parameter-location: client
          schema:
            type: string
          examples:
            Get a server communication link:
              value: 00000000-1111-2222-3333-444444444444
        - description: The name of the resource group that contains the resource. You can
            obtain this value from the Azure Resource Manager API or the portal.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Get a server communication link:
              value: sqlcrudtest-7398
        - $ref: "#/components/parameters/ServerNameParameter"
        - description: The name of the server communication link.
          in: path
          name: communicationLinkName
          required: true
          schema:
            type: string
          examples:
            Get a server communication link:
              value: link1
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerCommunicationLink"
              examples:
                Get a server communication link:
                  $ref: "#/components/examples/Get_a_server_communication_link"
      tags:
        - ServerCommunicationLinks
    put:
      description: Creates a server communication link.
      operationId: ServerCommunicationLinks_CreateOrUpdate
      parameters:
        - description: The API version to use for the request.
          in: query
          name: api-version
          required: true
          x-ms-parameter-location: client
          schema:
            type: string
          examples:
            Create a server communication link:
              value: 2014-04-01
        - description: The subscription ID that identifies an Azure subscription.
          in: path
          name: subscriptionId
          required: true
          x-ms-parameter-location: client
          schema:
            type: string
          examples:
            Create a server communication link:
              value: 00000000-1111-2222-3333-444444444444
        - description: The name of the resource group that contains the resource. You can
            obtain this value from the Azure Resource Manager API or the portal.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Create a server communication link:
              value: sqlcrudtest-7398
        - $ref: "#/components/parameters/ServerNameParameter"
        - description: The name of the server communication link.
          in: path
          name: communicationLinkName
          required: true
          schema:
            type: string
          examples:
            Create a server communication link:
              value: link1
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ServerCommunicationLink"
        description: The required parameters for creating a server communication link.
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerCommunicationLink"
              examples:
                Create a server communication link:
                  $ref: "#/components/examples/Create_a_server_communication_link"
        "202":
          description: Accepted
      tags:
        - ServerCommunicationLinks
      x-ms-long-running-operation: true
servers:
  - url: https://management.azure.com
components:
  examples:
    List_server_communication_links:
      value:
        value:
          - id: /subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/sqlcrudtest-7398/providers/Microsoft.Sql/servers/sqlcrudtest-4645/communicationLinks/link1
            location: Central US
            name: link1
            properties:
              partnerServer: sqlcrudtest-test
              state: Ready
            type: Microsoft.Sql/servers/communicationLinks
    Get_a_server_communication_link:
      value:
        id: /subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/sqlcrudtest-7398/providers/Microsoft.Sql/servers/sqlcrudtest-4645/communicationLinks/link1
        location: Central US
        name: link1
        properties:
          partnerServer: sqlcrudtest-test
          state: Ready
        type: Microsoft.Sql/servers/communicationLinks
    Create_a_server_communication_link:
      value:
        id: /subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/sqlcrudtest-7398/providers/Microsoft.Sql/servers/sqlcrudtest-4645/communicationLinks/link1
        location: Central US
        name: link1
        properties:
          partnerServer: sqlcrudtest-test
          state: Ready
        type: Microsoft.Sql/servers/communicationLinks
  parameters:
    ServerNameParameter:
      description: The name of the server.
      in: path
      name: serverName
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
      examples:
        List server communication links:
          value: sqlcrudtest-4645
        Delete a server communication link:
          value: sqlcrudtest-4645
        Get a server communication link:
          value: sqlcrudtest-4645
        Create a server communication link:
          value: sqlcrudtest-4645
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    ServerCommunicationLink:
      allOf:
        - allOf:
            - description: ARM resource.
              properties:
                id:
                  description: Resource ID.
                  readOnly: true
                  type: string
                name:
                  description: Resource name.
                  readOnly: true
                  type: string
                type:
                  description: Resource type.
                  readOnly: true
                  type: string
              type: object
              x-ms-azure-resource: true
          description: ARM proxy resource.
          properties: {}
          type: object
      description: Server communication link.
      properties:
        kind:
          description: Communication link kind.  This property is used for Azure Portal
            metadata.
          readOnly: true
          type: string
        location:
          description: Communication link location.
          readOnly: true
          type: string
        properties:
          $ref: "#/components/schemas/ServerCommunicationLinkProperties"
    ServerCommunicationLinkListResult:
      description: A list of server communication links.
      properties:
        value:
          description: The list of server communication links.
          items:
            $ref: "#/components/schemas/ServerCommunicationLink"
          type: array
    ServerCommunicationLinkProperties:
      description: The properties of a server communication link.
      properties:
        partnerServer:
          description: The name of the partner server.
          type: string
          x-ms-mutability:
            - create
            - read
        state:
          description: The state.
          readOnly: true
          type: string
      required:
        - partnerServer
