openapi: 3.0.0
info:
  description: The Admin Storage Management Client.
  title: StorageManagementClient
  version: 2019-08-08-preview
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/azsadmin/resource-manager/storage/Microsoft.Storage.Admin/preview/2019-08-08/quotas.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: azsadmin-quotas
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  "/subscriptions/{subscriptionId}/providers/Microsoft.Storage.Admin/locations/{location}/quotas":
    get:
      description: Returns a list of storage quotas at the given location.
      operationId: StorageQuotas_List
      parameters:
        - description: Subscription Id.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Returns a list of storage quotas at the given location.:
              value: 9ad61516-995c-4873-a21f-7e44904f0ed2
        - description: Resource location.
          in: path
          name: location
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Returns a list of storage quotas at the given location.:
              value: local
        - description: REST Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Returns a list of storage quotas at the given location.:
              value: 2019-08-08-preview
      responses:
        "200":
          description: OK -- The list of storage quotas has been returned.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StorageQuotaList"
              examples:
                Returns a list of storage quotas at the given location.:
                  $ref: "#/components/examples/Returns_a_list_of_storage_quotas_at_\
                    the_given_location."
        default:
          description: Error Response.
          content:
            application/json:
              schema:
                description: The error response for request which failed.
                properties:
                  code:
                    description: The error description code.
                    readOnly: true
                    type: string
                  details:
                    description: The error details information.
                    items:
                      type: string
                    readOnly: true
                    type: array
                  message:
                    description: The error description message.
                    readOnly: true
                    type: string
                  target:
                    description: The error target description.
                    readOnly: true
                    type: string
                type: object
      tags:
        - StorageQuotas
  "/subscriptions/{subscriptionId}/providers/Microsoft.Storage.Admin/locations/{location}/quotas/{quotaName}":
    delete:
      description: Delete an existing quota
      operationId: StorageQuotas_Delete
      parameters:
        - description: Subscription Id.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Delete an existing storage quota.:
              value: 9ad61516-995c-4873-a21f-7e44904f0ed2
        - description: REST Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Delete an existing storage quota.:
              value: 2019-08-08-preview
        - description: Resource location.
          in: path
          name: location
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Delete an existing storage quota.:
              value: local
        - $ref: "#/components/parameters/QuotaNameParameter"
      responses:
        "200":
          description: OK -- The storage quota has been deleted.
        default:
          description: Error Response.
          content:
            application/json:
              schema:
                description: The error response for request which failed.
                properties:
                  code:
                    description: The error description code.
                    readOnly: true
                    type: string
                  details:
                    description: The error details information.
                    items:
                      type: string
                    readOnly: true
                    type: array
                  message:
                    description: The error description message.
                    readOnly: true
                    type: string
                  target:
                    description: The error target description.
                    readOnly: true
                    type: string
                type: object
      tags:
        - StorageQuotas
    get:
      description: Returns the specified storage quota.
      operationId: StorageQuotas_Get
      parameters:
        - description: Subscription Id.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Returns the specified storage quota.:
              value: 9ad61516-995c-4873-a21f-7e44904f0ed2
        - description: REST Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Returns the specified storage quota.:
              value: 2019-08-08-preview
        - description: Resource location.
          in: path
          name: location
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Returns the specified storage quota.:
              value: local
        - $ref: "#/components/parameters/QuotaNameParameter"
      responses:
        "200":
          description: OK -- The storage quota has been returned.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StorageQuota"
              examples:
                Returns the specified storage quota.:
                  $ref: "#/components/examples/Returns_the_specified_storage_quota."
        default:
          description: Error Response.
          content:
            application/json:
              schema:
                description: The error response for request which failed.
                properties:
                  code:
                    description: The error description code.
                    readOnly: true
                    type: string
                  details:
                    description: The error details information.
                    items:
                      type: string
                    readOnly: true
                    type: array
                  message:
                    description: The error description message.
                    readOnly: true
                    type: string
                  target:
                    description: The error target description.
                    readOnly: true
                    type: string
                type: object
      tags:
        - StorageQuotas
    put:
      description: Create or update an existing storage quota.
      operationId: StorageQuotas_CreateOrUpdate
      parameters:
        - description: Subscription Id.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Create or update an existing storage quota.:
              value: 9ad61516-995c-4873-a21f-7e44904f0ed2
        - description: Resource location.
          in: path
          name: location
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Create or update an existing storage quota.:
              value: local
        - description: REST Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Create or update an existing storage quota.:
              value: 2019-08-08-preview
        - $ref: "#/components/parameters/QuotaNameParameter"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StorageQuota"
        description: The properties of quota being created or updated.
        required: true
        x-ms-parameter-location: method
      responses:
        "200":
          description: OK -- The storage quota has been created or updated.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StorageQuota"
              examples:
                Create or update an existing storage quota.:
                  $ref: "#/components/examples/Create_or_update_an_existing_storage\
                    _quota."
        default:
          description: Error Response.
          content:
            application/json:
              schema:
                description: The error response for request which failed.
                properties:
                  code:
                    description: The error description code.
                    readOnly: true
                    type: string
                  details:
                    description: The error details information.
                    items:
                      type: string
                    readOnly: true
                    type: array
                  message:
                    description: The error description message.
                    readOnly: true
                    type: string
                  target:
                    description: The error target description.
                    readOnly: true
                    type: string
                type: object
      tags:
        - StorageQuotas
servers:
  - url: https://adminmanagement.local.azurestack.external
components:
  examples:
    Returns_a_list_of_storage_quotas_at_the_given_location.:
      value:
        value:
          - id: /subscriptions/9ad61516-995c-4873-a21f-7e44904f0ed2/providers/Microsoft.Storage.Admin/locations/local/quotas/TestCreateQuota
            location: local
            name: local/TestCreateQuota
            properties:
              capacityInGb: 2048
              numberOfStorageAccounts: 20
            type: Microsoft.Storage.Admin/locations/quotas
    Returns_the_specified_storage_quota.:
      value:
        id: /subscriptions/9ad61516-995c-4873-a21f-7e44904f0ed2/providers/Microsoft.Storage.Admin/locations/local/quotas/TestCreateQuota
        location: local
        name: local/TestCreateQuota
        properties:
          capacityInGb: 2048
          numberOfStorageAccounts: 20
        type: Microsoft.Storage.Admin/locations/quotas
    Create_or_update_an_existing_storage_quota.:
      value:
        id: /subscriptions/9ad61516-995c-4873-a21f-7e44904f0ed2/providers/Microsoft.Storage.Admin/locations/local/quotas/TestCreateQuota
        location: local
        name: local/TestCreateQuota
        properties:
          capacityInGb: 1000
          numberOfStorageAccounts: 10000
        type: Microsoft.Storage.Admin/locations/quotas
  parameters:
    QuotaNameParameter:
      description: The name of the storage quota.
      in: path
      name: quotaName
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
      examples:
        Delete an existing storage quota.:
          value: TestCreateQuota
        Returns the specified storage quota.:
          value: TestCreateQuota
        Create or update an existing storage quota.:
          value: TestCreateQuota
  securitySchemes:
    azure_auth:
      description: Authorization uses an Azure Active Directory OAuth2 flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    StorageQuota:
      allOf:
        - description: Base resource object.
          properties:
            id:
              description: Resource ID.
              readOnly: true
              type: string
            location:
              description: Resource Location.
              readOnly: true
              type: string
            name:
              description: Resource Name.
              readOnly: true
              type: string
            type:
              description: Resource Type.
              readOnly: true
              type: string
          type: object
          x-ms-azure-resource: true
      description: Storage quota.
      properties:
        properties:
          $ref: "#/components/schemas/StorageQuotaProperties"
      type: object
    StorageQuotaList:
      description: Pageable list of storage quotas.
      properties:
        value:
          description: List of storage quotas.
          items:
            $ref: "#/components/schemas/StorageQuota"
          type: array
      type: object
    StorageQuotaProperties:
      description: Storage quota properties.
      properties:
        capacityInGb:
          default: 500
          description: Maximum capacity (GB).
          format: int32
          type: integer
        numberOfStorageAccounts:
          default: 20
          description: Total number of storage accounts.
          format: int32
          type: integer
      type: object
