openapi: 3.0.0
info:
  title: Azure Database Migration Service Resource Provider
  version: 2018-07-15-preview
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/datamigration/resource-manager/Microsoft.DataMigration/preview/2018-07-15-preview/definitions/ServiceFeatureOCITask.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: datamigration-ServiceFeatureOCITask
  x-tags:
    - Azure
    - Microsoft
paths: {}
servers:
  - url: https://azure.local
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    CheckOCIDriverTaskInput:
      description: Input for the service task to check for OCI drivers.
      properties:
        serverVersion:
          description: Version of the source server to check against.  Optional.
          type: string
      type: object
    CheckOCIDriverTaskOutput:
      description: Output for the service task to check for OCI drivers.
      properties:
        installedDriver:
          additionalProperties:
            items:
              $ref: "#/components/schemas/OracleOCIDriverInfo"
            type: array
          description: Information about the installed driver if found and valid.
          readOnly: true
          type: object
        validationErrors:
          description: Validation errors
          items:
            description: Exception object for all custom exceptions
            properties:
              actionableMessage:
                description: Actionable steps for this exception
                type: string
              filePath:
                description: The path to the file where exception occurred
                type: string
              hResult:
                description: Coded numerical value that is assigned to a specific exception
                type: integer
              lineNumber:
                description: The line number where exception occurred
                type: string
              message:
                description: Error message
                type: string
              stackTrace:
                description: Stack trace
                type: string
            type: object
          readOnly: true
          type: array
      type: object
    InstallOCIDriverTaskInput:
      description: Input for the service task to install an OCI driver.
      properties:
        driverPackageName:
          description: Name of the uploaded driver package to install.
          type: string
      type: object
    InstallOCIDriverTaskOutput:
      description: Output for the service task to install an OCI driver.
      properties:
        validationErrors:
          description: Validation errors
          items:
            description: Exception object for all custom exceptions
            properties:
              actionableMessage:
                description: Actionable steps for this exception
                type: string
              filePath:
                description: The path to the file where exception occurred
                type: string
              hResult:
                description: Coded numerical value that is assigned to a specific exception
                type: integer
              lineNumber:
                description: The line number where exception occurred
                type: string
              message:
                description: Error message
                type: string
              stackTrace:
                description: Stack trace
                type: string
            type: object
          readOnly: true
          type: array
      type: object
    OracleOCIDriverInfo:
      description: Information about an Oracle OCI driver.
      properties:
        archiveChecksum:
          description: The MD5 Base64 encoded checksum for the driver package.
          readOnly: true
          type: string
        assemblyVersion:
          description: Version listed in the OCI assembly 'oci.dll'
          readOnly: true
          type: string
        driverName:
          description: The name of the driver package
          readOnly: true
          type: string
        driverSize:
          description: The size in bytes of the driver package
          readOnly: true
          type: string
        oracleChecksum:
          description: The checksum for the driver package provided by Oracle.
          readOnly: true
          type: string
        supportedOracleVersions:
          description: List of Oracle database versions supported by this driver. Only
            major minor of the version is listed.
          items:
            type: string
          readOnly: true
          type: array
      type: object
    UploadOCIDriverTaskInput:
      description: Input for the service task to upload an OCI driver.
      properties:
        driverShare:
          description: File share information with Path, Username, and Password.
          properties:
            password:
              description: Password credential used to connect to the share location.
              type: string
            path:
              description: The folder path for this share.
              type: string
            userName:
              description: User name credential to connect to the share location
              type: string
          required:
            - path
          type: object
      type: object
    UploadOCIDriverTaskOutput:
      description: Output for the service task to upload an OCI driver.
      properties:
        driverPackageName:
          description: The name of the driver package that was validated and uploaded.
          readOnly: true
          type: string
        validationErrors:
          description: Validation errors
          items:
            description: Exception object for all custom exceptions
            properties:
              actionableMessage:
                description: Actionable steps for this exception
                type: string
              filePath:
                description: The path to the file where exception occurred
                type: string
              hResult:
                description: Coded numerical value that is assigned to a specific exception
                type: integer
              lineNumber:
                description: The line number where exception occurred
                type: string
              message:
                description: Error message
                type: string
              stackTrace:
                description: Stack trace
                type: string
            type: object
          readOnly: true
          type: array
      type: object
