openapi: 3.0.0
info:
  description: AzureBridge Admin Client.
  title: AzureBridgeAdminClient
  version: 2016-01-01
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/azsadmin/resource-manager/azurebridge/Microsoft.AzureBridge.Admin/preview/2016-01-01/Activation.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: azsadmin-Activation
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroup}/providers/Microsoft.AzureBridge.Admin/activations":
    get:
      description: Returns the list of activations.
      operationId: Activations_List
      parameters:
        - description: Subscription credentials which uniquely identify Microsoft Azure
            subscription.The subscription ID forms part of the URI for every
            service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Return product name.:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
        - description: The resource group the resource is located under.
          in: path
          name: resourceGroup
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Return product name.:
              value: azurestack
        - description: Client Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            default: 2016-01-01
          examples:
            Return product name.:
              value: 2015-06-01-preview
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ActivationResourcesPage"
              examples:
                Return product name.:
                  $ref: "#/components/examples/Return_product_name."
      tags:
        - Activations
      x-ms-pageable:
        nextLinkName: nextLink
  "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroup}/providers/Microsoft.AzureBridge.Admin/activations/{activationName}":
    delete:
      description: Delete an activation.
      operationId: Activations_Delete
      parameters:
        - description: Subscription credentials which uniquely identify Microsoft Azure
            subscription.The subscription ID forms part of the URI for every
            service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Delete an activation.:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
        - description: The resource group the resource is located under.
          in: path
          name: resourceGroup
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Delete an activation.:
              value: azurestack
        - description: Name of the activation.
          in: path
          name: activationName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Delete an activation.:
              value: default
        - description: Client Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            default: 2016-01-01
          examples:
            Delete an activation.:
              value: 2015-06-01-preview
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ActivationResource"
              examples:
                Delete an activation.:
                  $ref: "#/components/examples/Delete_an_activation."
      tags:
        - Activations
    get:
      description: Returns activation name.
      operationId: Activations_Get
      parameters:
        - description: Subscription credentials which uniquely identify Microsoft Azure
            subscription.The subscription ID forms part of the URI for every
            service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Return activation name.:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
        - description: The resource group the resource is located under.
          in: path
          name: resourceGroup
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Return activation name.:
              value: azurestack
        - description: Name of the activation.
          in: path
          name: activationName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Return activation name.:
              value: default
        - description: Client Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            default: 2016-01-01
          examples:
            Return activation name.:
              value: 2015-06-01-preview
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ActivationResource"
              examples:
                Return activation name.:
                  $ref: "#/components/examples/Return_activation_name."
        "404":
          description: Not Found
      tags:
        - Activations
    put:
      description: Create a new activation.
      operationId: Activations_CreateOrUpdate
      parameters:
        - description: Subscription credentials which uniquely identify Microsoft Azure
            subscription.The subscription ID forms part of the URI for every
            service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Return product name.:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
        - description: The resource group the resource is located under.
          in: path
          name: resourceGroup
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Return product name.:
              value: azurestack
        - description: Name of the activation.
          in: path
          name: activationName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Return product name.:
              value: default
        - description: Client Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            default: 2016-01-01
          examples:
            Return product name.:
              value: 2015-06-01-preview
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Activation"
        description: new activation.
        required: true
        x-ms-parameter-location: method
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ActivationResource"
              examples:
                Return product name.:
                  $ref: "#/components/examples/Return_product_name."
      tags:
        - Activations
servers:
  - url: https://adminmanagement.local.azurestack.external
components:
  examples:
    Return_product_name.:
      value:
        id: /subscriptions/b6a34e73-810f-4564-881a-8434c6c2e5c8/resourceGroups/azurestack-activation/providers/Microsoft.AzureBridge.Admin/activations/default
        location: local
        name: default
        properties:
          azureRegistrationResourceIdentifier: /subscriptions/4e9319a5-1cf7-4099-80ea-9aa2f09cb1e7/resourceGroups/azurestack/providers/Microsoft.AzureStack/registrations/AzureStack-e6135d07-4efa-439c-b899-24e03cbac5f9
          displayName: Azure Stack Activation
          expiration: 9999-12-30T15:59:59
          marketplaceSyndicationEnabled: true
          provisioningState: Succeeded
          usageReportingEnabled: true
        type: Microsoft.AzureBridge.Admin/activations
    Delete_an_activation.:
      value:
        id: /subscriptions/b6a34e73-810f-4564-881a-8434c6c2e5c8/resourceGroups/azurestack-activation/providers/Microsoft.AzureBridge.Admin/activations/default
        name: default
    Return_activation_name.:
      value:
        id: /subscriptions/b6a34e73-810f-4564-881a-8434c6c2e5c8/resourceGroups/azurestack-activation/providers/Microsoft.AzureBridge.Admin/activations/default
        location: local
        name: default
        properties:
          azureRegistrationResourceIdentifier: /subscriptions/4e9319a5-1cf7-4099-80ea-9aa2f09cb1e7/resourceGroups/azurestack/providers/Microsoft.AzureStack/registrations/AzureStack-e6135d07-4efa-439c-b899-24e03cbac5f9
          displayName: Azure Stack Activation
          expiration: 9999-12-30T15:59:59
          marketplaceSyndicationEnabled: true
          provisioningState: Succeeded
          usageReportingEnabled: true
        type: Microsoft.AzureBridge.Admin/activations
  securitySchemes:
    azure_auth:
      description: Authorization uses an Azure Active Directory OAuth2 flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    Activation:
      description: Holds properties related to activation.
      properties:
        azureRegistrationResourceIdentifier:
          description: Azure registration resource identifier.
          type: string
        displayName:
          description: Name displayed for the product.
          type: string
        expiration:
          description: The activation expiration.
          type: string
        marketplaceSyndicationEnabled:
          description: Value indicating whether the marketplace syndication feature is
            enabled.
          type: boolean
        provisioningState:
          description: The provisioning state of the resource.
          enum:
            - Stopped
            - Starting
            - Running
            - Stopping
            - Succeeded
            - Downloading
          type: string
          x-ms-enum:
            modelAsString: true
            name: ProvisioningState
        usageReportingEnabled:
          description: Value indicating whether the usage reporting feature is enabled.
          type: boolean
      type: object
    ActivationResource:
      allOf:
        - description: Base Resource Object
          properties:
            id:
              description: URI of the resource.
              readOnly: true
              type: string
            location:
              description: Location of the resource
              readOnly: true
              type: string
            name:
              description: Name of the resource.
              readOnly: true
              type: string
            tags:
              additionalProperties:
                type: string
              description: List of key value pairs.
              readOnly: true
              type: object
            type:
              description: Type of resource.
              readOnly: true
              type: string
          type: object
          x-ms-azure-resource: true
      description: Published activation resource.
      properties:
        properties:
          $ref: "#/components/schemas/Activation"
      type: object
    ActivationResourcesPage:
      description: Holds an array of activation resources and the next link.
      properties:
        nextLink:
          description: URI to the next page.
          type: string
        value:
          description: List of activation resources.
          items:
            $ref: "#/components/schemas/ActivationResource"
          type: array
