openapi: 3.0.0
info:
  description: Quota admin operation endpoints and objects.
  title: NetworkAdminManagementClient
  version: 2015-06-15
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/azsadmin/resource-manager/network/Microsoft.Network.Admin/preview/2015-06-15/Quotas.json
      version: "2.0"
  x-preferred: false
  x-providerName: azure.com
  x-serviceName: azsadmin-Quotas
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  "/subscriptions/{subscriptionId}/providers/Microsoft.Network.Admin/locations/{location}/quotas":
    get:
      description: List all quotas.
      operationId: Quotas_List
      parameters:
        - description: Subscription credentials which uniquely identify Microsoft Azure
            subscription. The subscription ID forms part of the URI for every
            service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            List all quotas:
              value: fc8456aa-4843-4079-a152-f3497c63aa73
        - description: Location of the resource.
          in: path
          name: location
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            List all quotas:
              value: local
        - description: Client API Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            default: 2015-06-15
          examples:
            List all quotas:
              value: 2015-06-15
        - description: OData filter parameter.
          in: query
          name: $filter
          x-ms-parameter-location: method
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QuotaList"
              examples:
                List all quotas:
                  $ref: "#/components/examples/List_all_quotas"
        "404":
          description: Not Found
      tags:
        - Quotas
      x-ms-odata: "#/components/schemas/Quota"
      x-ms-pageable: {}
  "/subscriptions/{subscriptionId}/providers/Microsoft.Network.Admin/locations/{location}/quotas/{resourceName}":
    delete:
      description: Delete a quota by name.
      operationId: Quotas_Delete
      parameters:
        - description: Subscription credentials which uniquely identify Microsoft Azure
            subscription. The subscription ID forms part of the URI for every
            service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Delete a quota by name.:
              value: fc8456aa-4843-4079-a152-f3497c63aa73
        - description: Location of the resource.
          in: path
          name: location
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Delete a quota by name.:
              value: local
        - description: Name of the resource.
          in: path
          name: resourceName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Delete a quota by name.:
              value: TestQuotaForUpdate
        - description: Client API Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            default: 2015-06-15
          examples:
            Delete a quota by name.:
              value: 2015-06-15
      responses:
        "200":
          description: OK
        "202":
          description: Accepted
        "204":
          description: No Content
      tags:
        - Network
      x-ms-long-running-operation: true
    get:
      description: Get a quota by name.
      operationId: Quotas_Get
      parameters:
        - description: Subscription credentials which uniquely identify Microsoft Azure
            subscription. The subscription ID forms part of the URI for every
            service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Get a quota by name:
              value: fc8456aa-4843-4079-a152-f3497c63aa73
        - description: Location of the resource.
          in: path
          name: location
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Get a quota by name:
              value: local
        - description: Name of the resource.
          in: path
          name: resourceName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Get a quota by name:
              value: Default Quota
        - description: Client API Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            default: 2015-06-15
          examples:
            Get a quota by name:
              value: 2015-06-15
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Quota"
              examples:
                Get a quota by name:
                  $ref: "#/components/examples/Get_a_quota_by_name"
        "404":
          description: Not Found
      tags:
        - Quotas
    put:
      description: Create or update a quota.
      operationId: Quotas_CreateOrUpdate
      parameters:
        - description: Subscription credentials which uniquely identify Microsoft Azure
            subscription. The subscription ID forms part of the URI for every
            service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Create or update a new quota:
              value: fc8456aa-4843-4079-a152-f3497c63aa73
        - description: Location of the resource.
          in: path
          name: location
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Create or update a new quota:
              value: local
        - description: Name of the resource.
          in: path
          name: resourceName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Create or update a new quota:
              value: TestQuotaForUpdate
        - description: Client API Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            default: 2015-06-15
          examples:
            Create or update a new quota:
              value: 2015-06-15
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Quota"
        description: New network quota to create.
        required: true
        x-ms-parameter-location: method
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Quota"
              examples:
                Create or update a new quota:
                  $ref: "#/components/examples/Create_or_update_a_new_quota"
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Quota"
              examples:
                Create or update a new quota:
                  $ref: "#/components/examples/Create_or_update_a_new_quota"
      tags:
        - Network
servers:
  - url: https://adminmanagement.local.azurestack.external
components:
  examples:
    List_all_quotas:
      value:
        value:
          - id: /subscriptions/fc8456aa-4843-4079-a152-f3497c63aa73/providers/Microsoft.Network.Admin/locations/local/quotas/Default
              Quota
            location: local
            name: Default Quota
            properties:
              maxLoadBalancersPerSubscription: 50
              maxNicsPerSubscription: 100
              maxPublicIpsPerSubscription: 50
              maxSecurityGroupsPerSubscription: 50
              maxVirtualNetworkGatewayConnectionsPerSubscription: 2
              maxVirtualNetworkGatewaysPerSubscription: 1
              maxVnetsPerSubscription: 50
              migrationPhase: None
              provisioningState: Succeeded
            type: Microsoft.Network.Admin/quotas
    Get_a_quota_by_name:
      value:
        id: /subscriptions/fc8456aa-4843-4079-a152-f3497c63aa73/providers/Microsoft.Network.Admin/locations/local/quotas/Default
          Quota
        location: local
        name: Default Quota
        properties:
          maxLoadBalancersPerSubscription: 50
          maxNicsPerSubscription: 100
          maxPublicIpsPerSubscription: 50
          maxSecurityGroupsPerSubscription: 50
          maxVirtualNetworkGatewayConnectionsPerSubscription: 2
          maxVirtualNetworkGatewaysPerSubscription: 1
          maxVnetsPerSubscription: 50
          migrationPhase: None
          provisioningState: Succeeded
        type: Microsoft.Network.Admin/quotas
    Create_or_update_a_new_quota:
      value:
        id: /subscriptions/fc8456aa-4843-4079-a152-f3497c63aa73/providers/Microsoft.Network.Admin/locations/local/quotas/TestQuotaForRemoval
        name: TestQuotaForRemoval
        properties:
          maxLoadBalancersPerSubscription: 32
          maxNicsPerSubscription: 4
          maxPublicIpsPerSubscription: 32
          maxSecurityGroupsPerSubscription: 2
          maxVirtualNetworkGatewayConnectionsPerSubscription: 32
          maxVirtualNetworkGatewaysPerSubscription: 32
          maxVnetsPerSubscription: 32
          migrationPhase: None
          provisioningState: Succeeded
        type: Microsoft.Network.Admin/quotas
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    MigrationPhase:
      description: State of migration such as None, Prepare, Commit, and Abort.
      enum:
        - None
        - Prepare
        - Commit
        - Abort
      type: string
      x-ms-enum:
        modelAsString: true
        name: MigrationPhaseType
    Quota:
      allOf:
        - description: Base Resource Object
          properties:
            id:
              description: URI of the resource.
              readOnly: true
              type: string
            location:
              description: Region location of resource.
              readOnly: true
              type: string
            name:
              description: Name of the resource.
              readOnly: true
              type: string
            tags:
              additionalProperties:
                type: string
              description: List of key value pairs.
              type: object
            type:
              description: Type of resource.
              readOnly: true
              type: string
          type: object
          x-ms-azure-resource: true
      description: Network quota resource.
      properties:
        properties:
          $ref: "#/components/schemas/QuotaProperties"
    QuotaList:
      description: A pageable list of network quotas.
      properties:
        nextLink:
          description: The URI to the next page.
          type: string
        value:
          description: List of quotas on this page.
          items:
            $ref: "#/components/schemas/Quota"
          type: array
      type: object
    QuotaProperties:
      allOf:
        - description: Objects which have a provisioning state.
          properties:
            provisioningState:
              description: The provisioning state.
              readOnly: true
              type: string
          type: object
      description: Properties of a quota.
      properties:
        maxLoadBalancersPerSubscription:
          description: Maximum number of load balancers a tenant subscription can provision.
          format: int64
          type: integer
        maxNicsPerSubscription:
          description: Maximum number of NICs a tenant subscription can provision.
          format: int64
          type: integer
        maxPublicIpsPerSubscription:
          description: Maximum number of public IP addresses a tenant subscription can
            provision.
          format: int64
          type: integer
        maxSecurityGroupsPerSubscription:
          description: Maximum number of security groups a tenant subscription can
            provision.
          format: int64
          type: integer
        maxVirtualNetworkGatewayConnectionsPerSubscription:
          description: Maximum number of virtual network gateway Connections a tenant
            subscription can provision.
          format: int64
          type: integer
        maxVirtualNetworkGatewaysPerSubscription:
          description: Maximum number of virtual network gateways a tenant subscription can
            provision.
          format: int64
          type: integer
        maxVnetsPerSubscription:
          description: Maximum number of virtual networks a tenant subscription can
            provision.
          format: int64
          type: integer
        migrationPhase:
          $ref: "#/components/schemas/MigrationPhase"
