openapi: 3.0.0
info:
  description: Use these REST APIs for getting the network connectivity status of your
    Azure API Management deployment. When the API Management service is deployed
    inside a Virtual Network, it needs to have access to other Azure resources
    it depends on. This also gives details about the DNS Servers visible to
    Azure API Management deployment.
  title: ApiManagementClient
  version: 2018-06-01-preview
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2018-06-01-preview/apimnetworkstatus.json
      version: "2.0"
  x-preferred: false
  x-providerName: azure.com
  x-serviceName: apimanagement-apimnetworkstatus
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ApiManagement/service/{serviceName}/locations/{locationName}/networkstatus":
    get:
      description: Gets the Connectivity Status to the external resources on which the Api
        Management service depends from inside the Cloud Service. This also
        returns the DNS Servers as visible to the CloudService.
      operationId: NetworkStatus_ListByLocation
      parameters:
        - description: Subscription credentials which uniquely identify Microsoft Azure
            subscription. The subscription ID forms part of the URI for every
            service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            ApiManagementServiceGetNetworkStatusByLocation:
              value: subid
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            ApiManagementServiceGetNetworkStatusByLocation:
              value: rg1
        - description: The name of the API Management service.
          in: path
          name: serviceName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 50
            pattern: ^[a-zA-Z](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?$
          examples:
            ApiManagementServiceGetNetworkStatusByLocation:
              value: apimService1
        - description: Location in which the API Management service is deployed. This is
            one of the Azure Regions like West US, East US, South Central US.
          in: path
          name: locationName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
          examples:
            ApiManagementServiceGetNetworkStatusByLocation:
              value: North Central US
        - description: Version of the API to be used with the client request.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            ApiManagementServiceGetNetworkStatusByLocation:
              value: 2018-06-01-preview
      responses:
        "200":
          description: Gets the Network status details.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NetworkStatusContract"
              examples:
                ApiManagementServiceGetNetworkStatusByLocation:
                  $ref: "#/components/examples/ApiManagementServiceGetNetworkStatus\
                    ByLocation"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error Response.
                properties:
                  error:
                    description: Error Body contract.
                    properties:
                      code:
                        description: Service-defined error code. This code serves as a
                          sub-status for the HTTP error code specified in the
                          response.
                        type: string
                      details:
                        description: The list of invalid fields send in request, in case of
                          validation error.
                        items:
                          description: Error Field contract.
                          properties:
                            code:
                              description: Property level error code.
                              type: string
                            message:
                              description: Human-readable representation of property-level
                                error.
                              type: string
                            target:
                              description: Property name.
                              type: string
                        type: array
                      message:
                        description: Human-readable representation of the error.
                        type: string
      tags:
        - NetworkStatus
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ApiManagement/service/{serviceName}/networkstatus":
    get:
      description: Gets the Connectivity Status to the external resources on which the Api
        Management service depends from inside the Cloud Service. This also
        returns the DNS Servers as visible to the CloudService.
      operationId: NetworkStatus_ListByService
      parameters:
        - description: Subscription credentials which uniquely identify Microsoft Azure
            subscription. The subscription ID forms part of the URI for every
            service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            ApiManagementServiceGetNetworkStatus:
              value: subid
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            ApiManagementServiceGetNetworkStatus:
              value: rg1
        - description: The name of the API Management service.
          in: path
          name: serviceName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 50
            pattern: ^[a-zA-Z](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?$
          examples:
            ApiManagementServiceGetNetworkStatus:
              value: apimService1
        - description: Version of the API to be used with the client request.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            ApiManagementServiceGetNetworkStatus:
              value: 2018-06-01-preview
      responses:
        "200":
          description: Gets the list Network status details for all regions in which
            service is deployed.
          content:
            application/json:
              schema:
                description: List of Network Status values.
                items:
                  $ref: "#/components/schemas/NetworkStatusContractByLocation"
                type: array
              examples:
                ApiManagementServiceGetNetworkStatus:
                  $ref: "#/components/examples/ApiManagementServiceGetNetworkStatus"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error Response.
                properties:
                  error:
                    description: Error Body contract.
                    properties:
                      code:
                        description: Service-defined error code. This code serves as a
                          sub-status for the HTTP error code specified in the
                          response.
                        type: string
                      details:
                        description: The list of invalid fields send in request, in case of
                          validation error.
                        items:
                          description: Error Field contract.
                          properties:
                            code:
                              description: Property level error code.
                              type: string
                            message:
                              description: Human-readable representation of property-level
                                error.
                              type: string
                            target:
                              description: Property name.
                              type: string
                        type: array
                      message:
                        description: Human-readable representation of the error.
                        type: string
      tags:
        - NetworkStatus
servers:
  - url: https://management.azure.com
components:
  examples:
    ApiManagementServiceGetNetworkStatusByLocation:
      value:
        connectivityStatus:
          - error: ""
            lastStatusChange: 2018-06-13T20:31:06.6590782Z
            lastUpdated: 2018-06-13T22:41:07.3844516Z
            name: apimgmtst6mtxxxxxxxx.blob.core.windows.net
            status: success
          - error: ""
            lastStatusChange: 2018-06-13T20:31:06.8934611Z
            lastUpdated: 2018-06-13T22:41:08.6657305Z
            name: apimgmtst6mtxxxxxxxx.file.core.windows.net
            status: success
          - error: ""
            lastStatusChange: 2018-06-13T20:31:06.7529128Z
            lastUpdated: 2018-06-13T22:41:08.7594708Z
            name: apimgmtst6mtxxxxxxxx.table.core.windows.net
            status: success
          - error: ""
            lastStatusChange: 2018-06-13T20:31:07.1125257Z
            lastUpdated: 2018-06-13T22:41:08.6969746Z
            name: https://prod3.metrics.nsatc.net:1886/RecoveryService
            status: success
          - error: ""
            lastStatusChange: 2018-06-13T20:31:07.0968711Z
            lastUpdated: 2018-06-13T22:41:09.5094848Z
            name: n20fxxx.database.windows.net
            status: success
          - error: ""
            lastStatusChange: 2018-06-13T20:41:09.8627827Z
            lastUpdated: 2018-06-13T22:41:29.4358865Z
            name: Scm
            status: success
        dnsServers:
          - 100.78.90.70
    ApiManagementServiceGetNetworkStatus:
      value:
        - location: North Central US
          networkStatus:
            connectivityStatus:
              - error: ""
                lastStatusChange: 2018-06-13T20:31:06.6590782Z
                lastUpdated: 2018-06-13T22:31:07.3274887Z
                name: apimgmtst6mtxxxxxxxx.blob.core.windows.net
                status: success
              - error: ""
                lastStatusChange: 2018-06-13T20:31:06.8934611Z
                lastUpdated: 2018-06-13T22:31:08.54627Z
                name: apimgmtst6mtxxxxxxxx.file.core.windows.net
                status: success
              - error: ""
                lastStatusChange: 2018-06-13T20:31:06.7529128Z
                lastUpdated: 2018-06-13T22:31:08.6556497Z
                name: apimgmtst6mtxxxxxxxx.table.core.windows.net
                status: success
              - error: ""
                lastStatusChange: 2018-06-13T20:31:07.1125257Z
                lastUpdated: 2018-06-13T22:31:08.5618943Z
                name: https://prod3.metrics.nsatc.net:1886/RecoveryService
                status: success
              - error: ""
                lastStatusChange: 2018-06-13T20:31:07.0968711Z
                lastUpdated: 2018-06-13T22:31:09.3275394Z
                name: n20fxxxxxxxx.database.windows.net
                status: success
              - error: ""
                lastStatusChange: 2018-06-13T20:41:09.8627827Z
                lastUpdated: 2018-06-13T22:31:28.0942291Z
                name: Scm
                status: success
            dnsServers:
              - 100.78.90.70
        - location: South Central US
          networkStatus:
            connectivityStatus:
              - error: ""
                lastStatusChange: 2018-06-13T21:36:24.6042279Z
                lastUpdated: 2018-06-13T22:36:26.6522053Z
                name: apimgmtst6mtxxxxxxxx.file.core.windows.net
                status: success
              - error: ""
                lastStatusChange: 2018-06-13T21:36:24.1587528Z
                lastUpdated: 2018-06-13T22:36:25.9959344Z
                name: apimgmtst6mtxxxxxxxx.table.core.windows.net
                status: success
              - error: ""
                lastStatusChange: 2018-06-13T21:36:24.5104599Z
                lastUpdated: 2018-06-13T22:36:25.0115192Z
                name: apimgmtstufddxxxxxxxx.blob.core.windows.net
                status: success
              - error: ""
                lastStatusChange: 2018-06-13T21:36:24.0962419Z
                lastUpdated: 2018-06-13T22:36:26.042817Z
                name: https://prod2.metrics.nsatc.net:1886/RecoveryService
                status: success
              - error: ""
                lastStatusChange: 2018-06-13T21:36:24.80737Z
                lastUpdated: 2018-06-13T22:36:26.7615872Z
                name: n20fxxxxxxxx.database.windows.net
                status: success
            dnsServers:
              - 100.92.34.14
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    ConnectivityStatusContract:
      description: Details about connectivity to a resource.
      properties:
        error:
          description: Error details of the connectivity to the resource.
          type: string
        lastStatusChange:
          description: >
            The date when the resource connectivity status last Changed from
            success to failure or vice-versa. The date conforms to the following
            format: `yyyy-MM-ddTHH:mm:ssZ` as specified by the ISO 8601
            standard.
          format: date-time
          type: string
        lastUpdated:
          description: >
            The date when the resource connectivity status was last updated.
            This status should be updated every 15 minutes. If this status has
            not been updated, then it means that the service has lost network
            connectivity to the resource, from inside the Virtual Network.The
            date conforms to the following format: `yyyy-MM-ddTHH:mm:ssZ` as
            specified by the ISO 8601 standard.
          format: date-time
          type: string
        name:
          description: The hostname of the resource which the service depends on. This can
            be the database, storage or any other azure resource on which the
            service depends upon.
          minLength: 1
          type: string
        status:
          description: Resource Connectivity Status Type identifier.
          enum:
            - initializing
            - success
            - failure
          type: string
          x-ms-enum:
            modelAsString: true
            name: ConnectivityStatusType
      required:
        - name
        - status
        - lastUpdated
        - lastStatusChange
    NetworkStatusContract:
      description: Network Status details.
      properties:
        connectivityStatus:
          description: Gets the list of Connectivity Status to the Resources on which the
            service depends upon.
          items:
            $ref: "#/components/schemas/ConnectivityStatusContract"
          type: array
        dnsServers:
          description: Gets the list of DNS servers IPV4 addresses.
          items:
            type: string
          type: array
      required:
        - dnsServers
        - connectivityStatus
    NetworkStatusContractByLocation:
      description: Network Status in the Location
      properties:
        location:
          description: Location of service
          minLength: 1
          type: string
        networkStatus:
          $ref: "#/components/schemas/NetworkStatusContract"
