openapi: 3.0.0
info:
  description: The Azure SQL Database management API provides a RESTful set of web services
    that interact with Azure SQL Database services to manage your external
    server administrators.
  title: Azure SQL Database API spec
  version: 2014-04-01
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/sql/resource-manager/Microsoft.Sql/stable/2014-04-01/serverAzureADAdministrators.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: sql-serverAzureADAdministrators
  x-tags:
    - Azure
    - Microsoft
paths:
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}/administrators":
    get:
      description: Returns a list of server Administrators.
      operationId: ServerAzureADAdministrators_ListByServer
      parameters:
        - description: The API version to use for the request.
          in: query
          name: api-version
          required: true
          x-ms-parameter-location: client
          schema:
            type: string
          examples:
            get a list of server administrators:
              value: 2014-04-01
        - description: The subscription ID that identifies an Azure subscription.
          in: path
          name: subscriptionId
          required: true
          x-ms-parameter-location: client
          schema:
            type: string
          examples:
            get a list of server administrators:
              value: 00000000-1111-2222-3333-444444444444
        - description: The name of the resource group that contains the resource. You can
            obtain this value from the Azure Resource Manager API or the portal.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            get a list of server administrators:
              value: sqlcrudtest-4799
        - $ref: "#/components/parameters/ServerNameParameter"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerAdministratorListResult"
              examples:
                get a list of server administrators:
                  $ref: "#/components/examples/get_a_list_of_server_administrators"
      tags:
        - ServerAdministrators
      x-ms-pageable: {}
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}/administrators/{administratorName}":
    delete:
      description: Deletes an existing server Active Directory Administrator.
      operationId: ServerAzureADAdministrators_Delete
      parameters:
        - description: The API version to use for the request.
          in: query
          name: api-version
          required: true
          x-ms-parameter-location: client
          schema:
            type: string
          examples:
            Delete a server administrator:
              value: 2014-04-01
        - description: The subscription ID that identifies an Azure subscription.
          in: path
          name: subscriptionId
          required: true
          x-ms-parameter-location: client
          schema:
            type: string
          examples:
            Delete a server administrator:
              value: 00000000-1111-2222-3333-444444444444
        - description: The name of the resource group that contains the resource. You can
            obtain this value from the Azure Resource Manager API or the portal.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Delete a server administrator:
              value: sqlcrudtest-4799
        - $ref: "#/components/parameters/ServerNameParameter"
        - $ref: "#/components/parameters/AdministratorNameParameter"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerAzureADAdministrator"
              examples:
                Delete a server administrator:
                  $ref: "#/components/examples/Delete_a_server_administrator"
        "202":
          description: Accepted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerAzureADAdministrator"
              examples:
                Delete a server administrator:
                  $ref: "#/components/examples/Delete_a_server_administrator"
        "204":
          description: No Content
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerAzureADAdministrator"
              examples:
                Delete a server administrator:
                  $ref: "#/components/examples/Delete_a_server_administrator"
      tags:
        - ServerAdministrators
      x-ms-long-running-operation: true
    get:
      description: Returns an server Administrator.
      operationId: ServerAzureADAdministrators_Get
      parameters:
        - description: The API version to use for the request.
          in: query
          name: api-version
          required: true
          x-ms-parameter-location: client
          schema:
            type: string
          examples:
            Get the Active Directory Administrator:
              value: 2014-04-01
        - description: The subscription ID that identifies an Azure subscription.
          in: path
          name: subscriptionId
          required: true
          x-ms-parameter-location: client
          schema:
            type: string
          examples:
            Get the Active Directory Administrator:
              value: 00000000-1111-2222-3333-444444444444
        - description: The name of the resource group that contains the resource. You can
            obtain this value from the Azure Resource Manager API or the portal.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Get the Active Directory Administrator:
              value: sqlcrudtest-4799
        - $ref: "#/components/parameters/ServerNameParameter"
        - $ref: "#/components/parameters/AdministratorNameParameter"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerAzureADAdministrator"
              examples:
                Get the Active Directory Administrator:
                  $ref: "#/components/examples/Get_the_Active_Directory_Administrat\
                    or"
      tags:
        - ServerAdministrators
    put:
      description: Creates a new Server Active Directory Administrator or updates an
        existing server Active Directory Administrator.
      operationId: ServerAzureADAdministrators_CreateOrUpdate
      parameters:
        - description: The API version to use for the request.
          in: query
          name: api-version
          required: true
          x-ms-parameter-location: client
          schema:
            type: string
          examples:
            Create/Update a server administrator:
              value: 2014-04-01
        - description: The subscription ID that identifies an Azure subscription.
          in: path
          name: subscriptionId
          required: true
          x-ms-parameter-location: client
          schema:
            type: string
          examples:
            Create/Update a server administrator:
              value: 00000000-1111-2222-3333-444444444444
        - description: The name of the resource group that contains the resource. You can
            obtain this value from the Azure Resource Manager API or the portal.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Create/Update a server administrator:
              value: sqlcrudtest-4799
        - $ref: "#/components/parameters/ServerNameParameter"
        - $ref: "#/components/parameters/AdministratorNameParameter"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ServerAzureADAdministrator"
        description: The required parameters for creating or updating an Active Directory
          Administrator.
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerAzureADAdministrator"
              examples:
                Create/Update a server administrator:
                  $ref: "#/components/examples/Create_Update_a_server_administrator"
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerAzureADAdministrator"
              examples:
                Create/Update a server administrator:
                  $ref: "#/components/examples/Create_Update_a_server_administrator"
        "202":
          description: Accepted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerAzureADAdministrator"
              examples:
                Create/Update a server administrator:
                  $ref: "#/components/examples/Create_Update_a_server_administrator"
      tags:
        - ServerAdministrators
      x-ms-long-running-operation: true
servers:
  - url: https://management.azure.com
components:
  examples:
    get_a_list_of_server_administrators:
      value:
        value:
          - id: /subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/sqlcrudtest-4799/providers/Microsoft.Sql/servers/sqlcrudtest-6440/providers/Microsoft.Sql/administrators/ActiveDirectory
            name: ActiveDirectory
            properties:
              administratorType: ActiveDirectory
              login: DSEngAll
              sid: 5e90ef3b-9b42-4777-819b-25c36961ea4d
              tenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47
    Delete_a_server_administrator:
      value: No Content
    Get_the_Active_Directory_Administrator:
      value:
        id: /subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/sqlcrudtest-4799/providers/Microsoft.Sql/servers/sqlcrudtest-6440/administrators/activeDirectory
        name: activeDirectory
        properties:
          administratorType: ActiveDirectory
          login: bob@contoso.com
          sid: c6b82b90-a647-49cb-8a62-0d2d3cb7ac7c
          tenantId: c6b82b90-a647-49cb-8a62-0d2d3cb7ac7c
    Create_Update_a_server_administrator:
      value: Accepted
  parameters:
    AdministratorNameParameter:
      description: Name of the server administrator resource.
      in: path
      name: administratorName
      required: true
      x-ms-enum:
        name: ServerAdministratorName
      x-ms-parameter-location: method
      schema:
        type: string
        enum:
          - activeDirectory
      examples:
        Delete a server administrator:
          value: activeDirectory
        Get the Active Directory Administrator:
          value: activeDirectory
        Create/Update a server administrator:
          value: activeDirectory
    DatabaseExpandParameter:
      description: "A comma separated list of child objects to expand in the response.
        Possible properties: serviceTierAdvisors, transparentDataEncryption."
      in: query
      name: $expand
      required: false
      x-ms-parameter-location: method
      schema:
        type: string
    ServerNameParameter:
      description: The name of the server.
      in: path
      name: serverName
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
      examples:
        get a list of server administrators:
          value: sqlcrudtest-6440
        Delete a server administrator:
          value: sqlcrudtest-6440
        Get the Active Directory Administrator:
          value: sqlcrudtest-6440
        Create/Update a server administrator:
          value: sqlcrudtest-6440
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    ServerAdministratorListResult:
      description: The response to a list Active Directory Administrators request.
      properties:
        value:
          description: The list of server Active Directory Administrators for the server.
          items:
            $ref: "#/components/schemas/ServerAzureADAdministrator"
          type: array
    ServerAdministratorProperties:
      description: The properties of an server Administrator.
      properties:
        administratorType:
          description: The type of administrator.
          enum:
            - ActiveDirectory
          type: string
          x-ms-enum:
            name: AdministratorType
        login:
          description: The server administrator login value.
          type: string
        sid:
          description: The server administrator Sid (Secure ID).
          format: uuid
          type: string
        tenantId:
          description: The server Active Directory Administrator tenant id.
          format: uuid
          type: string
      required:
        - tenantId
        - administratorType
        - login
        - sid
    ServerAzureADAdministrator:
      allOf:
        - allOf:
            - description: ARM resource.
              properties:
                id:
                  description: Resource ID.
                  readOnly: true
                  type: string
                name:
                  description: Resource name.
                  readOnly: true
                  type: string
                type:
                  description: Resource type.
                  readOnly: true
                  type: string
              type: object
              x-ms-azure-resource: true
          description: ARM proxy resource.
          properties: {}
          type: object
      description: An server Active Directory Administrator.
      properties:
        properties:
          $ref: "#/components/schemas/ServerAdministratorProperties"
