openapi: 3.0.0
info:
  description: Describes the schema of the Azure Key Vault events published to Azure Event
    Grid. This corresponds to the Data property of an EventGridEvent.
  title: Schema of Azure Key Vault events published to Azure Event Grid
  version: 2018-01-01
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/eventgrid/data-plane/Microsoft.KeyVault/stable/2018-01-01/KeyVault.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: eventgrid-KeyVault
  x-tags:
    - Azure
    - Microsoft
paths: {}
servers:
  - url: https://azure.local
components:
  schemas:
    KeyVaultCertificateExpiredEventData:
      description: Schema of the Data property of an EventGridEvent for an
        CertificateExpired event.
      properties:
        exp:
          description: The expiration date of the object that triggered this event
          type: number
        id:
          description: The id of the object that triggered this event.
          type: string
        nbf:
          description: Not before date of the object that triggered this event
          type: number
        objectName:
          description: The name of the object that triggered this event
          type: string
        objectType:
          description: The type of the object that triggered this event
          type: string
        vaultName:
          description: Key vault name of the object that triggered this event.
          type: string
        version:
          description: The version of the object that triggered this event
          type: string
      type: object
    KeyVaultCertificateNearExpiryEventData:
      description: Schema of the Data property of an EventGridEvent for an
        CertificateNearExpiry event.
      properties:
        exp:
          description: The expiration date of the object that triggered this event
          type: number
        id:
          description: The id of the object that triggered this event.
          type: string
        nbf:
          description: Not before date of the object that triggered this event
          type: number
        objectName:
          description: The name of the object that triggered this event
          type: string
        objectType:
          description: The type of the object that triggered this event
          type: string
        vaultName:
          description: Key vault name of the object that triggered this event.
          type: string
        version:
          description: The version of the object that triggered this event
          type: string
      type: object
    KeyVaultCertificateNewVersionCreatedEventData:
      description: Schema of the Data property of an EventGridEvent for an
        CertificateNewVersionCreated event.
      properties:
        exp:
          description: The expiration date of the object that triggered this event
          type: number
        id:
          description: The id of the object that triggered this event.
          type: string
        nbf:
          description: Not before date of the object that triggered this event
          type: number
        objectName:
          description: The name of the object that triggered this event
          type: string
        objectType:
          description: The type of the object that triggered this event
          type: string
        vaultName:
          description: Key vault name of the object that triggered this event.
          type: string
        version:
          description: The version of the object that triggered this event
          type: string
      type: object
    KeyVaultKeyExpiredEventData:
      description: Schema of the Data property of an EventGridEvent for an KeyExpired event.
      properties:
        exp:
          description: The expiration date of the object that triggered this event
          type: number
        id:
          description: The id of the object that triggered this event.
          type: string
        nbf:
          description: Not before date of the object that triggered this event
          type: number
        objectName:
          description: The name of the object that triggered this event
          type: string
        objectType:
          description: The type of the object that triggered this event
          type: string
        vaultName:
          description: Key vault name of the object that triggered this event.
          type: string
        version:
          description: The version of the object that triggered this event
          type: string
      type: object
    KeyVaultKeyNearExpiryEventData:
      description: Schema of the Data property of an EventGridEvent for an KeyNearExpiry
        event.
      properties:
        exp:
          description: The expiration date of the object that triggered this event
          type: number
        id:
          description: The id of the object that triggered this event.
          type: string
        nbf:
          description: Not before date of the object that triggered this event
          type: number
        objectName:
          description: The name of the object that triggered this event
          type: string
        objectType:
          description: The type of the object that triggered this event
          type: string
        vaultName:
          description: Key vault name of the object that triggered this event.
          type: string
        version:
          description: The version of the object that triggered this event
          type: string
      type: object
    KeyVaultKeyNewVersionCreatedEventData:
      description: Schema of the Data property of an EventGridEvent for an
        KeyNewVersionCreated event.
      properties:
        exp:
          description: The expiration date of the object that triggered this event
          type: number
        id:
          description: The id of the object that triggered this event.
          type: string
        nbf:
          description: Not before date of the object that triggered this event
          type: number
        objectName:
          description: The name of the object that triggered this event
          type: string
        objectType:
          description: The type of the object that triggered this event
          type: string
        vaultName:
          description: Key vault name of the object that triggered this event.
          type: string
        version:
          description: The version of the object that triggered this event
          type: string
      type: object
    KeyVaultSecretExpiredEventData:
      description: Schema of the Data property of an EventGridEvent for an SecretExpired
        event.
      properties:
        exp:
          description: The expiration date of the object that triggered this event
          type: number
        id:
          description: The id of the object that triggered this event.
          type: string
        nbf:
          description: Not before date of the object that triggered this event
          type: number
        objectName:
          description: The name of the object that triggered this event
          type: string
        objectType:
          description: The type of the object that triggered this event
          type: string
        vaultName:
          description: Key vault name of the object that triggered this event.
          type: string
        version:
          description: The version of the object that triggered this event
          type: string
      type: object
    KeyVaultSecretNearExpiryEventData:
      description: Schema of the Data property of an EventGridEvent for an SecretNearExpiry
        event.
      properties:
        exp:
          description: The expiration date of the object that triggered this event
          type: number
        id:
          description: The id of the object that triggered this event.
          type: string
        nbf:
          description: Not before date of the object that triggered this event
          type: number
        objectName:
          description: The name of the object that triggered this event
          type: string
        objectType:
          description: The type of the object that triggered this event
          type: string
        vaultName:
          description: Key vault name of the object that triggered this event.
          type: string
        version:
          description: The version of the object that triggered this event
          type: string
      type: object
    KeyVaultSecretNewVersionCreatedEventData:
      description: Schema of the Data property of an EventGridEvent for an
        SecretNewVersionCreated event.
      properties:
        exp:
          description: The expiration date of the object that triggered this event
          type: number
        id:
          description: The id of the object that triggered this event.
          type: string
        nbf:
          description: Not before date of the object that triggered this event
          type: number
        objectName:
          description: The name of the object that triggered this event
          type: string
        objectType:
          description: The type of the object that triggered this event
          type: string
        vaultName:
          description: Key vault name of the object that triggered this event.
          type: string
        version:
          description: The version of the object that triggered this event
          type: string
      type: object
