openapi: 3.0.0
info:
  description: API spec for Microsoft.Security (Azure Security Center) resource provider
  title: Security Center
  version: 2017-08-01-preview
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/security/resource-manager/Microsoft.Security/preview/2017-08-01-preview/securityContacts.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: security-securityContacts
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  "/subscriptions/{subscriptionId}/providers/Microsoft.Security/securityContacts":
    get:
      description: Security contact configurations for the subscription
      operationId: SecurityContacts_List
      parameters:
        - description: API version for the operation
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Update security contact data full:
              value: 2017-08-01-preview
            Update security contact data minimal:
              value: 2017-08-01-preview
        - description: Azure subscription ID
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
            pattern: ^[0-9A-Fa-f]{8}-([0-9A-Fa-f]{4}-){3}[0-9A-Fa-f]{12}$
          examples:
            Update security contact data full:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
            Update security contact data minimal:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SecurityContactList"
              examples:
                Update security contact data full:
                  $ref: "#/components/examples/Update_security_contact_data_full"
                Update security contact data minimal:
                  $ref: "#/components/examples/Update_security_contact_data_minimal"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response structure.
                properties:
                  error:
                    description: Error details.
                    properties:
                      code:
                        description: An identifier for the error. Codes are invariant and
                          are intended to be consumed programmatically.
                        readOnly: true
                        type: string
                      message:
                        description: A message describing the error, intended to be
                          suitable for display in a user interface.
                        readOnly: true
                        type: string
                    type: object
                    x-ms-external: true
                type: object
                x-ms-external: true
      tags:
        - Security Contacts
      x-ms-pageable:
        nextLinkName: nextLink
  "/subscriptions/{subscriptionId}/providers/Microsoft.Security/securityContacts/{securityContactName}":
    delete:
      description: Security contact configurations for the subscription
      operationId: SecurityContacts_Delete
      parameters:
        - description: API version for the operation
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Delete security contact data:
              value: 2017-08-01-preview
        - description: Azure subscription ID
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
            pattern: ^[0-9A-Fa-f]{8}-([0-9A-Fa-f]{4}-){3}[0-9A-Fa-f]{12}$
          examples:
            Delete security contact data:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
        - $ref: "#/components/parameters/SecurityContactName"
      responses:
        "204":
          description: No Content
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response structure.
                properties:
                  error:
                    description: Error details.
                    properties:
                      code:
                        description: An identifier for the error. Codes are invariant and
                          are intended to be consumed programmatically.
                        readOnly: true
                        type: string
                      message:
                        description: A message describing the error, intended to be
                          suitable for display in a user interface.
                        readOnly: true
                        type: string
                    type: object
                    x-ms-external: true
                type: object
                x-ms-external: true
      tags:
        - Security Contacts
    get:
      description: Security contact configurations for the subscription
      operationId: SecurityContacts_Get
      parameters:
        - description: API version for the operation
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Get security contact data full:
              value: 2017-08-01-preview
            Get security contact data minimal:
              value: 2017-08-01-preview
        - description: Azure subscription ID
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
            pattern: ^[0-9A-Fa-f]{8}-([0-9A-Fa-f]{4}-){3}[0-9A-Fa-f]{12}$
          examples:
            Get security contact data full:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
            Get security contact data minimal:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
        - $ref: "#/components/parameters/SecurityContactName"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SecurityContact"
              examples:
                Get security contact data full:
                  $ref: "#/components/examples/Get_security_contact_data_full"
                Get security contact data minimal:
                  $ref: "#/components/examples/Get_security_contact_data_minimal"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response structure.
                properties:
                  error:
                    description: Error details.
                    properties:
                      code:
                        description: An identifier for the error. Codes are invariant and
                          are intended to be consumed programmatically.
                        readOnly: true
                        type: string
                      message:
                        description: A message describing the error, intended to be
                          suitable for display in a user interface.
                        readOnly: true
                        type: string
                    type: object
                    x-ms-external: true
                type: object
                x-ms-external: true
      tags:
        - Security Contacts
    patch:
      description: Security contact configurations for the subscription
      operationId: SecurityContacts_Update
      parameters:
        - description: API version for the operation
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Update security contact data full:
              value: 2017-08-01-preview
            Update security contact data minimal:
              value: 2017-08-01-preview
        - description: Azure subscription ID
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
            pattern: ^[0-9A-Fa-f]{8}-([0-9A-Fa-f]{4}-){3}[0-9A-Fa-f]{12}$
          examples:
            Update security contact data full:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
            Update security contact data minimal:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
        - $ref: "#/components/parameters/SecurityContactName"
      requestBody:
        $ref: "#/components/requestBodies/SecurityContact"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SecurityContact"
              examples:
                Update security contact data full:
                  $ref: "#/components/examples/Update_security_contact_data_full"
                Update security contact data minimal:
                  $ref: "#/components/examples/Update_security_contact_data_minimal"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response structure.
                properties:
                  error:
                    description: Error details.
                    properties:
                      code:
                        description: An identifier for the error. Codes are invariant and
                          are intended to be consumed programmatically.
                        readOnly: true
                        type: string
                      message:
                        description: A message describing the error, intended to be
                          suitable for display in a user interface.
                        readOnly: true
                        type: string
                    type: object
                    x-ms-external: true
                type: object
                x-ms-external: true
      tags:
        - Security Contacts
    put:
      description: Security contact configurations for the subscription
      operationId: SecurityContacts_Create
      parameters:
        - description: API version for the operation
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Create security contact data full:
              value: 2017-08-01-preview
            Create security contact data minimal:
              value: 2017-08-01-preview
        - description: Azure subscription ID
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
            pattern: ^[0-9A-Fa-f]{8}-([0-9A-Fa-f]{4}-){3}[0-9A-Fa-f]{12}$
          examples:
            Create security contact data full:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
            Create security contact data minimal:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
        - $ref: "#/components/parameters/SecurityContactName"
      requestBody:
        $ref: "#/components/requestBodies/SecurityContact"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SecurityContact"
              examples:
                Create security contact data full:
                  $ref: "#/components/examples/Create_security_contact_data_full"
                Create security contact data minimal:
                  $ref: "#/components/examples/Create_security_contact_data_minimal"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response structure.
                properties:
                  error:
                    description: Error details.
                    properties:
                      code:
                        description: An identifier for the error. Codes are invariant and
                          are intended to be consumed programmatically.
                        readOnly: true
                        type: string
                      message:
                        description: A message describing the error, intended to be
                          suitable for display in a user interface.
                        readOnly: true
                        type: string
                    type: object
                    x-ms-external: true
                type: object
                x-ms-external: true
      tags:
        - Security Contacts
servers:
  - url: https://management.azure.com
components:
  examples:
    Update_security_contact_data_full:
      value:
        id: /subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23/providers/Microsoft.Security/securityContacts/default1
        name: default1
        properties:
          alertNotifications: On
          alertsToAdmins: Off
          email: john@contoso.com
          phone: (214)275-4038
        type: Microsoft.Security/securityContacts
    Update_security_contact_data_minimal:
      value:
        id: /subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23/providers/Microsoft.Security/securityContacts/default2
        name: default2
        properties:
          alertNotifications: On
          alertsToAdmins: Off
          email: chen@contoso.com
        type: Microsoft.Security/securityContacts
    Get_security_contact_data_full:
      value:
        id: /subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23/providers/Microsoft.Security/securityContacts/default1
        name: default1
        properties:
          alertNotifications: On
          alertsToAdmins: On
          email: john@contoso.com
          phone: (214)275-4038
        type: Microsoft.Security/securityContacts
    Get_security_contact_data_minimal:
      value:
        id: /subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23/providers/Microsoft.Security/securityContacts/default2
        name: default2
        properties:
          alertNotifications: On
          alertsToAdmins: On
          email: chen@contoso.com
        type: Microsoft.Security/securityContacts
    Create_security_contact_data_full:
      value:
        id: /subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23/providers/Microsoft.Security/securityContacts/default1
        name: default1
        properties:
          alertNotifications: On
          alertsToAdmins: On
          email: john@contoso.com
          phone: (214)275-4038
        type: Microsoft.Security/securityContacts
    Create_security_contact_data_minimal:
      value:
        id: /subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23/providers/Microsoft.Security/securityContacts/default2
        name: default2
        properties:
          alertNotifications: On
          alertsToAdmins: On
          email: chen@contoso.com
        type: Microsoft.Security/securityContacts
  parameters:
    SecurityContactName:
      description: Name of the security contact object
      in: path
      name: securityContactName
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
      examples:
        Delete security contact data:
          value: default1
        Get security contact data full:
          value: default1
        Get security contact data minimal:
          value: default2
        Update security contact data full:
          value: john
        Update security contact data minimal:
          value: default2
        Create security contact data full:
          value: default1
        Create security contact data minimal:
          value: default2
  requestBodies:
    SecurityContact:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/SecurityContact"
      description: Security contact object
      required: true
      x-ms-parameter-location: method
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    SecurityContact:
      allOf:
        - description: Describes an Azure resource.
          properties:
            id:
              description: Resource Id
              readOnly: true
              type: string
            name:
              description: Resource name
              readOnly: true
              type: string
            type:
              description: Resource type
              readOnly: true
              type: string
          type: object
          x-ms-azure-resource: true
      description: Contact details for security issues
      properties:
        properties:
          $ref: "#/components/schemas/SecurityContactProperties"
      type: object
    SecurityContactList:
      description: List of security contacts response
      properties:
        nextLink:
          description: The URI to fetch the next page.
          readOnly: true
          type: string
        value:
          description: List of security contacts
          items:
            $ref: "#/components/schemas/SecurityContact"
          readOnly: true
          type: array
      type: object
    SecurityContactProperties:
      description: describes security contact properties
      properties:
        alertNotifications:
          description: Whether to send security alerts notifications to the security contact
          enum:
            - On
            - Off
          type: string
          x-ms-enum:
            modelAsString: true
            name: alertNotifications
            values:
              - description: Get notifications on new alerts
                value: On
              - description: Don't get notifications on new alerts
                value: Off
        alertsToAdmins:
          description: Whether to send security alerts notifications to subscription admins
          enum:
            - On
            - Off
          type: string
          x-ms-enum:
            modelAsString: true
            name: alertsToAdmins
            values:
              - description: Send notification on new alerts to the subscription's admins
                value: On
              - description: Don't send notification on new alerts to the subscription's
                  admins
                value: Off
        email:
          description: The email of this security contact
          format: email
          type: string
        phone:
          description: The phone number of this security contact
          type: string
      required:
        - email
        - alertNotifications
        - alertsToAdmins
      type: object
