openapi: 3.0.0
info:
  description: Describes the schema of the Azure IoT Hub events published to Azure Event
    Grid. This corresponds to the Data property of an EventGridEvent.
  title: Schema of Azure IoT Hub events published to Azure Event Grid
  version: 2018-01-01
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/eventgrid/data-plane/Microsoft.Devices/stable/2018-01-01/IotHub.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: eventgrid-IotHub
  x-tags:
    - Azure
    - Microsoft
paths: {}
servers:
  - url: https://azure.local
components:
  schemas:
    DeviceConnectionStateEventInfo:
      description: Information about the device connection state event.
      properties:
        sequenceNumber:
          description: Sequence number is string representation of a hexadecimal number.
            string compare can be used to identify the larger number because
            both in ASCII and HEX numbers come after alphabets. If you are
            converting the string to hex, then the number is a 256 bit number.
          type: string
      type: object
    DeviceConnectionStateEventProperties:
      description: Schema of the Data property of an EventGridEvent for a device connection
        state event (DeviceConnected, DeviceDisconnected).
      properties:
        deviceConnectionStateEventInfo:
          $ref: "#/components/schemas/DeviceConnectionStateEventInfo"
        deviceId:
          description: "The unique identifier of the device. This case-sensitive string can
            be up to 128 characters long, and supports ASCII 7-bit alphanumeric
            characters plus the following special characters: - : . + % _ &#35;
            * ? ! ( ) , = @ ; $ '."
          type: string
        hubName:
          description: Name of the IoT Hub where the device was created or deleted.
          type: string
        moduleId:
          description: "The unique identifier of the module. This case-sensitive string can
            be up to 128 characters long, and supports ASCII 7-bit alphanumeric
            characters plus the following special characters: - : . + % _ &#35;
            * ? ! ( ) , = @ ; $ '."
          type: string
      type: object
    DeviceLifeCycleEventProperties:
      description: Schema of the Data property of an EventGridEvent for a device life cycle
        event (DeviceCreated, DeviceDeleted).
      properties:
        deviceId:
          description: "The unique identifier of the device. This case-sensitive string can
            be up to 128 characters long, and supports ASCII 7-bit alphanumeric
            characters plus the following special characters: - : . + % _ &#35;
            * ? ! ( ) , = @ ; $ '."
          type: string
        hubName:
          description: Name of the IoT Hub where the device was created or deleted.
          type: string
        twin:
          $ref: "#/components/schemas/DeviceTwinInfo"
      type: object
    DeviceTelemetryEventProperties:
      description: Schema of the Data property of an EventGridEvent for a device telemetry
        event (DeviceTelemetry).
      properties:
        body:
          description: The content of the message from the device.
          type: object
        properties:
          additionalProperties:
            type: string
          description: Application properties are user-defined strings that can be added to
            the message. These fields are optional.
          type: object
        systemProperties:
          additionalProperties:
            type: string
          description: System properties help identify contents and source of the messages.
          type: object
      type: object
    DeviceTwinInfo:
      description: Information about the device twin, which is the cloud representation of
        application device metadata.
      properties:
        authenticationType:
          description: "Authentication type used for this device: either SAS, SelfSigned,
            or CertificateAuthority."
          type: string
        cloudToDeviceMessageCount:
          description: Count of cloud to device messages sent to this device.
          type: number
        connectionState:
          description: Whether the device is connected or disconnected.
          type: string
        deviceId:
          description: The unique identifier of the device twin.
          type: string
        etag:
          description: A piece of information that describes the content of the device
            twin. Each etag is guaranteed to be unique per device twin.
          type: string
        lastActivityTime:
          description: The ISO8601 timestamp of the last activity.
          type: string
        properties:
          description: Properties JSON element.
          properties:
            desired:
              $ref: "#/components/schemas/DeviceTwinProperties"
            reported:
              $ref: "#/components/schemas/DeviceTwinProperties"
          type: object
        status:
          description: Whether the device twin is enabled or disabled.
          type: string
        statusUpdateTime:
          description: The ISO8601 timestamp of the last device twin status update.
          type: string
        version:
          description: An integer that is incremented by one each time the device twin is
            updated.
          type: number
        x509Thumbprint:
          description: The thumbprint is a unique value for the x509 certificate, commonly
            used to find a particular certificate in a certificate store. The
            thumbprint is dynamically generated using the SHA1 algorithm, and
            does not physically exist in the certificate.
          properties:
            primaryThumbprint:
              description: Primary thumbprint for the x509 certificate.
              type: string
            secondaryThumbprint:
              description: Secondary thumbprint for the x509 certificate.
              type: string
          type: object
      type: object
    DeviceTwinMetadata:
      description: Metadata information for the properties JSON document.
      properties:
        lastUpdated:
          description: The ISO8601 timestamp of the last time the properties were updated.
          type: string
          x-ms-client-name: $lastUpdated
      type: object
    DeviceTwinProperties:
      description: A portion of the properties that can be written only by the application
        back-end, and read by the device.
      properties:
        metadata:
          $ref: "#/components/schemas/DeviceTwinMetadata"
        version:
          description: Version of device twin properties.
          type: number
          x-ms-client-name: $version
      type: object
    IotHubDeviceConnectedEventData:
      allOf:
        - $ref: "#/components/schemas/DeviceConnectionStateEventProperties"
      description: Event data for Microsoft.Devices.DeviceConnected event.
      properties: {}
    IotHubDeviceCreatedEventData:
      allOf:
        - $ref: "#/components/schemas/DeviceLifeCycleEventProperties"
      description: Event data for Microsoft.Devices.DeviceCreated event.
      properties: {}
    IotHubDeviceDeletedEventData:
      allOf:
        - $ref: "#/components/schemas/DeviceLifeCycleEventProperties"
      description: Event data for Microsoft.Devices.DeviceDeleted event.
      properties: {}
    IotHubDeviceDisconnectedEventData:
      allOf:
        - $ref: "#/components/schemas/DeviceConnectionStateEventProperties"
      description: Event data for Microsoft.Devices.DeviceDisconnected event.
      properties: {}
    IotHubDeviceTelemetryEventData:
      allOf:
        - $ref: "#/components/schemas/DeviceTelemetryEventProperties"
      description: Event data for Microsoft.Devices.DeviceTelemetry event.
      properties: {}
