openapi: 3.0.0
info:
  title: Azure Database Migration Service Resource Provider
  version: 2018-04-19
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/datamigration/resource-manager/Microsoft.DataMigration/stable/2018-04-19/definitions/ValidateMigrationInputSqlServerSqlMITask.json
      version: "2.0"
  x-preferred: false
  x-providerName: azure.com
  x-serviceName: datamigration-ValidateMigrationInputSqlServerSqlMITask
  x-tags:
    - Azure
    - Microsoft
paths: {}
servers:
  - url: https://azure.local
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    ValidateMigrationInputSqlServerSqlMITaskInput:
      description: Input for task that validates migration input for SQL to Azure SQL
        Managed Instance
      properties:
        backupBlobShare:
          description: Blob container storage information.
          properties:
            sasUri:
              description: SAS URI of Azure Storage Account Container.
              type: string
          required:
            - sasUri
          type: object
        backupFileShare:
          description: File share information with Path, Username, and Password.
          properties:
            password:
              description: Password credential used to connect to the share location.
              type: string
            path:
              description: The folder path for this share.
              type: string
            userName:
              description: User name credential to connect to the share location
              type: string
          required:
            - path
          type: object
        backupMode:
          description: An enumeration of backup modes
          enum:
            - CreateBackup
            - ExistingBackup
          type: string
          x-ms-enum:
            modelAsString: true
            name: BackupMode
        selectedDatabases:
          description: Databases to migrate
          items:
            description: Database specific information for SQL to Azure SQL DB Managed
              Instance migration task inputs
            properties:
              backupFilePaths:
                description: The list of backup files to be used in case of existing
                  backups.
                items:
                  type: string
                type: array
              backupFileShare:
                description: File share information with Path, Username, and Password.
                properties:
                  password:
                    description: Password credential used to connect to the share location.
                    type: string
                  path:
                    description: The folder path for this share.
                    type: string
                  userName:
                    description: User name credential to connect to the share location
                    type: string
                required:
                  - path
                type: object
              name:
                description: Name of the database
                type: string
              restoreDatabaseName:
                description: Name of the database at destination
                type: string
            required:
              - name
              - restoreDatabaseName
            type: object
          type: array
        selectedLogins:
          description: Logins to migrate
          items:
            type: string
          type: array
        sourceConnectionInfo:
          allOf:
            - description: Defines the connection properties of a server
              discriminator:
                propertyName: type
              properties:
                password:
                  description: Password credential.
                  type: string
                type:
                  description: Type of connection info
                  type: string
                userName:
                  description: User name
                  type: string
              required:
                - type
              type: object
          description: Information for connecting to SQL database server
          properties:
            additionalSettings:
              description: Additional connection settings
              type: string
            authentication:
              description: An enumeration of possible authentication types when connecting
              enum:
                - None
                - WindowsAuthentication
                - SqlAuthentication
                - ActiveDirectoryIntegrated
                - ActiveDirectoryPassword
              type: string
              x-ms-enum:
                modelAsString: true
                name: AuthenticationType
            dataSource:
              description: Data source in the format
                Protocol:MachineName\SQLServerInstanceName,PortNumber
              type: string
            encryptConnection:
              default: true
              description: Whether to encrypt the connection
              type: boolean
            platform:
              description: An enumeration of source platform types
              enum:
                - SqlOnPrem
              type: string
              x-ms-enum:
                modelAsString: true
                name: SqlSourcePlatform
            trustServerCertificate:
              default: false
              description: Whether to trust the server certificate
              type: boolean
          required:
            - dataSource
          type: object
          x-ms-discriminator-value: SqlConnectionInfo
        targetConnectionInfo:
          allOf:
            - description: Defines the connection properties of a server
              discriminator:
                propertyName: type
              properties:
                password:
                  description: Password credential.
                  type: string
                type:
                  description: Type of connection info
                  type: string
                userName:
                  description: User name
                  type: string
              required:
                - type
              type: object
          description: Information for connecting to SQL database server
          properties:
            additionalSettings:
              description: Additional connection settings
              type: string
            authentication:
              description: An enumeration of possible authentication types when connecting
              enum:
                - None
                - WindowsAuthentication
                - SqlAuthentication
                - ActiveDirectoryIntegrated
                - ActiveDirectoryPassword
              type: string
              x-ms-enum:
                modelAsString: true
                name: AuthenticationType
            dataSource:
              description: Data source in the format
                Protocol:MachineName\SQLServerInstanceName,PortNumber
              type: string
            encryptConnection:
              default: true
              description: Whether to encrypt the connection
              type: boolean
            platform:
              description: An enumeration of source platform types
              enum:
                - SqlOnPrem
              type: string
              x-ms-enum:
                modelAsString: true
                name: SqlSourcePlatform
            trustServerCertificate:
              default: false
              description: Whether to trust the server certificate
              type: boolean
          required:
            - dataSource
          type: object
          x-ms-discriminator-value: SqlConnectionInfo
      required:
        - sourceConnectionInfo
        - targetConnectionInfo
        - selectedDatabases
        - backupBlobShare
      type: object
    ValidateMigrationInputSqlServerSqlMITaskOutput:
      description: Output for task that validates migration input for SQL to Azure SQL
        Managed Instance migrations
      properties:
        backupFolderErrors:
          description: Errors associated with the BackupFolder path
          items:
            description: Exception object for all custom exceptions
            properties:
              actionableMessage:
                description: Actionable steps for this exception
                type: string
              filePath:
                description: The path to the file where exception occurred
                readOnly: true
                type: string
              hResult:
                description: Coded numerical value that is assigned to a specific exception
                readOnly: true
                type: integer
              lineNumber:
                description: The line number where exception occurred
                readOnly: true
                type: string
              message:
                description: Error message
                readOnly: true
                type: string
              stackTrace:
                description: Stack trace
                readOnly: true
                type: string
            type: object
          readOnly: true
          type: array
        backupShareCredentialsErrors:
          description: Errors associated with backup share user name and password
            credentials
          items:
            description: Exception object for all custom exceptions
            properties:
              actionableMessage:
                description: Actionable steps for this exception
                type: string
              filePath:
                description: The path to the file where exception occurred
                readOnly: true
                type: string
              hResult:
                description: Coded numerical value that is assigned to a specific exception
                readOnly: true
                type: integer
              lineNumber:
                description: The line number where exception occurred
                readOnly: true
                type: string
              message:
                description: Error message
                readOnly: true
                type: string
              stackTrace:
                description: Stack trace
                readOnly: true
                type: string
            type: object
          readOnly: true
          type: array
        backupStorageAccountErrors:
          description: Errors associated with the storage account provided.
          items:
            description: Exception object for all custom exceptions
            properties:
              actionableMessage:
                description: Actionable steps for this exception
                type: string
              filePath:
                description: The path to the file where exception occurred
                readOnly: true
                type: string
              hResult:
                description: Coded numerical value that is assigned to a specific exception
                readOnly: true
                type: integer
              lineNumber:
                description: The line number where exception occurred
                readOnly: true
                type: string
              message:
                description: Error message
                readOnly: true
                type: string
              stackTrace:
                description: Stack trace
                readOnly: true
                type: string
            type: object
          readOnly: true
          type: array
        databaseBackupInfo:
          description: Information about backup files when existing backup mode is used.
          properties:
            backupFiles:
              description: The list of backup files for the current database.
              items:
                type: string
              readOnly: true
              type: array
            backupFinishDate:
              description: Date and time when the backup operation finished.
              format: date-time
              readOnly: true
              type: string
            backupType:
              description: Enum of the different backup types.
              enum:
                - Database
                - TransactionLog
                - File
                - DifferentialDatabase
                - DifferentialFile
                - Partial
                - DifferentialPartial
              type: string
              x-ms-enum:
                modelAsString: true
                name: BackupType
            databaseName:
              description: Database name.
              readOnly: true
              type: string
            familyCount:
              description: Number of files in the backup set.
              readOnly: true
              type: integer
            isCompressed:
              description: Whether the backup set is compressed
              readOnly: true
              type: boolean
            isDamaged:
              description: Database was damaged when backed up, but the backup operation
                was requested to continue despite errors.
              readOnly: true
              type: boolean
            position:
              description: Position of current database backup in the file.
              readOnly: true
              type: integer
          type: object
        existingBackupErrors:
          description: Errors associated with existing backup files.
          items:
            description: Exception object for all custom exceptions
            properties:
              actionableMessage:
                description: Actionable steps for this exception
                type: string
              filePath:
                description: The path to the file where exception occurred
                readOnly: true
                type: string
              hResult:
                description: Coded numerical value that is assigned to a specific exception
                readOnly: true
                type: integer
              lineNumber:
                description: The line number where exception occurred
                readOnly: true
                type: string
              message:
                description: Error message
                readOnly: true
                type: string
              stackTrace:
                description: Stack trace
                readOnly: true
                type: string
            type: object
          readOnly: true
          type: array
        id:
          description: Result identifier
          readOnly: true
          type: string
        name:
          description: Name of database
          readOnly: true
          type: string
        restoreDatabaseNameErrors:
          description: Errors associated with the RestoreDatabaseName
          items:
            description: Exception object for all custom exceptions
            properties:
              actionableMessage:
                description: Actionable steps for this exception
                type: string
              filePath:
                description: The path to the file where exception occurred
                readOnly: true
                type: string
              hResult:
                description: Coded numerical value that is assigned to a specific exception
                readOnly: true
                type: integer
              lineNumber:
                description: The line number where exception occurred
                readOnly: true
                type: string
              message:
                description: Error message
                readOnly: true
                type: string
              stackTrace:
                description: Stack trace
                readOnly: true
                type: string
            type: object
          readOnly: true
          type: array
      type: object
