openapi: 3.0.0
info:
  title: Azure Database Migration Service Resource Provider
  version: 2018-04-19
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/datamigration/resource-manager/Microsoft.DataMigration/stable/2018-04-19/definitions/ConnectToSourceSqlServerTask.json
      version: "2.0"
  x-preferred: false
  x-providerName: azure.com
  x-serviceName: datamigration-ConnectToSourceSqlServerTask
  x-tags:
    - Azure
    - Microsoft
paths: {}
servers:
  - url: https://azure.local
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    ConnectToSourceSqlServerTaskInput:
      description: Input for the task that validates connection to SQL Server and also
        validates source server requirements
      properties:
        checkPermissionsGroup:
          description: Permission group for validations. These groups will run a set of
            permissions for validating user activity. Select the permission
            group for the activity that you are performing.
          enum:
            - Default
            - MigrationFromSqlServerToAzureDB
            - MigrationFromSqlServerToAzureMI
            - MigrationFromMySQLToAzureDBForMySQL
          type: string
          x-ms-enum:
            name: ServerLevelPermissionsGroup
        collectAgentJobs:
          default: false
          description: Flag for whether to collect agent jobs from source server.
          type: boolean
        collectLogins:
          default: false
          description: Flag for whether to collect logins from source server.
          type: boolean
        sourceConnectionInfo:
          allOf:
            - description: Defines the connection properties of a server
              discriminator:
                propertyName: type
              properties:
                password:
                  description: Password credential.
                  type: string
                type:
                  description: Type of connection info
                  type: string
                userName:
                  description: User name
                  type: string
              required:
                - type
              type: object
          description: Information for connecting to SQL database server
          properties:
            additionalSettings:
              description: Additional connection settings
              type: string
            authentication:
              description: An enumeration of possible authentication types when connecting
              enum:
                - None
                - WindowsAuthentication
                - SqlAuthentication
                - ActiveDirectoryIntegrated
                - ActiveDirectoryPassword
              type: string
              x-ms-enum:
                modelAsString: true
                name: AuthenticationType
            dataSource:
              description: Data source in the format
                Protocol:MachineName\SQLServerInstanceName,PortNumber
              type: string
            encryptConnection:
              default: true
              description: Whether to encrypt the connection
              type: boolean
            platform:
              description: An enumeration of source platform types
              enum:
                - SqlOnPrem
              type: string
              x-ms-enum:
                modelAsString: true
                name: SqlSourcePlatform
            trustServerCertificate:
              default: false
              description: Whether to trust the server certificate
              type: boolean
          required:
            - dataSource
          type: object
          x-ms-discriminator-value: SqlConnectionInfo
      required:
        - sourceConnectionInfo
      type: object
    ConnectToSourceSqlServerTaskOutput:
      description: Output for the task that validates connection to SQL Server and also
        validates source server requirements
      discriminator:
        propertyName: resultType
      properties:
        id:
          description: Result identifier
          readOnly: true
          type: string
        resultType:
          description: Type of result - database level or task level
          type: string
      required:
        - resultType
      type: object
    ConnectToSourceSqlServerTaskOutputAgentJobLevel:
      allOf:
        - $ref: "#/components/schemas/ConnectToSourceSqlServerTaskOutput"
      description: AgentJob level output for the task that validates connection to SQL
        Server and also validates source server requirements
      properties:
        isEnabled:
          description: The state of the original AgentJob.
          readOnly: true
          type: boolean
        jobCategory:
          description: The type of AgentJob.
          readOnly: true
          type: string
        jobOwner:
          description: The owner of the AgentJob
          readOnly: true
          type: string
        lastExecutedOn:
          description: UTC Date and time when the AgentJob was last executed.
          format: date-time
          readOnly: true
          type: string
        migrationEligibility:
          description: Information about migration eligibility of a server object
          properties:
            isEligibleForMigration:
              description: Whether object is eligible for migration or not.
              readOnly: true
              type: boolean
            validationMessages:
              description: Information about eligibility failure for the server object.
              items:
                type: string
              readOnly: true
              type: array
          type: object
        name:
          description: AgentJob name
          readOnly: true
          type: string
      type: object
      x-ms-discriminator-value: AgentJobLevelOutput
    ConnectToSourceSqlServerTaskOutputDatabaseLevel:
      allOf:
        - $ref: "#/components/schemas/ConnectToSourceSqlServerTaskOutput"
      description: Database level output for the task that validates connection to SQL
        Server and also validates source server requirements
      properties:
        compatibilityLevel:
          description: An enumeration of SQL Server database compatibility levels
          enum:
            - CompatLevel80
            - CompatLevel90
            - CompatLevel100
            - CompatLevel110
            - CompatLevel120
            - CompatLevel130
            - CompatLevel140
          type: string
          x-ms-enum:
            modelAsString: true
            name: DatabaseCompatLevel
        databaseFiles:
          description: The list of database files
          items:
            description: Database file specific information
            properties:
              databaseName:
                description: Name of the database
                type: string
              fileType:
                description: An enumeration of SQL Server database file types
                enum:
                  - Rows
                  - Log
                  - Filestream
                  - NotSupported
                  - Fulltext
                type: string
                x-ms-enum:
                  modelAsString: true
                  name: DatabaseFileType
              id:
                description: Unique identifier for database file
                type: string
              logicalName:
                description: Logical name of the file
                type: string
              physicalFullName:
                description: Operating-system full path of the file
                type: string
              restoreFullName:
                description: Suggested full path of the file for restoring
                type: string
              sizeMB:
                description: Size of the file in megabytes
                format: double
                type: number
            type: object
          readOnly: true
          type: array
        databaseState:
          description: An enumeration of SQL Server Database states
          enum:
            - Online
            - Restoring
            - Recovering
            - RecoveryPending
            - Suspect
            - Emergency
            - Offline
            - Copying
            - OfflineSecondary
          type: string
          x-ms-enum:
            modelAsString: true
            name: DatabaseState
        name:
          description: Database name
          readOnly: true
          type: string
        sizeMB:
          description: Size of the file in megabytes
          format: double
          readOnly: true
          type: number
      type: object
      x-ms-discriminator-value: DatabaseLevelOutput
    ConnectToSourceSqlServerTaskOutputLoginLevel:
      allOf:
        - $ref: "#/components/schemas/ConnectToSourceSqlServerTaskOutput"
      description: Login level output for the task that validates connection to SQL Server
        and also validates source server requirements
      properties:
        defaultDatabase:
          description: The default database for the login.
          readOnly: true
          type: string
        isEnabled:
          description: The state of the login.
          readOnly: true
          type: boolean
        loginType:
          description: Enum mapping of SMO LoginType.
          enum:
            - WindowsUser
            - WindowsGroup
            - SqlLogin
            - Certificate
            - AsymmetricKey
            - ExternalUser
            - ExternalGroup
          type: string
          x-ms-enum:
            modelAsString: true
            name: LoginType
        migrationEligibility:
          description: Information about migration eligibility of a server object
          properties:
            isEligibleForMigration:
              description: Whether object is eligible for migration or not.
              readOnly: true
              type: boolean
            validationMessages:
              description: Information about eligibility failure for the server object.
              items:
                type: string
              readOnly: true
              type: array
          type: object
        name:
          description: Login name.
          readOnly: true
          type: string
      type: object
      x-ms-discriminator-value: LoginLevelOutput
    ConnectToSourceSqlServerTaskOutputTaskLevel:
      allOf:
        - $ref: "#/components/schemas/ConnectToSourceSqlServerTaskOutput"
      description: Task level output for the task that validates connection to SQL Server
        and also validates source server requirements
      properties:
        agentJobs:
          additionalProperties:
            type: string
          description: Source agent jobs as a map from agent job name to id.
          readOnly: true
          type: string
        databases:
          additionalProperties:
            type: string
          description: Source databases as a map from database name to database id
          readOnly: true
          type: string
        logins:
          additionalProperties:
            type: string
          description: Source logins as a map from login name to login id.
          readOnly: true
          type: string
        sourceServerBrandVersion:
          description: Source server brand version
          readOnly: true
          type: string
        sourceServerVersion:
          description: Source server version
          readOnly: true
          type: string
        validationErrors:
          description: Validation errors
          items:
            description: Exception object for all custom exceptions
            properties:
              actionableMessage:
                description: Actionable steps for this exception
                type: string
              filePath:
                description: The path to the file where exception occurred
                readOnly: true
                type: string
              hResult:
                description: Coded numerical value that is assigned to a specific exception
                readOnly: true
                type: integer
              lineNumber:
                description: The line number where exception occurred
                readOnly: true
                type: string
              message:
                description: Error message
                readOnly: true
                type: string
              stackTrace:
                description: Stack trace
                readOnly: true
                type: string
            type: object
          readOnly: true
          type: array
      type: object
      x-ms-discriminator-value: TaskLevelOutput
