openapi: 3.0.0
info:
  description: The Computer Vision API provides state-of-the-art algorithms to process
    images and return information. For example, it can be used to determine if
    an image contains mature content, or it can be used to find all the faces in
    an image.  It also has other features like estimating dominant and accent
    colors, categorizing the content of images, and describing an image with
    complete English sentences.  Additionally, it can also intelligently
    generate images thumbnails for displaying large images effectively.
  title: Form Recognizer Client
  version: 1.0-preview
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/cognitiveservices/data-plane/FormRecognizer/preview/v1.0/FormRecognizerReceiptOcr.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: cognitiveservices-FormRecognizerReceiptOcr
  x-tags:
    - Azure
    - Microsoft
paths: {}
servers:
  - url: https://azure.local
components:
  parameters:
    Endpoint:
      description: "Supported Cognitive Services endpoints (protocol and hostname, for
        example: https://westus2.api.cognitive.microsoft.com)."
      in: path
      name: Endpoint
      required: true
      x-ms-parameter-location: client
      x-ms-skip-url-encoding: true
      schema:
        type: string
  schemas:
    BoundingBox:
      description: Quadrangle bounding box, with coordinates in original image. The eight
        numbers represent the four points (x-coordinate, y-coordinate from the
        left-top corner of the image) of the detected rectangle from the
        left-top corner in the clockwise direction. For images, coordinates are
        in pixels. For PDF, coordinates are in inches.
      items:
        type: integer
        nullable: false
      type: array
    ComputerVisionError:
      description: Details about the API request error.
      properties:
        code:
          description: The error code.
          enum:
            - InvalidImageFormat
            - UnsupportedMediaType
            - InvalidImageUrl
            - NotSupportedFeature
            - NotSupportedImage
            - Timeout
            - InternalServerError
            - InvalidImageSize
            - BadArgument
            - DetectFaceError
            - NotSupportedLanguage
            - InvalidThumbnailSize
            - InvalidDetails
            - InvalidModel
            - CancelledRequest
            - NotSupportedVisualFeature
            - FailedToProcess
            - Unspecified
            - StorageException
          x-ms-enum:
            modelAsString: true
            name: ComputerVisionErrorCodes
        message:
          description: A message explaining the error reported by the service.
          type: string
        requestId:
          description: A unique request identifier.
          type: string
      required:
        - code
        - message
      type: object
    ImageUrl:
      properties:
        url:
          description: Publicly reachable URL of an image.
          type: string
      required:
        - url
      type: object
    Line:
      description: An object representing a recognized text line.
      properties:
        boundingBox:
          $ref: "#/components/schemas/BoundingBox"
        text:
          description: The text content of the line.
          type: string
        words:
          description: List of words in the text line.
          items:
            $ref: "#/components/schemas/Word"
          type: array
      type: object
    OperationStatus:
      description: Status code of the text operation.
      enum:
        - Not Started
        - Running
        - Failed
        - Succeeded
      type: string
      x-ms-enum:
        modelAsString: false
        name: TextOperationStatusCodes
      nullable: false
    TextRecognitionResult:
      description: An object representing a recognized text region
      properties:
        clockwiseOrientation:
          description: The orientation of the image in degrees in the clockwise direction.
            Range between [0, 360).
          type: number
        height:
          description: The height of the image in pixels or the PDF in inches.
          type: number
        lines:
          description: A list of recognized text lines.
          items:
            $ref: "#/components/schemas/Line"
          type: array
        page:
          description: The 1-based page number of the recognition result.
          type: integer
        unit:
          description: The unit used in the Width, Height and BoundingBox. For images, the
            unit is 'pixel'. For PDF, the unit is 'inch'.
          enum:
            - pixel
            - inch
          type: string
          x-ms-enum:
            modelAsString: false
            name: TextRecognitionResultDimensionUnit
          nullable: true
        width:
          description: The width of the image in pixels or the PDF in inches.
          type: number
      required:
        - lines
      type: object
    Word:
      description: An object representing a recognized word.
      properties:
        boundingBox:
          $ref: "#/components/schemas/BoundingBox"
        confidence:
          description: Qualitative confidence measure.
          enum:
            - High
            - Low
          type: string
          x-ms-enum:
            modelAsString: false
            name: TextRecognitionResultConfidenceClass
          nullable: true
        text:
          description: The text content of the word.
          type: string
      required:
        - boundingBox
        - text
      type: object
