openapi: 3.0.0
info:
  description: API spec for Microsoft.Security (Azure Security Center) resource provider
  title: Security Center
  version: 2017-08-01-preview
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/security/resource-manager/Microsoft.Security/preview/2017-08-01-preview/pricings.json
      version: "2.0"
  x-preferred: false
  x-providerName: azure.com
  x-serviceName: security-pricings
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  "/subscriptions/{subscriptionId}/providers/Microsoft.Security/pricings":
    get:
      description: Security pricing configurations in the subscription
      operationId: Pricings_List
      parameters:
        - description: API version for the operation
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Get pricings on subscription:
              value: 2017-08-01-preview
        - description: Azure subscription ID
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
            pattern: ^[0-9A-Fa-f]{8}-([0-9A-Fa-f]{4}-){3}[0-9A-Fa-f]{12}$
          examples:
            Get pricings on subscription:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PricingList"
              examples:
                Get pricings on subscription:
                  $ref: "#/components/examples/Get_pricings_on_subscription"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response structure.
                properties:
                  error:
                    description: Error details.
                    properties:
                      code:
                        description: An identifier for the error. Codes are invariant and
                          are intended to be consumed programmatically.
                        readOnly: true
                        type: string
                      message:
                        description: A message describing the error, intended to be
                          suitable for display in a user interface.
                        readOnly: true
                        type: string
                    type: object
                    x-ms-external: true
                type: object
                x-ms-external: true
      tags:
        - Pricings
      x-ms-pageable:
        nextLinkName: nextLink
  "/subscriptions/{subscriptionId}/providers/Microsoft.Security/pricings/{pricingName}":
    get:
      description: Security pricing configuration in the subscriptionSecurity pricing
        configuration in the subscription
      operationId: Pricings_GetSubscriptionPricing
      parameters:
        - description: API version for the operation
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Get pricings on subscription:
              value: 2017-08-01-preview
        - description: Azure subscription ID
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
            pattern: ^[0-9A-Fa-f]{8}-([0-9A-Fa-f]{4}-){3}[0-9A-Fa-f]{12}$
          examples:
            Get pricings on subscription:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
        - $ref: "#/components/parameters/PricingName"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pricing"
              examples:
                Get pricings on subscription:
                  $ref: "#/components/examples/Get_pricings_on_subscription"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response structure.
                properties:
                  error:
                    description: Error details.
                    properties:
                      code:
                        description: An identifier for the error. Codes are invariant and
                          are intended to be consumed programmatically.
                        readOnly: true
                        type: string
                      message:
                        description: A message describing the error, intended to be
                          suitable for display in a user interface.
                        readOnly: true
                        type: string
                    type: object
                    x-ms-external: true
                type: object
                x-ms-external: true
      tags:
        - Pricings
    put:
      description: Security pricing configuration in the subscription
      operationId: Pricings_UpdateSubscriptionPricing
      parameters:
        - description: API version for the operation
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Update pricings on subscription:
              value: 2017-08-01-preview
        - description: Azure subscription ID
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
            pattern: ^[0-9A-Fa-f]{8}-([0-9A-Fa-f]{4}-){3}[0-9A-Fa-f]{12}$
          examples:
            Update pricings on subscription:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
        - $ref: "#/components/parameters/PricingName"
      requestBody:
        $ref: "#/components/requestBodies/Pricing"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pricing"
              examples:
                Update pricings on subscription:
                  $ref: "#/components/examples/Update_pricings_on_subscription"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response structure.
                properties:
                  error:
                    description: Error details.
                    properties:
                      code:
                        description: An identifier for the error. Codes are invariant and
                          are intended to be consumed programmatically.
                        readOnly: true
                        type: string
                      message:
                        description: A message describing the error, intended to be
                          suitable for display in a user interface.
                        readOnly: true
                        type: string
                    type: object
                    x-ms-external: true
                type: object
                x-ms-external: true
      tags:
        - Pricings
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Security/pricings":
    get:
      description: Security pricing configurations in the resource group
      operationId: Pricings_ListByResourceGroup
      parameters:
        - description: API version for the operation
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Get pricings on subscription:
              value: 2017-08-01-preview
        - description: Azure subscription ID
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
            pattern: ^[0-9A-Fa-f]{8}-([0-9A-Fa-f]{4}-){3}[0-9A-Fa-f]{12}$
          examples:
            Get pricings on subscription:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
        - description: The name of the resource group within the user's subscription. The
            name is case insensitive.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._\(\)]+$
          examples:
            Get pricings on subscription:
              value: myRg
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PricingList"
              examples:
                Get pricings on subscription:
                  $ref: "#/components/examples/Get_pricings_on_subscription"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response structure.
                properties:
                  error:
                    description: Error details.
                    properties:
                      code:
                        description: An identifier for the error. Codes are invariant and
                          are intended to be consumed programmatically.
                        readOnly: true
                        type: string
                      message:
                        description: A message describing the error, intended to be
                          suitable for display in a user interface.
                        readOnly: true
                        type: string
                    type: object
                    x-ms-external: true
                type: object
                x-ms-external: true
      tags:
        - Pricings
      x-ms-pageable:
        nextLinkName: nextLink
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Security/pricings/{pricingName}":
    get:
      description: Security pricing configuration in the resource group
      operationId: Pricings_GetResourceGroupPricing
      parameters:
        - description: API version for the operation
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Get pricings on subscription:
              value: 2017-08-01-preview
        - description: Azure subscription ID
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
            pattern: ^[0-9A-Fa-f]{8}-([0-9A-Fa-f]{4}-){3}[0-9A-Fa-f]{12}$
          examples:
            Get pricings on subscription:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
        - description: The name of the resource group within the user's subscription. The
            name is case insensitive.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._\(\)]+$
          examples:
            Get pricings on subscription:
              value: myRg
        - $ref: "#/components/parameters/PricingName"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pricing"
              examples:
                Get pricings on subscription:
                  $ref: "#/components/examples/Get_pricings_on_subscription"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response structure.
                properties:
                  error:
                    description: Error details.
                    properties:
                      code:
                        description: An identifier for the error. Codes are invariant and
                          are intended to be consumed programmatically.
                        readOnly: true
                        type: string
                      message:
                        description: A message describing the error, intended to be
                          suitable for display in a user interface.
                        readOnly: true
                        type: string
                    type: object
                    x-ms-external: true
                type: object
                x-ms-external: true
      tags:
        - Pricings
    put:
      description: Security pricing configuration in the resource group
      operationId: Pricings_CreateOrUpdateResourceGroupPricing
      parameters:
        - description: API version for the operation
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Update pricings on resource group:
              value: 2017-08-01-preview
        - description: Azure subscription ID
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
            pattern: ^[0-9A-Fa-f]{8}-([0-9A-Fa-f]{4}-){3}[0-9A-Fa-f]{12}$
          examples:
            Update pricings on resource group:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
        - description: The name of the resource group within the user's subscription. The
            name is case insensitive.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._\(\)]+$
          examples:
            Update pricings on resource group:
              value: myRg
        - $ref: "#/components/parameters/PricingName"
      requestBody:
        $ref: "#/components/requestBodies/Pricing"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pricing"
              examples:
                Update pricings on resource group:
                  $ref: "#/components/examples/Update_pricings_on_resource_group"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response structure.
                properties:
                  error:
                    description: Error details.
                    properties:
                      code:
                        description: An identifier for the error. Codes are invariant and
                          are intended to be consumed programmatically.
                        readOnly: true
                        type: string
                      message:
                        description: A message describing the error, intended to be
                          suitable for display in a user interface.
                        readOnly: true
                        type: string
                    type: object
                    x-ms-external: true
                type: object
                x-ms-external: true
      tags:
        - Pricings
servers:
  - url: https://management.azure.com
components:
  examples:
    Get_pricings_on_subscription:
      value:
        id: /subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23/providers/Microsoft.Security/pricings/myRg
        name: myRg
        properties:
          pricingTier: Standard
        type: Microsoft.Security/pricings
    Update_pricings_on_subscription:
      value:
        id: /subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23/providers/Microsoft.Security/pricings/default
        name: default
        properties:
          pricingTier: Standard
        type: Microsoft.Security/pricings
    Update_pricings_on_resource_group:
      value:
        id: /subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23/providers/Microsoft.Security/pricings/myRg
        name: myRg
        properties:
          pricingTier: Standard
        type: Microsoft.Security/pricings
  parameters:
    PricingName:
      description: name of the pricing configuration
      in: path
      name: pricingName
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
      examples:
        Get pricings on subscription:
          value: myRg
        Update pricings on subscription:
          value: default
        Update pricings on resource group:
          value: myRg
  requestBodies:
    Pricing:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Pricing"
      description: Pricing object
      required: true
      x-ms-parameter-location: method
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    Pricing:
      allOf:
        - description: Describes an Azure resource.
          properties:
            id:
              description: Resource Id
              readOnly: true
              type: string
            name:
              description: Resource name
              readOnly: true
              type: string
            type:
              description: Resource type
              readOnly: true
              type: string
          type: object
          x-ms-azure-resource: true
      description: Pricing tier will be applied for the scope based on the resource ID
      properties:
        properties:
          $ref: "#/components/schemas/PricingProperties"
      type: object
    PricingList:
      description: List of pricing configurations response
      properties:
        nextLink:
          description: The URI to fetch the next page.
          readOnly: true
          type: string
        value:
          description: List of pricing configurations
          items:
            $ref: "#/components/schemas/Pricing"
          type: array
      required:
        - value
    PricingProperties:
      description: Pricing data
      properties:
        pricingTier:
          description: Pricing tier type
          enum:
            - Free
            - Standard
          type: string
          x-ms-enum:
            modelAsString: true
            name: pricingTier
            values:
              - description: Get free Azure security center experience with basic security
                  features
                value: Free
              - description: Get the standard Azure security center experience with
                  advanced security features
                value: Standard
      required:
        - pricingTier
      type: object
