openapi: 3.0.0
info:
  description: Azure Application Insights client for work item configurations for a
    component.
  title: ApplicationInsightsManagementClient
  version: 2015-05-01
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/applicationinsights/resource-manager/Microsoft.Insights/stable/2015-05-01/componentWorkItemConfigs_API.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: applicationinsights-componentWorkItemConfigs_API
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Insights/components/{resourceName}/DefaultWorkItemConfig":
    get:
      description: Gets default work item configurations that exist for the application
      operationId: WorkItemConfigurations_GetDefault
      parameters:
        - description: The name of the resource group. The name is case insensitive.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._\(\)]+$
          examples:
            WorkItemConfigurationsGetDefault:
              value: my-resource-group
        - description: The API version to use for this operation.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            minLength: 1
          examples:
            WorkItemConfigurationsGetDefault:
              value: 2015-05-01
        - description: The ID of the target subscription.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
            minLength: 1
          examples:
            WorkItemConfigurationsGetDefault:
              value: subid
        - $ref: "#/components/parameters/ResourceNameParameter"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WorkItemConfiguration"
              examples:
                WorkItemConfigurationsGetDefault:
                  $ref: "#/components/examples/WorkItemConfigurationsGetDefault"
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Insights/components/{resourceName}/WorkItemConfigs":
    get:
      description: Gets the list work item configurations that exist for the application
      operationId: WorkItemConfigurations_List
      parameters:
        - description: The name of the resource group. The name is case insensitive.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._\(\)]+$
          examples:
            WorkItemConfigurationsList:
              value: my-resource-group
        - description: The API version to use for this operation.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            minLength: 1
          examples:
            WorkItemConfigurationsList:
              value: 2015-05-01
        - description: The ID of the target subscription.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
            minLength: 1
          examples:
            WorkItemConfigurationsList:
              value: subid
        - $ref: "#/components/parameters/ResourceNameParameter"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WorkItemConfigurationsListResult"
              examples:
                WorkItemConfigurationsList:
                  $ref: "#/components/examples/WorkItemConfigurationsList"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WorkItemConfigurationError"
      x-ms-pageable: {}
    post:
      description: Create a work item configuration for an Application Insights component.
      operationId: WorkItemConfigurations_Create
      parameters:
        - description: The name of the resource group. The name is case insensitive.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._\(\)]+$
          examples:
            WorkItemConfigurationsCreate:
              value: my-resource-group
        - description: The API version to use for this operation.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            minLength: 1
          examples:
            WorkItemConfigurationsCreate:
              value: 2015-05-01
        - description: The ID of the target subscription.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
            minLength: 1
          examples:
            WorkItemConfigurationsCreate:
              value: subid
        - $ref: "#/components/parameters/ResourceNameParameter"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/WorkItemCreateConfiguration"
        description: Properties that need to be specified to create a work item
          configuration of a Application Insights component.
        required: true
      responses:
        "200":
          description: An object containing the work item configuration definition created
            by this PUT call.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WorkItemConfiguration"
              examples:
                WorkItemConfigurationsCreate:
                  $ref: "#/components/examples/WorkItemConfigurationsCreate"
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Insights/components/{resourceName}/WorkItemConfigs/{workItemConfigId}":
    delete:
      description: Delete a work item configuration of an Application Insights component.
      operationId: WorkItemConfigurations_Delete
      parameters:
        - description: The name of the resource group. The name is case insensitive.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._\(\)]+$
          examples:
            WorkItemConfigurationDelete:
              value: my-resource-group
        - description: The API version to use for this operation.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            minLength: 1
          examples:
            WorkItemConfigurationDelete:
              value: 2015-05-01
        - description: The ID of the target subscription.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
            minLength: 1
          examples:
            WorkItemConfigurationDelete:
              value: subid
        - $ref: "#/components/parameters/ResourceNameParameter"
        - $ref: "#/components/parameters/WorkItemConfigIdParameter"
      responses:
        "200":
          description: The work item configuration that was successfully deleted.
    get:
      description: Gets specified work item configuration for an Application Insights
        component.
      operationId: WorkItemConfigurations_GetItem
      parameters:
        - description: The name of the resource group. The name is case insensitive.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._\(\)]+$
          examples:
            WorkItemConfigurationsGetDefault:
              value: my-resource-group
        - description: The API version to use for this operation.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            minLength: 1
          examples:
            WorkItemConfigurationsGetDefault:
              value: 2015-05-01
        - description: The ID of the target subscription.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
            minLength: 1
          examples:
            WorkItemConfigurationsGetDefault:
              value: subid
        - $ref: "#/components/parameters/ResourceNameParameter"
        - $ref: "#/components/parameters/WorkItemConfigIdParameter"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WorkItemConfiguration"
              examples:
                WorkItemConfigurationsGetDefault:
                  $ref: "#/components/examples/WorkItemConfigurationsGetDefault"
    patch:
      description: Update a work item configuration for an Application Insights component.
      operationId: WorkItemConfigurations_UpdateItem
      parameters:
        - description: The name of the resource group. The name is case insensitive.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._\(\)]+$
          examples:
            WorkItemConfigurationsCreate:
              value: my-resource-group
        - description: The API version to use for this operation.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            minLength: 1
          examples:
            WorkItemConfigurationsCreate:
              value: 2015-05-01
        - description: The ID of the target subscription.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
            minLength: 1
          examples:
            WorkItemConfigurationsCreate:
              value: subid
        - $ref: "#/components/parameters/ResourceNameParameter"
        - $ref: "#/components/parameters/WorkItemConfigIdParameter"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/WorkItemCreateConfiguration"
        description: Properties that need to be specified to update a work item
          configuration for this Application Insights component.
        required: true
      responses:
        "200":
          description: Successful operation indicating the config updated by this PATCH
            call.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WorkItemConfiguration"
              examples:
                WorkItemConfigurationsCreate:
                  $ref: "#/components/examples/WorkItemConfigurationsCreate"
servers:
  - url: https://management.azure.com
components:
  examples:
    WorkItemConfigurationsGetDefault:
      value:
        ConfigDisplayName: Visual Studio Team Services
        ConfigProperties: '{"VSOAccountBaseUrl":"https://testtodelete.visualstudio.com","ProjectCollection":"DefaultCollection","Project":"todeletefirst","ResourceId":"d0662b05-439a-4a1b-840b-33a7f8b42ebf","ConfigurationType":"Standard","WorkItemType":"Bug","AreaPath":"todeletefirst","AssignedTo":""}'
        ConnectorId: d334e2a4-6733-488e-8645-a9fdc1694f41
        Id: Visual Studio Team Services
        IsDefault: true
    WorkItemConfigurationsList:
      value:
        - ConfigDisplayName: Visual Studio Team Services
          ConfigProperties: '{"VSOAccountBaseUrl":"https://testtodelete.visualstudio.com","ProjectCollection":"DefaultCollection","Project":"todeletefirst","ResourceId":"b370eeb2-5dff-4838-8253-ec3014b2c706","ConfigurationType":"Standard","WorkItemType":"Bug","AreaPath":"todeletefirst","AssignedTo":""}'
          ConnectorId: d334e2a4-6733-488e-8645-a9fdc1694f41
          Id: Visual Studio Team Services
          IsDefault: true
        - ConfigDisplayName: GitHub
          ConfigProperties: '{"GitHubAccountUrl":"https://github.com/jpiyali/testrepository","ResourceId":"b370eeb2-5dff-4838-8253-ec3014b2c706"}'
          ConnectorId: 4C89E219-D47E-4C14-866A-018D6D634CF3
          Id: GitHub
          IsDefault: false
    WorkItemConfigurationsCreate:
      value:
        ConfigDisplayName: Visual Studio Team Services
        ConfigProperties: '{"VSOAccountBaseUrl":"https://testtodelete.visualstudio.com","ProjectCollection":"DefaultCollection","Project":"todeletefirst","ResourceId":"d0662b05-439a-4a1b-840b-33a7f8b42ebf","ConfigurationType":"Standard","WorkItemType":"Bug","AreaPath":"todeletefirst","AssignedTo":""}'
        ConnectorId: d334e2a4-6733-488e-8645-a9fdc1694f41
        Id: Visual Studio Team Services
        IsDefault: true
  parameters:
    ResourceNameParameter:
      description: The name of the Application Insights component resource.
      in: path
      name: resourceName
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
      examples:
        WorkItemConfigurationsGetDefault:
          value: my-component
        WorkItemConfigurationsList:
          value: my-component
        WorkItemConfigurationsCreate:
          value: my-component
        WorkItemConfigurationDelete:
          value: my-component
    WorkItemConfigIdParameter:
      description: The unique work item configuration Id. This can be either friendly name
        of connector as defined in connector configuration
      in: path
      name: workItemConfigId
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
      examples:
        WorkItemConfigurationDelete:
          value: Visual Studio Team Services
        WorkItemConfigurationsGetDefault:
          value: Visual Studio Team Services
        WorkItemConfigurationsCreate:
          value: Visual Studio Team Services
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    InnerError:
      description: Inner error
      properties:
        diagnosticcontext:
          description: Provides correlation for request
          type: string
        time:
          description: Request time
          format: date-time
          type: string
      type: object
    WorkItemConfiguration:
      description: Work item configuration associated with an application insights resource.
      properties:
        ConfigDisplayName:
          description: Configuration friendly name
          type: string
        ConfigProperties:
          description: Serialized JSON object for detailed properties
          type: string
        ConnectorId:
          description: Connector identifier where work item is created
          type: string
        Id:
          description: Unique Id for work item
          type: string
        IsDefault:
          description: Boolean value indicating whether configuration is default
          type: boolean
      type: object
    WorkItemConfigurationError:
      description: Error associated with trying to get work item configuration or
        configurations
      properties:
        code:
          description: Error detail code and explanation
          type: string
        innererror:
          $ref: "#/components/schemas/InnerError"
        message:
          description: Error message
          type: string
      type: object
    WorkItemConfigurationsListResult:
      description: Work item configuration list result.
      properties:
        value:
          description: An array of work item configurations.
          items:
            $ref: "#/components/schemas/WorkItemConfiguration"
          readOnly: true
          type: array
    WorkItemCreateConfiguration:
      description: Work item configuration creation payload
      properties:
        ConnectorDataConfiguration:
          description: Serialized JSON object for detailed properties
          type: string
        ConnectorId:
          description: Unique connector id
          type: string
        ValidateOnly:
          description: Boolean indicating validate only
          type: boolean
        WorkItemProperties:
          additionalProperties:
            type: string
          description: Custom work item properties
          type: object
      type: object
