openapi: 3.0.0
info:
  title: Azure Data Migration Service Resource Provider
  version: 2018-03-15-preview
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/datamigration/resource-manager/Microsoft.DataMigration/preview/2018-03-15-preview/definitions/MigrateSqlServerSqlMITask.json
      version: "2.0"
  x-preferred: false
  x-providerName: azure.com
  x-serviceName: datamigration-MigrateSqlServerSqlMITask
  x-tags:
    - Azure
    - Microsoft
paths: {}
servers:
  - url: https://azure.local
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    MigrateSqlServerSqlMITaskInput:
      allOf:
        - description: Base class for migration task input
          properties:
            sourceConnectionInfo:
              allOf:
                - description: Defines the connection properties of a server
                  discriminator:
                    propertyName: type
                  properties:
                    password:
                      description: Password credential.
                      type: string
                    type:
                      description: Type of connection info
                      type: string
                    userName:
                      description: User name
                      type: string
                  required:
                    - type
                  type: object
              description: Information for connecting to SQL database server
              properties:
                additionalSettings:
                  description: Additional connection settings
                  type: string
                authentication:
                  description: An enumeration of possible authentication types when
                    connecting
                  enum:
                    - None
                    - WindowsAuthentication
                    - SqlAuthentication
                    - ActiveDirectoryIntegrated
                    - ActiveDirectoryPassword
                  type: string
                  x-ms-enum:
                    modelAsString: true
                    name: AuthenticationType
                dataSource:
                  description: Data source in the format
                    Protocol:MachineName\SQLServerInstanceName,PortNumber
                  type: string
                encryptConnection:
                  default: true
                  description: Whether to encrypt the connection
                  type: boolean
                trustServerCertificate:
                  default: false
                  description: Whether to trust the server certificate
                  type: boolean
              required:
                - dataSource
              type: object
              x-ms-discriminator-value: SqlConnectionInfo
            targetConnectionInfo:
              allOf:
                - description: Defines the connection properties of a server
                  discriminator:
                    propertyName: type
                  properties:
                    password:
                      description: Password credential.
                      type: string
                    type:
                      description: Type of connection info
                      type: string
                    userName:
                      description: User name
                      type: string
                  required:
                    - type
                  type: object
              description: Information for connecting to SQL database server
              properties:
                additionalSettings:
                  description: Additional connection settings
                  type: string
                authentication:
                  description: An enumeration of possible authentication types when
                    connecting
                  enum:
                    - None
                    - WindowsAuthentication
                    - SqlAuthentication
                    - ActiveDirectoryIntegrated
                    - ActiveDirectoryPassword
                  type: string
                  x-ms-enum:
                    modelAsString: true
                    name: AuthenticationType
                dataSource:
                  description: Data source in the format
                    Protocol:MachineName\SQLServerInstanceName,PortNumber
                  type: string
                encryptConnection:
                  default: true
                  description: Whether to encrypt the connection
                  type: boolean
                trustServerCertificate:
                  default: false
                  description: Whether to trust the server certificate
                  type: boolean
              required:
                - dataSource
              type: object
              x-ms-discriminator-value: SqlConnectionInfo
          required:
            - sourceConnectionInfo
            - targetConnectionInfo
          type: object
      description: Input for task that migrates SQL Server databases to Azure SQL Database
        Managed Instance.
      properties:
        backupBlobShare:
          description: Blob container storage information.
          properties:
            sasUri:
              description: SAS URI of Azure Storage Account Container.
              type: string
          required:
            - sasUri
          type: object
        backupFileShare:
          description: File share information with Path, Username, and Password.
          properties:
            password:
              description: Password credential used to connect to the share location.
              type: string
            path:
              description: The folder path for this share.
              type: string
            userName:
              description: User name credential to connect to the share location
              type: string
          required:
            - path
          type: object
        selectedDatabases:
          description: Databases to migrate
          items:
            description: Database specific information for SQL to Azure SQL DB Managed
              Instance migration task inputs
            properties:
              backupFileShare:
                description: File share information with Path, Username, and Password.
                properties:
                  password:
                    description: Password credential used to connect to the share location.
                    type: string
                  path:
                    description: The folder path for this share.
                    type: string
                  userName:
                    description: User name credential to connect to the share location
                    type: string
                required:
                  - path
                type: object
              name:
                description: Name of the database
                type: string
              restoreDatabaseName:
                description: Name of the database at destination
                type: string
            required:
              - name
              - restoreDatabaseName
            type: object
          type: array
      required:
        - selectedDatabases
        - backupBlobShare
      type: object
    MigrateSqlServerSqlMITaskOutput:
      description: Output for task that migrates SQL Server databases to Azure SQL Database
        Managed Instance.
      discriminator:
        propertyName: resultType
      properties:
        id:
          description: Result identifier
          readOnly: true
          type: string
        resultType:
          description: Result type
          type: string
      required:
        - resultType
      type: object
    MigrateSqlServerSqlMITaskOutputDatabaseLevel:
      allOf:
        - $ref: "#/components/schemas/MigrateSqlServerSqlMITaskOutput"
      description: Database level result for Sql Server to Sql MI migration.
      properties:
        databaseName:
          description: Name of the database
          readOnly: true
          type: string
        endedOn:
          description: Migration end time
          format: date-time
          readOnly: true
          type: string
        exceptionsAndWarnings:
          description: Migration exceptions and warnings
          items:
            description: Exception object for all custom exceptions
            properties:
              filePath:
                description: The path to the file where exception occurred
                type: string
              hResult:
                description: Coded numerical value that is assigned to a specific exception
                type: integer
              lineNumber:
                description: The line number where exception occurred
                type: string
              message:
                description: Error message
                type: string
              stackTrace:
                description: Stack trace
                type: string
            type: object
          readOnly: true
          type: array
        message:
          description: Migration progress message
          readOnly: true
          type: string
        stage:
          description: Current stage of migration
          enum:
            - None
            - Initialize
            - Backup
            - FileCopy
            - Restore
            - Completed
          type: string
          x-ms-enum:
            modelAsString: true
            name: DatabaseMigrationStage
        startedOn:
          description: Migration start time
          format: date-time
          readOnly: true
          type: string
        state:
          description: Current state of migration
          enum:
            - None
            - InProgress
            - Failed
            - Warning
            - Completed
            - Skipped
            - Stopped
          type: string
          x-ms-enum:
            modelAsString: true
            name: MigrationState
      type: object
      x-ms-discriminator-value: DatabaseLevelOutput
    MigrateSqlServerSqlMITaskOutputError:
      allOf:
        - $ref: "#/components/schemas/MigrateSqlServerSqlMITaskOutput"
      description: Task errors for Sql Server to Sql MI migration.
      properties:
        error:
          description: Exception object for all custom exceptions
          properties:
            filePath:
              description: The path to the file where exception occurred
              type: string
            hResult:
              description: Coded numerical value that is assigned to a specific exception
              type: integer
            lineNumber:
              description: The line number where exception occurred
              type: string
            message:
              description: Error message
              type: string
            stackTrace:
              description: Stack trace
              type: string
          type: object
        id:
          description: Unique identifier for the exception
          readOnly: true
          type: string
      type: object
      x-ms-discriminator-value: ErrorOutput
    MigrateSqlServerSqlMITaskOutputMigrationLevel:
      allOf:
        - $ref: "#/components/schemas/MigrateSqlServerSqlMITaskOutput"
      description: Migration level result for Sql server to Sql MI migration.
      properties:
        databases:
          additionalProperties:
            type: string
          description: Selected databases as a map from database name to database id
          readOnly: true
          type: string
        endedOn:
          description: Migration end time
          format: date-time
          readOnly: true
          type: string
        exceptionsAndWarnings:
          description: Migration exceptions and warnings.
          items:
            description: Exception object for all custom exceptions
            properties:
              filePath:
                description: The path to the file where exception occurred
                type: string
              hResult:
                description: Coded numerical value that is assigned to a specific exception
                type: integer
              lineNumber:
                description: The line number where exception occurred
                type: string
              message:
                description: Error message
                type: string
              stackTrace:
                description: Stack trace
                type: string
            type: object
          readOnly: true
          type: array
        message:
          description: Migration progress message
          readOnly: true
          type: string
        sourceServerBrandVersion:
          description: Source server brand version
          readOnly: true
          type: string
        sourceServerVersion:
          description: Source server version
          readOnly: true
          type: string
        startedOn:
          description: Migration start time
          format: date-time
          readOnly: true
          type: string
        state:
          description: Current state of migration
          enum:
            - None
            - InProgress
            - Failed
            - Warning
            - Completed
            - Skipped
            - Stopped
          type: string
          x-ms-enum:
            modelAsString: true
            name: MigrationState
        status:
          description: Current status of migration
          enum:
            - Default
            - Connecting
            - SourceAndTargetSelected
            - SelectLogins
            - Configured
            - Running
            - Error
            - Stopped
            - Completed
            - CompletedWithWarnings
          type: string
          x-ms-enum:
            modelAsString: true
            name: MigrationStatus
        targetServerBrandVersion:
          description: Target server brand version
          readOnly: true
          type: string
        targetServerVersion:
          description: Target server version
          readOnly: true
          type: string
      type: object
      x-ms-discriminator-value: MigrationLevelOutput
