openapi: 3.0.0
info:
  description: The Azure SQL Database management API provides a RESTful set of web APIs
    that interact with Azure SQL Database services to manage your databases. The
    API enables users to create, retrieve, update, and delete databases,
    servers, and other entities.
  title: SqlManagementClient
  version: 2015-05-01-preview
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/sql/resource-manager/Microsoft.Sql/preview/2015-05-01-preview/virtualNetworkRules.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: sql-virtualNetworkRules
  x-tags:
    - Azure
    - Microsoft
paths:
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}/virtualNetworkRules":
    get:
      description: Gets a list of virtual network rules in a server.
      operationId: VirtualNetworkRules_ListByServer
      parameters:
        - $ref: "#/components/parameters/ResourceGroupParameter"
        - $ref: "#/components/parameters/ServerNameParameter"
        - $ref: "#/components/parameters/SubscriptionIdParameter"
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: Successfully retrieved the list of virtual network rules.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VirtualNetworkRuleListResult"
              examples:
                List virtual network rules:
                  $ref: "#/components/examples/List_virtual_network_rules"
        default:
          description: >-
            *** Error Responses: ***

             * 404 SubscriptionDoesNotHaveServer - The requested server was not found

             * 404 ResourceNotFound - The requested resource was not found.
      tags:
        - VirtualNetworkRules
      x-ms-pageable:
        nextLinkName: nextLink
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}/virtualNetworkRules/{virtualNetworkRuleName}":
    delete:
      description: Deletes the virtual network rule with the given name.
      operationId: VirtualNetworkRules_Delete
      parameters:
        - $ref: "#/components/parameters/ResourceGroupParameter"
        - $ref: "#/components/parameters/ServerNameParameter"
        - description: The name of the virtual network rule.
          in: path
          name: virtualNetworkRuleName
          required: true
          schema:
            type: string
          examples:
            Delete a virtual network rule:
              value: vnet-firewall-rule
        - $ref: "#/components/parameters/SubscriptionIdParameter"
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: Successfully deleted the virtual network rule.
        "202":
          description: Accepted
        "204":
          description: The specified virtual network rule does not exist.
        default:
          description: >-
            *** Error Responses: ***

             * 400 InvalidResourceId - Invalid resource identifier.

             * 400 MismatchingSubscriptionWithUrl - The provided subscription did not match the subscription in the Url.

             * 400 MismatchingResourceGroupNameWithUrl - The provided resource group name did not match the name in the Url.

             * 400 MismatchingServerNameWithUrl - The provided server name did not match the name in the Url.

             * 400 NullVirtualNetworkRequest - Virtual Network Request is Null

             * 400 NullVirtualNetworkRequestParameters - Virtual Network Request Parameters are Null

             * 404 SubscriptionDoesNotHaveServer - The requested server was not found

             * 404 OperationIdNotFound - The operation with Id does not exist.

             * 409 OperationCancelled - The operation has been cancelled by user.

             * 409 OperationInterrupted - The operation on the resource could not be completed because it was interrupted by another operation on the same resource.

             * 500 OperationTimedOut - The operation timed out and automatically rolled back. Please retry the operation.
      tags:
        - VirtualNetworkRules
      x-ms-long-running-operation: true
    get:
      description: Gets a virtual network rule.
      operationId: VirtualNetworkRules_Get
      parameters:
        - $ref: "#/components/parameters/ResourceGroupParameter"
        - $ref: "#/components/parameters/ServerNameParameter"
        - description: The name of the virtual network rule.
          in: path
          name: virtualNetworkRuleName
          required: true
          schema:
            type: string
          examples:
            Gets a virtual network rule:
              value: vnet-firewall-rule
        - $ref: "#/components/parameters/SubscriptionIdParameter"
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: Successfully retrieved a specified virtual network rule.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VirtualNetworkRule"
              examples:
                Gets a virtual network rule:
                  $ref: "#/components/examples/Gets_a_virtual_network_rule"
        default:
          description: >-
            *** Error Responses: ***

             * 404 SubscriptionDoesNotHaveServer - The requested server was not found

             * 404 ResourceNotFound - The requested resource was not found.
      tags:
        - VirtualNetworkRules
    put:
      description: Creates or updates an existing virtual network rule.
      operationId: VirtualNetworkRules_CreateOrUpdate
      parameters:
        - $ref: "#/components/parameters/ResourceGroupParameter"
        - $ref: "#/components/parameters/ServerNameParameter"
        - description: The name of the virtual network rule.
          in: path
          name: virtualNetworkRuleName
          required: true
          schema:
            type: string
          examples:
            Create or update a virtual network rule:
              value: vnet-firewall-rule
        - $ref: "#/components/parameters/SubscriptionIdParameter"
        - $ref: "#/components/parameters/ApiVersionParameter"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VirtualNetworkRule"
        description: The requested virtual Network Rule Resource state.
        required: true
      responses:
        "200":
          description: Successfully updated a virtual network rule.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VirtualNetworkRule"
              examples:
                Create or update a virtual network rule:
                  $ref: "#/components/examples/Create_or_update_a_virtual_network_r\
                    ule"
        "201":
          description: Successfully created a virtual network rule.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VirtualNetworkRule"
              examples:
                Create or update a virtual network rule:
                  $ref: "#/components/examples/Create_or_update_a_virtual_network_r\
                    ule"
        "202":
          description: Accepted
        default:
          description: >-
            *** Error Responses: ***

             * 400 InvalidResourceId - Invalid resource identifier.

             * 400 MismatchingSubscriptionWithUrl - The provided subscription did not match the subscription in the Url.

             * 400 MismatchingResourceGroupNameWithUrl - The provided resource group name did not match the name in the Url.

             * 400 MismatchingServerNameWithUrl - The provided server name did not match the name in the Url.

             * 400 NullVirtualNetworkRequest - Virtual Network Request is Null

             * 400 NullVirtualNetworkRequestParameters - Virtual Network Request Parameters are Null

             * 400 NullVirtualNetworkSubnetId - The Virtual Network Subnet Id is null

             * 404 SubscriptionDoesNotHaveServer - The requested server was not found

             * 404 VirtualNetworkRuleNotEnabled - Azure SQL Server Virtual Network Rule feature is not enabled

             * 404 OperationIdNotFound - The operation with Id does not exist.

             * 409 OperationCancelled - The operation has been cancelled by user.

             * 409 OperationInterrupted - The operation on the resource could not be completed because it was interrupted by another operation on the same resource.

             * 500 OperationTimedOut - The operation timed out and automatically rolled back. Please retry the operation.
      tags:
        - VirtualNetworkRules
      x-ms-long-running-operation: true
servers:
  - url: https://management.azure.com
components:
  examples:
    List_virtual_network_rules:
      value:
        value:
          - id: /subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/Default/providers/Microsoft.Sql/servers/vnet-test-svr/virtualNetworkRules/vnet-firewall-rule
            name: vnet-firewall-rule
            properties:
              ignoreMissingVnetServiceEndpoint: false
              state: Ready
              virtualNetworkSubnetId: /subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/Default/providers/Microsoft.Network/virtualNetworks/testvnet/subnets/testsubnet
            type: Microsoft.Sql/servers/virtualNetworkRules
          - id: /subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/Default/providers/Microsoft.Sql/servers/vnet-test-svr/virtualNetworkRules/vnet-firewall-rule
            name: vnet-firewall-rule
            properties:
              ignoreMissingVnetServiceEndpoint: false
              state: Ready
              virtualNetworkSubnetId: /subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/Default/providers/Microsoft.Network/virtualNetworks/testvnet/subnets/testsubnet
            type: Microsoft.Sql/servers/virtualNetworkRules
    Gets_a_virtual_network_rule:
      value:
        id: /subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/Default/providers/Microsoft.Sql/servers/vnet-test-svr/virtualNetworkRules/vnet-firewall-rule
        name: vnet-firewall-rule
        properties:
          ignoreMissingVnetServiceEndpoint: false
          state: Ready
          virtualNetworkSubnetId: /subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/Default/providers/Microsoft.Network/virtualNetworks/testvnet/subnets/testsubnet
        type: Microsoft.Sql/servers/virtualNetworkRules
    Create_or_update_a_virtual_network_rule:
      value:
        id: /subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/Default/providers/Microsoft.Sql/servers/vnet-test-svr/virtualNetworkRules/vnet-firewall-rule
        name: vnet-firewall-rule
        properties:
          ignoreMissingVnetServiceEndpoint: false
          virtualNetworkSubnetId: /subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/Default/providers/Microsoft.Network/virtualNetworks/testvnet/subnets/testsubnet
        type: Microsoft.Sql/servers/virtualNetworkRules
  parameters:
    ApiVersionParameter:
      description: The API version to use for the request.
      in: query
      name: api-version
      required: true
      x-ms-parameter-location: client
      schema:
        type: string
      examples:
        List virtual network rules:
          value: 2015-05-01-preview
        Delete a virtual network rule:
          value: 2015-05-01-preview
        Gets a virtual network rule:
          value: 2015-05-01-preview
        Create or update a virtual network rule:
          value: 2015-05-01-preview
    DatabaseNameParameter:
      description: The name of the database.
      in: path
      name: databaseName
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
    ManagedInstanceNameParameter:
      description: The name of the managed instance.
      in: path
      name: managedInstanceName
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
    ResourceGroupParameter:
      description: The name of the resource group that contains the resource. You can
        obtain this value from the Azure Resource Manager API or the portal.
      in: path
      name: resourceGroupName
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
      examples:
        List virtual network rules:
          value: Default
        Delete a virtual network rule:
          value: Default
        Gets a virtual network rule:
          value: Default
        Create or update a virtual network rule:
          value: Default
    ServerNameParameter:
      description: The name of the server.
      in: path
      name: serverName
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
      examples:
        List virtual network rules:
          value: vnet-test-svr
        Delete a virtual network rule:
          value: vnet-test-svr
        Gets a virtual network rule:
          value: vnet-test-svr
        Create or update a virtual network rule:
          value: vnet-test-svr
    SqlVirtualMachineContainerNameParameter:
      description: The name of the SqlVirtualMachineContainer.
      in: path
      name: sqlVirtualMachineContainerName
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
    SqlVirtualMachineInstanceNameParameter:
      description: The name of the SqlVirtualMachineInstance.
      in: path
      name: sqlVirtualMachineInstanceName
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
    SubscriptionIdParameter:
      description: The subscription ID that identifies an Azure subscription.
      in: path
      name: subscriptionId
      required: true
      x-ms-parameter-location: client
      schema:
        type: string
      examples:
        List virtual network rules:
          value: 00000000-1111-2222-3333-444444444444
        Delete a virtual network rule:
          value: 00000000-1111-2222-3333-444444444444
        Gets a virtual network rule:
          value: 00000000-1111-2222-3333-444444444444
        Create or update a virtual network rule:
          value: 00000000-1111-2222-3333-444444444444
    VirtualClusterNameParameter:
      description: The name of the virtual cluster.
      in: path
      name: virtualClusterName
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    VirtualNetworkRule:
      allOf:
        - allOf:
            - description: ARM resource.
              properties:
                id:
                  description: Resource ID.
                  readOnly: true
                  type: string
                name:
                  description: Resource name.
                  readOnly: true
                  type: string
                type:
                  description: Resource type.
                  readOnly: true
                  type: string
              type: object
              x-ms-azure-resource: true
          description: ARM proxy resource.
          properties: {}
          type: object
      description: A virtual network rule.
      properties:
        properties:
          $ref: "#/components/schemas/VirtualNetworkRuleProperties"
      type: object
    VirtualNetworkRuleListResult:
      description: A list of virtual network rules.
      properties:
        nextLink:
          description: Link to retrieve next page of results.
          readOnly: true
          type: string
        value:
          description: Array of results.
          items:
            $ref: "#/components/schemas/VirtualNetworkRule"
          readOnly: true
          type: array
      type: object
    VirtualNetworkRuleProperties:
      description: Properties of a virtual network rule.
      properties:
        ignoreMissingVnetServiceEndpoint:
          description: Create firewall rule before the virtual network has vnet service
            endpoint enabled.
          type: boolean
        state:
          description: Virtual Network Rule State
          enum:
            - Initializing
            - InProgress
            - Ready
            - Deleting
            - Unknown
          readOnly: true
          type: string
          x-ms-enum:
            modelAsString: true
            name: VirtualNetworkRuleState
        virtualNetworkSubnetId:
          description: The ARM resource id of the virtual network subnet.
          type: string
      required:
        - virtualNetworkSubnetId
      type: object
