openapi: 3.0.0
info:
  description: Describes the schema of the Azure Storage events published to Azure Event
    Grid. This corresponds to the Data property of an EventGridEvent.
  title: Schema of Azure Storage events published to Azure Event Grid
  version: 2018-01-01
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/eventgrid/data-plane/Microsoft.Storage/stable/2018-01-01/Storage.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: eventgrid-Storage
  x-tags:
    - Azure
    - Microsoft
paths: {}
servers:
  - url: https://azure.local
components:
  schemas:
    StorageBlobCreatedEventData:
      description: Schema of the Data property of an EventGridEvent for an
        Microsoft.Storage.BlobCreated event.
      properties:
        api:
          description: The name of the API/operation that triggered this event.
          type: string
        blobType:
          description: The type of blob.
          type: string
        clientRequestId:
          description: A request id provided by the client of the storage API operation
            that triggered this event.
          type: string
        contentLength:
          description: The size of the blob in bytes. This is the same as what would be
            returned in the Content-Length header from the blob.
          format: int64
          type: integer
        contentType:
          description: The content type of the blob. This is the same as what would be
            returned in the Content-Type header from the blob.
          type: string
        eTag:
          description: The etag of the object at the time this event was triggered.
          type: string
        requestId:
          description: The request id generated by the Storage service for the storage API
            operation that triggered this event.
          type: string
        sequencer:
          description: An opaque string value representing the logical sequence of events
            for any particular blob name. Users can use standard string
            comparison to understand the relative sequence of two events on the
            same blob name.
          type: string
        storageDiagnostics:
          description: For service use only. Diagnostic data occasionally included by the
            Azure Storage service. This property should be ignored by event
            consumers.
          type: object
        url:
          description: The path to the blob.
          type: string
      type: object
    StorageBlobDeletedEventData:
      description: Schema of the Data property of an EventGridEvent for an
        Microsoft.Storage.BlobDeleted event.
      properties:
        api:
          description: The name of the API/operation that triggered this event.
          type: string
        blobType:
          description: The type of blob.
          type: string
        clientRequestId:
          description: A request id provided by the client of the storage API operation
            that triggered this event.
          type: string
        contentType:
          description: The content type of the blob. This is the same as what would be
            returned in the Content-Type header from the blob.
          type: string
        requestId:
          description: The request id generated by the Storage service for the storage API
            operation that triggered this event.
          type: string
        sequencer:
          description: An opaque string value representing the logical sequence of events
            for any particular blob name. Users can use standard string
            comparison to understand the relative sequence of two events on the
            same blob name.
          type: string
        storageDiagnostics:
          description: For service use only. Diagnostic data occasionally included by the
            Azure Storage service. This property should be ignored by event
            consumers.
          type: object
        url:
          description: The path to the blob.
          type: string
      type: object
