openapi: 3.0.0
info:
  title: Compute Admin Client
  version: 2015-12-01-preview
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/azsadmin/resource-manager/compute/Microsoft.Compute.Admin/preview/2015-12-01-preview/PlatformImages.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: azsadmin-PlatformImages
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  "/subscriptions/{subscriptionId}/providers/Microsoft.Compute.Admin/locations/{location}/artifactTypes/platformImage":
    get:
      description: Returns a list of all platform images.
      operationId: PlatformImages_List
      parameters:
        - description: Subscription credentials that uniquely identify Microsoft Azure
            subscription. The subscription ID forms part of the URI for every
            service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Returns a list of all platform images.:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
        - description: Location of the resource.
          in: path
          name: location
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Returns a list of all platform images.:
              value: local
        - description: Client API Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            default: 2015-12-01-preview
          examples:
            Returns a list of all platform images.:
              value: 2015-12-01-preview
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlatformImageList"
              examples:
                Returns a list of all platform images.:
                  $ref: "#/components/examples/Returns_a_list_of_all_platform_image\
                    s."
      summary: Returns all platform images.
      tags:
        - PlatformImages
  "/subscriptions/{subscriptionId}/providers/Microsoft.Compute.Admin/locations/{location}/artifactTypes/platformImage/publishers/{publisher}/offers/{offer}/skus/{sku}/versions/{version}":
    delete:
      description: Delete a platform image
      operationId: PlatformImages_Delete
      parameters:
        - description: Subscription credentials that uniquely identify Microsoft Azure
            subscription. The subscription ID forms part of the URI for every
            service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Delete a platform image.:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
        - description: Location of the resource.
          in: path
          name: location
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Delete a platform image.:
              value: local
        - description: Name of the publisher.
          in: path
          name: publisher
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Delete a platform image.:
              value: Canonical
        - $ref: "#/components/parameters/OfferParameter"
        - $ref: "#/components/parameters/SkuParameter"
        - description: The version of the resource.
          in: path
          name: version
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Delete a platform image.:
              value: "16.04"
        - description: Client API Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            default: 2015-12-01-preview
          examples:
            Delete a platform image.:
              value: 2015-12-01-preview
      responses:
        "200":
          description: OK
      summary: Deletes a platform image matching publisher, offer, skus and version
      tags:
        - PlatformImages
    get:
      description: Returns the specific platform image matching publisher, offer, skus and
        version.
      operationId: PlatformImages_Get
      parameters:
        - description: Subscription credentials that uniquely identify Microsoft Azure
            subscription. The subscription ID forms part of the URI for every
            service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Get a platform image by name.:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
        - description: Location of the resource.
          in: path
          name: location
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Get a platform image by name.:
              value: local
        - description: Name of the publisher.
          in: path
          name: publisher
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Get a platform image by name.:
              value: Canonical
        - $ref: "#/components/parameters/OfferParameter"
        - $ref: "#/components/parameters/SkuParameter"
        - description: The version of the resource.
          in: path
          name: version
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Get a platform image by name.:
              value: "16.04"
        - description: Client API Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            default: 2015-12-01-preview
          examples:
            Get a platform image by name.:
              value: 2015-12-01-preview
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlatformImage"
              examples:
                Get a platform image by name.:
                  $ref: "#/components/examples/Get_a_platform_image_by_name."
      summary: Returns the requested platform image.
      tags:
        - PlatformImages
    put:
      description: Creates a new platform image with given publisher, offer, skus and
        version.
      operationId: PlatformImages_Create
      parameters:
        - description: Subscription credentials that uniquely identify Microsoft Azure
            subscription. The subscription ID forms part of the URI for every
            service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Creates a new platform image.:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
        - description: Location of the resource.
          in: path
          name: location
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Creates a new platform image.:
              value: local
        - description: Name of the publisher.
          in: path
          name: publisher
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Creates a new platform image.:
              value: Canonical
        - $ref: "#/components/parameters/OfferParameter"
        - $ref: "#/components/parameters/SkuParameter"
        - description: The version of the resource.
          in: path
          name: version
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Creates a new platform image.:
              value: "16.04"
        - description: Client API Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            default: 2015-12-01-preview
          examples:
            Creates a new platform image.:
              value: 2015-12-01-preview
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PlatformImageParameters"
        description: New platform image.
        required: true
        x-ms-parameter-location: method
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlatformImage"
              examples:
                Creates a new platform image.:
                  $ref: "#/components/examples/Creates_a_new_platform_image."
        "201":
          description: CREATED
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlatformImage"
              examples:
                Creates a new platform image.:
                  $ref: "#/components/examples/Creates_a_new_platform_image."
        "202":
          description: ACCEPTED
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlatformImage"
              examples:
                Creates a new platform image.:
                  $ref: "#/components/examples/Creates_a_new_platform_image."
      summary: Creates a platform image.
      tags:
        - PlatformImages
      x-ms-long-running-operation: true
servers:
  - url: https://adminmanagement.local.azurestack.external
components:
  examples:
    Returns_a_list_of_all_platform_images.:
      value:
        - id: /subscriptions/8158498d-27b1-4ccf-9aa1-de0f925731e6/providers/Microsoft.Compute.Admin/locations/local/artifactTypes/platformImage/publishers/Canonical/offers/UbuntuServer/skus/16.04-LTS/versions/1.0.0
          location: local
          properties:
            osDisk:
              osType: Linux
              uri: https://test.blob.local.azurestack.external/test/medium.vhd
            provisioningState: Creating
          type: Microsoft.Compute.Admin/locations/artifactTypes/publishers/offers/skus/versions
    Get_a_platform_image_by_name.:
      value:
        id: /subscriptions/8158498d-27b1-4ccf-9aa1-de0f925731e6/providers/Microsoft.Compute.Admin/locations/local/artifactTypes/platformImage/publishers/Canonical/offers/UbuntuServer/skus/16.04-LTS/versions/1.0.0
        location: local
        properties:
          osDisk:
            osType: Linux
            uri: https://test.blob.local.azurestack.external/test/medium.vhd
          provisioningState: Creating
        type: Microsoft.Compute.Admin/locations/artifactTypes/publishers/offers/skus/versions
    Creates_a_new_platform_image.:
      value:
        id: /subscriptions/8158498d-27b1-4ccf-9aa1-de0f925731e6/providers/Microsoft.Compute.Admin/locations/local/artifactTypes/platformImage/publishers/Canonical/offers/UbuntuServer/skus/16.04-LTS/versions/1.0.0
        location: local
        properties:
          osDisk:
            osType: Linux
            uri: https://test.blob.local.azurestack.external/test/medium.vhd
          provisioningState: Creating
        type: Microsoft.Compute.Admin/locations/artifactTypes/publishers/offers/skus/versions
  parameters:
    OfferParameter:
      description: Name of the offer.
      in: path
      name: offer
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
      examples:
        Delete a platform image.:
          value: UbuntuServer
        Get a platform image by name.:
          value: UbuntuServer
        Creates a new platform image.:
          value: UbuntuServer
    SkuParameter:
      description: Name of the SKU.
      in: path
      name: sku
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
      examples:
        Delete a platform image.:
          value: 16.04-:LTS
        Get a platform image by name.:
          value: 16.04-:LTS
        Creates a new platform image.:
          value: 16.04-:LTS
  securitySchemes:
    azure_auth:
      description: Authorization uses an Azure Active Directory OAuth2 flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    DataDisk:
      description: Information about datadisk.
      properties:
        lun:
          description: Logical unit number.
          format: int32
          type: integer
        uri:
          description: Location of the disk template.
          type: string
      type: object
    ImageDetails:
      description: Information about the disk image.
      properties:
        billingPartNumber:
          description: The part number is used to bill for software costs.
          type: string
      type: object
    OsDisk:
      description: Operating system disk.
      properties:
        osType:
          $ref: "#/components/schemas/OsType"
        uri:
          description: Location of the disk.
          type: string
      type: object
    OsType:
      description: Operating system type.
      enum:
        - Unknown
        - Windows
        - Linux
      type: string
      x-ms-enum:
        name: OsType
    PlatformImage:
      allOf:
        - description: Base resource object.
          properties:
            id:
              description: ID of the resource.
              readOnly: true
              type: string
            location:
              description: Location of the resource.
              type: string
            name:
              description: Name of the resource.
              readOnly: true
              type: string
            type:
              description: Type of Resource.
              readOnly: true
              type: string
          type: object
          x-ms-azure-resource: true
      description: Platform image represents a virtual machine.
      properties:
        properties:
          $ref: "#/components/schemas/PlatformImageProperties"
      type: object
    PlatformImageList:
      description: List of platform images.
      items:
        $ref: "#/components/schemas/PlatformImage"
      type: array
    PlatformImageParameters:
      description: Parameters used to create a new platform image.
      properties:
        properties:
          $ref: "#/components/schemas/PlatformImageProperties"
      type: object
    PlatformImageProperties:
      description: Properties of platform image.
      properties:
        dataDisks:
          description: Data disks used by the platform image.
          items:
            $ref: "#/components/schemas/DataDisk"
          type: array
        details:
          $ref: "#/components/schemas/ImageDetails"
        osDisk:
          $ref: "#/components/schemas/OsDisk"
        provisioningState:
          description: The provisioning state of the resource.
          enum:
            - Creating
            - Failed
            - Succeeded
            - Canceled
          type: string
          x-ms-enum:
            name: ProvisioningState
      type: object
