openapi: 3.0.0
info:
  title: ManagementLockClient
  version: 2015-01-01
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/resources/resource-manager/Microsoft.Authorization/stable/2015-01-01/locks.json
      version: "2.0"
  x-preferred: false
  x-providerName: azure.com
  x-serviceName: resources-locks
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  "/subscriptions/{subscriptionId}/providers/Microsoft.Authorization/locks":
    get:
      description: Gets all the management locks of a subscription.
      operationId: ManagementLocks_ListAtSubscriptionLevel
      parameters:
        - description: The filter to apply on the operation.
          in: query
          name: $filter
          required: false
          schema:
            type: string
        - $ref: "#/components/parameters/ApiVersionParameter"
        - $ref: "#/components/parameters/SubscriptionIdParameter"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ManagementLockListResult"
      tags:
        - ManagementLocks
      x-ms-odata: "#/components/schemas/ManagementLockObject"
      x-ms-pageable:
        nextLinkName: nextLink
  "/subscriptions/{subscriptionId}/providers/Microsoft.Authorization/locks/{lockName}":
    delete:
      description: Deletes the management lock of a subscription.
      operationId: ManagementLocks_DeleteAtSubscriptionLevel
      parameters:
        - description: The name of lock.
          in: path
          name: lockName
          required: true
          schema:
            type: string
        - $ref: "#/components/parameters/ApiVersionParameter"
        - $ref: "#/components/parameters/SubscriptionIdParameter"
      responses:
        "200":
          description: OK
        "204":
          description: NoContent
      tags:
        - ManagementLocks
    get:
      description: Gets the management lock of a scope.
      operationId: ManagementLocks_Get
      parameters:
        - description: Name of the management lock.
          in: path
          name: lockName
          required: true
          schema:
            type: string
        - $ref: "#/components/parameters/ApiVersionParameter"
        - $ref: "#/components/parameters/SubscriptionIdParameter"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ManagementLockObject"
      tags:
        - ManagementLocks
    put:
      description: Create or update a management lock at the subscription level.
      operationId: ManagementLocks_CreateOrUpdateAtSubscriptionLevel
      parameters:
        - description: The name of lock.
          in: path
          name: lockName
          required: true
          schema:
            type: string
        - $ref: "#/components/parameters/ApiVersionParameter"
        - $ref: "#/components/parameters/SubscriptionIdParameter"
      requestBody:
        $ref: "#/components/requestBodies/ManagementLockObject"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ManagementLockObject"
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ManagementLockObject"
      tags:
        - ManagementLocks
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Authorization/locks":
    get:
      description: Gets all the management locks of a resource group.
      operationId: ManagementLocks_ListAtResourceGroupLevel
      parameters:
        - description: Resource group name.
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._\(\)]+$
        - description: The filter to apply on the operation.
          in: query
          name: $filter
          required: false
          schema:
            type: string
        - $ref: "#/components/parameters/ApiVersionParameter"
        - $ref: "#/components/parameters/SubscriptionIdParameter"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ManagementLockListResult"
      tags:
        - ManagementLocks
      x-ms-odata: "#/components/schemas/ManagementLockObject"
      x-ms-pageable:
        nextLinkName: nextLink
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Authorization/locks/{lockName}":
    delete:
      description: Deletes the management lock of a resource group.
      operationId: ManagementLocks_DeleteAtResourceGroupLevel
      parameters:
        - description: The resource group name.
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._\(\)]+$
        - description: The name of lock.
          in: path
          name: lockName
          required: true
          schema:
            type: string
        - $ref: "#/components/parameters/ApiVersionParameter"
        - $ref: "#/components/parameters/SubscriptionIdParameter"
      responses:
        "200":
          description: OK
        "204":
          description: NoContent
      tags:
        - ManagementLocks
    get:
      description: Gets a management lock at the resource group level.
      operationId: ManagementLocks_GetAtResourceGroupLevel
      parameters:
        - description: The resource group name.
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._\(\)]+$
        - description: The lock name.
          in: path
          name: lockName
          required: true
          schema:
            type: string
        - $ref: "#/components/parameters/ApiVersionParameter"
        - $ref: "#/components/parameters/SubscriptionIdParameter"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ManagementLockObject"
      tags:
        - ManagementLocks
    put:
      description: Create or update a management lock at the resource group level.
      operationId: ManagementLocks_CreateOrUpdateAtResourceGroupLevel
      parameters:
        - description: The resource group name.
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._\(\)]+$
        - description: The lock name.
          in: path
          name: lockName
          required: true
          schema:
            type: string
        - $ref: "#/components/parameters/ApiVersionParameter"
        - $ref: "#/components/parameters/SubscriptionIdParameter"
      requestBody:
        $ref: "#/components/requestBodies/ManagementLockObject"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ManagementLockObject"
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ManagementLockObject"
      tags:
        - ManagementLocks
  "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}/providers/Microsoft.Authorization/locks":
    get:
      description: Gets all the management locks of a resource or any level below resource.
      operationId: ManagementLocks_ListAtResourceLevel
      parameters:
        - description: The name of the resource group. The name is case insensitive.
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._\(\)]+$
        - description: Resource identity.
          in: path
          name: resourceProviderNamespace
          required: true
          schema:
            type: string
        - description: Resource identity.
          in: path
          name: parentResourcePath
          required: true
          x-ms-skip-url-encoding: true
          schema:
            type: string
        - description: Resource identity.
          in: path
          name: resourceType
          required: true
          x-ms-skip-url-encoding: true
          schema:
            type: string
        - description: Resource identity.
          in: path
          name: resourceName
          required: true
          schema:
            type: string
        - description: The filter to apply on the operation.
          in: query
          name: $filter
          required: false
          schema:
            type: string
        - $ref: "#/components/parameters/ApiVersionParameter"
        - $ref: "#/components/parameters/SubscriptionIdParameter"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ManagementLockListResult"
      tags:
        - ManagementLocks
      x-ms-odata: "#/components/schemas/ManagementLockObject"
      x-ms-pageable:
        nextLinkName: nextLink
  "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}/providers/Microsoft.Authorization/locks/{lockName}":
    delete:
      description: Deletes the management lock of a resource or any level below resource.
      operationId: ManagementLocks_DeleteAtResourceLevel
      parameters:
        - description: "The name of the resource group. "
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._\(\)]+$
        - description: Resource identity.
          in: path
          name: resourceProviderNamespace
          required: true
          schema:
            type: string
        - description: Resource identity.
          in: path
          name: parentResourcePath
          required: true
          x-ms-skip-url-encoding: true
          schema:
            type: string
        - description: Resource identity.
          in: path
          name: resourceType
          required: true
          x-ms-skip-url-encoding: true
          schema:
            type: string
        - description: Resource identity.
          in: path
          name: resourceName
          required: true
          schema:
            type: string
        - description: The name of lock.
          in: path
          name: lockName
          required: true
          schema:
            type: string
        - $ref: "#/components/parameters/ApiVersionParameter"
        - $ref: "#/components/parameters/SubscriptionIdParameter"
      responses:
        "200":
          description: OK
        "204":
          description: NoContent
      tags:
        - ManagementLocks
    put:
      description: Create or update a management lock at the resource level or any level
        below resource.
      operationId: ManagementLocks_CreateOrUpdateAtResourceLevel
      parameters:
        - description: "The name of the resource group. "
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._\(\)]+$
        - description: Resource identity.
          in: path
          name: resourceProviderNamespace
          required: true
          schema:
            type: string
        - description: Resource identity.
          in: path
          name: parentResourcePath
          required: true
          x-ms-skip-url-encoding: true
          schema:
            type: string
        - description: Resource identity.
          in: path
          name: resourceType
          required: true
          x-ms-skip-url-encoding: true
          schema:
            type: string
        - description: Resource identity.
          in: path
          name: resourceName
          required: true
          schema:
            type: string
        - description: The name of lock.
          in: path
          name: lockName
          required: true
          schema:
            type: string
        - $ref: "#/components/parameters/ApiVersionParameter"
        - $ref: "#/components/parameters/SubscriptionIdParameter"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ManagementLockObject"
        description: Create or update management lock parameters.
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ManagementLockObject"
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ManagementLockObject"
      tags:
        - ManagementLocks
servers:
  - url: https://management.azure.com
components:
  parameters:
    ApiVersionParameter:
      description: The API version to use for the operation.
      in: query
      name: api-version
      required: true
      schema:
        type: string
    SubscriptionIdParameter:
      description: The ID of the target subscription.
      in: path
      name: subscriptionId
      required: true
      schema:
        type: string
  requestBodies:
    ManagementLockObject:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ManagementLockObject"
      description: The management lock parameters.
      required: true
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    ManagementLockListResult:
      description: List of management locks.
      properties:
        nextLink:
          description: The URL to get the next set of results.
          type: string
        value:
          description: The list of locks.
          items:
            $ref: "#/components/schemas/ManagementLockObject"
          type: array
    ManagementLockObject:
      description: Management lock information.
      properties:
        id:
          description: The Id of the lock.
          readOnly: true
          type: string
        name:
          description: The name of the lock.
          type: string
        properties:
          $ref: "#/components/schemas/ManagementLockProperties"
        type:
          description: The type of the lock.
          readOnly: true
          type: string
      x-ms-azure-resource: true
    ManagementLockProperties:
      description: The management lock properties.
      properties:
        level:
          description: The lock level of the management lock.
          enum:
            - NotSpecified
            - CanNotDelete
            - ReadOnly
          type: string
          x-ms-enum:
            modelAsString: true
            name: LockLevel
        notes:
          description: The notes of the management lock.
          type: string
