openapi: 3.0.0
info:
  description: Azure Feature Exposure Control (AFEC) provides a mechanism for the resource
    providers to control feature exposure to users. Resource providers typically
    use this mechanism to provide public/private preview for new features prior
    to making them generally available. Users need to explicitly register for
    AFEC features to get access to such functionality.
  title: FeatureClient
  version: 2015-12-01
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/resources/resource-manager/Microsoft.Features/stable/2015-12-01/features.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: resources-features
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  /providers/Microsoft.Features/operations:
    get:
      description: Lists all of the available Microsoft.Features REST API operations.
      operationId: ListOperations
      parameters:
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: OK. The request has succeeded.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OperationListResult"
              examples:
                List Features operations:
                  $ref: "#/components/examples/List_Features_operations"
            text/json:
              schema:
                $ref: "#/components/schemas/OperationListResult"
              examples:
                List Features operations:
                  $ref: "#/components/examples/List_Features_operations"
      tags:
        - Operations
      x-ms-pageable:
        nextLinkName: nextLink
  "/subscriptions/{subscriptionId}/providers/Microsoft.Features/features":
    get:
      description: Gets all the preview features that are available through AFEC for the
        subscription.
      operationId: Features_ListAll
      parameters:
        - $ref: "#/components/parameters/ApiVersionParameter"
        - $ref: "#/components/parameters/SubscriptionIdParameter"
      responses:
        "200":
          description: OK - Returns an array containing metadata for each feature. The
            metadata includes the name of the feature, the registration state,
            the resource ID, and resource type.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FeatureOperationsListResult"
              examples:
                List subscription Features:
                  $ref: "#/components/examples/List_subscription_Features"
            text/json:
              schema:
                $ref: "#/components/schemas/FeatureOperationsListResult"
              examples:
                List subscription Features:
                  $ref: "#/components/examples/List_subscription_Features"
      tags:
        - Features
      x-ms-pageable:
        nextLinkName: nextLink
  "/subscriptions/{subscriptionId}/providers/Microsoft.Features/providers/{resourceProviderNamespace}/features":
    get:
      description: Gets all the preview features in a provider namespace that are available
        through AFEC for the subscription.
      operationId: Features_List
      parameters:
        - description: The namespace of the resource provider for getting features.
          in: path
          name: resourceProviderNamespace
          required: true
          schema:
            type: string
          examples:
            List provider Features:
              value: Resource Provider Namespace
        - $ref: "#/components/parameters/ApiVersionParameter"
        - $ref: "#/components/parameters/SubscriptionIdParameter"
      responses:
        "200":
          description: OK - Returns an array containing metadata for each feature in the
            resource provider. The metadata includes the name of the feature,
            the registration state, the resource ID, and resource type.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FeatureOperationsListResult"
              examples:
                List provider Features:
                  $ref: "#/components/examples/List_provider_Features"
            text/json:
              schema:
                $ref: "#/components/schemas/FeatureOperationsListResult"
              examples:
                List provider Features:
                  $ref: "#/components/examples/List_provider_Features"
      tags:
        - Features
      x-ms-pageable:
        nextLinkName: nextLink
  "/subscriptions/{subscriptionId}/providers/Microsoft.Features/providers/{resourceProviderNamespace}/features/{featureName}":
    get:
      description: Gets the preview feature with the specified name.
      operationId: Features_Get
      parameters:
        - description: The resource provider namespace for the feature.
          in: path
          name: resourceProviderNamespace
          required: true
          schema:
            type: string
          examples:
            Get feature:
              value: Resource Provider Namespace
        - description: The name of the feature to get.
          in: path
          name: featureName
          required: true
          schema:
            type: string
          examples:
            Get feature:
              value: feature
        - $ref: "#/components/parameters/ApiVersionParameter"
        - $ref: "#/components/parameters/SubscriptionIdParameter"
      responses:
        "200":
          description: OK - Returns metadata about the feature. The metadata includes the
            name of the feature, the registration state, the resource ID, and
            resource type.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FeatureResult"
              examples:
                Get feature:
                  $ref: "#/components/examples/Get_feature"
            text/json:
              schema:
                $ref: "#/components/schemas/FeatureResult"
              examples:
                Get feature:
                  $ref: "#/components/examples/Get_feature"
      tags:
        - Features
  "/subscriptions/{subscriptionId}/providers/Microsoft.Features/providers/{resourceProviderNamespace}/features/{featureName}/register":
    post:
      description: Registers the preview feature for the subscription.
      operationId: Features_Register
      parameters:
        - description: The namespace of the resource provider.
          in: path
          name: resourceProviderNamespace
          required: true
          schema:
            type: string
          examples:
            Register feature:
              value: Resource Provider Namespace
        - description: The name of the feature to register.
          in: path
          name: featureName
          required: true
          schema:
            type: string
          examples:
            Register feature:
              value: feature
        - $ref: "#/components/parameters/ApiVersionParameter"
        - $ref: "#/components/parameters/SubscriptionIdParameter"
      responses:
        "200":
          description: OK - Returns metadata about the registered feature. The metadata
            includes the name of the feature, the registration state, the
            resource ID, and resource type.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FeatureResult"
              examples:
                Register feature:
                  $ref: "#/components/examples/Register_feature"
            text/json:
              schema:
                $ref: "#/components/schemas/FeatureResult"
              examples:
                Register feature:
                  $ref: "#/components/examples/Register_feature"
      tags:
        - Features
servers:
  - url: https://management.azure.com
components:
  examples:
    List_Features_operations:
      value:
        value:
          - display:
              operation: Read
              provider: Microsoft.ResourceProvider
              resource: Resource1
            name: FeaturesOpeartion1
          - display:
              operation: Write
              provider: Microsoft.ResourceProvider
              resource: Resource2
            name: FeaturesOpeartion2
    List_subscription_Features:
      value:
        value:
          - id: feature_id1
            name: Feature1
            properties:
              state: registered
            type: type1
          - id: feature_id2
            name: Feature2
            properties:
              state: unregistered
            type: type2
    List_provider_Features:
      value:
        value:
          - id: feature_id1
            name: Feature1
            properties:
              state: registered
            type: type1
          - id: feature_id2
            name: Feature2
            properties:
              state: unregistered
            type: type2
    Get_feature:
      value:
        id: feature_id1
        name: Feature1
        properties:
          state: registered
        type: type1
    Register_feature:
      value:
        id: feature_id1
        name: Feature1
        properties:
          state: registered
        type: type1
  parameters:
    ApiVersionParameter:
      description: The API version to use for this operation.
      in: query
      name: api-version
      required: true
      schema:
        type: string
      examples:
        List Features operations:
          value: 2015-12-01
        List subscription Features:
          value: 2015-12-01
        List provider Features:
          value: 2015-12-01
        Get feature:
          value: 2015-12-01
        Register feature:
          value: 2015-12-01
    SubscriptionIdParameter:
      description: The ID of the target subscription.
      in: path
      name: subscriptionId
      required: true
      schema:
        type: string
      examples:
        List subscription Features:
          value: subid
        List provider Features:
          value: subid
        Get feature:
          value: subid
        Register feature:
          value: subid
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    FeatureOperationsListResult:
      description: List of previewed features.
      properties:
        nextLink:
          description: The URL to use for getting the next set of results.
          type: string
        value:
          description: The array of features.
          items:
            $ref: "#/components/schemas/FeatureResult"
          type: array
    FeatureProperties:
      description: Information about feature.
      properties:
        state:
          description: The registration state of the feature for the subscription.
          type: string
    FeatureResult:
      description: Previewed feature information.
      properties:
        id:
          description: The resource ID of the feature.
          type: string
        name:
          description: The name of the feature.
          type: string
        properties:
          $ref: "#/components/schemas/FeatureProperties"
        type:
          description: The resource type of the feature.
          type: string
    Operation:
      description: Microsoft.Features operation
      properties:
        display:
          description: The object that represents the operation.
          properties:
            operation:
              description: "Operation type: Read, write, delete, etc."
              type: string
            provider:
              description: "Service provider: Microsoft.Features"
              type: string
            resource:
              description: "Resource on which the operation is performed: Profile,
                endpoint, etc."
              type: string
        name:
          description: "Operation name: {provider}/{resource}/{operation}"
          type: string
      type: object
    OperationListResult:
      description: Result of the request to list Microsoft.Features operations. It contains
        a list of operations and a URL link to get the next set of results.
      properties:
        nextLink:
          description: URL to get the next set of operation list results if there are any.
          type: string
        value:
          description: List of Microsoft.Features operations.
          items:
            $ref: "#/components/schemas/Operation"
          type: array
