openapi: 3.0.0
info:
  description: Describes the schema of the Azure ServiceBus Messaging events published to
    Azure Event Grid. This corresponds to the Data property of an
    EventGridEvent.
  title: Schema of Azure ServiceBus Messaging events published to Azure Event Grid
  version: 2018-01-01
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/eventgrid/data-plane/Microsoft.ServiceBus/stable/2018-01-01/ServiceBus.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: eventgrid-ServiceBus
  x-tags:
    - Azure
    - Microsoft
paths: {}
servers:
  - url: https://azure.local
components:
  schemas:
    ServiceBusActiveMessagesAvailableWithNoListenersEventData:
      description: Schema of the Data property of an EventGridEvent for a
        Microsoft.ServiceBus.ActiveMessagesAvailableWithNoListeners event.
      properties:
        entityType:
          description: The entity type of the Microsoft.ServiceBus resource. Could be one
            of 'queue' or 'subscriber'.
          type: string
        namespaceName:
          description: The namespace name of the Microsoft.ServiceBus resource.
          type: string
        queueName:
          description: The name of the Microsoft.ServiceBus queue. If the entity type is of
            type 'subscriber', then this value will be null.
          type: string
        requestUri:
          description: The endpoint of the Microsoft.ServiceBus resource.
          type: string
        subscriptionName:
          description: The name of the Microsoft.ServiceBus topic's subscription. If the
            entity type is of type 'queue', then this value will be null.
          type: string
        topicName:
          description: The name of the Microsoft.ServiceBus topic. If the entity type is of
            type 'queue', then this value will be null.
          type: string
      type: object
    ServiceBusDeadletterMessagesAvailableWithNoListenersEventData:
      description: Schema of the Data property of an EventGridEvent for a
        Microsoft.ServiceBus.DeadletterMessagesAvailableWithNoListenersEvent
        event.
      properties:
        entityType:
          description: The entity type of the Microsoft.ServiceBus resource. Could be one
            of 'queue' or 'subscriber'.
          type: string
        namespaceName:
          description: The namespace name of the Microsoft.ServiceBus resource.
          type: string
        queueName:
          description: The name of the Microsoft.ServiceBus queue. If the entity type is of
            type 'subscriber', then this value will be null.
          type: string
        requestUri:
          description: The endpoint of the Microsoft.ServiceBus resource.
          type: string
        subscriptionName:
          description: The name of the Microsoft.ServiceBus topic's subscription. If the
            entity type is of type 'queue', then this value will be null.
          type: string
        topicName:
          description: The name of the Microsoft.ServiceBus topic. If the entity type is of
            type 'queue', then this value will be null.
          type: string
      type: object
