openapi: 3.0.0
info:
  title: Azure Database Migration Service Resource Provider
  version: 2018-04-19
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/datamigration/resource-manager/Microsoft.DataMigration/stable/2018-04-19/definitions/GetTdeCertificatesSqlTask.json
      version: "2.0"
  x-preferred: false
  x-providerName: azure.com
  x-serviceName: datamigration-GetTdeCertificatesSqlTask
  x-tags:
    - Azure
    - Microsoft
paths: {}
servers:
  - url: https://azure.local
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    GetTdeCertificatesSqlTaskInput:
      description: Input for the task that gets TDE certificates in Base64 encoded format.
      properties:
        backupFileShare:
          description: File share information with Path, Username, and Password.
          properties:
            password:
              description: Password credential used to connect to the share location.
              type: string
            path:
              description: The folder path for this share.
              type: string
            userName:
              description: User name credential to connect to the share location
              type: string
          required:
            - path
          type: object
        connectionInfo:
          allOf:
            - description: Defines the connection properties of a server
              discriminator:
                propertyName: type
              properties:
                password:
                  description: Password credential.
                  type: string
                type:
                  description: Type of connection info
                  type: string
                userName:
                  description: User name
                  type: string
              required:
                - type
              type: object
          description: Information for connecting to SQL database server
          properties:
            additionalSettings:
              description: Additional connection settings
              type: string
            authentication:
              description: An enumeration of possible authentication types when connecting
              enum:
                - None
                - WindowsAuthentication
                - SqlAuthentication
                - ActiveDirectoryIntegrated
                - ActiveDirectoryPassword
              type: string
              x-ms-enum:
                modelAsString: true
                name: AuthenticationType
            dataSource:
              description: Data source in the format
                Protocol:MachineName\SQLServerInstanceName,PortNumber
              type: string
            encryptConnection:
              default: true
              description: Whether to encrypt the connection
              type: boolean
            platform:
              description: An enumeration of source platform types
              enum:
                - SqlOnPrem
              type: string
              x-ms-enum:
                modelAsString: true
                name: SqlSourcePlatform
            trustServerCertificate:
              default: false
              description: Whether to trust the server certificate
              type: boolean
          required:
            - dataSource
          type: object
          x-ms-discriminator-value: SqlConnectionInfo
        selectedCertificates:
          description: List containing certificate names and corresponding password to use
            for encrypting the exported certificate.
          items:
            $ref: "#/components/schemas/SelectedCertificateInput"
          type: array
      required:
        - connectionInfo
        - backupFileShare
        - selectedCertificates
      type: object
    GetTdeCertificatesSqlTaskOutput:
      description: Output of the task that gets TDE certificates in Base64 encoded format.
      properties:
        base64EncodedCertificates:
          additionalProperties:
            items:
              type: string
            type: array
          description: Mapping from certificate name to base 64 encoded format.
          readOnly: true
          type: string
        validationErrors:
          description: Validation errors
          items:
            description: Exception object for all custom exceptions
            properties:
              actionableMessage:
                description: Actionable steps for this exception
                type: string
              filePath:
                description: The path to the file where exception occurred
                readOnly: true
                type: string
              hResult:
                description: Coded numerical value that is assigned to a specific exception
                readOnly: true
                type: integer
              lineNumber:
                description: The line number where exception occurred
                readOnly: true
                type: string
              message:
                description: Error message
                readOnly: true
                type: string
              stackTrace:
                description: Stack trace
                readOnly: true
                type: string
            type: object
          readOnly: true
          type: array
      type: object
    SelectedCertificateInput:
      description: Info for certificate to be exported for TDE enabled databases.
      properties:
        certificateName:
          description: Name of certificate to be exported.
          type: string
        password:
          description: Password to use for encrypting the exported certificate.
          type: string
      required:
        - certificateName
        - password
      type: object
