openapi: 3.0.0
info:
  title: AutomationManagement
  version: 2017-05-15-preview
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/automation/resource-manager/Microsoft.Automation/preview/2017-05-15-preview/sourceControlSyncJobStreams.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: automation-sourceControlSyncJobStreams
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}/sourceControls/{sourceControlName}/sourceControlSyncJobs/{sourceControlSyncJobId}/streams":
    get:
      description: Retrieve a list of sync job streams identified by sync job id.
      externalDocs:
        url: http://aka.ms/azureautomationsdk/sourcecontrolsyncjoboperations
      operationId: SourceControlSyncJobStreams_ListBySyncJob
      parameters:
        - description: Name of an Azure Resource group.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._]+$
          examples:
            Get a list of sync job streams identified by sync job id:
              value: rg
        - description: The name of the automation account.
          in: path
          name: automationAccountName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Get a list of sync job streams identified by sync job id:
              value: myAutomationAccount33
        - description: The source control name.
          in: path
          name: sourceControlName
          required: true
          schema:
            type: string
          examples:
            Get a list of sync job streams identified by sync job id:
              value: MySourceControl
        - description: The source control sync job id.
          in: path
          name: sourceControlSyncJobId
          required: true
          schema:
            type: string
            format: uuid
          examples:
            Get a list of sync job streams identified by sync job id:
              value: ce6fe3e3-9db3-4096-a6b4-82bfb4c10a2b
        - description: The filter to apply on the operation.
          in: query
          name: $filter
          required: false
          schema:
            type: string
        - description: Gets subscription credentials which uniquely identify Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Get a list of sync job streams identified by sync job id:
              value: subid
        - description: Client Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Get a list of sync job streams identified by sync job id:
              value: 2017-05-15-preview
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SourceControlSyncJobStreamsListBySyncJob"
              examples:
                Get a list of sync job streams identified by sync job id:
                  $ref: "#/components/examples/Get_a_list_of_sync_job_streams_ident\
                    ified_by_sync_job_id"
        default:
          description: Automation error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response of an operation failure
                properties:
                  code:
                    description: Error code
                    type: string
                  message:
                    description: Error message indicating why the operation failed.
                    type: string
                type: object
      tags:
        - SourceControlSyncJobStreams
      x-ms-pageable:
        nextLinkName: nextLink
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}/sourceControls/{sourceControlName}/sourceControlSyncJobs/{sourceControlSyncJobId}/streams/{streamId}":
    get:
      description: Retrieve a sync job stream identified by stream id.
      externalDocs:
        url: http://aka.ms/azureautomationsdk/sourcecontrolsyncjoboperations
      operationId: SourceControlSyncJobStreams_Get
      parameters:
        - description: Name of an Azure Resource group.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._]+$
          examples:
            Get a sync job stream identified by sync job stream id.:
              value: rg
        - description: The name of the automation account.
          in: path
          name: automationAccountName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Get a sync job stream identified by sync job stream id.:
              value: myAutomationAccount33
        - description: The source control name.
          in: path
          name: sourceControlName
          required: true
          schema:
            type: string
          examples:
            Get a sync job stream identified by sync job stream id.:
              value: MySourceControl
        - description: The source control sync job id.
          in: path
          name: sourceControlSyncJobId
          required: true
          schema:
            type: string
            format: uuid
          examples:
            Get a sync job stream identified by sync job stream id.:
              value: ce6fe3e3-9db3-4096-a6b4-82bfb4c10a2b
        - description: The id of the sync job stream.
          in: path
          name: streamId
          required: true
          schema:
            type: string
          examples:
            Get a sync job stream identified by sync job stream id.:
              value: b86c5c31-e9fd-4734-8764-ddd6c101e706_00636596855139029522_00000000000000000007
        - description: Gets subscription credentials which uniquely identify Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Get a sync job stream identified by sync job stream id.:
              value: subid
        - description: Client Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Get a sync job stream identified by sync job stream id.:
              value: 2017-05-15-preview
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SourceControlSyncJobStreamById"
              examples:
                Get a sync job stream identified by sync job stream id.:
                  $ref: "#/components/examples/Get_a_sync_job_stream_identified_by_\
                    sync_job_stream_id."
        default:
          description: Automation error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response of an operation failure
                properties:
                  code:
                    description: Error code
                    type: string
                  message:
                    description: Error message indicating why the operation failed.
                    type: string
                type: object
      tags:
        - SourceControlSyncJobStreams
servers:
  - url: https://management.azure.com
components:
  examples:
    Get_a_list_of_sync_job_streams_identified_by_sync_job_id:
      value:
        value:
          - id: /subscriptions/subid/resourceGroups/rg/providers/Microsoft.Automation/automationAccounts/myAutomationAccount33/sourceControls/MySourceControl/sourceControlSyncJobs/ce6fe3e3-9db3-4096-a6b4-82bfb4c10a2b/streams/b86c5c31-e9fd-4734-8764-ddd6c101e706_00636596855134810785_00000000000000000005
            properties:
              sourceControlSyncJobStreamId: b86c5c31-e9fd-4734-8764-ddd6c101e706_00636596855134810785_00000000000000000005
              streamType: Error
              summary: "ForbiddenError: The server failed to authenticate the request.
                Verify that the certificate is valid and is associated with this
                subscription."
              time: 2017-03-28T23:14:26.903+00:00
          - id: /subscriptions/subid/resourceGroups/rg/providers/Microsoft.Automation/automationAccounts/myAutomationAccount33/sourceControls/MySourceControl/sourceControlSyncJobs/ce6fe3e3-9db3-4096-a6b4-82bfb4c10a2b/streams/b86c5c31-e9fd-4734-8764-ddd6c101e706_00636596855136998262_00000000000000000006
            properties:
              sourceControlSyncJobStreamId: b86c5c31-e9fd-4734-8764-ddd6c101e706_00636596855136998262_00000000000000000006
              streamType: Error
              summary: "System.Management.Automation.RuntimeException: Cannot index
                into a null array.\r

                \   at CallSite.Target(Closure , CallSite ,
                Object , Int32 )\r

                \   at
                System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](Ca\
                llSite site, T0 arg0, T1 arg1)\r

                \   at
                System.Management.Automation.Interpreter.DynamicInstruction`3.R\
                un(InterpretedFrame frame)\r

                \   at
                System.Management.Automation.Interpreter.EnterTryCatchFinallyIn\
                struction.Run(InterpretedFrame frame)"
              time: 2017-03-28T23:14:27.903+00:00
          - id: /subscriptions/subid/resourceGroups/rg/providers/Microsoft.Automation/automationAccounts/myAutomationAccount33/sourceControls/MySourceControl/sourceControlSyncJobs/ce6fe3e3-9db3-4096-a6b4-82bfb4c10a2b/streams/b86c5c31-e9fd-4734-8764-ddd6c101e706_00636596855139029522_00000000000000000007
            properties:
              sourceControlSyncJobStreamId: b86c5c31-e9fd-4734-8764-ddd6c101e706_00636596855139029522_00000000000000000007
              streamType: Error
              summary: "System.Management.Automation.ParameterBindingValidationExcepti\
                on: Cannot validate argument on parameter 'Location'. The
                argument is null or empty. Provide an argument that is not null
                or empty, and then try the command again. --->
                System.Management.Automation.ValidationMetadataException: The
                argument is null or empty. Provide an argument that is not null
                or empty, and then try the command again.\r

                \   at
                System.Management.Automation.ValidateNotNullOrEmptyAttribute.Va\
                lidate(Object arguments, EngineIntrinsics engineIntrinsics)"
              time: 2017-03-28T23:14:28.903+00:00
    Get_a_sync_job_stream_identified_by_sync_job_stream_id.:
      value:
        id: /subscriptions/subid/resourceGroups/rg/providers/Microsoft.Automation/automationAccounts/myAutomationAccount33/sourceControls/MySourceControl/sourceControlSyncJobs/ce6fe3e3-9db3-4096-a6b4-82bfb4c10a2b/streams/b86c5c31-e9fd-4734-8764-ddd6c101e706_00636596855139029522_00000000000000000007
        properties:
          sourceControlSyncJobStreamId: b86c5c31-e9fd-4734-8764-ddd6c101e706_00636596855139029522_00000000000000000007
          streamText: "New-AzureAffinityGroup : Cannot validate argument on parameter
            'Location'. The argument is null or empty. Provide an \r

            argument that is not null or empty, and then try the
            command again.\r

            At DatabaseExportImport1fba401e-0:69 char:69\r

            + \r

            \ + CategoryInfo : InvalidData: . . . ."
          streamType: Error
          summary: ""
          time: 2017-03-28T23:14:26.903+00:00
          value:
            Exception:
              Message: "System.Management.Automation.ParameterBindingValidationExcepti\
                on: Cannot validate argument on parameter 'Location'. The
                argument is null or empty . . .} }"
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    SourceControlSyncJobStream:
      description: Definition of the source control sync job stream.
      properties:
        id:
          description: Resource id.
          readOnly: true
          type: string
        properties:
          $ref: "#/components/schemas/SourceControlSyncJobStreamProperties"
    SourceControlSyncJobStreamById:
      description: Definition of the source control sync job stream by id.
      properties:
        id:
          description: Resource id.
          readOnly: true
          type: string
        properties:
          $ref: "#/components/schemas/SourceControlSyncJobStreamByIdProperties"
    SourceControlSyncJobStreamByIdProperties:
      description: Definition of source control sync job stream by id properties.
      properties:
        sourceControlSyncJobStreamId:
          description: The sync job stream id.
          type: string
        streamText:
          description: The text of the sync job stream.
          type: string
        streamType:
          description: The type of the sync job stream.
          enum:
            - Error
            - Output
          type: string
          x-ms-enum:
            modelAsString: true
            name: streamType
        summary:
          description: The summary of the sync job stream.
          type: string
        time:
          description: The time of the sync job stream.
          format: date-time
          readOnly: true
          type: string
          nullable: true
        value:
          additionalProperties:
            type: object
          description: The values of the job stream.
          type: object
    SourceControlSyncJobStreamProperties:
      description: Definition of source control sync job stream properties.
      properties:
        sourceControlSyncJobStreamId:
          description: The sync job stream id.
          type: string
        streamType:
          description: The type of the sync job stream.
          enum:
            - Error
            - Output
          type: string
          x-ms-enum:
            modelAsString: true
            name: streamType
        summary:
          description: The summary of the sync job stream.
          type: string
        time:
          description: The time of the sync job stream.
          format: date-time
          readOnly: true
          type: string
          nullable: true
    SourceControlSyncJobStreamsListBySyncJob:
      description: The response model for the list source control sync job streams
        operation.
      properties:
        nextLink:
          description: The next link.
          readOnly: true
          type: string
        value:
          description: The list of source control sync job streams.
          items:
            $ref: "#/components/schemas/SourceControlSyncJobStream"
          type: array
