openapi: 3.0.0
info:
  description: The Admin Subscriptions Management Client.
  title: SubscriptionsManagementClient
  version: 2015-11-01
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/azsadmin/resource-manager/subscriptions/Microsoft.Subscriptions.Admin/preview/2015-11-01/DelegatedProvider.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: azsadmin-DelegatedProvider
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  "/subscriptions/{subscriptionId}/providers/Microsoft.Subscriptions.Admin/delegatedProviders":
    get:
      description: Get the list of delegatedProviders.
      operationId: DelegatedProviders_List
      parameters:
        - description: Subscription credentials which uniquely identify Microsoft Azure
            subscription.The subscription ID forms part of the URI for every
            service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Get the list of delegatedProviders.:
              value: 8ab2551d-41e5-489b-9273-1cdf1cbc7dc6
        - description: Client Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            default: 2015-11-01
          examples:
            Get the list of delegatedProviders.:
              value: 2015-11-01
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                description: List of subscriptions.
                properties:
                  nextLink:
                    description: URI to the next page.
                    type: string
                  value:
                    description: Subscription definition.
                    items:
                      description: List of supported operations.
                      properties:
                        delegatedProviderSubscriptionId:
                          description: Parent DelegatedProvider subscription identifier.
                          type: string
                        displayName:
                          description: Subscription name.
                          type: string
                        externalReferenceId:
                          description: External reference identifier.
                          type: string
                        id:
                          description: Fully qualified identifier.
                          type: string
                        offerId:
                          description: Identifier of the offer under the scope of a
                            delegated provider.
                          type: string
                        owner:
                          description: Subscription owner.
                          type: string
                        routingResourceManagerType:
                          description: Resource manager type.
                          enum:
                            - Default
                            - Admin
                          type: string
                          x-ms-enum:
                            modelAsString: true
                            name: ResourceManagerType
                        state:
                          description: Subscription notification state.
                          enum:
                            - NotDefined
                            - Enabled
                            - Warned
                            - PastDue
                            - Disabled
                            - Deleted
                            - Deleting
                            - PartiallyDeleted
                          type: string
                          x-ms-enum:
                            modelAsString: true
                            name: SubscriptionState
                            values:
                              - description: Subscription is active. New resources can be
                                  created.
                                name: Enabled
                                value: Enabled
                              - description: This state is not used in Azure Stack.
                                name: PastDue
                                value: PastDue
                              - description: This state is not used in Azure Stack.
                                name: Warned
                                value: Warned
                              - description: Subscription is not active and usage is not
                                  reported. Resources are shut down (VMs stopped
                                  and deallocated, IP addresses are freed, etc).
                                  During this period, the Azure Stack Operator
                                  can re-enable the subscription which allows
                                  creation of new resources but doesn’t
                                  automatically restore disabled resources.
                                name: Disabled
                                value: Disabled
                              - description: This state is unique to Azure Stack and is
                                  only visible to the Azure Stack Operator, and
                                  if used, to the respective Delegated Provider.
                                  Resources and Data are being deleted before
                                  subscription state is set to Deleted. This
                                  state cannot be reversed. It means that
                                  deletion is in progress.
                                name: Deleting
                                value: Deleting
                              - description: Final state of subscription. All resources and
                                  data are deleted. This state cannot be
                                  reversed.
                                name: Deleted
                                value: Deleted
                              - description: This state is not used in Azure Stack.
                                name: NotDefined
                                value: NotDefined
                              - description: This state is unique to Azure Stack and is
                                  only visible to the Azure Stack Operator, and
                                  if used, to the respective Delegated Provider.
                                  It means that deletion failed.  You can’t
                                  reverse the deletion process, so in this state
                                  all you can do is restart deletion.  This
                                  state is not reported to RPs.
                                name: PartiallyDeleted
                                value: PartiallyDeleted
                        subscriptionId:
                          description: Subscription identifier.
                          type: string
                        tenantId:
                          description: Directory tenant identifier.
                          type: string
                      type: object
                    type: array
              examples:
                Get the list of delegatedProviders.:
                  $ref: "#/components/examples/Get_the_list_of_delegatedProviders."
      tags:
        - DelegatedProviders
      x-ms-pageable: {}
  "/subscriptions/{subscriptionId}/providers/Microsoft.Subscriptions.Admin/delegatedProviders/{delegatedProvider}":
    get:
      description: Get the specified delegated provider.
      operationId: DelegatedProviders_Get
      parameters:
        - description: Subscription credentials which uniquely identify Microsoft Azure
            subscription.The subscription ID forms part of the URI for every
            service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Get the specified delegated provider.:
              value: 8ab2551d-41e5-489b-9273-1cdf1cbc7dc6
        - description: DelegatedProvider identifier.
          in: path
          name: delegatedProvider
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Get the specified delegated provider.:
              value: ServiceAdmin
        - description: Client Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            default: 2015-11-01
          examples:
            Get the specified delegated provider.:
              value: 2015-11-01
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                description: List of supported operations.
                properties:
                  delegatedProviderSubscriptionId:
                    description: Parent DelegatedProvider subscription identifier.
                    type: string
                  displayName:
                    description: Subscription name.
                    type: string
                  externalReferenceId:
                    description: External reference identifier.
                    type: string
                  id:
                    description: Fully qualified identifier.
                    type: string
                  offerId:
                    description: Identifier of the offer under the scope of a delegated
                      provider.
                    type: string
                  owner:
                    description: Subscription owner.
                    type: string
                  routingResourceManagerType:
                    description: Resource manager type.
                    enum:
                      - Default
                      - Admin
                    type: string
                    x-ms-enum:
                      modelAsString: true
                      name: ResourceManagerType
                  state:
                    description: Subscription notification state.
                    enum:
                      - NotDefined
                      - Enabled
                      - Warned
                      - PastDue
                      - Disabled
                      - Deleted
                      - Deleting
                      - PartiallyDeleted
                    type: string
                    x-ms-enum:
                      modelAsString: true
                      name: SubscriptionState
                      values:
                        - description: Subscription is active. New resources can be created.
                          name: Enabled
                          value: Enabled
                        - description: This state is not used in Azure Stack.
                          name: PastDue
                          value: PastDue
                        - description: This state is not used in Azure Stack.
                          name: Warned
                          value: Warned
                        - description: Subscription is not active and usage is not
                            reported. Resources are shut down (VMs stopped and
                            deallocated, IP addresses are freed, etc). During
                            this period, the Azure Stack Operator can re-enable
                            the subscription which allows creation of new
                            resources but doesn’t automatically restore disabled
                            resources.
                          name: Disabled
                          value: Disabled
                        - description: This state is unique to Azure Stack and is only
                            visible to the Azure Stack Operator, and if used, to
                            the respective Delegated Provider. Resources and
                            Data are being deleted before subscription state is
                            set to Deleted. This state cannot be reversed. It
                            means that deletion is in progress.
                          name: Deleting
                          value: Deleting
                        - description: Final state of subscription. All resources and data
                            are deleted. This state cannot be reversed.
                          name: Deleted
                          value: Deleted
                        - description: This state is not used in Azure Stack.
                          name: NotDefined
                          value: NotDefined
                        - description: This state is unique to Azure Stack and is only
                            visible to the Azure Stack Operator, and if used, to
                            the respective Delegated Provider. It means that
                            deletion failed.  You can’t reverse the deletion
                            process, so in this state all you can do is restart
                            deletion.  This state is not reported to RPs.
                          name: PartiallyDeleted
                          value: PartiallyDeleted
                  subscriptionId:
                    description: Subscription identifier.
                    type: string
                  tenantId:
                    description: Directory tenant identifier.
                    type: string
                type: object
              examples:
                Get the specified delegated provider.:
                  $ref: "#/components/examples/Get_the_specified_delegated_provider."
      tags:
        - DelegatedProviders
servers:
  - url: https://adminmanagement.local.azurestack.external
components:
  examples:
    Get_the_list_of_delegatedProviders.:
      value:
        value:
          - delegatedProviderSubscriptionId: 8ab2551d-41e5-489b-9273-1cdf1cbc7dc6
            displayName: Default Provider Subscription
            id: /subscriptions/8ab2551d-41e5-489b-9273-1cdf1cbc7dc6/providers/Microsoft.Subscriptions.Admin/subscriptions/8ab2551d-41e5-489b-9273-1cdf1cbc7dc6
            offerId: /subscriptions/8ab2551d-41e5-489b-9273-1cdf1cbc7dc6/resourceGroups/system.global/providers/Microsoft.Subscriptions.Admin/offers/5790469D-0852-480D-AF9F-F4CCE1BB8B62
            owner: admin@contoso.com
            routingResourceManagerType: Admin
            state: Enabled
            subscriptionId: 8ab2551d-41e5-489b-9273-1cdf1cbc7dc6
            tenantId: 2b3697e6-a7a2-4cdd-a3d4-f4ef6505cd4f
          - delegatedProviderSubscriptionId: 8ab2551d-41e5-489b-9273-1cdf1cbc7dc6
            displayName: ResellerSub
            id: /subscriptions/8ab2551d-41e5-489b-9273-1cdf1cbc7dc6/providers/Microsoft.Subscriptions.Admin/subscriptions/5ef8575a-14db-4d02-8313-b9122385722b
            offerId: /subscriptions/8ab2551d-41e5-489b-9273-1cdf1cbc7dc6/resourceGroups/testrg/providers/Microsoft.Subscriptions.Admin/offers/reselleroffer
            owner: tenantadmin1@msazurestack.onmicrosoft.com
            routingResourceManagerType: Default
            state: Enabled
            subscriptionId: 5ef8575a-14db-4d02-8313-b9122385722b
            tenantId: 2b3697e6-a7a2-4cdd-a3d4-f4ef6505cd4f
    Get_the_specified_delegated_provider.:
      value:
        delegatedProviderSubscriptionId: 8ab2551d-41e5-489b-9273-1cdf1cbc7dc6
        displayName: Default Provider Subscription
        id: /subscriptions/8ab2551d-41e5-489b-9273-1cdf1cbc7dc6/providers/Microsoft.Subscriptions.Admin/subscriptions/8ab2551d-41e5-489b-9273-1cdf1cbc7dc6
        offerId: /subscriptions/8ab2551d-41e5-489b-9273-1cdf1cbc7dc6/resourceGroups/system.global/providers/Microsoft.Subscriptions.Admin/offers/5790469D-0852-480D-AF9F-F4CCE1BB8B62
        owner: admin@contoso.com
        routingResourceManagerType: Admin
        state: Enabled
        subscriptionId: 8ab2551d-41e5-489b-9273-1cdf1cbc7dc6
        tenantId: 2b3697e6-a7a2-4cdd-a3d4-f4ef6505cd4f
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
