openapi: 3.0.0
info:
  description: Mixed Reality Resource Provider Proxy API
  title: Mixed Reality
  version: 2019-12-02-preview
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/mixedreality/resource-manager/Microsoft.MixedReality/preview/2019-12-02-preview/proxy.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: mixedreality-proxy
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  /providers/Microsoft.MixedReality/operations:
    get:
      description: Exposing Available Operations
      operationId: Operations_List
      parameters:
        - description: Version of the API to be used with the client request.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            OperationPage:
              value: 2019-02-28-preview
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OperationPage"
              examples:
                OperationPage:
                  $ref: "#/components/examples/OperationPage"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Response on Error
                properties:
                  code:
                    description: String that can be used to programmatically identify the
                      error.
                    type: string
                  details:
                    description: An array of JSON objects that MUST contain name/value
                      pairs for code and message, and MAY contain a name/value
                      pair for target, as described above.The contents of this
                      section are service-defined but must adhere to the
                      aforementioned schema.
                    type: string
                  message:
                    description: Describes the error in detail and provides debugging
                      information
                    type: string
                  target:
                    description: The target of the particular error
                    type: string
                required:
                  - message
                  - code
                type: object
      tags:
        - Proxy
      x-ms-pageable:
        nextLinkName: nextLink
  "/subscriptions/{subscriptionId}/providers/Microsoft.MixedReality/locations/{location}/checkNameAvailability":
    post:
      description: Check Name Availability for local uniqueness
      operationId: CheckNameAvailabilityLocal
      parameters:
        - description: Azure subscription ID.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            CheckLocalNameAvailability:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
        - description: The location in which uniqueness will be verified.
          in: path
          name: location
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._\(\)]+$
          examples:
            CheckLocalNameAvailability:
              value: Global
        - description: Version of the API to be used with the client request.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            CheckLocalNameAvailability:
              value: 2019-02-28-preview
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CheckNameAvailabilityRequest"
        description: Check Name Availability Request.
        required: true
        x-ms-parameter-location: method
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CheckNameAvailabilityResponse"
              examples:
                CheckLocalNameAvailability:
                  $ref: "#/components/examples/CheckLocalNameAvailability"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Response on Error
                properties:
                  code:
                    description: String that can be used to programmatically identify the
                      error.
                    type: string
                  details:
                    description: An array of JSON objects that MUST contain name/value
                      pairs for code and message, and MAY contain a name/value
                      pair for target, as described above.The contents of this
                      section are service-defined but must adhere to the
                      aforementioned schema.
                    type: string
                  message:
                    description: Describes the error in detail and provides debugging
                      information
                    type: string
                  target:
                    description: The target of the particular error
                    type: string
                required:
                  - message
                  - code
                type: object
      tags:
        - Proxy
servers:
  - url: https://management.azure.com
components:
  examples:
    OperationPage:
      value:
        value:
          - display:
              description: Registers a subscription for the Mixed Reality resource provider.
              operation: Registers the Mixed Reality resource provider
              provider: Microsoft.MixedReality
              resource: Mixed Reality resource provider
            name: Microsoft.MixedReality/register/action
          - display:
              description: Deletes the resource for
                Microsoft.MixedReality/SpatialAnchorsAccounts
              operation: Delete Spatial Anchors Accounts
              provider: Microsoft.MixedReality
              resource: SpatialAnchorsAccounts
            name: Microsoft.MixedReality/SpatialAnchorsAccounts/delete
          - display:
              description: Gets the resource for
                Microsoft.MixedReality/SpatialAnchorsAccounts
              operation: Get Spatial Anchors Accounts
              provider: Microsoft.MixedReality
              resource: SpatialAnchorsAccounts
            name: Microsoft.MixedReality/SpatialAnchorsAccounts/read
          - display:
              description: Updates the resource for
                Microsoft.MixedReality/SpatialAnchorsAccounts
              operation: Update Spatial Anchors Accounts
              provider: Microsoft.MixedReality
              resource: SpatialAnchorsAccounts
            name: Microsoft.MixedReality/SpatialAnchorsAccounts/write
    CheckLocalNameAvailability:
      value:
        message: ...
        nameAvailable: "false"
        reason: AlreadyExists
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: Impersonate your user account
  schemas:
    CheckNameAvailabilityRequest:
      description: Check Name Availability Request
      properties:
        name:
          description: Resource Name To Verify
          type: string
        type:
          description: Fully qualified resource type which includes provider namespace
          type: string
      required:
        - name
        - type
      type: object
    CheckNameAvailabilityResponse:
      description: Check Name Availability Response
      properties:
        message:
          description: detail message
          type: string
        nameAvailable:
          $ref: "#/components/schemas/NameAvailability"
        reason:
          $ref: "#/components/schemas/NameUnavailableReason"
      required:
        - nameAvailable
      type: object
    NameAvailability:
      description: Whether or not the name is available.
      enum:
        - "true"
        - "false"
      type: string
      x-ms-enum:
        modelAsString: true
        name: NameAvailability
    NameUnavailableReason:
      description: reason of name unavailable.
      enum:
        - Invalid
        - AlreadyExists
      type: string
      x-ms-enum:
        modelAsString: true
        name: NameUnavailableReason
    Operation:
      description: REST API operation
      properties:
        display:
          $ref: "#/components/schemas/OperationDisplay"
        name:
          description: "Operation name: {provider}/{resource}/{operation}"
          type: string
      type: object
    OperationDisplay:
      description: The object that represents the operation.
      properties:
        description:
          description: Description of operation
          type: string
        operation:
          description: "Operation type: Read, write, delete, etc."
          type: string
        provider:
          description: "Service provider: Microsoft.ResourceProvider"
          type: string
        resource:
          description: "Resource on which the operation is performed: Profile, endpoint,
            etc."
          type: string
      required:
        - provider
        - resource
        - operation
        - description
      type: object
    OperationPage:
      description: Result of the request to list Resource Provider operations. It contains
        a list of operations and a URL link to get the next set of results.
      properties:
        nextLink:
          description: URL to get the next set of operation list results if there are any.
          type: string
        value:
          description: List of operations supported by the Resource Provider.
          items:
            $ref: "#/components/schemas/Operation"
          type: array
