openapi: 3.0.0
info:
  description: To manage and control access to your resources, you can define customized
    policies and assign them at a scope.
  title: PolicyClient
  version: 2016-12-01
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/resources/resource-manager/Microsoft.Authorization/stable/2016-12-01/policyDefinitions.json
      version: "2.0"
  x-preferred: false
  x-providerName: azure.com
  x-serviceName: resources-policyDefinitions
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  /providers/Microsoft.Authorization/policyDefinitions:
    get:
      description: Gets all the built in policy definitions.
      operationId: PolicyDefinitions_ListBuiltIn
      parameters:
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: OK - Returns an array of built in policy definitions.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PolicyDefinitionListResult"
            text/json:
              schema:
                $ref: "#/components/schemas/PolicyDefinitionListResult"
      tags:
        - PolicyDefinitions
      x-ms-pageable:
        nextLinkName: nextLink
  "/providers/Microsoft.Authorization/policyDefinitions/{policyDefinitionName}":
    get:
      description: Gets the built in policy definition.
      operationId: PolicyDefinitions_GetBuiltIn
      parameters:
        - description: The name of the built in policy definition to get.
          in: path
          name: policyDefinitionName
          required: true
          schema:
            type: string
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: OK - Returns information about the built in policy definition.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PolicyDefinition"
            text/json:
              schema:
                $ref: "#/components/schemas/PolicyDefinition"
      tags:
        - PolicyDefinitions
  "/providers/Microsoft.Management/managementgroups/{managementGroupId}/providers/Microsoft.Authorization/policyDefinitions":
    get:
      description: Gets all the policy definitions for a subscription at management group
        level.
      operationId: PolicyDefinitions_ListByManagementGroup
      parameters:
        - $ref: "#/components/parameters/ApiVersionParameter"
        - $ref: "#/components/parameters/ManagementGroupIdParameter"
      responses:
        "200":
          description: OK - Returns ana array of policy definitions.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PolicyDefinitionListResult"
            text/json:
              schema:
                $ref: "#/components/schemas/PolicyDefinitionListResult"
      tags:
        - PolicyDefinitions
      x-ms-pageable:
        nextLinkName: nextLink
  "/providers/Microsoft.Management/managementgroups/{managementGroupId}/providers/Microsoft.Authorization/policyDefinitions/{policyDefinitionName}":
    delete:
      description: Deletes a policy definition at management group level.
      operationId: PolicyDefinitions_DeleteAtManagementGroup
      parameters:
        - description: The name of the policy definition to delete.
          in: path
          name: policyDefinitionName
          required: true
          schema:
            type: string
        - $ref: "#/components/parameters/ApiVersionParameter"
        - $ref: "#/components/parameters/ManagementGroupIdParameter"
      responses:
        "200":
          description: OK
        "204":
          description: No Content
      tags:
        - PolicyDefinitions
    get:
      description: Gets the policy definition at management group level.
      operationId: PolicyDefinitions_GetAtManagementGroup
      parameters:
        - description: The name of the policy definition to get.
          in: path
          name: policyDefinitionName
          required: true
          schema:
            type: string
        - $ref: "#/components/parameters/ApiVersionParameter"
        - $ref: "#/components/parameters/ManagementGroupIdParameter"
      responses:
        "200":
          description: OK - Returns information about the policy definition.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PolicyDefinition"
            text/json:
              schema:
                $ref: "#/components/schemas/PolicyDefinition"
      tags:
        - PolicyDefinitions
    put:
      description: Creates or updates a policy definition at management group level.
      operationId: PolicyDefinitions_CreateOrUpdateAtManagementGroup
      parameters:
        - description: The name of the policy definition to create.
          in: path
          name: policyDefinitionName
          required: true
          schema:
            type: string
        - $ref: "#/components/parameters/ApiVersionParameter"
        - $ref: "#/components/parameters/ManagementGroupIdParameter"
      requestBody:
        $ref: "#/components/requestBodies/PolicyDefinition"
      responses:
        "201":
          description: Created - Returns information about the policy definition.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PolicyDefinition"
            text/json:
              schema:
                $ref: "#/components/schemas/PolicyDefinition"
      tags:
        - PolicyDefinitions
  "/subscriptions/{subscriptionId}/providers/Microsoft.Authorization/policyDefinitions":
    get:
      description: Gets all the policy definitions for a subscription.
      operationId: PolicyDefinitions_List
      parameters:
        - $ref: "#/components/parameters/ApiVersionParameter"
        - $ref: "#/components/parameters/SubscriptionIdParameter"
      responses:
        "200":
          description: OK - Returns ana array of policy definitions.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PolicyDefinitionListResult"
            text/json:
              schema:
                $ref: "#/components/schemas/PolicyDefinitionListResult"
      tags:
        - PolicyDefinitions
      x-ms-pageable:
        nextLinkName: nextLink
  "/subscriptions/{subscriptionId}/providers/Microsoft.Authorization/policyDefinitions/{policyDefinitionName}":
    delete:
      description: Deletes a policy definition.
      operationId: PolicyDefinitions_Delete
      parameters:
        - description: The name of the policy definition to delete.
          in: path
          name: policyDefinitionName
          required: true
          schema:
            type: string
        - $ref: "#/components/parameters/ApiVersionParameter"
        - $ref: "#/components/parameters/SubscriptionIdParameter"
      responses:
        "200":
          description: OK
        "204":
          description: No Content
      tags:
        - PolicyDefinitions
    get:
      description: Gets the policy definition.
      operationId: PolicyDefinitions_Get
      parameters:
        - description: The name of the policy definition to get.
          in: path
          name: policyDefinitionName
          required: true
          schema:
            type: string
        - $ref: "#/components/parameters/ApiVersionParameter"
        - $ref: "#/components/parameters/SubscriptionIdParameter"
      responses:
        "200":
          description: OK - Returns information about the policy definition.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PolicyDefinition"
            text/json:
              schema:
                $ref: "#/components/schemas/PolicyDefinition"
      tags:
        - PolicyDefinitions
    put:
      description: Creates or updates a policy definition.
      operationId: PolicyDefinitions_CreateOrUpdate
      parameters:
        - description: The name of the policy definition to create.
          in: path
          name: policyDefinitionName
          required: true
          schema:
            type: string
        - $ref: "#/components/parameters/ApiVersionParameter"
        - $ref: "#/components/parameters/SubscriptionIdParameter"
      requestBody:
        $ref: "#/components/requestBodies/PolicyDefinition"
      responses:
        "201":
          description: Created - Returns information about the policy definition.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PolicyDefinition"
            text/json:
              schema:
                $ref: "#/components/schemas/PolicyDefinition"
      tags:
        - PolicyDefinitions
servers:
  - url: https://management.azure.com
components:
  parameters:
    ApiVersionParameter:
      description: The API version to use for the operation.
      in: query
      name: api-version
      required: true
      schema:
        type: string
    ManagementGroupIdParameter:
      description: The ID of the management group.
      in: path
      name: managementGroupId
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
    SubscriptionIdParameter:
      description: The ID of the target subscription.
      in: path
      name: subscriptionId
      required: true
      schema:
        type: string
  requestBodies:
    PolicyDefinition:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PolicyDefinition"
        text/json:
          schema:
            $ref: "#/components/schemas/PolicyDefinition"
      description: The policy definition properties.
      required: true
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    PolicyDefinition:
      description: The policy definition.
      properties:
        id:
          description: The ID of the policy definition.
          readOnly: true
          type: string
        name:
          description: The name of the policy definition.
          readOnly: true
          type: string
        properties:
          $ref: "#/components/schemas/PolicyDefinitionProperties"
      x-ms-azure-resource: true
    PolicyDefinitionListResult:
      description: List of policy definitions.
      properties:
        nextLink:
          description: The URL to use for getting the next set of results.
          type: string
        value:
          description: An array of policy definitions.
          items:
            $ref: "#/components/schemas/PolicyDefinition"
          type: array
    PolicyDefinitionProperties:
      description: The policy definition properties.
      properties:
        description:
          description: The policy definition description.
          type: string
        displayName:
          description: The display name of the policy definition.
          type: string
        metadata:
          description: The policy definition metadata.
          type: object
        mode:
          description: The policy definition mode. Possible values are NotSpecified,
            Indexed, and All.
          enum:
            - NotSpecified
            - Indexed
            - All
          type: string
          x-ms-enum:
            modelAsString: true
            name: policyMode
        parameters:
          description: Required if a parameter is used in policy rule.
          type: object
        policyRule:
          description: The policy rule.
          type: object
        policyType:
          description: The type of policy definition. Possible values are NotSpecified,
            BuiltIn, and Custom.
          enum:
            - NotSpecified
            - BuiltIn
            - Custom
          type: string
          x-ms-enum:
            modelAsString: true
            name: policyType
