openapi: 3.0.0
info:
  title: Azure Database Migration Service Resource Provider
  version: 2018-04-19
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/datamigration/resource-manager/Microsoft.DataMigration/stable/2018-04-19/definitions/ConnectToTargetSqlDbTask.json
      version: "2.0"
  x-preferred: false
  x-providerName: azure.com
  x-serviceName: datamigration-ConnectToTargetSqlDbTask
  x-tags:
    - Azure
    - Microsoft
paths: {}
servers:
  - url: https://azure.local
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    ConnectToTargetSqlDbTaskInput:
      description: Input for the task that validates connection to SQL DB and target server
        requirements
      properties:
        targetConnectionInfo:
          allOf:
            - description: Defines the connection properties of a server
              discriminator:
                propertyName: type
              properties:
                password:
                  description: Password credential.
                  type: string
                type:
                  description: Type of connection info
                  type: string
                userName:
                  description: User name
                  type: string
              required:
                - type
              type: object
          description: Information for connecting to SQL database server
          properties:
            additionalSettings:
              description: Additional connection settings
              type: string
            authentication:
              description: An enumeration of possible authentication types when connecting
              enum:
                - None
                - WindowsAuthentication
                - SqlAuthentication
                - ActiveDirectoryIntegrated
                - ActiveDirectoryPassword
              type: string
              x-ms-enum:
                modelAsString: true
                name: AuthenticationType
            dataSource:
              description: Data source in the format
                Protocol:MachineName\SQLServerInstanceName,PortNumber
              type: string
            encryptConnection:
              default: true
              description: Whether to encrypt the connection
              type: boolean
            platform:
              description: An enumeration of source platform types
              enum:
                - SqlOnPrem
              type: string
              x-ms-enum:
                modelAsString: true
                name: SqlSourcePlatform
            trustServerCertificate:
              default: false
              description: Whether to trust the server certificate
              type: boolean
          required:
            - dataSource
          type: object
          x-ms-discriminator-value: SqlConnectionInfo
      required:
        - targetConnectionInfo
      type: object
    ConnectToTargetSqlDbTaskOutput:
      description: Output for the task that validates connection to SQL DB and target
        server requirements
      properties:
        databases:
          additionalProperties:
            type: string
          description: Source databases as a map from database name to database id
          readOnly: true
          type: string
        id:
          description: Result identifier
          readOnly: true
          type: string
        targetServerBrandVersion:
          description: Target server brand version
          readOnly: true
          type: string
        targetServerVersion:
          description: Version of the target server
          readOnly: true
          type: string
      type: object
