openapi: 3.0.0
info:
  description: The Microsoft Azure Network management API provides a RESTful set of web
    services that interact with Microsoft Azure Networks service to manage your
    network resources. The API has entities that capture the relationship
    between an end user and the Microsoft Azure Networks service.
  title: NetworkManagementClient
  version: 2019-04-01
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/network/resource-manager/Microsoft.Network/stable/2019-04-01/ddosCustomPolicy.json
      version: "2.0"
  x-preferred: false
  x-providerName: azure.com
  x-serviceName: network-ddosCustomPolicy
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/ddosCustomPolicies/{ddosCustomPolicyName}":
    delete:
      description: Deletes the specified DDoS custom policy.
      operationId: DdosCustomPolicies_Delete
      parameters:
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
          examples:
            Delete DDoS custom policy:
              value: rg1
        - description: The name of the DDoS custom policy.
          in: path
          name: ddosCustomPolicyName
          required: true
          schema:
            type: string
          examples:
            Delete DDoS custom policy:
              value: test-ddos-custom-policy
        - description: Client API version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Delete DDoS custom policy:
              value: 2019-04-01
        - description: The subscription credentials which uniquely identify the Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Delete DDoS custom policy:
              value: subid
      responses:
        "200":
          description: Delete successful.
        "202":
          description: Accepted and the operation will complete asynchronously.
        "204":
          description: Request successful. Resource does not exist.
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CloudError"
      tags:
        - ddosCustomPolicies
      x-ms-long-running-operation: true
      x-ms-long-running-operation-options:
        final-state-via: location
    get:
      description: Gets information about the specified DDoS custom policy.
      operationId: DdosCustomPolicies_Get
      parameters:
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
          examples:
            Get DDoS custom policy:
              value: rg1
        - description: The name of the DDoS custom policy.
          in: path
          name: ddosCustomPolicyName
          required: true
          schema:
            type: string
          examples:
            Get DDoS custom policy:
              value: test-ddos-custom-policy
        - description: Client API version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Get DDoS custom policy:
              value: 2019-04-01
        - description: The subscription credentials which uniquely identify the Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Get DDoS custom policy:
              value: subid
      responses:
        "200":
          description: Request successful. The operation returns the specified DDoS custom
            policy resource.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DdosCustomPolicy"
              examples:
                Get DDoS custom policy:
                  $ref: "#/components/examples/Get_DDoS_custom_policy"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CloudError"
      tags:
        - ddosCustomPolicies
    patch:
      description: Update a DDoS custom policy tags.
      operationId: DdosCustomPolicies_UpdateTags
      parameters:
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
          examples:
            DDoS Custom policy Update tags:
              value: rg1
        - description: The name of the DDoS custom policy.
          in: path
          name: ddosCustomPolicyName
          required: true
          schema:
            type: string
          examples:
            DDoS Custom policy Update tags:
              value: test-ddos-custom-policy
        - description: Client API version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            DDoS Custom policy Update tags:
              value: 2019-04-01
        - description: The subscription credentials which uniquely identify the Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            DDoS Custom policy Update tags:
              value: subid
      requestBody:
        content:
          application/json:
            schema:
              description: Tags object for patch operations.
              properties:
                tags:
                  additionalProperties:
                    type: string
                  description: Resource tags.
                  type: object
        description: Parameters supplied to the update DDoS custom policy resource tags.
        required: true
      responses:
        "200":
          description: Update successful. The operation returns the resulting DDoS custom
            policy resource.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DdosCustomPolicy"
              examples:
                DDoS Custom policy Update tags:
                  $ref: "#/components/examples/DDoS_Custom_policy_Update_tags"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CloudError"
      tags:
        - ddosCustomPolicies
      x-ms-long-running-operation: true
    put:
      description: Creates or updates a DDoS custom policy.
      operationId: DdosCustomPolicies_CreateOrUpdate
      parameters:
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
          examples:
            Create DDoS custom policy:
              value: rg1
        - description: The name of the DDoS custom policy.
          in: path
          name: ddosCustomPolicyName
          required: true
          schema:
            type: string
          examples:
            Create DDoS custom policy:
              value: test-ddos-custom-policy
        - description: Client API version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Create DDoS custom policy:
              value: 2019-04-01
        - description: The subscription credentials which uniquely identify the Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Create DDoS custom policy:
              value: subid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DdosCustomPolicy"
        description: Parameters supplied to the create or update operation.
        required: true
      responses:
        "200":
          description: Update successful. The operation returns the resulting DDoS custom
            policy resource.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DdosCustomPolicy"
              examples:
                Create DDoS custom policy:
                  $ref: "#/components/examples/Create_DDoS_custom_policy"
        "201":
          description: Create successful. The operation returns the resulting DDoS custom
            policy resource.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DdosCustomPolicy"
              examples:
                Create DDoS custom policy:
                  $ref: "#/components/examples/Create_DDoS_custom_policy"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CloudError"
      tags:
        - ddosCustomPolicies
      x-ms-long-running-operation: true
      x-ms-long-running-operation-options:
        final-state-via: azure-async-operation
servers:
  - url: https://management.azure.com
components:
  examples:
    Get_DDoS_custom_policy:
      value:
        id: /subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/ddosCustomPolicies/test-ddos-custom-policy
        location: westus
        name: test-ddos-custom-policy
        properties:
          provisioningState: Succeeded
          publicIPAddresses:
            - id: /subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/publicIPAddresses/test-ip
          resourceGuid: 00000000-0000-0000-0000-000000000000
        type: Microsoft.Network/ddosCustomPolicies
    DDoS_Custom_policy_Update_tags:
      value:
        id: /subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/ddosCustomPolicies/test-ddos-custom-policy
        location: westus
        name: test-ddos-custom-policy
        properties:
          protocolCustomSettings:
            - protocol: Tcp
              triggerRateOverride: "20000"
          provisioningState: Succeeded
          publicIPAddresses: []
          resourceGuid: 00000000-0000-0000-0000-000000000000
        tags:
          tag1: value1
          tag2: value2
        type: Microsoft.Network/ddosCustomPolicies
    Create_DDoS_custom_policy:
      value:
        id: /subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/ddosCustomPolicies/test-ddos-custom-policy
        location: westus
        name: test-ddos-custom-policy
        properties:
          protocolCustomSettings:
            - protocol: Tcp
              triggerRateOverride: "20000"
          provisioningState: Succeeded
          publicIPAddresses: []
          resourceGuid: 00000000-0000-0000-0000-000000000000
        type: Microsoft.Network/ddosCustomPolicies
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    CloudError:
      description: An error response from the Batch service.
      properties:
        error:
          $ref: "#/components/schemas/CloudErrorBody"
      x-ms-external: true
    CloudErrorBody:
      description: An error response from the Batch service.
      properties:
        code:
          description: An identifier for the error. Codes are invariant and are intended to
            be consumed programmatically.
          type: string
        details:
          description: A list of additional details about the error.
          items:
            $ref: "#/components/schemas/CloudErrorBody"
          type: array
        message:
          description: A message describing the error, intended to be suitable for display
            in a user interface.
          type: string
        target:
          description: The target of the particular error. For example, the name of the
            property in error.
          type: string
      x-ms-external: true
    DdosCustomPolicy:
      allOf:
        - description: Common resource representation.
          properties:
            id:
              description: Resource ID.
              type: string
            location:
              description: Resource location.
              type: string
            name:
              description: Resource name.
              readOnly: true
              type: string
            tags:
              additionalProperties:
                type: string
              description: Resource tags.
              type: object
            type:
              description: Resource type.
              readOnly: true
              type: string
          x-ms-azure-resource: true
      description: A DDoS custom policy in a resource group.
      properties:
        etag:
          description: A unique read-only string that changes whenever the resource is
            updated.
          readOnly: true
          type: string
        properties:
          $ref: "#/components/schemas/DdosCustomPolicyPropertiesFormat"
    DdosCustomPolicyPropertiesFormat:
      description: DDoS custom policy properties.
      properties:
        protocolCustomSettings:
          description: The protocol-specific DDoS policy customization parameters.
          items:
            $ref: "#/components/schemas/ProtocolCustomSettingsFormat"
          readOnly: false
          type: array
        provisioningState:
          description: "The provisioning state of the DDoS custom policy resource. Possible
            values are: 'Succeeded', 'Updating', 'Deleting', and 'Failed'."
          readOnly: true
          type: string
        publicIPAddresses:
          description: The list of public IPs associated with the DDoS custom policy
            resource. This list is read-only.
          items:
            description: Reference to another subresource.
            properties:
              id:
                description: Resource ID.
                type: string
            x-ms-azure-resource: true
          readOnly: true
          type: array
        resourceGuid:
          description: The resource GUID property of the DDoS custom policy resource. It
            uniquely identifies the resource, even if the user changes its name
            or migrate the resource across subscriptions or resource groups.
          readOnly: true
          type: string
    ProtocolCustomSettingsFormat:
      description: DDoS custom policy properties.
      properties:
        protocol:
          description: The protocol for which the DDoS protection policy is being
            customized.
          enum:
            - Tcp
            - Udp
            - Syn
          readOnly: false
          type: string
          x-ms-enum:
            modelAsString: true
            name: DdosCustomPolicyProtocol
        sourceRateOverride:
          description: The customized DDoS protection source rate.
          readOnly: false
          type: string
        triggerRateOverride:
          description: The customized DDoS protection trigger rate.
          readOnly: false
          type: string
        triggerSensitivityOverride:
          description: "The customized DDoS protection trigger rate sensitivity degrees.
            High: Trigger rate set with most sensitivity w.r.t. normal traffic.
            Default: Trigger rate set with moderate sensitivity w.r.t. normal
            traffic. Low: Trigger rate set with less sensitivity w.r.t. normal
            traffic. Relaxed: Trigger rate set with least sensitivity w.r.t.
            normal traffic."
          enum:
            - Relaxed
            - Low
            - Default
            - High
          readOnly: false
          type: string
          x-ms-enum:
            modelAsString: true
            name: DdosCustomPolicyTriggerSensitivityOverride
