openapi: 3.0.0
info:
  description: Scale unit operation endpoints and objects.
  title: FabricAdminClient
  version: 2016-05-01
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/azsadmin/resource-manager/fabric/Microsoft.Fabric.Admin/preview/2016-05-01/ScaleUnit.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: azsadmin-ScaleUnit
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Fabric.Admin/fabricLocations/{location}/scaleUnits":
    get:
      description: Returns a list of all scale units at a location.
      operationId: ScaleUnits_List
      parameters:
        - description: Subscription credentials that uniquely identify Microsoft Azure
            subscription. The subscription ID forms part of the URI for every
            service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Returns a list of all scale units at a location.:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
        - description: Name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Returns a list of all scale units at a location.:
              value: System.local
        - description: Location of the resource.
          in: path
          name: location
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Returns a list of all scale units at a location.:
              value: local
        - description: Client API Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            default: 2016-05-01
          examples:
            Returns a list of all scale units at a location.:
              value: 2016-05-01
        - description: OData filter parameter.
          in: query
          name: $filter
          x-ms-parameter-location: method
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScaleUnitList"
              examples:
                Returns a list of all scale units at a location.:
                  $ref: "#/components/examples/Returns_a_list_of_all_scale_units_at\
                    _a_location."
        "404":
          description: NOT FOUND
      tags:
        - ScaleUnits
      x-ms-odata: "#/components/schemas/ScaleUnit"
      x-ms-pageable:
        nextLinkName: nextLink
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Fabric.Admin/fabricLocations/{location}/scaleUnits/{scaleUnit}":
    get:
      description: Returns the requested scale unit.
      operationId: ScaleUnits_Get
      parameters:
        - description: Subscription credentials that uniquely identify Microsoft Azure
            subscription. The subscription ID forms part of the URI for every
            service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Returns the requested scale unit:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
        - description: Name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Returns the requested scale unit:
              value: System.local
        - description: Location of the resource.
          in: path
          name: location
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Returns the requested scale unit:
              value: local
        - $ref: "#/components/parameters/ScaleUnitParameter"
        - description: Client API Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            default: 2016-05-01
          examples:
            Returns the requested scale unit:
              value: 2016-05-01
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScaleUnit"
              examples:
                Returns the requested scale unit:
                  $ref: "#/components/examples/Returns_the_requested_scale_unit"
        "404":
          description: NOT FOUND
      tags:
        - ScaleUnits
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Fabric.Admin/fabricLocations/{location}/scaleUnits/{scaleUnit}/createFromJson":
    post:
      description: Add a new scale unit.
      operationId: ScaleUnits_CreateFromJson
      parameters:
        - description: Subscription credentials that uniquely identify Microsoft Azure
            subscription. The subscription ID forms part of the URI for every
            service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Add a new scale unit.:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
        - description: Name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Add a new scale unit.:
              value: System.local
        - description: Location of the resource.
          in: path
          name: location
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Add a new scale unit.:
              value: local
        - $ref: "#/components/parameters/ScaleUnitParameter"
        - description: Client API Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            default: 2016-05-01
          examples:
            Add a new scale unit.:
              value: 2016-05-01
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateFromJsonScaleUnitParametersList"
        description: A list of input data that allows for creating the new scale unit.
        required: true
        x-ms-parameter-location: method
      responses:
        "200":
          description: OK
        "202":
          description: ACCEPTED
      tags:
        - ScaleUnits
      x-ms-long-running-operation: true
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Fabric.Admin/fabricLocations/{location}/scaleUnits/{scaleUnit}/scaleOut":
    post:
      description: Scales out a scale unit.
      operationId: ScaleUnits_ScaleOut
      parameters:
        - description: Subscription credentials that uniquely identify Microsoft Azure
            subscription. The subscription ID forms part of the URI for every
            service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Scales out a scale unit.:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
        - description: Name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Scales out a scale unit.:
              value: System.local
        - description: Location of the resource.
          in: path
          name: location
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Scales out a scale unit.:
              value: local
        - $ref: "#/components/parameters/ScaleUnitParameter"
        - description: Client API Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            default: 2016-05-01
          examples:
            Scales out a scale unit.:
              value: 2016-05-01
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ScaleOutScaleUnitParametersList"
        description: A list of input data that allows for adding a set of scale unit nodes.
        required: true
        x-ms-parameter-location: method
      responses:
        "200":
          description: OK
        "202":
          description: ACCEPTED
      tags:
        - ScaleUnits
      x-ms-long-running-operation: true
servers:
  - url: https://adminmanagement.local.azurestack.external
components:
  examples:
    Returns_a_list_of_all_scale_units_at_a_location.:
      value:
        value:
          - id: /subscriptions/23a94a7f-64b3-42d8-807c-733284339015/resourceGroups/System.local/providers/Microsoft.Fabric.Admin/fabricLocations/local/scaleUnits/S-Cluster
            location: local
            name: S-Cluster
            properties:
              isMultiNode: false
              logicalFaultDomain: 0
              nodes:
                - /subscriptions/23a94a7f-64b3-42d8-807c-733284339015/resourceGroups/system.local/providers/Microsoft.Fabric.Admin/fabricLocations/local/scaleUnitNodes/HC1u15a2437
              scaleUnitType: HyperConverged
              state: Running
              totalCapacity:
                cores: 32
                memoryGB: 511.8877
            tags: {}
            type: Microsoft.Fabric.Admin/fabricLocations/scaleUnits
    Returns_the_requested_scale_unit:
      value:
        id: /subscriptions/23a94a7f-64b3-42d8-807c-733284339015/resourceGroups/System.local/providers/Microsoft.Fabric.Admin/fabricLocations/local/scaleUnits/S-Cluster
        location: local
        name: S-Cluster
        properties:
          isMultiNode: false
          logicalFaultDomain: 0
          nodes:
            - /subscriptions/23a94a7f-64b3-42d8-807c-733284339015/resourceGroups/system.local/providers/Microsoft.Fabric.Admin/fabricLocations/local/scaleUnitNodes/HC1u15a2437
          scaleUnitType: HyperConverged
          state: Running
          totalCapacity:
            cores: 32
            memoryGB: 511.8877
        tags: {}
        type: Microsoft.Fabric.Admin/fabricLocations/scaleUnits
  parameters:
    ScaleUnitParameter:
      description: Name of the scale units.
      in: path
      name: scaleUnit
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
      examples:
        Returns the requested scale unit:
          value: S-Cluster
        Add a new scale unit.:
          value: cluster
        Scales out a scale unit.:
          value: S-Cluster
  securitySchemes:
    azure_auth:
      description: Authorization uses an Azure Active Directory OAuth2 flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    CreateFromJsonScaleUnitParametersList:
      description: A list of input data that allows for creating the new scale unit.
      properties:
        clusterName:
          description: Cluster name for the new scale unit.
          type: string
        infrastructureNetwork:
          $ref: "#/components/schemas/NetworkDefinitionParameter"
        netQosPriority:
          description: The network QOS priority setting.
          format: int32
          type: integer
        physicalNodes:
          description: List of nodes in the scale unit.
          items:
            $ref: "#/components/schemas/DeploymentJsonPhysicalNodeParameters"
          type: array
        softwareBgpAsn:
          description: The software ASN for the cluster's rack.
          type: string
        storageNetwork:
          $ref: "#/components/schemas/NetworkDefinitionParameter"
        torSwitchBgpAsn:
          description: The ASN for the cluster's rack TOR.
          type: string
        torSwitchBgpPeerIp:
          description: The list of IP addresses used for TOR communication.
          items:
            type: string
          type: array
      type: object
    DeploymentJsonPhysicalNodeParameters:
      description: Description of a bare metal node used for scale unit scale out
        operations.
      properties:
        bmcIpAddress:
          description: BMC address of the physical machine.
          type: string
          x-ms-client-name: BMCIPAddress
        name:
          description: Computer name of the physical machine.
          type: string
      type: object
    NetworkDefinitionParameter:
      description: A definition of the network received from a new cluster operation.
      properties:
        subnet:
          description: The subnet IP mask in the example format 10.0.0.0/25.
          items:
            type: string
          type: array
        vlanId:
          description: The Vlan ID of the subnet.
          items:
            type: string
          type: array
      type: object
    ScaleOutScaleUnitParameters:
      description: Input data that allows for adding a scale unit node.
      properties:
        bmcIpv4Address:
          description: BMC address of the physical machine.
          type: string
          x-ms-client-name: BMCIPv4Address
        computerName:
          description: Computer name of the physical machine.
          type: string
      type: object
    ScaleOutScaleUnitParametersList:
      description: A list of input data that allows for adding a set of scale unit nodes.
      properties:
        awaitStorageConvergence:
          description: Flag indicates if the operation should wait for storage to converge
            before returning.
          type: boolean
        nodeList:
          description: List of nodes in the scale unit.
          items:
            $ref: "#/components/schemas/ScaleOutScaleUnitParameters"
          type: array
      type: object
    ScaleUnit:
      allOf:
        - description: Base resource object.
          properties:
            id:
              description: URI of the resource.
              readOnly: true
              type: string
            location:
              description: The region where the resource is located.
              type: string
            name:
              description: Name of the resource.
              readOnly: true
              type: string
            tags:
              additionalProperties:
                type: string
              description: List of key-value pairs.
              type: object
            type:
              description: Type of resource.
              readOnly: true
              type: string
          type: object
          x-ms-azure-resource: true
      description: Represents a cluster. Generally, the cluster will be a collection of
        hosts backed by failover cluster manager.
      properties:
        properties:
          $ref: "#/components/schemas/ScaleUnitModel"
      type: object
    ScaleUnitCapacity:
      description: The capacity information for a physical machine.
      properties:
        cores:
          description: The number of CPU cores for the physical machine.
          format: int64
          type: integer
        memoryGB:
          description: The memory for the physical machine.
          format: float
          type: number
      type: object
    ScaleUnitList:
      description: A pageable list of scale units.
      properties:
        nextLink:
          description: URI to the next page.
          type: string
        value:
          description: List of scale units.
          items:
            $ref: "#/components/schemas/ScaleUnit"
          type: array
      type: object
    ScaleUnitModel:
      description: Properties of a scale unit.
      properties:
        isMultiNode:
          description: Denotes if more than one node in cluster.
          type: boolean
        logicalFaultDomain:
          description: Fault domain name of the cluster.
          format: int32
          type: integer
        model:
          description: Model of the servers in the cluster.
          type: string
        nodes:
          description: List of nodes in the server.
          items:
            type: string
          type: array
        scaleUnitType:
          description: Type of cluster.
          enum:
            - Unknown
            - ComputeOnly
            - StorageOnly
            - HyperConverged
          type: string
          x-ms-enum:
            modelAsString: true
            name: ScaleUnitType
        state:
          description: Current state of the cluster.
          enum:
            - Unknown
            - Creating
            - Running
            - Upgrading
            - Deleting
          type: string
          x-ms-enum:
            modelAsString: true
            name: ScaleUnitState
        totalCapacity:
          $ref: "#/components/schemas/ScaleUnitCapacity"
      type: object
