openapi: 3.0.0
info:
  title: Azure Database Migration Service Resource Provider
  version: 2018-04-19
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/datamigration/resource-manager/Microsoft.DataMigration/stable/2018-04-19/definitions/Commands.json
      version: "2.0"
  x-preferred: false
  x-providerName: azure.com
  x-serviceName: datamigration-Commands
  x-tags:
    - Azure
    - Microsoft
paths: {}
servers:
  - url: https://azure.local
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    CommandProperties:
      description: Base class for all types of DMS command properties. If command is not
        supported by current client, this object is returned.
      discriminator:
        propertyName: commandType
      properties:
        commandType:
          description: Command type.
          type: string
        errors:
          description: Array of errors. This is ignored if submitted.
          items:
            description: Error information in OData format.
            properties:
              code:
                description: The machine-readable description of the error, such as
                  'InvalidRequest' or 'InternalServerError'
                readOnly: true
                type: string
              details:
                description: Inner errors that caused this error
                items:
                  $ref: "#/components/schemas/ODataError"
                readOnly: true
                type: array
              message:
                description: The human-readable description of the error
                readOnly: true
                type: string
            type: object
          readOnly: true
          type: array
        state:
          description: The state of the command. This is ignored if submitted.
          enum:
            - Unknown
            - Accepted
            - Running
            - Succeeded
            - Failed
          readOnly: true
          type: string
          x-ms-enum:
            modelAsString: true
            name: CommandState
      required:
        - commandType
      type: object
    MigrateMISyncCompleteCommandInput:
      description: Input for command that completes online migration for an Azure SQL
        Database Managed Instance.
      properties:
        sourceDatabaseName:
          description: Name of managed instance database
          type: string
      required:
        - sourceDatabaseName
      type: object
    MigrateMISyncCompleteCommandOutput:
      description: Output for command that completes online migration for an Azure SQL
        Database Managed Instance.
      properties:
        errors:
          description: List of errors that happened during the command execution
          items:
            description: Exception object for all custom exceptions
            properties:
              actionableMessage:
                description: Actionable steps for this exception
                type: string
              filePath:
                description: The path to the file where exception occurred
                readOnly: true
                type: string
              hResult:
                description: Coded numerical value that is assigned to a specific exception
                readOnly: true
                type: integer
              lineNumber:
                description: The line number where exception occurred
                readOnly: true
                type: string
              message:
                description: Error message
                readOnly: true
                type: string
              stackTrace:
                description: Stack trace
                readOnly: true
                type: string
            type: object
          type: array
      type: object
    MigrateMISyncCompleteCommandProperties:
      allOf:
        - $ref: "#/components/schemas/CommandProperties"
      description: Properties for the command that completes online migration for an Azure
        SQL Database Managed Instance.
      properties:
        input:
          $ref: "#/components/schemas/MigrateMISyncCompleteCommandInput"
        output:
          $ref: "#/components/schemas/MigrateMISyncCompleteCommandOutput"
      type: object
      x-ms-discriminator-value: Migrate.SqlServer.AzureDbSqlMi.Complete
    MigrateSyncCompleteCommandInput:
      description: Input for command that completes sync migration for a database.
      properties:
        commitTimeStamp:
          description: Time stamp to complete
          format: date-time
          type: string
        databaseName:
          description: Name of database
          type: string
      required:
        - databaseName
      type: object
    MigrateSyncCompleteCommandOutput:
      description: Output for command that completes sync migration for a database.
      properties:
        errors:
          description: List of errors that happened during the command execution
          items:
            description: Exception object for all custom exceptions
            properties:
              actionableMessage:
                description: Actionable steps for this exception
                type: string
              filePath:
                description: The path to the file where exception occurred
                readOnly: true
                type: string
              hResult:
                description: Coded numerical value that is assigned to a specific exception
                readOnly: true
                type: integer
              lineNumber:
                description: The line number where exception occurred
                readOnly: true
                type: string
              message:
                description: Error message
                readOnly: true
                type: string
              stackTrace:
                description: Stack trace
                readOnly: true
                type: string
            type: object
          readOnly: true
          type: array
        id:
          description: Result identifier
          readOnly: true
          type: string
      type: object
    MigrateSyncCompleteCommandProperties:
      allOf:
        - $ref: "#/components/schemas/CommandProperties"
      description: Properties for the command that completes sync migration for a database.
      properties:
        input:
          $ref: "#/components/schemas/MigrateSyncCompleteCommandInput"
        output:
          $ref: "#/components/schemas/MigrateSyncCompleteCommandOutput"
      type: object
      x-ms-discriminator-value: Migrate.Sync.Complete.Database
    ODataError: {}
