openapi: 3.0.0
info:
  title: LUIS Runtime Client
  version: 3.0-preview
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/cognitiveservices/data-plane/LUIS/Runtime/preview/v3.0/LUIS-Runtime.json
      version: "2.0"
  x-preferred: false
  x-providerName: azure.com
  x-serviceName: cognitiveservices-LUIS-Runtime
  x-tags:
    - Azure
    - Microsoft
security:
  - apiKeyHeader: []
paths:
  "/apps/{appId}/slots/{slotName}/predict":
    get:
      description: Gets the predictions for an application slot.
      operationId: Prediction_GetSlotPredictionGET
      parameters:
        - description: The application ID.
          in: path
          name: appId
          required: true
          schema:
            type: string
            format: uuid
          examples:
            Successful Get Slot Predictions From Endpoint Via Get request:
              value: "{Application Id}"
        - description: The application slot name.
          in: path
          name: slotName
          required: true
          schema:
            type: string
          examples:
            Successful Get Slot Predictions From Endpoint Via Get request:
              value: "{Slot Name}"
        - description: The query to predict.
          in: query
          name: query
          required: true
          schema:
            type: string
          examples:
            Successful Get Slot Predictions From Endpoint Via Get request:
              value: forward to frank 30 dollars through HSBC
        - description: Indicates whether to get extra metadata for the entities predictions
            or not.
          in: query
          name: verbose
          schema:
            type: boolean
        - description: Indicates whether to return all the intents in the response or just
            the top intent.
          in: query
          name: show-all-intents
          schema:
            type: boolean
        - description: Indicates whether to log the endpoint query or not.
          in: query
          name: log
          schema:
            type: boolean
      responses:
        "200":
          description: The prediction for the supplied query.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PredictionResponse"
              examples:
                Successful Get Slot Predictions From Endpoint Via Get request:
                  $ref: "#/components/examples/Successful_Get_Slot_Predictions_From\
                    _Endpoint_Via_Get_request"
        default:
          description: Unexpected error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      description: Gets the predictions for an application slot.
      operationId: Prediction_GetSlotPrediction
      parameters:
        - description: The application ID.
          in: path
          name: appId
          required: true
          schema:
            type: string
            format: uuid
          examples:
            Successful Get Slot Predictions From Endpoint Via Post request:
              value: "{Application Id}"
        - description: The application slot name.
          in: path
          name: slotName
          required: true
          schema:
            type: string
          examples:
            Successful Get Slot Predictions From Endpoint Via Post request:
              value: "{Slot Name}"
        - description: Indicates whether to get extra metadata for the entities predictions
            or not.
          in: query
          name: verbose
          schema:
            type: boolean
        - description: Indicates whether to return all the intents in the response or just
            the top intent.
          in: query
          name: show-all-intents
          schema:
            type: boolean
        - description: Indicates whether to log the endpoint query or not.
          in: query
          name: log
          schema:
            type: boolean
      requestBody:
        $ref: "#/components/requestBodies/PredictionRequest"
      responses:
        "200":
          description: The prediction for the supplied query.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PredictionResponse"
              examples:
                Successful Get Slot Predictions From Endpoint Via Post request:
                  $ref: "#/components/examples/Successful_Get_Slot_Predictions_From\
                    _Endpoint_Via_Post_request"
        default:
          description: Unexpected error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  "/apps/{appId}/versions/{versionId}/predict":
    get:
      description: Gets the predictions for an application version.
      operationId: Prediction_GetVersionPredictionGET
      parameters:
        - description: The application ID.
          in: path
          name: appId
          required: true
          schema:
            type: string
            format: uuid
          examples:
            Successful Get Version Predictions From Endpoint Via Get request:
              value: "{Application Id}"
        - description: The application version ID.
          in: path
          name: versionId
          required: true
          schema:
            type: string
          examples:
            Successful Get Version Predictions From Endpoint Via Get request:
              value: "{Version Id}"
        - description: The query to predict.
          in: query
          name: query
          required: true
          schema:
            type: string
          examples:
            Successful Get Version Predictions From Endpoint Via Get request:
              value: forward to frank 30 dollars through HSBC
        - description: Indicates whether to get extra metadata for the entities predictions
            or not.
          in: query
          name: verbose
          schema:
            type: boolean
        - description: Indicates whether to return all the intents in the response or just
            the top intent.
          in: query
          name: show-all-intents
          schema:
            type: boolean
        - description: Indicates whether to log the endpoint query or not.
          in: query
          name: log
          schema:
            type: boolean
      responses:
        "200":
          description: The prediction for the supplied query.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PredictionResponse"
              examples:
                Successful Get Version Predictions From Endpoint Via Get request:
                  $ref: "#/components/examples/Successful_Get_Version_Predictions_F\
                    rom_Endpoint_Via_Get_request"
        default:
          description: Unexpected error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      description: Gets the predictions for an application version.
      operationId: Prediction_GetVersionPrediction
      parameters:
        - description: The application ID.
          in: path
          name: appId
          required: true
          schema:
            type: string
            format: uuid
          examples:
            Successful Get Version Predictions From Endpoint Via Post request:
              value: "{Application Id}"
        - description: The application version ID.
          in: path
          name: versionId
          required: true
          schema:
            type: string
          examples:
            Successful Get Version Predictions From Endpoint Via Post request:
              value: "{Version Id}"
        - description: Indicates whether to get extra metadata for the entities predictions
            or not.
          in: query
          name: verbose
          schema:
            type: boolean
        - description: Indicates whether to return all the intents in the response or just
            the top intent.
          in: query
          name: show-all-intents
          schema:
            type: boolean
        - description: Indicates whether to log the endpoint query or not.
          in: query
          name: log
          schema:
            type: boolean
      requestBody:
        $ref: "#/components/requestBodies/PredictionRequest"
      responses:
        "200":
          description: The prediction for the supplied query.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PredictionResponse"
              examples:
                Successful Get Version Predictions From Endpoint Via Post request:
                  $ref: "#/components/examples/Successful_Get_Version_Predictions_F\
                    rom_Endpoint_Via_Post_request"
        default:
          description: Unexpected error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
servers:
  - url: https://azure.local
  - url: "{Endpoint}/luis/v3.0-preview"
    variables:
      Endpoint:
        description: "Supported Cognitive Services endpoints (protocol and hostname, for
          example: https://westus.api.cognitive.microsoft.com)."
        x-ms-parameter-location: client
        x-ms-skip-url-encoding: true
        default: ""
components:
  examples:
    Successful_Get_Slot_Predictions_From_Endpoint_Via_Get_request:
      value:
        prediction:
          entities:
            Bank:
              - HSBC
            frank:
              - frank
            money:
              - unit: Dollar
                value: 30
            number:
              - 30
          intents:
            give:
              score: 0.943442
          normalizedQuery: forward to frank 30 dollars through hsbc
          sentiment:
            label: positive
            score: 0.9163064
          topIntent: give
        query: forward to frank 30 dollars through HSBC
    Successful_Get_Slot_Predictions_From_Endpoint_Via_Post_request:
      value:
        prediction:
          entities:
            Bank:
              - text: International Bank
            Employees:
              - - frank
            money:
              - unit: Dollar
                value: 30
            number:
              - 30
          intents:
            give:
              score: 0.943442
          normalizedQuery: forward to frank 30 dollars through hsbc
          sentiment:
            label: positive
            score: 0.9163064
          topIntent: give
        query: forward to frank 30 dollars through HSBC
    Successful_Get_Version_Predictions_From_Endpoint_Via_Get_request:
      value:
        prediction:
          entities:
            Bank:
              - text: International Bank
            Employees:
              - - frank
            money:
              - unit: Dollar
                value: 30
            number:
              - 30
          intents:
            give:
              score: 0.943442
          normalizedQuery: forward to frank 30 dollars through hsbc
          sentiment:
            label: positive
            score: 0.9163064
          topIntent: give
        query: forward to frank 30 dollars through HSBC
    Successful_Get_Version_Predictions_From_Endpoint_Via_Post_request:
      value:
        prediction:
          entities:
            Bank:
              - text: International Bank
            Employees:
              - - frank
            money:
              - unit: Dollar
                value: 30
            number:
              - 30
          intents:
            give:
              score: 0.943442
          normalizedQuery: forward to frank 30 dollars through hsbc
          sentiment:
            label: positive
            score: 0.9163064
          topIntent: give
        query: forward to frank 30 dollars through HSBC
  parameters:
    Endpoint:
      description: "Supported Cognitive Services endpoints (protocol and hostname, for
        example: https://westus.api.cognitive.microsoft.com)."
      in: path
      name: Endpoint
      required: true
      x-ms-parameter-location: client
      x-ms-skip-url-encoding: true
      schema:
        type: string
  requestBodies:
    PredictionRequest:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PredictionRequest"
      description: The prediction request parameters.
      required: true
  securitySchemes:
    apiKeyHeader:
      in: header
      name: Ocp-Apim-Subscription-Key
      type: apiKey
  schemas:
    DynamicList:
      description: Defines an extension for a list entity.
      properties:
        listEntityName:
          description: The name of the list entity to extend.
          type: string
        requestLists:
          description: The lists to append on the extended list entity.
          items:
            $ref: "#/components/schemas/RequestList"
          type: array
      required:
        - listEntityName
        - requestLists
      type: object
    Error:
      description: Represents the error that occurred.
      properties:
        error:
          $ref: "#/components/schemas/ErrorBody"
      required:
        - error
      type: object
    ErrorBody:
      description: Represents the definition of the error that occurred.
      properties:
        code:
          description: The error code.
          type: string
        message:
          description: The error message.
          type: string
      required:
        - code
        - message
      type: object
    ExternalEntity:
      description: Defines a user predicted entity that extends an already existing one.
      properties:
        entityLength:
          description: The length of the predicted entity.
          format: int32
          type: integer
        entityName:
          description: The name of the entity to extend.
          type: string
        resolution:
          description: A user supplied custom resolution to return as the entity's
            prediction.
        startIndex:
          description: The start character index of the predicted entity.
          format: int32
          type: integer
      required:
        - entityName
        - startIndex
        - entityLength
      type: object
    Intent:
      description: Represents an intent prediction.
      properties:
        childApp:
          $ref: "#/components/schemas/Prediction"
        score:
          description: The score of the fired intent.
          format: float
          type: number
      type: object
    Prediction:
      description: Represents the prediction of a query.
      properties:
        alteredQuery:
          description: The query after spell checking. Only set if spell check was enabled
            and a spelling mistake was found.
          type: string
        entities:
          additionalProperties: {}
          description: The dictionary representing the entities that fired.
          type: object
        intents:
          additionalProperties:
            $ref: "#/components/schemas/Intent"
          description: A dictionary representing the intents that fired.
          type: object
        normalizedQuery:
          description: The query after pre-processing and normalization.
          type: string
        sentiment:
          $ref: "#/components/schemas/Sentiment"
        topIntent:
          description: The name of the top scoring intent.
          type: string
      required:
        - normalizedQuery
        - topIntent
        - intents
        - entities
      type: object
    PredictionRequest:
      description: Represents the prediction request parameters.
      properties:
        dynamicLists:
          description: The dynamically created list entities for this request.
          items:
            $ref: "#/components/schemas/DynamicList"
          type: array
        externalEntities:
          description: The externally predicted entities for this request.
          items:
            $ref: "#/components/schemas/ExternalEntity"
          type: array
        options:
          $ref: "#/components/schemas/PredictionRequestOptions"
        query:
          description: The query to predict.
          type: string
      required:
        - query
      type: object
    PredictionRequestOptions:
      description: The custom options for the prediction request.
      properties:
        datetimeReference:
          description: The reference DateTime used for predicting datetime entities.
          format: date-time
          type: string
        overridePredictions:
          description: Whether to make the external entities resolution override the
            predictions if an overlap occurs.
          type: boolean
      type: object
    PredictionResponse:
      description: Represents the prediction response.
      properties:
        prediction:
          $ref: "#/components/schemas/Prediction"
        query:
          description: The query used in the prediction.
          type: string
      required:
        - query
        - prediction
      type: object
    RequestList:
      description: Defines a sub-list to append to an existing list entity.
      properties:
        canonicalForm:
          description: The canonical form of the sub-list.
          type: string
        name:
          description: The name of the sub-list.
          type: string
        synonyms:
          description: The synonyms of the canonical form.
          items:
            type: string
          type: array
      required:
        - canonicalForm
      type: object
    Sentiment:
      description: The result of the sentiment analysis.
      properties:
        label:
          description: The label of the sentiment analysis result.
          type: string
        score:
          description: The sentiment score of the query.
          format: float
          type: number
      required:
        - score
      type: object
