openapi: 3.0.0
info:
  title: AutomationManagement
  version: 2015-10-31
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/automation/resource-manager/Microsoft.Automation/stable/2015-10-31/hybridRunbookWorkerGroup.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: automation-hybridRunbookWorkerGroup
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}/hybridRunbookWorkerGroups":
    get:
      description: Retrieve a list of hybrid runbook worker groups.
      externalDocs:
        url: http://aka.ms/azureautomationsdk/hybridrunbookworkergroupoperations
      operationId: HybridRunbookWorkerGroup_ListByAutomationAccount
      parameters:
        - description: Name of an Azure Resource group.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._]+$
          examples:
            List hybrid worker groups by Automation Account:
              value: udtest
        - description: The name of the automation account.
          in: path
          name: automationAccountName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            List hybrid worker groups by Automation Account:
              value: testaccount
        - description: The filter to apply on the operation.
          in: query
          name: $filter
          required: false
          schema:
            type: string
        - description: Gets subscription credentials which uniquely identify Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            List hybrid worker groups by Automation Account:
              value: subid
        - description: Client Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            List hybrid worker groups by Automation Account:
              value: 2015-10-31
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HybridRunbookWorkerGroupsListResult"
              examples:
                List hybrid worker groups by Automation Account:
                  $ref: "#/components/examples/List_hybrid_worker_groups_by_Automat\
                    ion_Account"
        default:
          description: Automation error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response of an operation failure
                properties:
                  code:
                    description: Error code
                    type: string
                  message:
                    description: Error message indicating why the operation failed.
                    type: string
                type: object
      tags:
        - HybridRunbookWorkerGroup
      x-ms-odata: "#/components/schemas/HybridRunbookWorkerGroup"
      x-ms-pageable:
        nextLinkName: nextLink
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}/hybridRunbookWorkerGroups/{hybridRunbookWorkerGroupName}":
    delete:
      description: Delete a hybrid runbook worker group.
      externalDocs:
        url: http://aka.ms/azureautomationsdk/hybridrunbookworkergroupoperations
      operationId: HybridRunbookWorkerGroup_Delete
      parameters:
        - description: Name of an Azure Resource group.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._]+$
          examples:
            Delete a hybrid worker group:
              value: rg
        - description: The name of the automation account.
          in: path
          name: automationAccountName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Delete a hybrid worker group:
              value: myAutomationAccount20
        - description: The hybrid runbook worker group name
          in: path
          name: hybridRunbookWorkerGroupName
          required: true
          schema:
            type: string
          examples:
            Delete a hybrid worker group:
              value: myGroup
        - description: Gets subscription credentials which uniquely identify Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Delete a hybrid worker group:
              value: subid
        - description: Client Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Delete a hybrid worker group:
              value: 2015-10-31
      responses:
        "200":
          description: OK
        default:
          description: Automation error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response of an operation failure
                properties:
                  code:
                    description: Error code
                    type: string
                  message:
                    description: Error message indicating why the operation failed.
                    type: string
                type: object
      tags:
        - HybridRunbookWorkerGroup
    get:
      description: Retrieve a hybrid runbook worker group.
      externalDocs:
        url: http://aka.ms/azureautomationsdk/hybridrunbookworkergroupoperations
      operationId: HybridRunbookWorkerGroup_Get
      parameters:
        - description: Name of an Azure Resource group.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._]+$
          examples:
            Get a hybrid worker group:
              value: rg
        - description: The name of the automation account.
          in: path
          name: automationAccountName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Get a hybrid worker group:
              value: testaccount
        - description: The hybrid runbook worker group name
          in: path
          name: hybridRunbookWorkerGroupName
          required: true
          schema:
            type: string
          examples:
            Get a hybrid worker group:
              value: TestHybridGroup
        - description: Gets subscription credentials which uniquely identify Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Get a hybrid worker group:
              value: subid
        - description: Client Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Get a hybrid worker group:
              value: 2015-10-31
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HybridRunbookWorkerGroup"
              examples:
                Get a hybrid worker group:
                  $ref: "#/components/examples/Get_a_hybrid_worker_group"
        default:
          description: Automation error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response of an operation failure
                properties:
                  code:
                    description: Error code
                    type: string
                  message:
                    description: Error message indicating why the operation failed.
                    type: string
                type: object
      tags:
        - HybridRunbookWorkerGroup
    patch:
      description: Update a hybrid runbook worker group.
      externalDocs:
        url: http://aka.ms/azureautomationsdk/hybridrunbookworkergroupoperations
      operationId: HybridRunbookWorkerGroup_Update
      parameters:
        - description: Name of an Azure Resource group.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._]+$
          examples:
            Update hybrid worker group:
              value: rg
        - description: The name of the automation account.
          in: path
          name: automationAccountName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Update hybrid worker group:
              value: testaccount
        - description: The hybrid runbook worker group name
          in: path
          name: hybridRunbookWorkerGroupName
          required: true
          schema:
            type: string
          examples:
            Update hybrid worker group:
              value: TestHybridGroup
        - description: Gets subscription credentials which uniquely identify Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Update hybrid worker group:
              value: subid
        - description: Client Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Update hybrid worker group:
              value: 2015-10-31
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/HybridRunbookWorkerGroupUpdateParameters"
        description: The hybrid runbook worker group
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HybridRunbookWorkerGroup"
              examples:
                Update hybrid worker group:
                  $ref: "#/components/examples/Update_hybrid_worker_group"
        default:
          description: Automation error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response of an operation failure
                properties:
                  code:
                    description: Error code
                    type: string
                  message:
                    description: Error message indicating why the operation failed.
                    type: string
                type: object
      tags:
        - HybridRunbookWorkerGroup
servers:
  - url: https://management.azure.com
components:
  examples:
    List_hybrid_worker_groups_by_Automation_Account:
      value:
        value:
          - credential:
              name: myRunAsCredentialName
            hybridRunbookWorkers:
              - ip: 134.1.1.1
                name: TestMachine
                registrationTime: 2017-03-24T12:43:43.053855-07:00
            id: /subscriptions/subid/resourceGroups/udtest/providers/Microsoft.Automation/automationAccounts/testaccount/hybridRunbookWorkerGroups/TestWorkerGroup
            name: TestWorkerGroup
    Get_a_hybrid_worker_group:
      value:
        credential:
          name: myRunAsCredentialName
        hybridRunbookWorkers:
          - ip: 100.1.1.1
            name: TestHybridWorker
            registrationTime: 2017-03-24T12:43:45.0146578-07:00
        id: /subscriptions/subid/resourceGroups/rg/providers/Microsoft.Automation/automationAccounts/testaccount/hybridRunbookWorkerGroups/TestHybridGroup
        name: TestHybridGroup
    Update_hybrid_worker_group:
      value:
        credential:
          name: myRunAsCredentialName
        hybridRunbookWorkers:
          - ip: 100.1.1.1
            name: TestHybridWorker
            registrationTime: 2017-03-24T12:43:45.0146578-07:00
        id: /subscriptions/subid/resourceGroups/rg/providers/Microsoft.Automation/automationAccounts/testaccount/hybridRunbookWorkerGroups/TestHybridGroup
        name: TestHybridGroup
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    HybridRunbookWorker:
      description: Definition of hybrid runbook worker.
      properties:
        ip:
          description: Gets or sets the assigned machine IP address.
          type: string
        lastSeenDateTime:
          description: Last Heartbeat from the Worker
          format: date-time
          type: string
          nullable: false
        name:
          description: Gets or sets the worker machine name.
          type: string
        registrationTime:
          description: Gets or sets the registration time of the worker machine.
          format: date-time
          type: string
          nullable: false
    HybridRunbookWorkerGroup:
      description: Definition of hybrid runbook worker group.
      properties:
        credential:
          $ref: "#/components/schemas/RunAsCredentialAssociationProperty"
        groupType:
          description: Type of the HybridWorkerGroup.
          enum:
            - User
            - System
          type: string
          x-ms-enum:
            modelAsString: true
            name: GroupTypeEnum
        hybridRunbookWorkers:
          description: Gets or sets the list of hybrid runbook workers.
          items:
            $ref: "#/components/schemas/HybridRunbookWorker"
          type: array
        id:
          description: Gets or sets the id of the resource.
          type: string
        name:
          description: Gets or sets the name of the group.
          type: string
    HybridRunbookWorkerGroupUpdateParameters:
      description: Parameters supplied to the update operation.
      properties:
        credential:
          $ref: "#/components/schemas/RunAsCredentialAssociationProperty"
    HybridRunbookWorkerGroupsListResult:
      description: The response model for the list hybrid runbook worker groups.
      properties:
        nextLink:
          description: Gets or sets the next link.
          type: string
        value:
          description: Gets or sets a list of hybrid runbook worker groups.
          items:
            $ref: "#/components/schemas/HybridRunbookWorkerGroup"
          type: array
    RunAsCredentialAssociationProperty:
      description: Definition of RunAs credential to use for hybrid worker.
      properties:
        name:
          description: Gets or sets the name of the credential.
          type: string
