openapi: 3.0.0
info:
  title: DataFactoryManagementClient
  version: 2017-09-01-preview
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/datafactory/resource-manager/Microsoft.DataFactory/preview/2017-09-01-preview/entityTypes/Trigger.json
      version: "2.0"
  x-preferred: false
  x-providerName: azure.com
  x-serviceName: datafactory-Trigger
  x-tags:
    - Azure
    - Microsoft
paths: {}
servers:
  - url: https://azure.local
components:
  schemas:
    BlobEventTypes:
      description: Blob event types.
      items:
        enum:
          - Microsoft.Storage.BlobCreated
          - Microsoft.Storage.BlobDeleted
        type: string
        x-ms-enum:
          modelAsString: true
          name: BlobEventTypes
      type: array
    BlobEventsTrigger:
      allOf:
        - $ref: "#/components/schemas/MultiplePipelineTrigger"
      description: Trigger that runs every time a Blob event occurs.
      properties:
        typeProperties:
          description: Blob Events Trigger properties.
          properties:
            blobPathBeginsWith:
              description: "The blob path must begin with the pattern provided for trigger
                to fire. For example, '/records/blobs/december/' will only fire
                the trigger for blobs in the december folder under the records
                container. At least one of these must be provided:
                blobPathBeginsWith, blobPathEndsWith."
              type: string
            blobPathEndsWith:
              description: "The blob path must end with the pattern provided for trigger to
                fire. For example, 'december/boxes.csv' will only fire the
                trigger for blobs named boxes in a december folder. At least one
                of these must be provided: blobPathBeginsWith,
                blobPathEndsWith."
              type: string
            events:
              $ref: "#/components/schemas/BlobEventTypes"
            ignoreEmptyBlobs:
              description: If set to true, blobs with zero bytes will be ignored.
              type: boolean
            scope:
              description: The ARM resource ID of the Storage Account.
              type: string
          required:
            - events
            - scope
          x-ms-client-flatten: true
      required:
        - typeProperties
      type: object
    BlobTrigger:
      allOf:
        - $ref: "#/components/schemas/MultiplePipelineTrigger"
      description: Trigger that runs every time the selected Blob container changes.
      properties:
        typeProperties:
          description: Blob Trigger properties.
          properties:
            folderPath:
              description: The path of the container/folder that will trigger the pipeline.
              type: string
            linkedService:
              description: Linked service reference type.
              properties:
                parameters:
                  additionalProperties:
                    type: object
                  description: An object mapping parameter names to argument values.
                  type: object
                referenceName:
                  description: Reference LinkedService name.
                  type: string
                type:
                  description: Linked service reference type.
                  enum:
                    - LinkedServiceReference
                  type: string
              required:
                - type
                - referenceName
            maxConcurrency:
              description: The max number of parallel files to handle when it is triggered.
              type: integer
          required:
            - folderPath
            - maxConcurrency
            - linkedService
          x-ms-client-flatten: true
      required:
        - typeProperties
      type: object
    DayOfWeek:
      description: The days of the week.
      enum:
        - Sunday
        - Monday
        - Tuesday
        - Wednesday
        - Thursday
        - Friday
        - Saturday
      type: string
      x-ms-enum:
        modelAsString: false
        name: DayOfWeek
    MultiplePipelineTrigger:
      allOf:
        - $ref: "#/components/schemas/Trigger"
      description: Base class for all triggers that support one to many model for trigger
        to pipeline.
      properties:
        pipelines:
          description: Pipelines that need to be started.
          items:
            description: Pipeline that needs to be triggered with the given parameters.
            properties:
              parameters:
                additionalProperties:
                  type: object
                description: An object mapping parameter names to argument values.
                type: object
              pipelineReference:
                description: Pipeline reference type.
                properties:
                  name:
                    description: Reference name.
                    type: string
                  referenceName:
                    description: Reference pipeline name.
                    type: string
                  type:
                    description: Pipeline reference type.
                    enum:
                      - PipelineReference
                    type: string
                required:
                  - type
                  - referenceName
          type: array
      x-ms-discriminator-value: MultiplePipelineTrigger
    RecurrenceFrequency:
      description: Enumerates possible frequency option for the schedule trigger.
      enum:
        - NotSpecified
        - Minute
        - Hour
        - Day
        - Week
        - Month
        - Year
      type: string
      x-ms-enum:
        modelAsString: true
        name: RecurrenceFrequency
    RecurrenceSchedule:
      additionalProperties:
        type: object
      description: The recurrence schedule.
      properties:
        hours:
          description: The hours.
          items:
            format: int32
            type: integer
          type: array
        minutes:
          description: The minutes.
          items:
            format: int32
            type: integer
          type: array
        monthDays:
          description: The month days.
          items:
            format: int32
            type: integer
          type: array
        monthlyOccurrences:
          description: The monthly occurrences.
          items:
            $ref: "#/components/schemas/RecurrenceScheduleOccurrence"
          type: array
        weekDays:
          description: The days of the week.
          items:
            enum:
              - Sunday
              - Monday
              - Tuesday
              - Wednesday
              - Thursday
              - Friday
              - Saturday
            type: string
            x-ms-enum:
              modelAsString: false
              name: DaysOfWeek
          type: array
      type: object
    RecurrenceScheduleOccurrence:
      additionalProperties:
        type: object
      description: The recurrence schedule occurrence.
      properties:
        day:
          $ref: "#/components/schemas/DayOfWeek"
        occurrence:
          description: The occurrence.
          format: int32
          type: integer
      type: object
    RetryPolicy:
      description: Execution policy for an activity.
      properties:
        count:
          description: "Maximum ordinary retry attempts. Default is 0. Type: integer (or
            Expression with resultType integer), minimum: 0."
          type: object
        intervalInSeconds:
          description: Interval between retries in seconds. Default is 30.
          maximum: 86400
          minimum: 30
          type: integer
    ScheduleTrigger:
      allOf:
        - $ref: "#/components/schemas/MultiplePipelineTrigger"
      description: Trigger that creates pipeline runs periodically, on schedule.
      properties:
        typeProperties:
          description: Schedule Trigger properties.
          properties:
            recurrence:
              $ref: "#/components/schemas/ScheduleTriggerRecurrence"
          required:
            - recurrence
          x-ms-client-flatten: true
      required:
        - typeProperties
      type: object
    ScheduleTriggerRecurrence:
      additionalProperties:
        type: object
      description: The workflow trigger recurrence.
      properties:
        endTime:
          description: The end time.
          format: date-time
          type: string
        frequency:
          $ref: "#/components/schemas/RecurrenceFrequency"
        interval:
          description: The interval.
          format: int32
          type: integer
        schedule:
          $ref: "#/components/schemas/RecurrenceSchedule"
        startTime:
          description: The start time.
          format: date-time
          type: string
        timeZone:
          description: The time zone.
          type: string
      type: object
    Trigger:
      additionalProperties:
        type: object
      description: Azure data factory nested object which contains information about
        creating pipeline run
      discriminator:
        propertyName: type
      properties:
        description:
          description: Trigger description.
          type: string
        runtimeState:
          $ref: "#/components/schemas/TriggerRuntimeState"
        type:
          description: Trigger type.
          type: string
      required:
        - type
      type: object
    TriggerRuntimeState:
      description: Enumerates possible state of Triggers.
      enum:
        - Started
        - Stopped
        - Disabled
      type: string
      x-ms-enum:
        modelAsString: true
        name: TriggerRuntimeState
    TumblingWindowFrequency:
      description: Enumerates possible frequency option for the tumbling window trigger.
      enum:
        - Minute
        - Hour
      type: string
      x-ms-enum:
        modelAsString: true
        name: TumblingWindowFrequency
    TumblingWindowTrigger:
      allOf:
        - $ref: "#/components/schemas/Trigger"
      description: Trigger that schedules pipeline runs for all fixed time interval windows
        from a start time without gaps and also supports backfill scenarios
        (when start time is in the past).
      properties:
        pipeline:
          description: Pipeline that needs to be triggered with the given parameters.
          properties:
            parameters:
              additionalProperties:
                type: object
              description: An object mapping parameter names to argument values.
              type: object
            pipelineReference:
              description: Pipeline reference type.
              properties:
                name:
                  description: Reference name.
                  type: string
                referenceName:
                  description: Reference pipeline name.
                  type: string
                type:
                  description: Pipeline reference type.
                  enum:
                    - PipelineReference
                  type: string
              required:
                - type
                - referenceName
        typeProperties:
          description: Tumbling Window Trigger properties.
          properties:
            delay:
              description: "Specifies how long the trigger waits past due time before
                triggering new run. It doesn't alter window start and end time.
                The default is 0. Type: string (or Expression with resultType
                string), pattern:
                ((\\d+)\\.)?(\\d\\d):(60|([0-5][0-9])):(60|([0-5][0-9]))."
              type: object
            endTime:
              description: The end time for the time period for the trigger during which
                events are fired for windows that are ready. Only UTC time is
                currently supported.
              format: date-time
              type: string
            frequency:
              $ref: "#/components/schemas/TumblingWindowFrequency"
            interval:
              description: The interval of the time windows. The minimum interval allowed
                is 15 Minutes.
              format: int32
              type: integer
            maxConcurrency:
              description: The max number of parallel time windows (ready for execution)
                for which a new run is triggered.
              maximum: 50
              minimum: 1
              type: integer
            retryPolicy:
              $ref: "#/components/schemas/RetryPolicy"
            startTime:
              description: The start time for the time period for the trigger during which
                events are fired for windows that are ready. Only UTC time is
                currently supported.
              format: date-time
              type: string
          required:
            - frequency
            - interval
            - startTime
            - maxConcurrency
          x-ms-client-flatten: true
      required:
        - pipeline
        - typeProperties
      type: object
