openapi: 3.0.0
info:
  description: Use these REST APIs for performing operations on Quota entity associated
    with your Azure API Management deployment. To configure call rate limit and
    quota policies refer to [how to configure call rate limit and
    quota](https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-product-with-rules#a-namepolicies-ato-configure-call-rate-limit-and-quota-policies).
  title: ApiManagementClient
  version: 2016-10-10
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2016-10-10/apimquotas.json
      version: "2.0"
  x-preferred: false
  x-providerName: azure.com
  x-serviceName: apimanagement-apimquotas
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ApiManagement/service/{serviceName}/quotas/{quotaCounterKey}":
    get:
      description: Lists a collection of current quota counter periods associated with the
        counter-key configured in the policy on the specified service instance.
        The api does not support paging yet.
      externalDocs:
        description: Document describing how to configure the quota policies.
        url: https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-product-with-rules#a-namepolicies-ato-configure-call-rate-limit-and-quota-policies
      operationId: QuotaByCounterKeys_ListByService
      parameters:
        - description: Subscription credentials which uniquely identify Microsoft Azure
            subscription. The subscription ID forms part of the URI for every
            service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
        - description: The name of the API Management service.
          in: path
          name: serviceName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 50
            pattern: ^[a-zA-Z](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?$
        - $ref: "#/components/parameters/QuotaCounterKeyParameter"
        - description: Version of the API to be used with the client request.
          in: query
          name: api-version
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Lists a collection of the quota counter values.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QuotaCounterCollection"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error Body contract.
                properties:
                  code:
                    description: Service-defined error code. This code serves as a
                      sub-status for the HTTP error code specified in the
                      response.
                    type: string
                  details:
                    description: The list of invalid fields send in request, in case of
                      validation error.
                    items:
                      description: Error Field contract.
                      properties:
                        code:
                          description: Property level error code.
                          type: string
                        message:
                          description: Human-readable representation of property-level
                            error.
                          type: string
                        target:
                          description: Property name.
                          type: string
                    type: array
                  message:
                    description: Human-readable representation of the error.
                    type: string
      tags:
        - QuotaByCounterKeys
    patch:
      description: Updates all the quota counter values specified with the existing quota
        counter key to a value in the specified service instance. This should be
        used for reset of the quota counter values.
      operationId: QuotaByCounterKeys_Update
      parameters:
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
        - description: The name of the API Management service.
          in: path
          name: serviceName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 50
            pattern: ^[a-zA-Z](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?$
        - $ref: "#/components/parameters/QuotaCounterKeyParameter"
        - description: Version of the API to be used with the client request.
          in: query
          name: api-version
          required: true
          schema:
            type: string
        - description: Subscription credentials which uniquely identify Microsoft Azure
            subscription. The subscription ID forms part of the URI for every
            service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/QuotaCounterValueContract"
        description: The value of the quota counter to be applied to all quota counter
          periods.
        required: true
      responses:
        "204":
          description: All the quota counter periods were successfully updated.
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error Body contract.
                properties:
                  code:
                    description: Service-defined error code. This code serves as a
                      sub-status for the HTTP error code specified in the
                      response.
                    type: string
                  details:
                    description: The list of invalid fields send in request, in case of
                      validation error.
                    items:
                      description: Error Field contract.
                      properties:
                        code:
                          description: Property level error code.
                          type: string
                        message:
                          description: Human-readable representation of property-level
                            error.
                          type: string
                        target:
                          description: Property name.
                          type: string
                    type: array
                  message:
                    description: Human-readable representation of the error.
                    type: string
      tags:
        - QuotaByCounterKeys
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ApiManagement/service/{serviceName}/quotas/{quotaCounterKey}/{quotaPeriodKey}":
    get:
      description: Gets the value of the quota counter associated with the counter-key in
        the policy for the specific period in service instance.
      externalDocs:
        description: Document describing how to configure the quota policies.
        url: https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-product-with-rules#a-namepolicies-ato-configure-call-rate-limit-and-quota-policies
      operationId: QuotaByPeriodKeys_Get
      parameters:
        - description: Subscription credentials which uniquely identify Microsoft Azure
            subscription. The subscription ID forms part of the URI for every
            service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
        - description: The name of the API Management service.
          in: path
          name: serviceName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 50
            pattern: ^[a-zA-Z](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?$
        - $ref: "#/components/parameters/QuotaCounterKeyParameter"
        - $ref: "#/components/parameters/QuotaPeriodKeyParameter"
        - description: Version of the API to be used with the client request.
          in: query
          name: api-version
          required: true
          schema:
            type: string
      responses:
        "200":
          description: The response body contains the Quota counter details for the
            specified period.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QuotaCounterContract"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error Body contract.
                properties:
                  code:
                    description: Service-defined error code. This code serves as a
                      sub-status for the HTTP error code specified in the
                      response.
                    type: string
                  details:
                    description: The list of invalid fields send in request, in case of
                      validation error.
                    items:
                      description: Error Field contract.
                      properties:
                        code:
                          description: Property level error code.
                          type: string
                        message:
                          description: Human-readable representation of property-level
                            error.
                          type: string
                        target:
                          description: Property name.
                          type: string
                    type: array
                  message:
                    description: Human-readable representation of the error.
                    type: string
      tags:
        - QuotaByPeriodKeys
    patch:
      description: Updates an existing quota counter value in the specified service
        instance.
      operationId: QuotaByPeriodKeys_Update
      parameters:
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
        - description: The name of the API Management service.
          in: path
          name: serviceName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 50
            pattern: ^[a-zA-Z](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?$
        - $ref: "#/components/parameters/QuotaCounterKeyParameter"
        - $ref: "#/components/parameters/QuotaPeriodKeyParameter"
        - description: Version of the API to be used with the client request.
          in: query
          name: api-version
          required: true
          schema:
            type: string
        - description: Subscription credentials which uniquely identify Microsoft Azure
            subscription. The subscription ID forms part of the URI for every
            service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/QuotaCounterValueContract"
        description: The value of the Quota counter to be applied on the specified period.
        required: true
      responses:
        "204":
          description: The quota counter value was successfully updated.
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error Body contract.
                properties:
                  code:
                    description: Service-defined error code. This code serves as a
                      sub-status for the HTTP error code specified in the
                      response.
                    type: string
                  details:
                    description: The list of invalid fields send in request, in case of
                      validation error.
                    items:
                      description: Error Field contract.
                      properties:
                        code:
                          description: Property level error code.
                          type: string
                        message:
                          description: Human-readable representation of property-level
                            error.
                          type: string
                        target:
                          description: Property name.
                          type: string
                    type: array
                  message:
                    description: Human-readable representation of the error.
                    type: string
      tags:
        - QuotaByPeriodKeys
servers:
  - url: https://management.azure.com
components:
  parameters:
    QuotaCounterKeyParameter:
      description: Quota counter key identifier.
      in: path
      name: quotaCounterKey
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
    QuotaPeriodKeyParameter:
      description: Quota period key identifier.
      in: path
      name: quotaPeriodKey
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    QuotaCounterCollection:
      description: Paged Quota Counter list representation.
      properties:
        count:
          description: Total record count number across all pages.
          format: int64
          type: integer
        nextLink:
          description: Next page link if any.
          type: string
        value:
          description: Quota counter values.
          items:
            $ref: "#/components/schemas/QuotaCounterContract"
          type: array
    QuotaCounterContract:
      allOf:
        - $ref: "#/components/schemas/QuotaCounterValueContract"
      description: Quota counter details.
      properties:
        counterKey:
          description: The Key value of the Counter. Must not be empty.
          minLength: 1
          type: string
        periodEndTime:
          description: >
            The date of the end of Counter Period. The date conforms to the
            following format: `yyyy-MM-ddTHH:mm:ssZ` as specified by the ISO
            8601 standard.
          format: date-time
          type: string
        periodKey:
          description: Identifier of the Period for which the counter was collected. Must
            not be empty.
          minLength: 1
          type: string
        periodStartTime:
          description: >
            The date of the start of Counter Period. The date conforms to the
            following format: `yyyy-MM-ddTHH:mm:ssZ` as specified by the ISO
            8601 standard.
          format: date-time
          type: string
      required:
        - counterKey
        - periodKey
        - periodStartTime
        - periodEndTime
    QuotaCounterValueContract:
      description: Quota counter value details.
      properties:
        callsCount:
          description: Number of times Counter was called.
          format: int32
          type: integer
        kbTransferred:
          description: Data Transferred in KiloBytes.
          format: double
          type: number
