openapi: 3.0.0
info:
  description: Provides read and update functionality for Azure SQL Server backup long term
    retention vault
  title: Azure SQL Server Backup Long Term Retention Vault
  version: 2014-04-01
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/sql/resource-manager/Microsoft.Sql/stable/2014-04-01/backupLongTermRetentionVaults.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: sql-backupLongTermRetentionVaults
  x-tags:
    - Azure
    - Microsoft
paths:
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}/backupLongTermRetentionVaults":
    get:
      description: Gets server backup long term retention vaults in a server
      operationId: BackupLongTermRetentionVaults_ListByServer
      parameters:
        - description: The API version to use for the request.
          in: query
          name: api-version
          required: true
          x-ms-parameter-location: client
          schema:
            type: string
          examples:
            Get backup long term retention vault:
              value: 2014-04-01
        - description: The subscription ID that identifies an Azure subscription.
          in: path
          name: subscriptionId
          required: true
          x-ms-parameter-location: client
          schema:
            type: string
          examples:
            Get backup long term retention vault:
              value: 00000000-1111-2222-3333-444444444444
        - description: The name of the resource group that contains the resource. You can
            obtain this value from the Azure Resource Manager API or the portal.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Get backup long term retention vault:
              value: longtermretentiontest-1234
        - $ref: "#/components/parameters/ServerNameParameter"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BackupLongTermRetentionVaultListResult"
              examples:
                Get backup long term retention vault:
                  $ref: "#/components/examples/Get_backup_long_term_retention_vault"
      tags:
        - BackupLongTermRetentionVaults
      x-ms-pageable: {}
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}/backupLongTermRetentionVaults/{backupLongTermRetentionVaultName}":
    get:
      description: Gets a server backup long term retention vault
      operationId: BackupLongTermRetentionVaults_Get
      parameters:
        - description: The API version to use for the request.
          in: query
          name: api-version
          required: true
          x-ms-parameter-location: client
          schema:
            type: string
          examples:
            Get backup long term retention vault:
              value: 2014-04-01
        - description: The subscription ID that identifies an Azure subscription.
          in: path
          name: subscriptionId
          required: true
          x-ms-parameter-location: client
          schema:
            type: string
          examples:
            Get backup long term retention vault:
              value: 00000000-1111-2222-3333-444444444444
        - description: The name of the resource group that contains the resource. You can
            obtain this value from the Azure Resource Manager API or the portal.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Get backup long term retention vault:
              value: longtermretentiontest-1234
        - $ref: "#/components/parameters/ServerNameParameter"
        - description: The name of the Azure SQL Server backup LongTermRetention vault
          in: path
          name: backupLongTermRetentionVaultName
          required: true
          x-ms-enum:
            modelAsString: true
            name: BackupLongTermRetentionVaultName
          schema:
            type: string
            enum:
              - RegisteredVault
          examples:
            Get backup long term retention vault:
              value: RegisteredVault
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BackupLongTermRetentionVault"
              examples:
                Get backup long term retention vault:
                  $ref: "#/components/examples/Get_backup_long_term_retention_vault"
      tags:
        - BackupLongTermRetentionVaults
    put:
      description: Updates a server backup long term retention vault
      operationId: BackupLongTermRetentionVaults_CreateOrUpdate
      parameters:
        - description: The API version to use for the request.
          in: query
          name: api-version
          required: true
          x-ms-parameter-location: client
          schema:
            type: string
          examples:
            Update backup long term retention vault:
              value: 2014-04-01
        - description: The subscription ID that identifies an Azure subscription.
          in: path
          name: subscriptionId
          required: true
          x-ms-parameter-location: client
          schema:
            type: string
          examples:
            Update backup long term retention vault:
              value: 00000000-1111-2222-3333-444444444444
        - description: The name of the resource group that contains the resource. You can
            obtain this value from the Azure Resource Manager API or the portal.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Update backup long term retention vault:
              value: longtermretentiontest-1234
        - $ref: "#/components/parameters/ServerNameParameter"
        - description: The name of the backup long term retention vault
          in: path
          name: backupLongTermRetentionVaultName
          required: true
          x-ms-enum:
            modelAsString: true
            name: BackupLongTermRetentionVaultName
          schema:
            type: string
            enum:
              - RegisteredVault
          examples:
            Update backup long term retention vault:
              value: RegisteredVault
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BackupLongTermRetentionVault"
        description: The required parameters to update a backup long term retention vault
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BackupLongTermRetentionVault"
              examples:
                Update backup long term retention vault:
                  $ref: "#/components/examples/Update_backup_long_term_retention_va\
                    ult"
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BackupLongTermRetentionVault"
              examples:
                Update backup long term retention vault:
                  $ref: "#/components/examples/Update_backup_long_term_retention_va\
                    ult"
        "202":
          description: Accepted
      tags:
        - BackupLongTermRetentionVaults
      x-ms-long-running-operation: true
servers:
  - url: https://management.azure.com
components:
  examples:
    Get_backup_long_term_retention_vault:
      value:
        id: /subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/longtermretentiontest-1234/providers/Microsoft.Sql/servers/longtermretentiontest-5678/backupLongTermRetentionVaults/RegisteredVault
        location: Japan East
        name: RegisteredVault
        properties:
          recoveryServicesVaultResourceId: /subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/longtermretentionvaulttest-1234/providers/Microsoft.RecoveryServices/vaults/testVaultabc
        type: Microsoft.Sql/servers/backupLongTermRetentionVaults
    Update_backup_long_term_retention_vault:
      value:
        id: /subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/longtermretentiontest-1234/providers/Microsoft.Sql/servers/longtermretentiontest-5678/backupLongTermRetentionVaults/RegisteredVault
        location: Japan East
        name: RegisteredVault
        properties:
          recoveryServicesVaultResourceId: /subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/longtermretentionvaulttest-1234/providers/Microsoft.RecoveryServices/vaults/testVaultabc
        type: Microsoft.Sql/servers/backupLongTermRetentionVaults
  parameters:
    ServerNameParameter:
      description: The name of the server.
      in: path
      name: serverName
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
      examples:
        Get backup long term retention vault:
          value: longtermretentiontest-5678
        Update backup long term retention vault:
          value: longtermretentiontest-5678
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    BackupLongTermRetentionVault:
      allOf:
        - allOf:
            - description: ARM resource.
              properties:
                id:
                  description: Resource ID.
                  readOnly: true
                  type: string
                name:
                  description: Resource name.
                  readOnly: true
                  type: string
                type:
                  description: Resource type.
                  readOnly: true
                  type: string
              type: object
              x-ms-azure-resource: true
          description: ARM proxy resource.
          properties: {}
          type: object
      description: A backup long term retention vault
      properties:
        location:
          description: The geo-location where the resource lives
          readOnly: true
          type: string
        properties:
          $ref: "#/components/schemas/BackupLongTermRetentionVaultProperties"
    BackupLongTermRetentionVaultListResult:
      description: Represents the response to a list vaults request.
      properties:
        value:
          description: The list of vaults in the server.
          items:
            $ref: "#/components/schemas/BackupLongTermRetentionVault"
          type: array
      required:
        - value
    BackupLongTermRetentionVaultProperties:
      description: The properties of a backup long term retention vault.
      properties:
        recoveryServicesVaultResourceId:
          description: The azure recovery services vault resource id
          type: string
      required:
        - recoveryServicesVaultResourceId
