openapi: 3.0.0
info:
  title: Common types
  version: "1.0"
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/sql/resource-manager/common/v1/types.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: sql-types
  x-tags:
    - Azure
    - Microsoft
paths: {}
servers:
  - url: https://azure.local
components:
  parameters:
    ApiVersionParameter:
      description: The API version to use for the request.
      in: query
      name: api-version
      required: true
      x-ms-parameter-location: client
      schema:
        type: string
    ResourceGroupParameter:
      description: The name of the resource group that contains the resource. You can
        obtain this value from the Azure Resource Manager API or the portal.
      in: path
      name: resourceGroupName
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
    SubscriptionIdParameter:
      description: The subscription ID that identifies an Azure subscription.
      in: path
      name: subscriptionId
      required: true
      x-ms-parameter-location: client
      schema:
        type: string
  schemas:
    ProxyResource:
      allOf:
        - $ref: "#/components/schemas/Resource"
      description: ARM proxy resource.
      properties: {}
      type: object
    Resource:
      description: ARM resource.
      properties:
        id:
          description: Resource ID.
          readOnly: true
          type: string
        name:
          description: Resource name.
          readOnly: true
          type: string
        type:
          description: Resource type.
          readOnly: true
          type: string
      type: object
      x-ms-azure-resource: true
    ResourceIdentity:
      description: Azure Active Directory identity configuration for a resource.
      properties:
        principalId:
          description: The Azure Active Directory principal id.
          format: uuid
          readOnly: true
          type: string
        tenantId:
          description: The Azure Active Directory tenant id.
          format: uuid
          readOnly: true
          type: string
        type:
          description: The identity type. Set this to 'SystemAssigned' in order to
            automatically create and assign an Azure Active Directory principal
            for the resource.
          enum:
            - SystemAssigned
          type: string
          x-ms-enum:
            modelAsString: true
            name: IdentityType
      type: object
    Sku:
      description: An ARM Resource SKU.
      properties:
        capacity:
          description: Capacity of the particular SKU.
          format: int32
          type: integer
        family:
          description: If the service has different generations of hardware, for the same
            SKU, then that can be captured here.
          type: string
        name:
          description: The name of the SKU, typically, a letter + Number code, e.g. P3.
          type: string
        size:
          description: Size of the particular SKU
          type: string
        tier:
          description: The tier or edition of the particular SKU, e.g. Basic, Premium.
          type: string
      required:
        - name
      type: object
    TrackedResource:
      allOf:
        - $ref: "#/components/schemas/Resource"
      description: ARM tracked top level resource.
      properties:
        location:
          description: Resource location.
          type: string
          x-ms-mutability:
            - read
            - create
        tags:
          additionalProperties:
            type: string
          description: Resource tags.
          type: object
      required:
        - location
      type: object
