openapi: 3.0.0
info:
  title: AutomationManagement
  version: 2015-10-31
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/automation/resource-manager/Microsoft.Automation/stable/2015-10-31/dscNodeConfiguration.json
      version: "2.0"
  x-preferred: false
  x-providerName: azure.com
  x-serviceName: automation-dscNodeConfiguration
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}/nodeConfigurations":
    get:
      description: Retrieve a list of dsc node configurations.
      externalDocs:
        url: http://aka.ms/azureautomationsdk/dscnodeconfigurations
      operationId: DscNodeConfiguration_ListByAutomationAccount
      parameters:
        - description: Name of an Azure Resource group.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._]+$
          examples:
            List DSC node configurations by Automation Account:
              value: rg
        - description: The name of the automation account.
          in: path
          name: automationAccountName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            List DSC node configurations by Automation Account:
              value: myAutomationAccount33
        - description: The filter to apply on the operation.
          in: query
          name: $filter
          required: false
          schema:
            type: string
        - description: Gets subscription credentials which uniquely identify Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            List DSC node configurations by Automation Account:
              value: subid
        - description: Client Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            List DSC node configurations by Automation Account:
              value: 2015-10-31
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DscNodeConfigurationListResult"
              examples:
                List DSC node configurations by Automation Account:
                  $ref: "#/components/examples/List_DSC_node_configurations_by_Auto\
                    mation_Account"
        default:
          description: Automation error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response of an operation failure
                properties:
                  code:
                    description: Error code
                    type: string
                  message:
                    description: Error message indicating why the operation failed.
                    type: string
                type: object
      tags:
        - DscNodeConfiguration
      x-ms-pageable:
        nextLinkName: nextLink
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}/nodeConfigurations/{nodeConfigurationName}":
    delete:
      description: Delete the Dsc node configurations by node configuration.
      externalDocs:
        url: http://aka.ms/azureautomationsdk/dscnodeconfigurations
      operationId: DscNodeConfiguration_Delete
      parameters:
        - description: Name of an Azure Resource group.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._]+$
          examples:
            Delete a DSC node configuration:
              value: rg
        - description: The name of the automation account.
          in: path
          name: automationAccountName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Delete a DSC node configuration:
              value: myAutomationAccount20
        - description: The Dsc node configuration name.
          in: path
          name: nodeConfigurationName
          required: true
          schema:
            type: string
          examples:
            Delete a DSC node configuration:
              value: configName.nodeConfigName
        - description: Gets subscription credentials which uniquely identify Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Delete a DSC node configuration:
              value: subid
        - description: Client Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Delete a DSC node configuration:
              value: 2015-10-31
      responses:
        "200":
          description: OK
        default:
          description: Automation error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response of an operation failure
                properties:
                  code:
                    description: Error code
                    type: string
                  message:
                    description: Error message indicating why the operation failed.
                    type: string
                type: object
      tags:
        - DscNodeConfiguration
    get:
      description: Retrieve the Dsc node configurations by node configuration.
      externalDocs:
        url: http://aka.ms/azureautomationsdk/dscnodeconfigurations
      operationId: DscNodeConfiguration_Get
      parameters:
        - description: Name of an Azure Resource group.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._]+$
          examples:
            Get a DSC node configuration:
              value: rg
        - description: The name of the automation account.
          in: path
          name: automationAccountName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Get a DSC node configuration:
              value: myAutomationAccount33
        - description: The Dsc node configuration name.
          in: path
          name: nodeConfigurationName
          required: true
          schema:
            type: string
          examples:
            Get a DSC node configuration:
              value: SetupServer.localhost
        - description: Gets subscription credentials which uniquely identify Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Get a DSC node configuration:
              value: subid
        - description: Client Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Get a DSC node configuration:
              value: 2015-10-31
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DscNodeConfiguration"
              examples:
                Get a DSC node configuration:
                  $ref: "#/components/examples/Get_a_DSC_node_configuration"
        default:
          description: Automation error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response of an operation failure
                properties:
                  code:
                    description: Error code
                    type: string
                  message:
                    description: Error message indicating why the operation failed.
                    type: string
                type: object
      tags:
        - DscNodeConfiguration
    put:
      description: Create the node configuration identified by node configuration name.
      externalDocs:
        url: http://aka.ms/azureautomationsdk/dscnodeconfigurations
      operationId: DscNodeConfiguration_CreateOrUpdate
      parameters:
        - description: Name of an Azure Resource group.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._]+$
          examples:
            Get a DSC node configuration:
              value: rg
        - description: The name of the automation account.
          in: path
          name: automationAccountName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Get a DSC node configuration:
              value: myAutomationAccount20
        - description: The create or update parameters for configuration.
          in: path
          name: nodeConfigurationName
          required: true
          schema:
            type: string
          examples:
            Get a DSC node configuration:
              value: configName.nodeConfigName
        - description: Gets subscription credentials which uniquely identify Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Get a DSC node configuration:
              value: subid
        - description: Client Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Get a DSC node configuration:
              value: 2015-10-31
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DscNodeConfigurationCreateOrUpdateParamet\
                ers"
        description: The create or update parameters for configuration.
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DscNodeConfiguration"
              examples:
                Get a DSC node configuration:
                  $ref: "#/components/examples/Get_a_DSC_node_configuration"
        default:
          description: Automation error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response of an operation failure
                properties:
                  code:
                    description: Error code
                    type: string
                  message:
                    description: Error message indicating why the operation failed.
                    type: string
                type: object
      tags:
        - DscNodeConfiguration
servers:
  - url: https://management.azure.com
components:
  examples:
    List_DSC_node_configurations_by_Automation_Account:
      value:
        value:
          - configuration:
              name: SetupServer
            creationTime: 2017-03-28T23:17:06.8901968+00:00
            id: /subscriptions/subid/resourceGroups/rg/providers/Microsoft.Automation/automationAccounts/myAutomationAccount33/nodeConfigurations/SetupServer.localhost
            lastModifiedTime: 2017-03-28T23:17:06.8901968+00:00
            name: SetupServer.localhost
    Get_a_DSC_node_configuration:
      value:
        configuration:
          name: configName
        creationTime: 2017-06-16T01:18:39.010771+00:00
        id: /subscriptions/subid/resourceGroups/rg/providers/Microsoft.Automation/automationAccounts/myAutomationAccount20/nodeConfigurations/nodeConfigName
        lastModifiedTime: 2017-06-16T01:18:39.010771+00:00
        name: nodeConfigName
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    ContentHash:
      description: Definition of the runbook property type.
      properties:
        algorithm:
          description: Gets or sets the content hash algorithm used to hash the content.
          type: string
        value:
          description: Gets or sets expected hash value of the content.
          type: string
      required:
        - algorithm
        - value
    ContentSource:
      description: Definition of the content source.
      properties:
        hash:
          $ref: "#/components/schemas/ContentHash"
        type:
          description: Gets or sets the content source type.
          enum:
            - embeddedContent
            - uri
          type: string
          x-ms-enum:
            modelAsString: true
            name: ContentSourceType
        value:
          description: Gets or sets the value of the content. This is based on the content
            source type.
          type: string
        version:
          description: Gets or sets the version of the content.
          type: string
    DscConfigurationAssociationProperty:
      description: The Dsc configuration property associated with the entity.
      properties:
        name:
          description: Gets or sets the name of the Dsc configuration.
          type: string
    DscNodeConfiguration:
      allOf:
        - allOf:
            - description: The core properties of ARM resources
              properties:
                id:
                  description: Fully qualified resource Id for the resource
                  readOnly: true
                  type: string
                name:
                  description: The name of the resource
                  readOnly: true
                  type: string
                type:
                  description: The type of the resource.
                  readOnly: true
                  type: string
              type: object
              x-ms-azure-resource: true
          description: ARM proxy resource.
          properties: {}
          type: object
      description: Definition of the dsc node configuration.
      properties:
        configuration:
          $ref: "#/components/schemas/DscConfigurationAssociationProperty"
        creationTime:
          description: Gets or sets creation time.
          format: date-time
          type: string
          nullable: false
        lastModifiedTime:
          description: Gets or sets the last modified time.
          format: date-time
          type: string
          nullable: false
    DscNodeConfigurationCreateOrUpdateParameters:
      description: The parameters supplied to the create or update node configuration
        operation.
      properties:
        configuration:
          $ref: "#/components/schemas/DscConfigurationAssociationProperty"
        incrementNodeConfigurationBuild:
          description: If a new build version of NodeConfiguration is required.
          type: boolean
        name:
          description: Name of the node configuration.
          type: string
        source:
          $ref: "#/components/schemas/ContentSource"
      required:
        - source
        - name
        - configuration
    DscNodeConfigurationListResult:
      description: The response model for the list job operation.
      properties:
        nextLink:
          description: Gets or sets the next link.
          type: string
        value:
          description: Gets or sets a list of Dsc node configurations.
          items:
            $ref: "#/components/schemas/DscNodeConfiguration"
          type: array
