openapi: 3.0.0
info:
  description: Describes the schema of the Azure Maps events published to Azure Event Grid.
    This corresponds to the Data property of an EventGridEvent.
  title: Schema of Azure Maps events published to Azure Event Grid
  version: 2018-01-01
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/eventgrid/data-plane/Microsoft.Maps/stable/2018-01-01/Maps.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: eventgrid-Maps
  x-tags:
    - Azure
    - Microsoft
paths: {}
servers:
  - url: https://azure.local
components:
  schemas:
    MapsGeofenceEnteredEventData:
      allOf:
        - $ref: "#/components/schemas/MapsGeofenceEventProperties"
      description: Schema of the Data property of an EventGridEvent for a
        Microsoft.Maps.GeofenceEntered event.
      properties: {}
    MapsGeofenceEventProperties:
      description: Schema of the Data property of an EventGridEvent for a Geofence event
        (GeofenceEntered, GeofenceExited, GeofenceResult).
      properties:
        expiredGeofenceGeometryId:
          description: Lists of the geometry ID of the geofence which is expired relative
            to the user time in the request.
          items:
            type: string
          type: array
        geometries:
          description: Lists the fence geometries that either fully contain the coordinate
            position or have an overlap with the searchBuffer around the fence.
          items:
            $ref: "#/components/schemas/MapsGeofenceGeometry"
          type: array
        invalidPeriodGeofenceGeometryId:
          description: Lists of the geometry ID of the geofence which is in invalid period
            relative to the user time in the request.
          items:
            type: string
          type: array
        isEventPublished:
          description: True if at least one event is published to the Azure Maps event
            subscriber, false if no event is published to the Azure Maps event
            subscriber.
          type: boolean
      type: object
    MapsGeofenceExitedEventData:
      allOf:
        - $ref: "#/components/schemas/MapsGeofenceEventProperties"
      description: Schema of the Data property of an EventGridEvent for a
        Microsoft.Maps.GeofenceExited event.
      properties: {}
    MapsGeofenceGeometry:
      description: The geofence geometry.
      properties:
        deviceId:
          description: ID of the device.
          type: string
        distance:
          description: Distance from the coordinate to the closest border of the geofence.
            Positive means the coordinate is outside of the geofence. If the
            coordinate is outside of the geofence, but more than the value of
            searchBuffer away from the closest geofence border, then the value
            is 999. Negative means the coordinate is inside of the geofence. If
            the coordinate is inside the polygon, but more than the value of
            searchBuffer away from the closest geofencing border,then the value
            is -999. A value of 999 means that there is great confidence the
            coordinate is well outside the geofence. A value of -999 means that
            there is great confidence the coordinate is well within the
            geofence.
          type: number
        geometryId:
          description: The unique ID for the geofence geometry.
          type: string
        nearestLat:
          description: Latitude of the nearest point of the geometry.
          type: number
        nearestLon:
          description: Longitude of the nearest point of the geometry.
          type: number
        udId:
          description: The unique id returned from user upload service when uploading a
            geofence. Will not be included in geofencing post API.
          type: string
      type: object
    MapsGeofenceResultEventData:
      allOf:
        - $ref: "#/components/schemas/MapsGeofenceEventProperties"
      description: Schema of the Data property of an EventGridEvent for a
        Microsoft.Maps.GeofenceResult event.
      properties: {}
