openapi: 3.0.0
info:
  description: The Admin Subscriptions Management Client.
  title: SubscriptionsManagementClient
  version: 2015-11-01
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/azsadmin/resource-manager/subscriptions/Microsoft.Subscriptions.Admin/preview/2015-11-01/OfferDelegation.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: azsadmin-OfferDelegation
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.Subscriptions.Admin/offers/{offer}/offerDelegations":
    get:
      description: Get the list of offer delegations.
      operationId: OfferDelegations_List
      parameters:
        - description: Subscription credentials which uniquely identify Microsoft Azure
            subscription.The subscription ID forms part of the URI for every
            service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Get the list of offer delegations.:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
        - description: The resource group the resource is located under.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Get the list of offer delegations.:
              value: RG
        - description: Name of an offer.
          in: path
          name: offer
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Get the list of offer delegations.:
              value: Default Offer
        - description: Client Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            default: 2015-11-01
          examples:
            Get the list of offer delegations.:
              value: 2015-11-01
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OfferDelegationList"
              examples:
                Get the list of offer delegations.:
                  $ref: "#/components/examples/Get_the_list_of_offer_delegations."
      tags:
        - OfferDelegations
      x-ms-pageable:
        nextLinkName: nextLink
  "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.Subscriptions.Admin/offers/{offer}/offerDelegations/{offerDelegationName}":
    delete:
      description: Delete the specified offer delegation.
      operationId: OfferDelegations_Delete
      parameters:
        - description: Subscription credentials which uniquely identify Microsoft Azure
            subscription.The subscription ID forms part of the URI for every
            service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Delete the specified offer delegation.:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
        - description: The resource group the resource is located under.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Delete the specified offer delegation.:
              value: cnur9852subscrrg374
        - description: Name of an offer.
          in: path
          name: offer
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Delete the specified offer delegation.:
              value: cnur9852tenantoffer374
        - $ref: "#/components/parameters/OfferDelegationParameter"
        - description: Client Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            default: 2015-11-01
          examples:
            Delete the specified offer delegation.:
              value: 2015-11-01
      responses:
        "200":
          description: OK
        "204":
          description: No Content
      tags:
        - OfferDelegations
    get:
      description: Get the specified offer delegation.
      operationId: OfferDelegations_Get
      parameters:
        - description: Subscription credentials which uniquely identify Microsoft Azure
            subscription.The subscription ID forms part of the URI for every
            service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Get the specified offer delegation.:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
        - description: The resource group the resource is located under.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Get the specified offer delegation.:
              value: cnur9852subscrrg374
        - description: Name of an offer.
          in: path
          name: offer
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Get the specified offer delegation.:
              value: cnur9852tenantoffer374
        - $ref: "#/components/parameters/OfferDelegationParameter"
        - description: Client Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            default: 2015-11-01
          examples:
            Get the specified offer delegation.:
              value: 2015-11-01
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OfferDelegation"
              examples:
                Get the specified offer delegation.:
                  $ref: "#/components/examples/Get_the_specified_offer_delegation."
      tags:
        - OfferDelegations
    put:
      description: Create or update the offer delegation.
      operationId: OfferDelegations_CreateOrUpdate
      parameters:
        - description: Subscription credentials which uniquely identify Microsoft Azure
            subscription.The subscription ID forms part of the URI for every
            service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Create or update the offer delegation.:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
        - description: The resource group the resource is located under.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Create or update the offer delegation.:
              value: cnur9852subscrrg374
        - description: Name of an offer.
          in: path
          name: offer
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Create or update the offer delegation.:
              value: cnur9852tenantoffer374
        - $ref: "#/components/parameters/OfferDelegationParameter"
        - description: Client Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            default: 2015-11-01
          examples:
            Create or update the offer delegation.:
              value: 2015-11-01
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OfferDelegation"
        description: New offer delegation parameter.
        required: true
        x-ms-parameter-location: method
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OfferDelegation"
              examples:
                Create or update the offer delegation.:
                  $ref: "#/components/examples/Create_or_update_the_offer_delegatio\
                    n."
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OfferDelegation"
              examples:
                Create or update the offer delegation.:
                  $ref: "#/components/examples/Create_or_update_the_offer_delegatio\
                    n."
      tags:
        - OfferDelegations
servers:
  - url: https://adminmanagement.local.azurestack.external
components:
  examples:
    Get_the_list_of_offer_delegations.:
      value:
        value:
          - id: /subscriptions/2ac7d4ad-fece-4cf0-bc29-e8678897fa75/resourceGroups/cnur9852subscrrg374/providers/Microsoft.Subscriptions.Admin/offers/cnur9852tenantoffer374/offerDelegations/testOfferDelegation
            location: local
            name: cnur9852tenantoffer374/testOfferDelegation
            properties:
              subscriptionId: 9e8052f2-70df-44c0-8300-f97949ca75f0
            type: Microsoft.Subscriptions.Admin/offers/offerDelegations
    Get_the_specified_offer_delegation.:
      value:
        id: /subscriptions/2ac7d4ad-fece-4cf0-bc29-e8678897fa75/resourceGroups/cnur9852subscrrg374/providers/Microsoft.Subscriptions.Admin/offers/cnur9852tenantoffer374/offerDelegations/testOfferDelegation
        location: local
        name: cnur9852tenantoffer374/testOfferDelegation
        properties:
          subscriptionId: 9e8052f2-70df-44c0-8300-f97949ca75f0
        type: Microsoft.Subscriptions.Admin/offers/offerDelegations
    Create_or_update_the_offer_delegation.:
      value:
        id: /subscriptions/2ac7d4ad-fece-4cf0-bc29-e8678897fa75/resourceGroups/cnur9852subscrrg374/providers/Microsoft.Subscriptions.Admin/offers/cnur9852tenantoffer374/offerDelegations/testOfferDelegation
        location: local
        name: cnur9852tenantoffer374/testOfferDelegation
        properties:
          subscriptionId: 9e8052f2-70df-44c0-8300-f97949ca75f0
        type: Microsoft.Subscriptions.Admin/offers/offerDelegations
  parameters:
    OfferDelegationParameter:
      description: Name of a offer delegation.
      in: path
      name: offerDelegationName
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
      examples:
        Delete the specified offer delegation.:
          value: testOfferDelegation
        Get the specified offer delegation.:
          value: testOfferDelegation
        Create or update the offer delegation.:
          value: testOfferDelegation
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    OfferDelegation:
      allOf:
        - description: Base Resource Object
          properties:
            id:
              description: URI of the resource.
              readOnly: true
              type: string
            location:
              description: Location of the resource
              type: string
            name:
              description: Name of the resource.
              readOnly: true
              type: string
            tags:
              additionalProperties:
                type: string
              description: List of key-value pairs.
              readOnly: true
              type: object
            type:
              description: Type of resource.
              readOnly: true
              type: string
          type: object
          x-ms-azure-resource: true
      description: Offer delegation.
      properties:
        properties:
          $ref: "#/components/schemas/OfferDelegationProperties"
      type: object
    OfferDelegationList:
      description: .
      properties:
        nextLink:
          description: Continuation token
          type: string
        value:
          description: Array of usage aggregates.
          items:
            $ref: "#/components/schemas/OfferDelegation"
          type: array
    OfferDelegationProperties:
      description: Properties for an offer delegation.
      properties:
        subscriptionId:
          description: Identifier of the subscription receiving the delegated offer.
          type: string
      type: object
