openapi: 3.0.0
info:
  description: The Microsoft Azure Network management API provides a RESTful set of web
    services that interact with Microsoft Azure Networks service to manage your
    network resources. The API has entities that capture the relationship
    between an end user and the Microsoft Azure Networks service.
  title: NetworkManagementClient
  version: 2018-11-01
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/network/resource-manager/Microsoft.Network/stable/2018-11-01/ddosProtectionPlan.json
      version: "2.0"
  x-preferred: false
  x-providerName: azure.com
  x-serviceName: network-ddosProtectionPlan
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  "/subscriptions/{subscriptionId}/providers/Microsoft.Network/ddosProtectionPlans":
    get:
      description: Gets all DDoS protection plans in a subscription.
      operationId: DdosProtectionPlans_List
      parameters:
        - description: Client API version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            List all DDoS protection plans:
              value: 2018-11-01
        - description: The subscription credentials which uniquely identify the Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            List all DDoS protection plans:
              value: subid
      responses:
        "200":
          description: Request successful. The operation returns a list of DDoS protection
            plan resources.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DdosProtectionPlanListResult"
              examples:
                List all DDoS protection plans:
                  $ref: "#/components/examples/List_all_DDoS_protection_plans"
      tags:
        - DdosProtectionPlans
      x-ms-pageable:
        nextLinkName: nextLink
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/ddosProtectionPlans":
    get:
      description: Gets all the DDoS protection plans in a resource group.
      operationId: DdosProtectionPlans_ListByResourceGroup
      parameters:
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
          examples:
            List DDoS protection plans in resource group:
              value: rg1
        - description: Client API version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            List DDoS protection plans in resource group:
              value: 2018-11-01
        - description: The subscription credentials which uniquely identify the Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            List DDoS protection plans in resource group:
              value: subid
      responses:
        "200":
          description: Request successful. The operation returns a list of DDoS protection
            plan resources.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DdosProtectionPlanListResult"
              examples:
                List DDoS protection plans in resource group:
                  $ref: "#/components/examples/List_DDoS_protection_plans_in_resour\
                    ce_group"
      tags:
        - DdosProtectionPlans
      x-ms-pageable:
        nextLinkName: nextLink
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/ddosProtectionPlans/{ddosProtectionPlanName}":
    delete:
      description: Deletes the specified DDoS protection plan.
      operationId: DdosProtectionPlans_Delete
      parameters:
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
          examples:
            Delete DDoS protection plan:
              value: rg1
        - description: The name of the DDoS protection plan.
          in: path
          name: ddosProtectionPlanName
          required: true
          schema:
            type: string
          examples:
            Delete DDoS protection plan:
              value: test-plan
        - description: Client API version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Delete DDoS protection plan:
              value: 2018-11-01
        - description: The subscription credentials which uniquely identify the Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Delete DDoS protection plan:
              value: subid
      responses:
        "200":
          description: Delete successful.
        "202":
          description: Accepted and the operation will complete asynchronously.
        "204":
          description: Request successful. Resource does not exist.
      tags:
        - DdosProtectionPlans
      x-ms-long-running-operation: true
    get:
      description: Gets information about the specified DDoS protection plan.
      operationId: DdosProtectionPlans_Get
      parameters:
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
          examples:
            Get DDoS protection plan:
              value: rg1
        - description: The name of the DDoS protection plan.
          in: path
          name: ddosProtectionPlanName
          required: true
          schema:
            type: string
          examples:
            Get DDoS protection plan:
              value: test-plan
        - description: Client API version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Get DDoS protection plan:
              value: 2018-11-01
        - description: The subscription credentials which uniquely identify the Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Get DDoS protection plan:
              value: subid
      responses:
        "200":
          description: Request successful. The operation returns the specified DDoS
            protection plan resource.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DdosProtectionPlan"
              examples:
                Get DDoS protection plan:
                  $ref: "#/components/examples/Get_DDoS_protection_plan"
      tags:
        - DdosProtectionPlans
    patch:
      description: Update a DDoS protection plan tags
      operationId: DdosProtectionPlans_UpdateTags
      parameters:
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
          examples:
            DDoS protection plan Update tags:
              value: rg1
        - description: The name of the DDoS protection plan.
          in: path
          name: ddosProtectionPlanName
          required: true
          schema:
            type: string
          examples:
            DDoS protection plan Update tags:
              value: test-plan
        - description: Client API version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            DDoS protection plan Update tags:
              value: 2018-11-01
        - description: The subscription credentials which uniquely identify the Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            DDoS protection plan Update tags:
              value: subid
      requestBody:
        content:
          application/json:
            schema:
              description: Tags object for patch operations.
              properties:
                tags:
                  additionalProperties:
                    type: string
                  description: Resource tags.
                  type: object
        description: Parameters supplied to the update DDoS protection plan resource tags.
        required: true
      responses:
        "200":
          description: Update successful. The operation returns the resulting DDoS
            protection plan resource.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DdosProtectionPlan"
              examples:
                DDoS protection plan Update tags:
                  $ref: "#/components/examples/DDoS_protection_plan_Update_tags"
      tags:
        - DdosProtectionPlans
      x-ms-long-running-operation: true
    put:
      description: Creates or updates a DDoS protection plan.
      operationId: DdosProtectionPlans_CreateOrUpdate
      parameters:
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
          examples:
            Create DDoS protection plan:
              value: rg1
        - description: The name of the DDoS protection plan.
          in: path
          name: ddosProtectionPlanName
          required: true
          schema:
            type: string
          examples:
            Create DDoS protection plan:
              value: test-plan
        - description: Client API version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Create DDoS protection plan:
              value: 2018-11-01
        - description: The subscription credentials which uniquely identify the Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Create DDoS protection plan:
              value: subid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DdosProtectionPlan"
        description: Parameters supplied to the create or update operation.
        required: true
      responses:
        "200":
          description: Update successful. The operation returns the resulting DDoS
            protection plan resource.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DdosProtectionPlan"
              examples:
                Create DDoS protection plan:
                  $ref: "#/components/examples/Create_DDoS_protection_plan"
        "201":
          description: Create successful. The operation returns the resulting DDoS
            protection plan resource.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DdosProtectionPlan"
              examples:
                Create DDoS protection plan:
                  $ref: "#/components/examples/Create_DDoS_protection_plan"
      tags:
        - DdosProtectionPlans
      x-ms-long-running-operation: true
servers:
  - url: https://management.azure.com
components:
  examples:
    List_all_DDoS_protection_plans:
      value:
        value:
          - id: /subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/ddosProtectionPlans/plan1
            location: westus
            name: plan1
            properties:
              provisioningState: Succeeded
              resourceGuid: 00000000-0000-0000-0000-000000000000
              virtualNetworks:
                - id: /subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/virtualNetworks/test-vnet1
            type: Microsoft.Network/ddosProtectionPlans
          - id: /subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/ddosProtectionPlans/plan2
            location: westus
            name: plan2
            properties:
              provisioningState: Succeeded
              resourceGuid: 00000000-0000-0000-0000-000000000000
              virtualNetworks:
                - id: /subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/virtualNetworks/test-vnet2
                - id: /subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/virtualNetworks/test-vnet3
            type: Microsoft.Network/ddosProtectionPlans
    List_DDoS_protection_plans_in_resource_group:
      value:
        value:
          - id: /subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/ddosProtectionPlans/plan1
            location: westus
            name: plan1
            properties:
              provisioningState: Succeeded
              resourceGuid: 00000000-0000-0000-0000-000000000000
              virtualNetworks:
                - id: /subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/virtualNetworks/test-vnet
            type: Microsoft.Network/ddosProtectionPlans
          - id: /subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/ddosProtectionPlans/plan2
            location: westus
            name: plan2
            properties:
              provisioningState: Succeeded
              resourceGuid: 00000000-0000-0000-0000-000000000000
              virtualNetworks:
                - id: /subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/virtualNetworks/test-vnet
            type: Microsoft.Network/ddosProtectionPlans
    Get_DDoS_protection_plan:
      value:
        id: /subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/ddosProtectionPlans/test-plan
        location: westus
        name: test-plan
        properties:
          provisioningState: Succeeded
          resourceGuid: 00000000-0000-0000-0000-000000000000
          virtualNetworks:
            - id: /subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/virtualNetworks/test-vnet
        type: Microsoft.Network/ddosProtectionPlans
    DDoS_protection_plan_Update_tags:
      value:
        id: /subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/ddosProtectionPlans/test-plan
        location: westus
        name: test-plan
        properties:
          provisioningState: Succeeded
          resourceGuid: 00000000-0000-0000-0000-000000000000
          virtualNetworks: []
        tags:
          tag1: value1
          tag2: value2
        type: Microsoft.Network/ddosProtectionPlans
    Create_DDoS_protection_plan:
      value:
        id: /subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/ddosProtectionPlans/test-plan
        location: westus
        name: test-plan
        properties:
          provisioningState: Succeeded
          resourceGuid: 00000000-0000-0000-0000-000000000000
          virtualNetworks: []
        type: Microsoft.Network/ddosProtectionPlans
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    DdosProtectionPlan:
      description: A DDoS protection plan in a resource group.
      properties:
        etag:
          description: A unique read-only string that changes whenever the resource is
            updated.
          readOnly: true
          type: string
        id:
          description: Resource ID.
          readOnly: true
          type: string
        location:
          description: Resource location.
          type: string
        name:
          description: Resource name.
          readOnly: true
          type: string
        properties:
          $ref: "#/components/schemas/DdosProtectionPlanPropertiesFormat"
        tags:
          additionalProperties:
            type: string
          description: Resource tags.
          type: object
        type:
          description: Resource type.
          readOnly: true
          type: string
      x-ms-azure-resource: true
    DdosProtectionPlanListResult:
      description: A list of DDoS protection plans.
      properties:
        nextLink:
          description: The URL to get the next set of results.
          readOnly: true
          type: string
        value:
          description: A list of DDoS protection plans.
          items:
            $ref: "#/components/schemas/DdosProtectionPlan"
          type: array
    DdosProtectionPlanPropertiesFormat:
      description: DDoS protection plan properties.
      properties:
        provisioningState:
          description: "The provisioning state of the DDoS protection plan resource.
            Possible values are: 'Succeeded', 'Updating', 'Deleting', and
            'Failed'."
          readOnly: true
          type: string
        resourceGuid:
          description: The resource GUID property of the DDoS protection plan resource. It
            uniquely identifies the resource, even if the user changes its name
            or migrate the resource across subscriptions or resource groups.
          readOnly: true
          type: string
        virtualNetworks:
          description: The list of virtual networks associated with the DDoS protection
            plan resource. This list is read-only.
          items:
            description: Reference to another subresource.
            properties:
              id:
                description: Resource ID.
                type: string
            x-ms-azure-resource: true
          readOnly: true
          type: array
