openapi: 3.0.0
info:
  description: API to Add/Remove/List Guest Diagnostics Configuration to Azure Resources
  title: Guest Diagnostic Settings
  version: 2018-06-01-preview
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-ms-code-generation-settings:
    name: MonitorManagementClient
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/monitor/resource-manager/Microsoft.Insights/preview/2018-06-01-preview/guestDiagnosticSettings_API.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: monitor-guestDiagnosticSettings_API
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  "/subscriptions/{subscriptionId}/providers/microsoft.insights/guestDiagnosticSettings":
    get:
      description: Get a list of all guest diagnostic settings in a subscription.
      operationId: guestDiagnosticsSettings_List
      parameters:
        - $ref: "#/components/parameters/SubscriptionIdParameter"
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: The request succeeded.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GuestDiagnosticSettingsList"
        default:
          description: An error occurred and the list of guest diagnostic settings could
            not be retrieved.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      x-ms-pageable: {}
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/microsoft.insights/guestDiagnosticSettings":
    get:
      description: Get a list of all guest diagnostic settings in a resource group.
      operationId: guestDiagnosticsSettings_ListByResourceGroup
      parameters:
        - $ref: "#/components/parameters/ResourceGroupNameParameter"
        - $ref: "#/components/parameters/SubscriptionIdParameter"
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: The request succeeded.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GuestDiagnosticSettingsList"
        default:
          description: An error occurred and the list of guest diagnostic settings could
            not be retrieved.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      x-ms-pageable: {}
  "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/microsoft.insights/guestDiagnosticSettings/{diagnosticSettingsName}":
    delete:
      description: Delete guest diagnostics settings.
      operationId: guestDiagnosticsSettings_Delete
      parameters:
        - $ref: "#/components/parameters/ResourceGroupNameParameter"
        - $ref: "#/components/parameters/DiagnosticSettingNameParameter"
        - $ref: "#/components/parameters/SubscriptionIdParameter"
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: The diagnostic settings was successfully deleted.
        "204":
          description: The diagnostic settings does not exist. It may have already been
            deleted.
        default:
          description: An error occurred and the diagnostic settings could not be deleted.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      tags:
        - GuestDiagnosticsSettings
    get:
      description: Gets guest diagnostics settings.
      operationId: guestDiagnosticsSettings_Get
      parameters:
        - $ref: "#/components/parameters/ResourceGroupNameParameter"
        - $ref: "#/components/parameters/DiagnosticSettingNameParameter"
        - $ref: "#/components/parameters/SubscriptionIdParameter"
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: The request succeeded.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GuestDiagnosticSettingsResource"
        default:
          description: An error occurred and the diagnostic settings could not be retrieved.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      tags:
        - GuestDiagnosticsSettings
    patch:
      description: Updates guest diagnostics settings.
      operationId: guestDiagnosticsSettings_Update
      parameters:
        - $ref: "#/components/parameters/ResourceGroupNameParameter"
        - $ref: "#/components/parameters/DiagnosticSettingNameParameter"
        - $ref: "#/components/parameters/ApiVersionParameter"
        - $ref: "#/components/parameters/SubscriptionIdParameter"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GuestDiagnosticSettingsPatchResource"
        description: The configuration to patch.
        required: true
      responses:
        "200":
          description: An existing guest diagnostic settings was successfully updated.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GuestDiagnosticSettingsResource"
        "201":
          description: A new guest diagnostic settings was successfully created.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GuestDiagnosticSettingsResource"
        default:
          description: An error occurred and the guest diagnostic settings could not be
            created or updated.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    put:
      description: Creates or updates guest diagnostics settings.
      operationId: guestDiagnosticsSettings_CreateOrUpdate
      parameters:
        - $ref: "#/components/parameters/ResourceGroupNameParameter"
        - $ref: "#/components/parameters/DiagnosticSettingNameParameter"
        - $ref: "#/components/parameters/ApiVersionParameter"
        - $ref: "#/components/parameters/SubscriptionIdParameter"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GuestDiagnosticSettingsResource"
        description: The configuration to create or update.
        required: true
      responses:
        "200":
          description: An existing guest diagnostic settings was successfully updated.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GuestDiagnosticSettingsResource"
              examples:
                Create or update a guest diagnostic settings:
                  $ref: "#/components/examples/Create_or_update_a_guest_diagnostic_\
                    settings"
        "201":
          description: A new guest diagnostic settings was successfully created.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GuestDiagnosticSettingsResource"
              examples:
                Create or update a guest diagnostic settings:
                  $ref: "#/components/examples/Create_or_update_a_guest_diagnostic_\
                    settings"
        default:
          description: An error occurred and the guest diagnostic settings could not be
            created or updated.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      tags:
        - GuestDiagnosticsSettings
servers:
  - url: https://management.azure.com
components:
  examples:
    Create_or_update_a_guest_diagnostic_settings:
      value:
        id: /subscriptions/187f412d-1758-44d9-b052-169e2564721d/resourceGroups/Default-ResourceGroup/providers/microsoft.insights/guestDiagnosticSettings/SampleDiagSetting
        location: West US
        name: SampleDiagSetting
        properties:
          dataSources:
            - configuration:
                perfCounters:
                  - name: \Process(_Total)\%Processor Time
                    samplingPeriod: PT1M
                  - name: \Process(_Total)\Working Set
                    samplingPeriod: PT1M
              kind: PerformanceCounter
              sinks:
                - kind: LogAnalytics
          osType: Windows
        tags: {}
        type: Microsoft.Insights/guestDiagnosticSettings
  parameters:
    ApiVersionParameter:
      description: Client Api Version.
      in: query
      name: api-version
      required: true
      schema:
        type: string
      examples:
        Create or update a guest diagnostic settings:
          value: 2018-06-01-preview
    DiagnosticSettingNameParameter:
      description: The name of the diagnostic setting.
      in: path
      name: diagnosticSettingsName
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
      examples:
        Create or update a guest diagnostic settings:
          value: SampleDiagSetting
    ResourceGroupNameParameter:
      description: The name of the resource group.
      in: path
      name: resourceGroupName
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
      examples:
        Create or update a guest diagnostic settings:
          value: Default-ResourceGroup
    SubscriptionIdParameter:
      description: The Azure subscription Id.
      in: path
      name: subscriptionId
      required: true
      schema:
        type: string
      examples:
        Create or update a guest diagnostic settings:
          value: 187f412d-1758-44d9-b052-169e2564721d
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    DataSource:
      description: Data source object contains configuration to collect telemetry and one
        or more sinks to send that telemetry data to
      properties:
        configuration:
          $ref: "#/components/schemas/DataSourceConfiguration"
        kind:
          description: Datasource kind
          enum:
            - PerformanceCounter
            - ETWProviders
            - WindowsEventLogs
          type: string
        sinks:
          items:
            $ref: "#/components/schemas/SinkConfiguration"
          type: array
      required:
        - kind
        - configuration
        - sinks
      type: object
    DataSourceConfiguration:
      properties:
        eventLogs:
          description: Windows event logs configuration.
          items:
            $ref: "#/components/schemas/EventLogConfiguration"
          type: array
        perfCounters:
          description: Performance counter configuration
          items:
            $ref: "#/components/schemas/PerformanceCounterConfiguration"
          type: array
        providers:
          description: ETW providers configuration
          items:
            $ref: "#/components/schemas/EtwProviderConfiguration"
          type: array
      type: object
    ErrorResponse:
      description: Describes the format of Error response.
      properties:
        code:
          description: Error code
          type: string
        message:
          description: Error message indicating why the operation failed.
          type: string
      type: object
    EtwEventConfiguration:
      properties:
        filter:
          type: string
        id:
          type: integer
        name:
          type: string
      required:
        - name
        - id
      type: object
    EtwProviderConfiguration:
      properties:
        events:
          items:
            $ref: "#/components/schemas/EtwEventConfiguration"
          type: array
        id:
          type: string
      required:
        - id
        - events
      type: object
    EventLogConfiguration:
      properties:
        filter:
          type: string
        logName:
          type: string
      required:
        - logName
      type: object
    GuestDiagnosticSettings:
      description: Virtual machine diagnostic settings
      properties:
        dataSources:
          description: the array of data source object which are configured to collect and
            send data
          items:
            $ref: "#/components/schemas/DataSource"
          type: array
        osType:
          description: Operating system type for the configuration
          enum:
            - Windows
            - Linux
          type: string
        proxySetting:
          type: string
    GuestDiagnosticSettingsList:
      description: A list of guest diagnostic settings.
      properties:
        nextLink:
          description: Provides the link to retrieve the next set of elements.
          type: string
        value:
          description: The list of guest diagnostic settings.
          items:
            $ref: "#/components/schemas/GuestDiagnosticSettingsResource"
          type: array
    GuestDiagnosticSettingsPatchResource:
      description: An diagnostic settings object for the body of patch operations.
      properties:
        properties:
          $ref: "#/components/schemas/GuestDiagnosticSettings"
        tags:
          additionalProperties:
            type: string
          description: Resource tags
    GuestDiagnosticSettingsResource:
      allOf:
        - $ref: "#/components/schemas/Resource"
      description: Virtual machine guest diagnostics settings resource.
      properties:
        properties:
          $ref: "#/components/schemas/GuestDiagnosticSettings"
      required:
        - properties
      type: object
    PerformanceCounterConfiguration:
      properties:
        instance:
          type: string
        name:
          type: string
        samplingPeriod:
          type: string
      required:
        - name
        - samplingPeriod
      type: object
    Resource:
      description: An azure resource object
      properties:
        id:
          description: Azure resource Id
          readOnly: true
          type: string
        location:
          description: Resource location
          type: string
          x-ms-mutability:
            - create
            - read
        name:
          description: Azure resource name
          readOnly: true
          type: string
        tags:
          additionalProperties:
            type: string
          description: Resource tags
        type:
          description: Azure resource type
          readOnly: true
          type: string
      required:
        - location
      x-ms-azure-resource: true
    SinkConfiguration:
      properties:
        kind:
          enum:
            - EventHub
            - ApplicationInsights
            - LogAnalytics
          type: string
      required:
        - kind
      type: object
