openapi: 3.0.0
info:
  description: Azure Application Insights client for Annotations for a component.
  title: ApplicationInsightsManagementClient
  version: 2015-05-01
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/applicationinsights/resource-manager/Microsoft.Insights/stable/2015-05-01/componentAnnotations_API.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: applicationinsights-componentAnnotations_API
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Insights/components/{resourceName}/Annotations":
    get:
      description: Gets the list of annotations for a component for given time range
      operationId: Annotations_List
      parameters:
        - description: The name of the resource group. The name is case insensitive.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._\(\)]+$
          examples:
            AnnotationsList:
              value: my-resource-group
        - description: The API version to use for this operation.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            minLength: 1
          examples:
            AnnotationsList:
              value: 2015-05-01
        - description: The ID of the target subscription.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
            minLength: 1
          examples:
            AnnotationsList:
              value: subid
        - $ref: "#/components/parameters/ResourceNameParameter"
        - $ref: "#/components/parameters/StartParameter"
        - $ref: "#/components/parameters/EndParameter"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AnnotationsListResult"
              examples:
                AnnotationsList:
                  $ref: "#/components/examples/AnnotationsList"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AnnotationError"
      x-ms-pageable: {}
    put:
      description: Create an Annotation of an Application Insights component.
      operationId: Annotations_Create
      parameters:
        - description: The name of the resource group. The name is case insensitive.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._\(\)]+$
          examples:
            AnnotationsCreate:
              value: my-resource-group
        - description: The API version to use for this operation.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            minLength: 1
          examples:
            AnnotationsCreate:
              value: 2015-05-01
        - description: The ID of the target subscription.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
            minLength: 1
          examples:
            AnnotationsCreate:
              value: subid
        - $ref: "#/components/parameters/ResourceNameParameter"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Annotation"
        description: Properties that need to be specified to create an annotation of a
          Application Insights component.
        required: true
      responses:
        "200":
          description: An object containing the annotation definition created by this PUT
            call.
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Annotation"
                type: array
              examples:
                AnnotationsCreate:
                  $ref: "#/components/examples/AnnotationsCreate"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AnnotationError"
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Insights/components/{resourceName}/Annotations/{annotationId}":
    delete:
      description: Delete an Annotation of an Application Insights component.
      operationId: Annotations_Delete
      parameters:
        - description: The name of the resource group. The name is case insensitive.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._\(\)]+$
          examples:
            AnnotationsDelete:
              value: my-resource-group
        - description: The API version to use for this operation.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            minLength: 1
          examples:
            AnnotationsDelete:
              value: 2015-05-01
        - description: The ID of the target subscription.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
            minLength: 1
          examples:
            AnnotationsDelete:
              value: subid
        - $ref: "#/components/parameters/ResourceNameParameter"
        - $ref: "#/components/parameters/AnnotationIdParameter"
      responses:
        "200":
          description: The annotation that was successfully deleted.
    get:
      description: Get the annotation for given id.
      operationId: Annotations_Get
      parameters:
        - description: The name of the resource group. The name is case insensitive.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._\(\)]+$
          examples:
            AnnotationsGet:
              value: my-resource-group
        - description: The API version to use for this operation.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            minLength: 1
          examples:
            AnnotationsGet:
              value: 2015-05-01
        - description: The ID of the target subscription.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
            minLength: 1
          examples:
            AnnotationsGet:
              value: subid
        - $ref: "#/components/parameters/ResourceNameParameter"
        - $ref: "#/components/parameters/AnnotationIdParameter"
      responses:
        "200":
          description: The Annotation object for this id.
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Annotation"
                type: array
              examples:
                AnnotationsGet:
                  $ref: "#/components/examples/AnnotationsGet"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AnnotationError"
servers:
  - url: https://management.azure.com
components:
  examples:
    AnnotationsList:
      value:
        - AnnotationName: InsightsPortal-20180126-1
          Category: Deployment
          EventTime: 2018-01-29T20:30:31+00:00
          Id: 4de4524f-fca5-44a8-b7e6-a67d5107796e
          Properties: '{"ReleaseDefinitionName":"InsightsPortal-PPEProd-KeyVault","ReleaseRequestedFor":"6a970e9b-6220-47f3-a78c-b8be97506698","TeamFoundationCollectionUri":"https://mseng.visualstudio.com/","BuildNumber":"20180126.1","ReleaseDescription":"Triggered
            by InsightsPortal_master_PROD1_vNext
            20180126.1.","ReleaseId":"31075","ReleaseWebUrl":"https://mseng.visualstudio.com/96a62c4a-58c2-4dbb-94b6-5979ebc7f2af/_release?releaseId=31075\u0026_a=release-summary","SourceBranch":"refs/heads/master","BuildRepositoryProvider":"TfsGit","ReleaseEnvironmentName":"AIMON
            VIP
            SWAP","BuildRepositoryName":"InsightsPortal","ReleaseName":"InsightsPortal-20180126-1"}'
        - AnnotationName: InsightsPortal-20180125-1
          Category: Deployment
          EventTime: 2018-01-29T20:38:35+00:00
          Id: 9a82214f-8f98-4699-b5bc-cad6101ed223
          Properties: '{"ReleaseDefinitionName":"InsightsPortal-PPEProd-KeyVault","ReleaseRequestedFor":"6a970e9b-6220-47f3-a78c-b8be97506698","TeamFoundationCollectionUri":"https://mseng.visualstudio.com/","BuildNumber":"20180125.1","ReleaseDescription":"Triggered
            by InsightsPortal_master_PROD1_vNext
            20180125.1.","ReleaseId":"31035","ReleaseWebUrl":"https://mseng.visualstudio.com/96a62c4a-58c2-4dbb-94b6-5979ebc7f2af/_release?releaseId=31035\u0026_a=release-summary","SourceBranch":"refs/heads/master","BuildRepositoryProvider":"TfsGit","ReleaseEnvironmentName":"Prod
            VIP Swap
            ","BuildRepositoryName":"InsightsPortal","ReleaseName":"InsightsPortal-20180125-1"}'
    AnnotationsCreate:
      value:
        - AnnotationName: TestAnnotation
          Category: Text
          EventTime: 2018-01-31T13:41:38.657+00:00
          Id: 444e2c08-274a-4bbb-a89e-d77bb720f44a
          Properties: '{"Comments":"Testing","Label":"Success"}'
    AnnotationsGet:
      value:
        - AnnotationName: TestAnnotation
          Category: Text
          EventTime: 2018-01-31T13:41:38.657+00:00
          Id: 444e2c08-274a-4bbb-a89e-d77bb720f44a
          Properties: '{"Comments":"Testing","Label":"Success"}'
  parameters:
    AnnotationIdParameter:
      description: The unique annotation ID. This is unique within a Application Insights
        component.
      in: path
      name: annotationId
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
      examples:
        AnnotationsDelete:
          value: bb820f1b-3110-4a8b-ba2c-8c1129d7eb6a
        AnnotationsGet:
          value: 444e2c08-274a-4bbb-a89e-d77bb720f44a
    EndParameter:
      description: The end time to query for annotations.
      in: query
      name: end
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
      examples:
        AnnotationsList:
          value: 2018-02-06T00%253A33A00.000Z
    ResourceNameParameter:
      description: The name of the Application Insights component resource.
      in: path
      name: resourceName
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
      examples:
        AnnotationsList:
          value: my-component
        AnnotationsCreate:
          value: my-component
        AnnotationsDelete:
          value: my-component
        AnnotationsGet:
          value: my-component
    StartParameter:
      description: The start time to query from for annotations, cannot be older than 90
        days from current date.
      in: query
      name: start
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
      examples:
        AnnotationsList:
          value: 2018-02-05T00%253A30%253A00.000Z
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    Annotation:
      description: Annotation associated with an application insights resource.
      properties:
        AnnotationName:
          description: Name of annotation
          type: string
        Category:
          description: Category of annotation, free form
          type: string
        EventTime:
          description: Time when event occurred
          format: date-time
          type: string
        Id:
          description: Unique Id for annotation
          type: string
        Properties:
          description: Serialized JSON object for detailed properties
          type: string
        RelatedAnnotation:
          default: "null"
          description: Related parent annotation if any
          type: string
      type: object
    AnnotationError:
      description: Error associated with trying to create annotation with Id that already
        exist
      properties:
        code:
          description: Error detail code and explanation
          type: string
        innererror:
          $ref: "#/components/schemas/InnerError"
        message:
          description: Error message
          type: string
      type: object
    AnnotationsListResult:
      description: Annotations list result.
      properties:
        value:
          description: An array of annotations.
          items:
            $ref: "#/components/schemas/Annotation"
          readOnly: true
          type: array
    InnerError:
      description: Inner error
      properties:
        diagnosticcontext:
          description: Provides correlation for request
          type: string
        time:
          description: Request time
          format: date-time
          type: string
      type: object
