openapi: 3.0.0
info:
  title: Azure Data Migration Service Resource Provider
  version: 2018-03-15-preview
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/datamigration/resource-manager/Microsoft.DataMigration/preview/2018-03-15-preview/definitions/TasksCommon.json
      version: "2.0"
  x-preferred: false
  x-providerName: azure.com
  x-serviceName: datamigration-TasksCommon
  x-tags:
    - Azure
    - Microsoft
paths: {}
servers:
  - url: https://azure.local
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    BlobShare:
      description: Blob container storage information.
      properties:
        sasUri:
          description: SAS URI of Azure Storage Account Container.
          type: string
      required:
        - sasUri
      type: object
    DataItemMigrationSummaryResult:
      description: Basic summary of a data item migration
      properties:
        endedOn:
          description: Migration end time
          format: date-time
          readOnly: true
          type: string
        errorPrefix:
          description: Wildcard string prefix to use for querying all errors of the item
          readOnly: true
          type: string
        itemsCompletedCount:
          description: Number of successfully completed items
          format: int64
          readOnly: true
          type: integer
        itemsCount:
          description: Number of items
          format: int64
          readOnly: true
          type: integer
        name:
          description: Name of the item
          readOnly: true
          type: string
        resultPrefix:
          description: Wildcard string prefix to use for querying all sub-tem results of
            the item
          readOnly: true
          type: string
        startedOn:
          description: Migration start time
          format: date-time
          readOnly: true
          type: string
        state:
          $ref: "#/components/schemas/MigrationState"
        statusMessage:
          description: Status message
          readOnly: true
          type: string
      type: object
    DataMigrationError:
      description: Migration Task errors
      properties:
        message:
          description: Error description
          readOnly: true
          type: string
        type:
          $ref: "#/components/schemas/ErrorType"
      type: object
    DataMigrationProjectMetadata:
      description: Common metadata for migration projects
      properties:
        selectedMigrationTables:
          description: List of tables selected for migration
          items:
            $ref: "#/components/schemas/MigrationTableMetadata"
          readOnly: true
          type: array
        sourceServerName:
          description: Source server name
          readOnly: true
          type: string
        sourceServerPort:
          description: Source server port number
          readOnly: true
          type: string
        sourceUsername:
          description: Source username
          readOnly: true
          type: string
        targetDbName:
          description: Target database name
          readOnly: true
          type: string
        targetServerName:
          description: Target server name
          readOnly: true
          type: string
        targetUsername:
          description: Target username
          readOnly: true
          type: string
        targetUsingWinAuth:
          description: Whether target connection is Windows authentication
          readOnly: true
          type: boolean
      type: object
    Database:
      description: Information about a single database
      properties:
        collation:
          description: Collation name of the database
          type: string
        compatibilityLevel:
          $ref: "#/components/schemas/DatabaseCompatLevel"
        databaseState:
          $ref: "#/components/schemas/DatabaseState"
        fqdn:
          description: Fully qualified name
          type: string
        id:
          description: Unique identifier for the database
          type: string
        installId:
          description: Install id of the database
          type: string
        name:
          description: Name of the database
          type: string
        serverCoreCount:
          description: Number of cores on the server
          type: integer
        serverDefaultBackupPath:
          description: Default path of the backup folder
          type: string
        serverDefaultDataPath:
          description: Default path of the data files
          type: string
        serverDefaultLogPath:
          description: Default path of the log files
          type: string
        serverEdition:
          description: Edition of the server
          type: string
        serverId:
          description: The unique Server Id
          type: string
        serverLevel:
          description: Product level of the server (RTM, SP, CTP).
          type: string
        serverName:
          description: Name of the server
          type: string
        serverVersion:
          description: Version of the server
          type: string
        serverVisibleOnlineCoreCount:
          description: Number of cores on the server that have VISIBLE ONLINE status
          type: integer
      type: object
    DatabaseCompatLevel:
      description: An enumeration of SQL Server database compatibility levels
      enum:
        - CompatLevel80
        - CompatLevel90
        - CompatLevel100
        - CompatLevel110
        - CompatLevel120
        - CompatLevel130
        - CompatLevel140
      type: string
      x-ms-enum:
        modelAsString: true
        name: DatabaseCompatLevel
    DatabaseFileInfo:
      description: Database file specific information
      properties:
        databaseName:
          description: Name of the database
          type: string
        fileType:
          $ref: "#/components/schemas/DatabaseFileType"
        id:
          description: Unique identifier for database file
          type: string
        logicalName:
          description: Logical name of the file
          type: string
        physicalFullName:
          description: Operating-system full path of the file
          type: string
        restoreFullName:
          description: Suggested full path of the file for restoring
          type: string
        sizeMB:
          description: Size of the file in megabytes
          format: double
          type: number
      type: object
    DatabaseFileInput:
      description: Database file specific information for input
      properties:
        fileType:
          $ref: "#/components/schemas/DatabaseFileType"
        id:
          description: Unique identifier for database file
          type: string
        logicalName:
          description: Logical name of the file
          type: string
        physicalFullName:
          description: Operating-system full path of the file
          type: string
        restoreFullName:
          description: Suggested full path of the file for restoring
          type: string
      type: object
    DatabaseFileType:
      description: An enumeration of SQL Server database file types
      enum:
        - Rows
        - Log
        - Filestream
        - NotSupported
        - Fulltext
      type: string
      x-ms-enum:
        modelAsString: true
        name: DatabaseFileType
    DatabaseMigrationStage:
      description: Current stage of migration
      enum:
        - None
        - Initialize
        - Backup
        - FileCopy
        - Restore
        - Completed
      type: string
      x-ms-enum:
        modelAsString: true
        name: DatabaseMigrationStage
    DatabaseObjectName:
      description: A representation of the name of an object in a database
      properties:
        databaseName:
          description: The unescaped name of the database containing the object
          readOnly: true
          type: string
        objectName:
          description: The unescaped name of the object
          readOnly: true
          type: string
        objectType:
          $ref: "#/components/schemas/DatabaseObjectType"
        schemaName:
          description: The unescaped name of the schema containing the object
          readOnly: true
          type: string
      type: object
    DatabaseObjectType:
      description: An enumeration of type of objects
      enum:
        - StoredProcedures
        - Table
        - User
        - View
        - Function
      type: string
      x-ms-enum:
        modelAsString: true
        name: ObjectType
    DatabaseState:
      description: An enumeration of SQL Server Database states
      enum:
        - Online
        - Restoring
        - Recovering
        - RecoveryPending
        - Suspect
        - Emergency
        - Offline
        - Copying
        - OfflineSecondary
      type: string
      x-ms-enum:
        modelAsString: true
        name: DatabaseState
    ErrorType:
      description: Error type
      enum:
        - Default
        - Warning
        - Error
      type: string
      x-ms-enum:
        modelAsString: true
        name: ErrorType
    FileShare:
      description: File share information with Path, Username, and Password.
      properties:
        password:
          description: Password credential used to connect to the share location.
          type: string
        path:
          description: The folder path for this share.
          type: string
        userName:
          description: User name credential to connect to the share location
          type: string
      required:
        - path
      type: object
    MigrateSqlServerSqlMIDatabaseInput:
      description: Database specific information for SQL to Azure SQL DB Managed Instance
        migration task inputs
      properties:
        backupFileShare:
          $ref: "#/components/schemas/FileShare"
        name:
          description: Name of the database
          type: string
        restoreDatabaseName:
          description: Name of the database at destination
          type: string
      required:
        - name
        - restoreDatabaseName
      type: object
    MigrateSqlServerSqlServerDatabaseInput:
      description: Database specific information for SQL to SQL migration task inputs
      properties:
        backupFileShare:
          $ref: "#/components/schemas/FileShare"
        databaseFiles:
          description: The list of database files
          items:
            $ref: "#/components/schemas/DatabaseFileInput"
          type: array
        name:
          description: Name of the database
          type: string
        restoreDatabaseName:
          description: Name of the database at destination
          type: string
      type: object
    MigrationState:
      description: Current state of migration
      enum:
        - None
        - InProgress
        - Failed
        - Warning
        - Completed
        - Skipped
        - Stopped
      type: string
      x-ms-enum:
        modelAsString: true
        name: MigrationState
    MigrationStatus:
      description: Current status of migration
      enum:
        - Default
        - Connecting
        - SourceAndTargetSelected
        - SelectLogins
        - Configured
        - Running
        - Error
        - Stopped
        - Completed
        - CompletedWithWarnings
      type: string
      x-ms-enum:
        modelAsString: true
        name: MigrationStatus
    MigrationTableMetadata:
      description: Metadata for tables selected in migration project
      properties:
        sourceTableName:
          description: Source table name
          readOnly: true
          type: string
        targetTableName:
          description: Target table name
          readOnly: true
          type: string
      type: object
    SqlMigrationTaskInput:
      description: Base class for migration task input
      properties:
        sourceConnectionInfo:
          allOf:
            - description: Defines the connection properties of a server
              discriminator:
                propertyName: type
              properties:
                password:
                  description: Password credential.
                  type: string
                type:
                  description: Type of connection info
                  type: string
                userName:
                  description: User name
                  type: string
              required:
                - type
              type: object
          description: Information for connecting to SQL database server
          properties:
            additionalSettings:
              description: Additional connection settings
              type: string
            authentication:
              description: An enumeration of possible authentication types when connecting
              enum:
                - None
                - WindowsAuthentication
                - SqlAuthentication
                - ActiveDirectoryIntegrated
                - ActiveDirectoryPassword
              type: string
              x-ms-enum:
                modelAsString: true
                name: AuthenticationType
            dataSource:
              description: Data source in the format
                Protocol:MachineName\SQLServerInstanceName,PortNumber
              type: string
            encryptConnection:
              default: true
              description: Whether to encrypt the connection
              type: boolean
            trustServerCertificate:
              default: false
              description: Whether to trust the server certificate
              type: boolean
          required:
            - dataSource
          type: object
          x-ms-discriminator-value: SqlConnectionInfo
        targetConnectionInfo:
          allOf:
            - description: Defines the connection properties of a server
              discriminator:
                propertyName: type
              properties:
                password:
                  description: Password credential.
                  type: string
                type:
                  description: Type of connection info
                  type: string
                userName:
                  description: User name
                  type: string
              required:
                - type
              type: object
          description: Information for connecting to SQL database server
          properties:
            additionalSettings:
              description: Additional connection settings
              type: string
            authentication:
              description: An enumeration of possible authentication types when connecting
              enum:
                - None
                - WindowsAuthentication
                - SqlAuthentication
                - ActiveDirectoryIntegrated
                - ActiveDirectoryPassword
              type: string
              x-ms-enum:
                modelAsString: true
                name: AuthenticationType
            dataSource:
              description: Data source in the format
                Protocol:MachineName\SQLServerInstanceName,PortNumber
              type: string
            encryptConnection:
              default: true
              description: Whether to encrypt the connection
              type: boolean
            trustServerCertificate:
              default: false
              description: Whether to trust the server certificate
              type: boolean
          required:
            - dataSource
          type: object
          x-ms-discriminator-value: SqlConnectionInfo
      required:
        - sourceConnectionInfo
        - targetConnectionInfo
      type: object
