openapi: 3.0.0
info:
  title: Azure Database Migration Service Resource Provider
  version: 2018-04-19
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/datamigration/resource-manager/Microsoft.DataMigration/stable/2018-04-19/definitions/ResourceSkus.json
      version: "2.0"
  x-preferred: false
  x-providerName: azure.com
  x-serviceName: datamigration-ResourceSkus
  x-tags:
    - Azure
    - Microsoft
paths: {}
servers:
  - url: https://azure.local
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    ResourceSku:
      description: Describes an available DMS SKU.
      properties:
        apiVersions:
          description: The api versions that support this SKU.
          items:
            type: string
          readOnly: true
          type: array
        capabilities:
          description: A name value pair to describe the capability.
          items:
            $ref: "#/components/schemas/ResourceSkuCapabilities"
          readOnly: true
          type: array
        capacity:
          $ref: "#/components/schemas/ResourceSkuCapacity"
        costs:
          description: Metadata for retrieving price info.
          items:
            $ref: "#/components/schemas/ResourceSkuCosts"
          readOnly: true
          type: array
        family:
          description: The Family of this particular SKU.
          readOnly: true
          type: string
        kind:
          description: The Kind of resources that are supported in this SKU.
          readOnly: true
          type: string
        locations:
          description: The set of locations that the SKU is available.
          items:
            type: string
          readOnly: true
          type: array
        name:
          description: The name of SKU.
          readOnly: true
          type: string
        resourceType:
          description: The type of resource the SKU applies to.
          readOnly: true
          type: string
        restrictions:
          description: The restrictions because of which SKU cannot be used. This is empty
            if there are no restrictions.
          items:
            $ref: "#/components/schemas/ResourceSkuRestrictions"
          readOnly: true
          type: array
        size:
          description: The Size of the SKU.
          readOnly: true
          type: string
        tier:
          description: Specifies the tier of DMS in a scale set.
          readOnly: true
          type: string
    ResourceSkuCapabilities:
      description: Describes The SKU capabilities object.
      properties:
        name:
          description: An invariant to describe the feature.
          readOnly: true
          type: string
        value:
          description: An invariant if the feature is measured by quantity.
          readOnly: true
          type: string
    ResourceSkuCapacity:
      description: Describes scaling information of a SKU.
      properties:
        default:
          description: The default capacity.
          format: int64
          readOnly: true
          type: integer
        maximum:
          description: The maximum capacity.
          format: int64
          readOnly: true
          type: integer
        minimum:
          description: The minimum capacity.
          format: int64
          readOnly: true
          type: integer
        scaleType:
          description: The scale type applicable to the SKU.
          enum:
            - Automatic
            - Manual
            - None
          readOnly: true
          type: string
          x-ms-enum:
            modelAsString: true
            name: ResourceSkuCapacityScaleType
    ResourceSkuCosts:
      description: Describes metadata for retrieving price info.
      properties:
        extendedUnit:
          description: An invariant to show the extended unit.
          readOnly: true
          type: string
        meterID:
          description: Used for querying price from commerce.
          readOnly: true
          type: string
        quantity:
          description: The multiplier is needed to extend the base metered cost.
          format: int64
          readOnly: true
          type: integer
    ResourceSkuRestrictions:
      description: Describes scaling information of a SKU.
      properties:
        reasonCode:
          description: The reason code for restriction.
          enum:
            - QuotaId
            - NotAvailableForSubscription
          readOnly: true
          type: string
          x-ms-enum:
            modelAsString: true
            name: ResourceSkuRestrictionsReasonCode
        type:
          description: The type of restrictions.
          enum:
            - location
          readOnly: true
          type: string
          x-ms-enum:
            modelAsString: true
            name: ResourceSkuRestrictionsType
        values:
          description: The value of restrictions. If the restriction type is set to
            location. This would be different locations where the SKU is
            restricted.
          items:
            type: string
          readOnly: true
          type: array
    ResourceSkusResult:
      description: The DMS List SKUs operation response.
      properties:
        nextLink:
          description: The uri to fetch the next page of DMS SKUs. Call ListNext() with
            this to fetch the next page of DMS SKUs.
          type: string
        value:
          description: The list of SKUs available for the subscription.
          items:
            $ref: "#/components/schemas/ResourceSku"
          type: array
      required:
        - value
