openapi: 3.0.0
info:
  description: API spec for Microsoft.Security (Azure Security Center) resource provider
  title: Security Center
  version: 2017-08-01-preview
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/security/resource-manager/Microsoft.Security/preview/2017-08-01-preview/workspaceSettings.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: security-workspaceSettings
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  "/subscriptions/{subscriptionId}/providers/Microsoft.Security/workspaceSettings":
    get:
      description: Settings about where we should store your security data and logs. If the
        result is empty, it means that no custom-workspace configuration was set
      operationId: WorkspaceSettings_List
      parameters:
        - description: API version for the operation
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Get workspace settings on subscription:
              value: 2017-08-01-preview
        - description: Azure subscription ID
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
            pattern: ^[0-9A-Fa-f]{8}-([0-9A-Fa-f]{4}-){3}[0-9A-Fa-f]{12}$
          examples:
            Get workspace settings on subscription:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WorkspaceSettingList"
              examples:
                Get workspace settings on subscription:
                  $ref: "#/components/examples/Get_workspace_settings_on_subscripti\
                    on"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response structure.
                properties:
                  error:
                    description: Error details.
                    properties:
                      code:
                        description: An identifier for the error. Codes are invariant and
                          are intended to be consumed programmatically.
                        readOnly: true
                        type: string
                      message:
                        description: A message describing the error, intended to be
                          suitable for display in a user interface.
                        readOnly: true
                        type: string
                    type: object
                    x-ms-external: true
                type: object
                x-ms-external: true
      tags:
        - Workspace Settings
      x-ms-pageable:
        nextLinkName: nextLink
  "/subscriptions/{subscriptionId}/providers/Microsoft.Security/workspaceSettings/{workspaceSettingName}":
    delete:
      description: Deletes the custom workspace settings for this subscription. new VMs
        will report to the default workspace
      operationId: WorkspaceSettings_Delete
      parameters:
        - description: API version for the operation
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Delete a workspace setting data for resource group:
              value: 2017-08-01-preview
        - description: Azure subscription ID
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
            pattern: ^[0-9A-Fa-f]{8}-([0-9A-Fa-f]{4}-){3}[0-9A-Fa-f]{12}$
          examples:
            Delete a workspace setting data for resource group:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
        - $ref: "#/components/parameters/WorkspaceSettingName"
      responses:
        "204":
          description: No Content
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response structure.
                properties:
                  error:
                    description: Error details.
                    properties:
                      code:
                        description: An identifier for the error. Codes are invariant and
                          are intended to be consumed programmatically.
                        readOnly: true
                        type: string
                      message:
                        description: A message describing the error, intended to be
                          suitable for display in a user interface.
                        readOnly: true
                        type: string
                    type: object
                    x-ms-external: true
                type: object
                x-ms-external: true
      tags:
        - Workspace Settings
    get:
      description: Settings about where we should store your security data and logs. If the
        result is empty, it means that no custom-workspace configuration was set
      operationId: WorkspaceSettings_Get
      parameters:
        - description: API version for the operation
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Get a workspace setting on subscription:
              value: 2017-08-01-preview
        - description: Azure subscription ID
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
            pattern: ^[0-9A-Fa-f]{8}-([0-9A-Fa-f]{4}-){3}[0-9A-Fa-f]{12}$
          examples:
            Get a workspace setting on subscription:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
        - $ref: "#/components/parameters/WorkspaceSettingName"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WorkspaceSetting"
              examples:
                Get a workspace setting on subscription:
                  $ref: "#/components/examples/Get_a_workspace_setting_on_subscript\
                    ion"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response structure.
                properties:
                  error:
                    description: Error details.
                    properties:
                      code:
                        description: An identifier for the error. Codes are invariant and
                          are intended to be consumed programmatically.
                        readOnly: true
                        type: string
                      message:
                        description: A message describing the error, intended to be
                          suitable for display in a user interface.
                        readOnly: true
                        type: string
                    type: object
                    x-ms-external: true
                type: object
                x-ms-external: true
      tags:
        - Workspace Settings
    patch:
      description: Settings about where we should store your security data and logs
      operationId: WorkspaceSettings_Update
      parameters:
        - description: API version for the operation
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Update a workspace setting data for subscription:
              value: 2017-08-01-preview
        - description: Azure subscription ID
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
            pattern: ^[0-9A-Fa-f]{8}-([0-9A-Fa-f]{4}-){3}[0-9A-Fa-f]{12}$
          examples:
            Update a workspace setting data for subscription:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
        - $ref: "#/components/parameters/WorkspaceSettingName"
      requestBody:
        $ref: "#/components/requestBodies/WorkspaceSetting"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WorkspaceSetting"
              examples:
                Update a workspace setting data for subscription:
                  $ref: "#/components/examples/Update_a_workspace_setting_data_for_\
                    subscription"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response structure.
                properties:
                  error:
                    description: Error details.
                    properties:
                      code:
                        description: An identifier for the error. Codes are invariant and
                          are intended to be consumed programmatically.
                        readOnly: true
                        type: string
                      message:
                        description: A message describing the error, intended to be
                          suitable for display in a user interface.
                        readOnly: true
                        type: string
                    type: object
                    x-ms-external: true
                type: object
                x-ms-external: true
      tags:
        - Workspace Settings
    put:
      description: creating settings about where we should store your security data and logs
      operationId: WorkspaceSettings_Create
      parameters:
        - description: API version for the operation
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Create a workspace setting data for subscription:
              value: 2017-08-01-preview
        - description: Azure subscription ID
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
            pattern: ^[0-9A-Fa-f]{8}-([0-9A-Fa-f]{4}-){3}[0-9A-Fa-f]{12}$
          examples:
            Create a workspace setting data for subscription:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
        - $ref: "#/components/parameters/WorkspaceSettingName"
      requestBody:
        $ref: "#/components/requestBodies/WorkspaceSetting"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WorkspaceSetting"
              examples:
                Create a workspace setting data for subscription:
                  $ref: "#/components/examples/Create_a_workspace_setting_data_for_\
                    subscription"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response structure.
                properties:
                  error:
                    description: Error details.
                    properties:
                      code:
                        description: An identifier for the error. Codes are invariant and
                          are intended to be consumed programmatically.
                        readOnly: true
                        type: string
                      message:
                        description: A message describing the error, intended to be
                          suitable for display in a user interface.
                        readOnly: true
                        type: string
                    type: object
                    x-ms-external: true
                type: object
                x-ms-external: true
      tags:
        - Workspace Settings
servers:
  - url: https://management.azure.com
components:
  examples:
    Get_workspace_settings_on_subscription:
      value:
        value:
          - id: /subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23/providers/Microsoft.Security/workspaceSettings/default
            name: default
            properties:
              scope: /subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23
              workspaceId: /subscriptions/c4930e90-cd72-4aa5-93e9-2d081d129569/resourceGroups/myRg/providers/Microsoft.OperationalInsights/workspaces/myWorkspace1
            type: Microsoft.Security/workspaceSettings
          - id: /subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23/resourceGroups/myRg/providers/Microsoft.Security/workspaceSettings/myRg
            name: myRg
            properties:
              scope: /subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23/resourceGroups/myRg
              workspaceId: /subscriptions/c4930e90-cd72-4aa5-93e9-2d081d129569/resourceGroups/myOtherRg/providers/Microsoft.OperationalInsights/workspaces/myWorkspace2
            type: Microsoft.Security/workspaceSettings
    Get_a_workspace_setting_on_subscription:
      value:
        id: /subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23/providers/Microsoft.Security/workspaceSettings/default
        name: default
        properties:
          scope: /subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23
          workspaceId: /subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23/resourceGroups/myRg/providers/Microsoft.OperationalInsights/workspaces/myWorkspace
        type: Microsoft.Security/workspaceSettings
    Update_a_workspace_setting_data_for_subscription:
      value:
        id: /subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23/providers/Microsoft.Security/workspaceSettings/default
        name: default
        properties:
          scope: /subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23
          workspaceId: /subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23/resourceGroups/myRg/providers/Microsoft.OperationalInsights/workspaces/myWorkspace
        type: Microsoft.Security/workspaceSettings
    Create_a_workspace_setting_data_for_subscription:
      value:
        id: /subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23/providers/Microsoft.Security/workspaceSettings/default
        name: default
        properties:
          scope: /subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23
          workspaceId: /subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23/resourceGroups/myRg/providers/Microsoft.OperationalInsights/workspaces/myWorkspace
        type: Microsoft.Security/workspaceSettings
  parameters:
    WorkspaceSettingName:
      description: Name of the security setting
      in: path
      name: workspaceSettingName
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
      examples:
        Delete a workspace setting data for resource group:
          value: default
        Get a workspace setting on subscription:
          value: default
        Update a workspace setting data for subscription:
          value: default
        Create a workspace setting data for subscription:
          value: default
  requestBodies:
    WorkspaceSetting:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/WorkspaceSetting"
      description: Security data setting object
      required: true
      x-ms-parameter-location: method
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    WorkspaceSetting:
      allOf:
        - description: Describes an Azure resource.
          properties:
            id:
              description: Resource Id
              readOnly: true
              type: string
            name:
              description: Resource name
              readOnly: true
              type: string
            type:
              description: Resource type
              readOnly: true
              type: string
          type: object
          x-ms-azure-resource: true
      description: Configures where to store the OMS agent data for workspaces under a scope
      properties:
        properties:
          $ref: "#/components/schemas/WorkspaceSettingProperties"
      type: object
    WorkspaceSettingList:
      description: List of workspace settings response
      properties:
        nextLink:
          description: The URI to fetch the next page.
          readOnly: true
          type: string
        value:
          description: List of workspace settings
          items:
            $ref: "#/components/schemas/WorkspaceSetting"
          type: array
      required:
        - value
    WorkspaceSettingProperties:
      description: Workspace setting data
      properties:
        scope:
          description: All the VMs in this scope will send their security data to the
            mentioned workspace unless overridden by a setting with more
            specific scope
          type: string
        workspaceId:
          description: The full Azure ID of the workspace to save the data in
          type: string
      required:
        - workspaceId
        - scope
      type: object
