openapi: 3.0.0
info:
  description: The Microsoft Azure Network management API provides a RESTful set of web
    services that interact with Microsoft Azure Networks service to manage your
    network resources. The API has entities that capture the relationship
    between an end user and the Microsoft Azure Networks service.
  title: NetworkManagementClient
  version: 2018-07-01
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/network/resource-manager/Microsoft.Network/stable/2018-07-01/applicationSecurityGroup.json
      version: "2.0"
  x-preferred: false
  x-providerName: azure.com
  x-serviceName: network-applicationSecurityGroup
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  "/subscriptions/{subscriptionId}/providers/Microsoft.Network/applicationSecurityGroups":
    get:
      description: Gets all application security groups in a subscription.
      operationId: ApplicationSecurityGroups_ListAll
      parameters:
        - description: Client API version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            List all application security groups:
              value: 2018-07-01
        - description: The subscription credentials which uniquely identify the Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            List all application security groups:
              value: subid
      responses:
        "200":
          description: Request successful. The operation returns a list of application
            security group resources.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApplicationSecurityGroupListResult"
              examples:
                List all application security groups:
                  $ref: "#/components/examples/List_all_application_security_groups"
      tags:
        - ApplicationSecurityGroups
      x-ms-pageable:
        nextLinkName: nextLink
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/applicationSecurityGroups":
    get:
      description: Gets all the application security groups in a resource group.
      operationId: ApplicationSecurityGroups_List
      parameters:
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
          examples:
            List load balancers in resource group:
              value: rg1
        - description: Client API version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            List load balancers in resource group:
              value: 2018-07-01
        - description: The subscription credentials which uniquely identify the Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            List load balancers in resource group:
              value: subid
      responses:
        "200":
          description: Request successful. The operation returns a list of application
            security group resources.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApplicationSecurityGroupListResult"
              examples:
                List load balancers in resource group:
                  $ref: "#/components/examples/List_load_balancers_in_resource_group"
      tags:
        - ApplicationSecurityGroups
      x-ms-pageable:
        nextLinkName: nextLink
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/applicationSecurityGroups/{applicationSecurityGroupName}":
    delete:
      description: Deletes the specified application security group.
      operationId: ApplicationSecurityGroups_Delete
      parameters:
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
          examples:
            Delete application security group:
              value: rg1
        - description: The name of the application security group.
          in: path
          name: applicationSecurityGroupName
          required: true
          schema:
            type: string
          examples:
            Delete application security group:
              value: test-asg
        - description: Client API version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Delete application security group:
              value: 2018-07-01
        - description: The subscription credentials which uniquely identify the Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Delete application security group:
              value: subid
      responses:
        "200":
          description: Delete successful.
        "202":
          description: Accepted and the operation will complete asynchronously.
        "204":
          description: Request successful. Resource does not exist.
      tags:
        - ApplicationSecurityGroups
      x-ms-long-running-operation: true
    get:
      description: Gets information about the specified application security group.
      operationId: ApplicationSecurityGroups_Get
      parameters:
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
          examples:
            Get application security group:
              value: rg1
        - description: The name of the application security group.
          in: path
          name: applicationSecurityGroupName
          required: true
          schema:
            type: string
          examples:
            Get application security group:
              value: test-asg
        - description: Client API version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Get application security group:
              value: 2018-07-01
        - description: The subscription credentials which uniquely identify the Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Get application security group:
              value: subid
      responses:
        "200":
          description: Request successful. The operation returns the specified application
            security group resource.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApplicationSecurityGroup"
              examples:
                Get application security group:
                  $ref: "#/components/examples/Get_application_security_group"
      tags:
        - ApplicationSecurityGroups
    put:
      description: Creates or updates an application security group.
      operationId: ApplicationSecurityGroups_CreateOrUpdate
      parameters:
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
          examples:
            Create application security group:
              value: rg1
        - description: The name of the application security group.
          in: path
          name: applicationSecurityGroupName
          required: true
          schema:
            type: string
          examples:
            Create application security group:
              value: test-asg
        - description: Client API version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Create application security group:
              value: 2018-07-01
        - description: The subscription credentials which uniquely identify the Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Create application security group:
              value: subid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ApplicationSecurityGroup"
        description: Parameters supplied to the create or update ApplicationSecurityGroup
          operation.
        required: true
      responses:
        "200":
          description: Update successful. The operation returns the resulting application
            security group resource.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApplicationSecurityGroup"
              examples:
                Create application security group:
                  $ref: "#/components/examples/Create_application_security_group"
        "201":
          description: Create successful. The operation returns the resulting application
            security group resource.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApplicationSecurityGroup"
              examples:
                Create application security group:
                  $ref: "#/components/examples/Create_application_security_group"
      tags:
        - ApplicationSecurityGroups
      x-ms-long-running-operation: true
servers:
  - url: https://management.azure.com
components:
  examples:
    List_all_application_security_groups:
      value:
        value:
          - id: /subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/applicationSecurityGroups/asg1
            location: westus
            name: asg1
            properties:
              provisioningState: Succeeded
              resourceGuid: 00000000-0000-0000-0000-000000000000
            type: Microsoft.Network/applicationSecurityGroups
          - id: /subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/applicationSecurityGroups/asg2
            location: westus
            name: asg2
            properties:
              provisioningState: Succeeded
              resourceGuid: 00000000-0000-0000-0000-000000000000
            type: Microsoft.Network/applicationSecurityGroups
    List_load_balancers_in_resource_group:
      value:
        value:
          - id: /subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/applicationSecurityGroups/asg1
            location: westus
            name: asg1
            properties:
              provisioningState: Succeeded
              resourceGuid: 00000000-0000-0000-0000-000000000000
            type: Microsoft.Network/applicationSecurityGroups
          - id: /subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/applicationSecurityGroups/asg2
            location: westus
            name: asg2
            properties:
              provisioningState: Succeeded
              resourceGuid: 00000000-0000-0000-0000-000000000000
            type: Microsoft.Network/applicationSecurityGroups
    Get_application_security_group:
      value:
        id: /subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/applicationSecurityGroups/test-asg
        location: westus
        name: test-asg
        properties:
          provisioningState: Succeeded
          resourceGuid: 00000000-0000-0000-0000-000000000000
        type: Microsoft.Network/applicationSecurityGroups
    Create_application_security_group:
      value:
        id: /subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/applicationSecurityGroups/test-asg
        location: westus
        name: test-asg
        properties:
          provisioningState: Succeeded
          resourceGuid: 00000000-0000-0000-0000-000000000000
        type: Microsoft.Network/applicationSecurityGroups
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    ApplicationSecurityGroup:
      allOf:
        - description: Common resource representation.
          properties:
            id:
              description: Resource ID.
              type: string
            location:
              description: Resource location.
              type: string
            name:
              description: Resource name.
              readOnly: true
              type: string
            tags:
              additionalProperties:
                type: string
              description: Resource tags.
              type: object
            type:
              description: Resource type.
              readOnly: true
              type: string
          x-ms-azure-resource: true
      description: An application security group in a resource group.
      properties:
        etag:
          description: A unique read-only string that changes whenever the resource is
            updated.
          readOnly: true
          type: string
        properties:
          $ref: "#/components/schemas/ApplicationSecurityGroupPropertiesFormat"
    ApplicationSecurityGroupListResult:
      description: A list of application security groups.
      properties:
        nextLink:
          description: The URL to get the next set of results.
          readOnly: true
          type: string
        value:
          description: A list of application security groups.
          items:
            $ref: "#/components/schemas/ApplicationSecurityGroup"
          type: array
    ApplicationSecurityGroupPropertiesFormat:
      description: Application security group properties.
      properties:
        provisioningState:
          description: "The provisioning state of the application security group resource.
            Possible values are: 'Succeeded', 'Updating', 'Deleting', and
            'Failed'."
          readOnly: true
          type: string
        resourceGuid:
          description: The resource GUID property of the application security group
            resource. It uniquely identifies a resource, even if the user
            changes its name or migrate the resource across subscriptions or
            resource groups.
          readOnly: true
          type: string
