openapi: 3.0.0
info:
  description: File containing commonly referenced parameters.
  title: Common Referenced Parameters File
  version: 2017-08-30
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/cognitiveservices/data-plane/Common/BasicRegions.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: cognitiveservices-BasicRegions
  x-tags:
    - Azure
    - Microsoft
paths: {}
servers:
  - url: https://azure.local
components:
  parameters:
    AzureRegion:
      description: Supported Azure regions for Cognitive Services endpoints
      in: path
      name: AzureRegion
      required: true
      x-ms-enum:
        modelAsString: false
        name: AzureRegions
      x-ms-parameter-location: client
      x-ms-skip-url-encoding: true
      schema:
        type: string
        enum:
          - westus
          - westeurope
          - southeastasia
          - eastus2
          - westcentralus
