openapi: 3.0.0
info:
  description: Provides read and update functionality for Azure SQL Database backup long
    term retention policy
  title: Azure SQL Database Backup Long Term Retention Policy
  version: 2014-04-01
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/sql/resource-manager/Microsoft.Sql/stable/2014-04-01/backupLongTermRetentionPolicies.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: sql-backupLongTermRetentionPolicies
  x-tags:
    - Azure
    - Microsoft
paths:
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}/databases/{databaseName}/backupLongTermRetentionPolicies":
    get:
      description: Returns a database backup long term retention policy
      operationId: BackupLongTermRetentionPolicies_ListByDatabase
      parameters:
        - description: The API version to use for the request.
          in: query
          name: api-version
          required: true
          x-ms-parameter-location: client
          schema:
            type: string
          examples:
            Get backup long term retention policy:
              value: 2014-04-01
        - description: The subscription ID that identifies an Azure subscription.
          in: path
          name: subscriptionId
          required: true
          x-ms-parameter-location: client
          schema:
            type: string
          examples:
            Get backup long term retention policy:
              value: 00000000-1111-2222-3333-444444444444
        - description: The name of the resource group that contains the resource. You can
            obtain this value from the Azure Resource Manager API or the portal.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Get backup long term retention policy:
              value: longtermretentiontest-1234
        - $ref: "#/components/parameters/ServerNameParameter"
        - description: The name of the database.
          in: path
          name: databaseName
          required: true
          schema:
            type: string
          examples:
            Get backup long term retention policy:
              value: longtermretentiontest-9012
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BackupLongTermRetentionPolicyListResult"
              examples:
                Get backup long term retention policy:
                  $ref: "#/components/examples/Get_backup_long_term_retention_policy"
      tags:
        - BackupLongTermRetentionPolicies
      x-ms-pageable: {}
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}/databases/{databaseName}/backupLongTermRetentionPolicies/{backupLongTermRetentionPolicyName}":
    get:
      description: Returns a database backup long term retention policy
      operationId: BackupLongTermRetentionPolicies_Get
      parameters:
        - description: The API version to use for the request.
          in: query
          name: api-version
          required: true
          x-ms-parameter-location: client
          schema:
            type: string
          examples:
            Get backup long term retention policy:
              value: 2014-04-01
        - description: The subscription ID that identifies an Azure subscription.
          in: path
          name: subscriptionId
          required: true
          x-ms-parameter-location: client
          schema:
            type: string
          examples:
            Get backup long term retention policy:
              value: 00000000-1111-2222-3333-444444444444
        - description: The name of the resource group that contains the resource. You can
            obtain this value from the Azure Resource Manager API or the portal.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Get backup long term retention policy:
              value: longtermretentiontest-1234
        - $ref: "#/components/parameters/ServerNameParameter"
        - description: The name of the database.
          in: path
          name: databaseName
          required: true
          schema:
            type: string
          examples:
            Get backup long term retention policy:
              value: longtermretentiontest-9012
        - description: The name of the backup long term retention policy
          in: path
          name: backupLongTermRetentionPolicyName
          required: true
          x-ms-enum:
            modelAsString: true
            name: BackupLongTermRetentionPolicyName
          schema:
            type: string
            enum:
              - Default
          examples:
            Get backup long term retention policy:
              value: Default
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BackupLongTermRetentionPolicy"
              examples:
                Get backup long term retention policy:
                  $ref: "#/components/examples/Get_backup_long_term_retention_policy"
      tags:
        - BackupLongTermRetentionPolicies
    put:
      description: Creates or updates a database backup long term retention policy
      operationId: BackupLongTermRetentionPolicies_CreateOrUpdate
      parameters:
        - description: The API version to use for the request.
          in: query
          name: api-version
          required: true
          x-ms-parameter-location: client
          schema:
            type: string
          examples:
            Update backup long term retention policy:
              value: 2014-04-01
        - description: The subscription ID that identifies an Azure subscription.
          in: path
          name: subscriptionId
          required: true
          x-ms-parameter-location: client
          schema:
            type: string
          examples:
            Update backup long term retention policy:
              value: 00000000-1111-2222-3333-444444444444
        - description: The name of the resource group that contains the resource. You can
            obtain this value from the Azure Resource Manager API or the portal.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Update backup long term retention policy:
              value: longtermretentiontest-1234
        - $ref: "#/components/parameters/ServerNameParameter"
        - description: The name of the database
          in: path
          name: databaseName
          required: true
          schema:
            type: string
          examples:
            Update backup long term retention policy:
              value: longtermretentiontest-9012
        - description: The name of the backup long term retention policy
          in: path
          name: backupLongTermRetentionPolicyName
          required: true
          x-ms-enum:
            modelAsString: true
            name: BackupLongTermRetentionPolicyName
          schema:
            type: string
            enum:
              - Default
          examples:
            Update backup long term retention policy:
              value: Default
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BackupLongTermRetentionPolicy"
        description: The required parameters to update a backup long term retention policy
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BackupLongTermRetentionPolicy"
              examples:
                Update backup long term retention policy:
                  $ref: "#/components/examples/Update_backup_long_term_retention_po\
                    licy"
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BackupLongTermRetentionPolicy"
              examples:
                Update backup long term retention policy:
                  $ref: "#/components/examples/Update_backup_long_term_retention_po\
                    licy"
        "202":
          description: Accepted
      tags:
        - BackupLongTermRetentionPolicies
      x-ms-long-running-operation: true
servers:
  - url: https://management.azure.com
components:
  examples:
    Get_backup_long_term_retention_policy:
      value:
        id: /subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/longtermretentiontest-1234/providers/Microsoft.Sql/servers/longtermretentiontest-5678/databases/longtermretentiontest-9012/backupLongTermRetentionPolicies/Default
        location: Japan East
        name: Default
        properties:
          recoveryServicesBackupPolicyResourceId: /subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/longtermretentionvaulttest-1234/providers/Microsoft.RecoveryServices/vaults/testVaultabc/backupPolicies/testPolicyxyz
          state: Enabled
        type: Microsoft.Sql/servers/databases/backupLongTermRetentionPolicies
    Update_backup_long_term_retention_policy:
      value:
        id: /subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/longtermretentiontest-1234/providers/Microsoft.Sql/servers/longtermretentiontest-5678/databases/longtermretentiontest-9012/backupLongTermRetentionPolicies/Default
        location: Japan East
        name: Default
        properties:
          recoveryServicesBackupPolicyResourceId: /subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/longtermretentionvaulttest-1234/providers/Microsoft.RecoveryServices/vaults/testVaultabc/backupPolicies/testPolicyxyz
          state: Enabled
        type: Microsoft.Sql/servers/databases/backupLongTermRetentionPolicies
  parameters:
    ServerNameParameter:
      description: The name of the server.
      in: path
      name: serverName
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
      examples:
        Get backup long term retention policy:
          value: longtermretentiontest-5678
        Update backup long term retention policy:
          value: longtermretentiontest-5678
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    BackupLongTermRetentionPolicy:
      allOf:
        - allOf:
            - description: ARM resource.
              properties:
                id:
                  description: Resource ID.
                  readOnly: true
                  type: string
                name:
                  description: Resource name.
                  readOnly: true
                  type: string
                type:
                  description: Resource type.
                  readOnly: true
                  type: string
              type: object
              x-ms-azure-resource: true
          description: ARM proxy resource.
          properties: {}
          type: object
      description: A backup long term retention policy
      properties:
        location:
          description: The geo-location where the resource lives
          readOnly: true
          type: string
        properties:
          $ref: "#/components/schemas/BackupLongTermRetentionPolicyProperties"
    BackupLongTermRetentionPolicyListResult:
      description: Represents the response to a list long-term retention policies request.
      properties:
        value:
          description: The list of long-term retention policies in the database.
          items:
            $ref: "#/components/schemas/BackupLongTermRetentionPolicy"
          type: array
      required:
        - value
    BackupLongTermRetentionPolicyProperties:
      description: The properties of a backup long term retention policy
      properties:
        recoveryServicesBackupPolicyResourceId:
          description: The azure recovery services backup protection policy resource id
          type: string
        state:
          description: The status of the backup long term retention policy
          enum:
            - Disabled
            - Enabled
          type: string
          x-ms-enum:
            name: BackupLongTermRetentionPolicyState
      required:
        - state
        - recoveryServicesBackupPolicyResourceId
