openapi: 3.0.0
info:
  description: Use these REST APIs for getting the network connectivity status of your
    Azure API Management deployment. When the API Management service is deployed
    inside a Virtual Network, it needs to have access to other Azure resources
    it depends on. This also gives details about the DNS Servers visible to
    Azure API Management deployment.
  title: ApiManagementClient
  version: 2017-03-01
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2017-03-01/apimnetworkstatus.json
      version: "2.0"
  x-preferred: false
  x-providerName: azure.com
  x-serviceName: apimanagement-apimnetworkstatus
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ApiManagement/service/{serviceName}/locations/{locationName}/networkstatus":
    get:
      description: Gets the Connectivity Status to the external resources on which the Api
        Management service depends from inside the Cloud Service. This also
        returns the DNS Servers as visible to the CloudService.
      operationId: NetworkStatus_ListByLocation
      parameters:
        - description: Subscription credentials which uniquely identify Microsoft Azure
            subscription. The subscription ID forms part of the URI for every
            service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            ApiManagementServiceGetNetworkStatusByLocation:
              value: subid
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            ApiManagementServiceGetNetworkStatusByLocation:
              value: rg1
        - description: The name of the API Management service.
          in: path
          name: serviceName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 50
            pattern: ^[a-zA-Z](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?$
          examples:
            ApiManagementServiceGetNetworkStatusByLocation:
              value: apimService1
        - $ref: "#/components/parameters/LocationNameParameter"
        - description: Version of the API to be used with the client request.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            ApiManagementServiceGetNetworkStatusByLocation:
              value: 2017-03-01
      responses:
        "200":
          description: Gets the Network status details.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NetworkStatusContract"
              examples:
                ApiManagementServiceGetNetworkStatusByLocation:
                  $ref: "#/components/examples/ApiManagementServiceGetNetworkStatus\
                    ByLocation"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error Body contract.
                properties:
                  code:
                    description: Service-defined error code. This code serves as a
                      sub-status for the HTTP error code specified in the
                      response.
                    type: string
                  details:
                    description: The list of invalid fields send in request, in case of
                      validation error.
                    items:
                      description: Error Field contract.
                      properties:
                        code:
                          description: Property level error code.
                          type: string
                        message:
                          description: Human-readable representation of property-level
                            error.
                          type: string
                        target:
                          description: Property name.
                          type: string
                    type: array
                  message:
                    description: Human-readable representation of the error.
                    type: string
      tags:
        - NetworkStatus
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ApiManagement/service/{serviceName}/networkstatus":
    get:
      description: Gets the Connectivity Status to the external resources on which the Api
        Management service depends from inside the Cloud Service. This also
        returns the DNS Servers as visible to the CloudService.
      operationId: NetworkStatus_ListByService
      parameters:
        - description: Subscription credentials which uniquely identify Microsoft Azure
            subscription. The subscription ID forms part of the URI for every
            service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            ApiManagementServiceGetNetworkStatus:
              value: subid
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            ApiManagementServiceGetNetworkStatus:
              value: rg1
        - description: The name of the API Management service.
          in: path
          name: serviceName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 50
            pattern: ^[a-zA-Z](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?$
          examples:
            ApiManagementServiceGetNetworkStatus:
              value: apimService1
        - description: Version of the API to be used with the client request.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            ApiManagementServiceGetNetworkStatus:
              value: 2017-03-01
      responses:
        "200":
          description: Gets the Network status details.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NetworkStatusContract"
              examples:
                ApiManagementServiceGetNetworkStatus:
                  $ref: "#/components/examples/ApiManagementServiceGetNetworkStatus"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error Body contract.
                properties:
                  code:
                    description: Service-defined error code. This code serves as a
                      sub-status for the HTTP error code specified in the
                      response.
                    type: string
                  details:
                    description: The list of invalid fields send in request, in case of
                      validation error.
                    items:
                      description: Error Field contract.
                      properties:
                        code:
                          description: Property level error code.
                          type: string
                        message:
                          description: Human-readable representation of property-level
                            error.
                          type: string
                        target:
                          description: Property name.
                          type: string
                    type: array
                  message:
                    description: Human-readable representation of the error.
                    type: string
      tags:
        - NetworkStatus
servers:
  - url: https://management.azure.com
components:
  examples:
    ApiManagementServiceGetNetworkStatusByLocation:
      value:
        connectivityStatus:
          - error: ""
            lastStatusChange: 2017-04-13T19:39:53.5543347Z
            lastUpdated: 2017-06-01T23:13:07.9054516Z
            name: apimgmtstxaleb7*******.blob.core.windows.net
            status: success
          - error: ""
            lastStatusChange: 2017-04-13T19:39:53.7262408Z
            lastUpdated: 2017-06-01T23:13:08.1242042Z
            name: apimgmtstxaleb7*******.file.core.windows.net
            status: success
          - error: ""
            lastStatusChange: 2017-05-27T17:52:41.3592337Z
            lastUpdated: 2017-06-01T23:08:22.9140197Z
            name: Scm
            status: success
          - error: ""
            lastStatusChange: 2017-04-13T19:39:53.5543347Z
            lastUpdated: 2017-06-01T23:13:08.0617078Z
            name: "****seqi.database.windows.net"
            status: success
        dnsServers:
          - 10.20.32.69
          - 10.20.237.143
    ApiManagementServiceGetNetworkStatus:
      value:
        - location: Central US
          networkStatus:
            connectivityStatus:
              - error: ""
                lastStatusChange: 2017-06-28T23:17:34.9009011Z
                lastUpdated: 2017-06-28T23:37:35.1518379Z
                name: ap********.blob.core.windows.net
                status: success
              - error: ""
                lastStatusChange: 2017-06-28T23:17:35.2579713Z
                lastUpdated: 2017-06-28T23:37:35.9161347Z
                name: ap********.file.core.windows.net
                status: success
              - error: ""
                lastStatusChange: 2017-06-28T23:17:35.0079651Z
                lastUpdated: 2017-06-28T23:37:35.2130114Z
                name: e*****.database.windows.net
                status: success
              - error: ""
                lastStatusChange: 2017-06-28T23:27:36.8198739Z
                lastUpdated: 2017-06-28T23:37:37.4401208Z
                name: Scm
                status: success
            dnsServers:
              - 10.20.37.126
              - 10.20.244.38
        - location: West US
          networkStatus:
            connectivityStatus:
              - error: ""
                lastStatusChange: 2017-06-28T23:17:06.4831818Z
                lastUpdated: 2017-06-28T23:37:07.1803004Z
                name: ap********.file.core.windows.net
                status: success
              - error: ""
                lastStatusChange: 2017-06-28T23:17:05.7332755Z
                lastUpdated: 2017-06-28T23:37:05.9303015Z
                name: bb******.blob.core.windows.net
                status: success
              - error: ""
                lastStatusChange: 2017-06-28T23:17:06.1237965Z
                lastUpdated: 2017-06-28T23:37:07.1178113Z
                name: e******.database.windows.net
                status: success
            dnsServers:
              - 10.64.3.87
              - 10.64.5.29
              - 10.20.32.105
  parameters:
    LocationNameParameter:
      description: Location in which the API Management service is deployed. This is one of
        the Azure Regions like West US, East US, South Central US.
      in: path
      name: locationName
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
        minLength: 1
      examples:
        ApiManagementServiceGetNetworkStatusByLocation:
          value: East Asia
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    ConnectivityStatusContract:
      description: Details about connectivity to a resource.
      properties:
        error:
          description: Error details of the connectivity to the resource.
          type: string
        lastStatusChange:
          description: >
            The date when the resource connectivity status last Changed from
            success to failure or vice-versa. The date conforms to the following
            format: `yyyy-MM-ddTHH:mm:ssZ` as specified by the ISO 8601
            standard.
          format: date-time
          type: string
        lastUpdated:
          description: >
            The date when the resource connectivity status was last updated.
            This status should be updated every 15 minutes. If this status has
            not been updated, then it means that the service has lost network
            connectivity to the resource, from inside the Virtual Network.The
            date conforms to the following format: `yyyy-MM-ddTHH:mm:ssZ` as
            specified by the ISO 8601 standard.
          format: date-time
          type: string
        name:
          description: The hostname of the resource which the service depends on. This can
            be the database, storage or any other azure resource on which the
            service depends upon.
          minLength: 1
          type: string
        status:
          description: Resource Connectivity Status Type identifier.
          enum:
            - initializing
            - success
            - failure
          type: string
          x-ms-enum:
            modelAsString: true
            name: ConnectivityStatusType
      required:
        - name
        - status
        - lastUpdated
        - lastStatusChange
    NetworkStatusContract:
      description: Network Status details.
      properties:
        connectivityStatus:
          description: Gets the list of Connectivity Status to the Resources on which the
            service depends upon.
          items:
            $ref: "#/components/schemas/ConnectivityStatusContract"
          type: array
        dnsServers:
          description: Gets the list of DNS servers IPV4 addresses.
          items:
            type: string
          type: array
      required:
        - dnsServers
        - connectivityStatus
