openapi: 3.0.0
info:
  title: AutomationManagement
  version: 2015-10-31
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/automation/resource-manager/Microsoft.Automation/stable/2015-10-31/jobSchedule.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: automation-jobSchedule
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}/jobSchedules":
    get:
      description: Retrieve a list of job schedules.
      externalDocs:
        url: http://aka.ms/azureautomationsdk/jobscheduleoperations
      operationId: JobSchedule_ListByAutomationAccount
      parameters:
        - description: Name of an Azure Resource group.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._]+$
          examples:
            List all job schedules by automation account:
              value: rg
        - description: The name of the automation account.
          in: path
          name: automationAccountName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            List all job schedules by automation account:
              value: ContoseAutomationAccount
        - description: The filter to apply on the operation.
          in: query
          name: $filter
          required: false
          schema:
            type: string
        - description: Gets subscription credentials which uniquely identify Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            List all job schedules by automation account:
              value: subid
        - description: Client Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            List all job schedules by automation account:
              value: 2015-10-31
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JobScheduleListResult"
              examples:
                List all job schedules by automation account:
                  $ref: "#/components/examples/List_all_job_schedules_by_automation\
                    _account"
        default:
          description: Automation error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response of an operation failure
                properties:
                  code:
                    description: Error code
                    type: string
                  message:
                    description: Error message indicating why the operation failed.
                    type: string
                type: object
      tags:
        - JobSchedule
      x-ms-odata: "#/components/schemas/JobSchedule"
      x-ms-pageable:
        nextLinkName: nextLink
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}/jobSchedules/{jobScheduleId}":
    delete:
      description: Delete the job schedule identified by job schedule name.
      externalDocs:
        url: http://aka.ms/azureautomationsdk/jobscheduleoperations
      operationId: JobSchedule_Delete
      parameters:
        - description: Name of an Azure Resource group.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._]+$
          examples:
            Delete a job schedule:
              value: rg
        - description: The name of the automation account.
          in: path
          name: automationAccountName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Delete a job schedule:
              value: ContoseAutomationAccount
        - description: The job schedule name.
          in: path
          name: jobScheduleId
          required: true
          schema:
            type: string
            format: uuid
          examples:
            Delete a job schedule:
              value: 0fa462ba-3aa2-4138-83ca-9ebc3bc55cdc
        - description: Gets subscription credentials which uniquely identify Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Delete a job schedule:
              value: subid
        - description: Client Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Delete a job schedule:
              value: 2015-10-31
      responses:
        "200":
          description: OK
        default:
          description: Automation error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response of an operation failure
                properties:
                  code:
                    description: Error code
                    type: string
                  message:
                    description: Error message indicating why the operation failed.
                    type: string
                type: object
      tags:
        - JobSchedule
    get:
      description: Retrieve the job schedule identified by job schedule name.
      externalDocs:
        url: http://aka.ms/azureautomationsdk/jobscheduleoperations
      operationId: JobSchedule_Get
      parameters:
        - description: Name of an Azure Resource group.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._]+$
          examples:
            Get a job schedule:
              value: rg
        - description: The name of the automation account.
          in: path
          name: automationAccountName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Get a job schedule:
              value: ContoseAutomationAccount
        - description: The job schedule name.
          in: path
          name: jobScheduleId
          required: true
          schema:
            type: string
            format: uuid
          examples:
            Get a job schedule:
              value: 0fa462ba-3aa2-4138-83ca-9ebc3bc55cdc
        - description: Gets subscription credentials which uniquely identify Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Get a job schedule:
              value: subid
        - description: Client Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Get a job schedule:
              value: 2015-10-31
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JobSchedule"
              examples:
                Get a job schedule:
                  $ref: "#/components/examples/Get_a_job_schedule"
        default:
          description: Automation error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response of an operation failure
                properties:
                  code:
                    description: Error code
                    type: string
                  message:
                    description: Error message indicating why the operation failed.
                    type: string
                type: object
      tags:
        - JobSchedule
    put:
      description: Create a job schedule.
      externalDocs:
        url: http://aka.ms/azureautomationsdk/jobscheduleoperations
      operationId: JobSchedule_Create
      parameters:
        - description: Name of an Azure Resource group.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._]+$
          examples:
            Create a job schedule:
              value: rg
        - description: The name of the automation account.
          in: path
          name: automationAccountName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Create a job schedule:
              value: ContoseAutomationAccount
        - description: The job schedule name.
          in: path
          name: jobScheduleId
          required: true
          schema:
            type: string
            format: uuid
          examples:
            Create a job schedule:
              value: 0fa462ba-3aa2-4138-83ca-9ebc3bc55cdc
        - description: Gets subscription credentials which uniquely identify Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Create a job schedule:
              value: subid
        - description: Client Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Create a job schedule:
              value: 2015-10-31
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/JobScheduleCreateParameters"
        description: The parameters supplied to the create job schedule operation.
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JobSchedule"
              examples:
                Create a job schedule:
                  $ref: "#/components/examples/Create_a_job_schedule"
        default:
          description: Automation error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response of an operation failure
                properties:
                  code:
                    description: Error code
                    type: string
                  message:
                    description: Error message indicating why the operation failed.
                    type: string
                type: object
      tags:
        - JobSchedule
servers:
  - url: https://management.azure.com
components:
  examples:
    List_all_job_schedules_by_automation_account:
      value:
        value:
          - id: /subscriptions/subid/resourceGroups/rg/providers/Microsoft.Automation/automationAccounts/ContoseAutomationAccount/jobSchedules/2f4d8f35-ecd5-44ee-a019-2382fec58fb7
            properties:
              jobScheduleId: 2f4d8f35-ecd5-44ee-a019-2382fec58fb7
              runbook:
                name: TestRunbook
              schedule:
                name: JobScheduleforTestRunbook
          - id: /subscriptions/subid/resourceGroups/rg/providers/Microsoft.Automation/automationAccounts/ContoseAutomationAccount/jobSchedules/446f7a33-86ff-45a1-b71c-f998f701b443
            properties:
              jobScheduleId: 446f7a33-86ff-45a1-b71c-f998f701b443
              runbook:
                name: TestRunbook
              schedule:
                name: TestSchedule
          - id: /subscriptions/subid/resourceGroups/rg/providers/Microsoft.Automation/automationAccounts/ContoseAutomationAccount/jobSchedules/0fa462ba-3aa2-4138-83ca-9ebc3bc55cdc
            properties:
              jobScheduleId: 0fa462ba-3aa2-4138-83ca-9ebc3bc55cdc
              runbook:
                name: TestRunbook
              schedule:
                name: ScheduleNameGoesHere332204b5-debe-4348-a5c7-6357457189f2
    Get_a_job_schedule:
      value:
        id: /subscriptions/subid/resourceGroups/rg/providers/Microsoft.Automation/automationAccounts/ContoseAutomationAccount/jobSchedules/0fa462ba-3aa2-4138-83ca-9ebc3bc55cdc
        properties:
          jobScheduleId: 0fa462ba-3aa2-4138-83ca-9ebc3bc55cdc
          parameters:
            jobscheduletag01: jobschedulevalue01
            jobscheduletag02: jobschedulevalue02
          runbook:
            name: TestRunbook
          schedule:
            name: ScheduleNameGoesHere332204b5-debe-4348-a5c7-6357457189f2
    Create_a_job_schedule:
      value:
        id: /subscriptions/subid/resourceGroups/rg/providers/Microsoft.Automation/automationAccounts/ContoseAutomationAccount/jobSchedules/0fa462ba-3aa2-4138-83ca-9ebc3bc55cdc
        properties:
          jobScheduleId: 0fa462ba-3aa2-4138-83ca-9ebc3bc55cdc
          parameters:
            jobscheduletag01: jobschedulevalue01
            jobscheduletag02: jobschedulevalue02
          runbook:
            name: TestRunbook
          schedule:
            name: ScheduleNameGoesHere332204b5-debe-4348-a5c7-6357457189f2
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    JobSchedule:
      description: Definition of the job schedule.
      properties:
        id:
          description: Gets the id of the resource.
          readOnly: true
          type: string
        name:
          description: Gets the name of the variable.
          readOnly: true
          type: string
        properties:
          $ref: "#/components/schemas/JobScheduleProperties"
        type:
          description: Resource type
          readOnly: true
          type: string
    JobScheduleCreateParameters:
      description: The parameters supplied to the create job schedule operation.
      properties:
        properties:
          $ref: "#/components/schemas/JobScheduleCreateProperties"
      required:
        - properties
    JobScheduleCreateProperties:
      description: The parameters supplied to the create job schedule operation.
      properties:
        parameters:
          additionalProperties:
            type: string
          description: Gets or sets a list of job properties.
          type: object
        runOn:
          description: Gets or sets the hybrid worker group that the scheduled job should
            run on.
          type: string
        runbook:
          $ref: "#/components/schemas/RunbookAssociationProperty"
        schedule:
          $ref: "#/components/schemas/ScheduleAssociationProperty"
      required:
        - schedule
        - runbook
    JobScheduleListResult:
      description: The response model for the list job schedule operation.
      properties:
        nextLink:
          description: Gets or sets the next link.
          type: string
        value:
          description: Gets or sets a list of job schedules.
          items:
            $ref: "#/components/schemas/JobSchedule"
          type: array
    JobScheduleProperties:
      description: Definition of job schedule parameters.
      properties:
        jobScheduleId:
          description: Gets or sets the id of job schedule.
          type: string
        parameters:
          additionalProperties:
            type: string
          description: Gets or sets the parameters of the job schedule.
          type: object
        runOn:
          description: Gets or sets the hybrid worker group that the scheduled job should
            run on.
          type: string
        runbook:
          $ref: "#/components/schemas/RunbookAssociationProperty"
        schedule:
          $ref: "#/components/schemas/ScheduleAssociationProperty"
    RunbookAssociationProperty:
      description: The runbook property associated with the entity.
      properties:
        name:
          description: Gets or sets the name of the runbook.
          type: string
    ScheduleAssociationProperty:
      description: The schedule property associated with the entity.
      properties:
        name:
          description: Gets or sets the name of the Schedule.
          type: string
