openapi: 3.0.0
info:
  title: Common types
  version: "1.0"
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/common-types/resource-management/v1/types.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: common-types
  x-tags:
    - Azure
    - Microsoft
paths: {}
servers:
  - url: https://azure.local
components:
  parameters:
    ApiVersionParameter:
      description: The API version to use for this operation.
      in: query
      name: api-version
      required: true
      schema:
        type: string
        minLength: 1
    ResourceGroupNameParameter:
      description: The name of the resource group. The name is case insensitive.
      in: path
      name: resourceGroupName
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
        minLength: 1
        maxLength: 90
        pattern: ^[-\w\._\(\)]+$
    SubscriptionIdParameter:
      description: The ID of the target subscription.
      in: path
      name: subscriptionId
      required: true
      schema:
        type: string
        minLength: 1
  schemas:
    AzureEntityResource:
      allOf:
        - $ref: "#/components/schemas/Resource"
      description: The resource model definition for a Azure Resource Manager resource with
        an etag.
      properties:
        etag:
          description: Resource Etag.
          readOnly: true
          type: string
      x-ms-client-name: AzureEntityResource
    ErrorAdditionalInfo:
      description: The resource management error additional info.
      properties:
        info:
          description: The additional info.
          readOnly: true
          type: object
        type:
          description: The additional info type.
          readOnly: true
          type: string
    ErrorResponse:
      description: The resource management error response.
      properties:
        additionalInfo:
          description: The error additional info.
          items:
            $ref: "#/components/schemas/ErrorAdditionalInfo"
          readOnly: true
          type: array
        code:
          description: The error code.
          readOnly: true
          type: string
        details:
          description: The error details.
          items:
            $ref: "#/components/schemas/ErrorResponse"
          readOnly: true
          type: array
        message:
          description: The error message.
          readOnly: true
          type: string
        target:
          description: The error target.
          readOnly: true
          type: string
    Identity:
      description: Identity for the resource.
      properties:
        principalId:
          description: The principal ID of resource identity.
          readOnly: true
          type: string
        tenantId:
          description: The tenant ID of resource.
          readOnly: true
          type: string
        type:
          description: The identity type.
          enum:
            - SystemAssigned
          type: string
          x-ms-enum:
            modelAsString: false
            name: ResourceIdentityType
    Plan:
      description: Plan for the resource.
      properties:
        name:
          description: A user defined name of the 3rd Party Artifact that is being procured.
          type: string
        product:
          description: "The 3rd Party artifact that is being procured. E.g. NewRelic.
            Product maps to the OfferID specified for the artifact at the time
            of Data Market onboarding. "
          type: string
        promotionCode:
          description: A publisher provided promotion code as provisioned in Data Market
            for the said product/artifact.
          type: string
        publisher:
          description: The publisher of the 3rd Party Artifact that is being bought. E.g.
            NewRelic
          type: string
        version:
          description: The version of the desired product/artifact.
          type: string
      required:
        - name
        - publisher
        - product
    ProxyResource:
      allOf:
        - $ref: "#/components/schemas/Resource"
      description: The resource model definition for a ARM proxy resource. It will have
        everything other than required location and tags
    Resource:
      properties:
        id:
          description: Fully qualified resource Id for the resource. Ex -
            /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}
          readOnly: true
          type: string
        name:
          description: The name of the resource
          readOnly: true
          type: string
        type:
          description: The type of the resource. Ex- Microsoft.Compute/virtualMachines or
            Microsoft.Storage/storageAccounts.
          readOnly: true
          type: string
      x-ms-azure-resource: true
    ResourceModelWithAllowedPropertySet:
      description: The resource model definition containing the full set of allowed
        properties for a resource. Except properties bag, there cannot be a top
        level property outside of this set.
      properties:
        etag:
          description: "The etag field is *not* required. If it is provided in the response
            body, it must also be provided as a header per the normal etag
            convention.  Entity tags are used for comparing two or more entities
            from the same requested resource. HTTP/1.1 uses entity tags in the
            etag (section 14.19), If-Match (section 14.24), If-None-Match
            (section 14.26), and If-Range (section 14.27) header fields. "
          readOnly: true
          type: string
        id:
          description: Fully qualified resource Id for the resource. Ex -
            /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}
          readOnly: true
          type: string
          x-ms-mutability:
            - read
        identity:
          allOf:
            - $ref: "#/components/schemas/Identity"
        kind:
          description: Metadata used by portal/tooling/etc to render different UX
            experiences for resources of the same type; e.g. ApiApps are a kind
            of Microsoft.Web/sites type.  If supported, the resource provider
            must validate and persist this value.
          pattern: ^[-\w\._,\(\)]+$
          type: string
          x-ms-mutability:
            - read
            - create
        location:
          description: The geo-location where the resource lives
          type: string
          x-ms-mutability:
            - read
            - create
        managedBy:
          description: The  fully qualified resource ID of the resource that manages this
            resource. Indicates if this resource is managed by another azure
            resource. If this is present, complete mode deployment will not
            delete the resource if it is removed from the template since it is
            managed by another resource.
          type: string
          x-ms-mutability:
            - read
            - create
            - update
        name:
          description: The name of the resource
          readOnly: true
          type: string
        plan:
          allOf:
            - $ref: "#/components/schemas/Plan"
        sku:
          allOf:
            - $ref: "#/components/schemas/Sku"
        tags:
          additionalProperties:
            type: string
          description: Resource tags.
          type: object
          x-ms-mutability:
            - read
            - create
            - update
        type:
          description: The type of the resource. Ex- Microsoft.Compute/virtualMachines or
            Microsoft.Storage/storageAccounts..
          readOnly: true
          type: string
          x-ms-mutability:
            - read
      x-ms-azure-resource: true
    Sku:
      description: The resource model definition representing SKU
      properties:
        capacity:
          description: If the SKU supports scale out/in then the capacity integer should be
            included. If scale out/in is not possible for the resource this may
            be omitted.
          format: int32
          type: integer
        family:
          description: If the service has different generations of hardware, for the same
            SKU, then that can be captured here.
          type: string
        name:
          description: The name of the SKU. Ex - P3. It is typically a letter+number code
          type: string
        size:
          description: "The SKU size. When the name field is the combination of tier and
            some other value, this would be the standalone code. "
          type: string
        tier:
          description: This field is required to be implemented by the Resource Provider if
            the service has more than one tier, but is not required on a PUT.
          enum:
            - Free
            - Basic
            - Standard
            - Premium
          type: string
          x-ms-enum:
            modelAsString: false
            name: SkuTier
      required:
        - name
    TrackedResource:
      allOf:
        - $ref: "#/components/schemas/Resource"
      description: The resource model definition for a ARM tracked top level resource
      properties:
        location:
          description: The geo-location where the resource lives
          type: string
          x-ms-mutability:
            - read
            - create
        tags:
          additionalProperties:
            type: string
          description: Resource tags.
          type: object
          x-ms-mutability:
            - read
            - create
            - update
      required:
        - location
