openapi: 3.0.0
info:
  title: Azure Database Migration Service Resource Provider
  version: 2018-04-19
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/datamigration/resource-manager/Microsoft.DataMigration/stable/2018-04-19/definitions/MigrateSqlServerSqlDbSyncTask.json
      version: "2.0"
  x-preferred: false
  x-providerName: azure.com
  x-serviceName: datamigration-MigrateSqlServerSqlDbSyncTask
  x-tags:
    - Azure
    - Microsoft
paths: {}
servers:
  - url: https://azure.local
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    MigrateSqlServerSqlDbSyncTaskInput:
      allOf:
        - description: Base class for migration task input
          properties:
            sourceConnectionInfo:
              allOf:
                - description: Defines the connection properties of a server
                  discriminator:
                    propertyName: type
                  properties:
                    password:
                      description: Password credential.
                      type: string
                    type:
                      description: Type of connection info
                      type: string
                    userName:
                      description: User name
                      type: string
                  required:
                    - type
                  type: object
              description: Information for connecting to SQL database server
              properties:
                additionalSettings:
                  description: Additional connection settings
                  type: string
                authentication:
                  description: An enumeration of possible authentication types when
                    connecting
                  enum:
                    - None
                    - WindowsAuthentication
                    - SqlAuthentication
                    - ActiveDirectoryIntegrated
                    - ActiveDirectoryPassword
                  type: string
                  x-ms-enum:
                    modelAsString: true
                    name: AuthenticationType
                dataSource:
                  description: Data source in the format
                    Protocol:MachineName\SQLServerInstanceName,PortNumber
                  type: string
                encryptConnection:
                  default: true
                  description: Whether to encrypt the connection
                  type: boolean
                platform:
                  description: An enumeration of source platform types
                  enum:
                    - SqlOnPrem
                  type: string
                  x-ms-enum:
                    modelAsString: true
                    name: SqlSourcePlatform
                trustServerCertificate:
                  default: false
                  description: Whether to trust the server certificate
                  type: boolean
              required:
                - dataSource
              type: object
              x-ms-discriminator-value: SqlConnectionInfo
            targetConnectionInfo:
              allOf:
                - description: Defines the connection properties of a server
                  discriminator:
                    propertyName: type
                  properties:
                    password:
                      description: Password credential.
                      type: string
                    type:
                      description: Type of connection info
                      type: string
                    userName:
                      description: User name
                      type: string
                  required:
                    - type
                  type: object
              description: Information for connecting to SQL database server
              properties:
                additionalSettings:
                  description: Additional connection settings
                  type: string
                authentication:
                  description: An enumeration of possible authentication types when
                    connecting
                  enum:
                    - None
                    - WindowsAuthentication
                    - SqlAuthentication
                    - ActiveDirectoryIntegrated
                    - ActiveDirectoryPassword
                  type: string
                  x-ms-enum:
                    modelAsString: true
                    name: AuthenticationType
                dataSource:
                  description: Data source in the format
                    Protocol:MachineName\SQLServerInstanceName,PortNumber
                  type: string
                encryptConnection:
                  default: true
                  description: Whether to encrypt the connection
                  type: boolean
                platform:
                  description: An enumeration of source platform types
                  enum:
                    - SqlOnPrem
                  type: string
                  x-ms-enum:
                    modelAsString: true
                    name: SqlSourcePlatform
                trustServerCertificate:
                  default: false
                  description: Whether to trust the server certificate
                  type: boolean
              required:
                - dataSource
              type: object
              x-ms-discriminator-value: SqlConnectionInfo
          required:
            - sourceConnectionInfo
            - targetConnectionInfo
          type: object
      description: Input for the task that migrates on-prem SQL Server databases to Azure
        SQL Database for online migrations
      properties:
        selectedDatabases:
          description: Databases to migrate
          items:
            description: Database specific information for SQL to Azure SQL DB sync
              migration task inputs
            properties:
              id:
                description: Unique identifier for database
                type: string
              migrationSetting:
                additionalProperties:
                  type: string
                description: Migration settings which tune the migration behavior
                type: object
              name:
                description: Name of database
                type: string
              schemaName:
                description: Schema name to be migrated
                type: string
              sourceSetting:
                additionalProperties:
                  type: string
                description: Source settings to tune source endpoint migration behavior
                type: object
              tableMap:
                additionalProperties:
                  type: string
                description: Mapping of source to target tables
                type: object
              targetDatabaseName:
                description: Target database name
                type: string
              targetSetting:
                additionalProperties:
                  type: string
                description: Target settings to tune target endpoint migration behavior
                type: object
            type: object
          type: array
        validationOptions:
          description: Types of validations to run after the migration
          properties:
            enableDataIntegrityValidation:
              description: Allows to perform a checksum based data integrity validation
                between source and target for the selected database / tables .
              type: boolean
            enableQueryAnalysisValidation:
              description: Allows to perform a quick and intelligent query analysis by
                retrieving queries from the source database and executes them in
                the target. The result will have execution statistics for
                executions in source and target databases for the extracted
                queries.
              type: boolean
            enableSchemaValidation:
              description: Allows to compare the schema information between source and
                target.
              type: boolean
          type: object
      required:
        - selectedDatabases
      type: object
    MigrateSqlServerSqlDbSyncTaskOutput:
      description: Output for the task that migrates on-prem SQL Server databases to Azure
        SQL Database for online migrations
      discriminator:
        propertyName: resultType
      properties:
        id:
          description: Result identifier
          readOnly: true
          type: string
        resultType:
          description: Result type
          readOnly: true
          type: string
      type: object
    MigrateSqlServerSqlDbSyncTaskOutputDatabaseError:
      allOf:
        - $ref: "#/components/schemas/MigrateSqlServerSqlDbSyncTaskOutput"
      properties:
        errorMessage:
          description: Error message
          type: string
        events:
          description: List of error events.
          items:
            description: Database migration errors for online migration
            properties:
              eventText:
                description: Event text.
                readOnly: true
                type: string
              eventTypeString:
                description: Event type.
                readOnly: true
                type: string
              timestampString:
                description: String value of timestamp.
                readOnly: true
                type: string
            type: object
          type: array
      type: object
      x-ms-discriminator-value: DatabaseLevelErrorOutput
    MigrateSqlServerSqlDbSyncTaskOutputDatabaseLevel:
      allOf:
        - $ref: "#/components/schemas/MigrateSqlServerSqlDbSyncTaskOutput"
      properties:
        appliedChanges:
          description: Number of applied changes
          format: int64
          readOnly: true
          type: integer
        cdcDeleteCounter:
          description: Number of cdc deletes
          format: int64
          readOnly: true
          type: integer
        cdcInsertCounter:
          description: Number of cdc inserts
          format: int64
          readOnly: true
          type: integer
        cdcUpdateCounter:
          description: Number of cdc updates
          format: int64
          readOnly: true
          type: integer
        databaseName:
          description: Name of the database
          readOnly: true
          type: string
        endedOn:
          description: Migration end time
          format: date-time
          readOnly: true
          type: string
        fullLoadCompletedTables:
          description: Number of tables completed in full load
          format: int64
          readOnly: true
          type: integer
        fullLoadErroredTables:
          description: Number of tables errored in full load
          format: int64
          readOnly: true
          type: integer
        fullLoadLoadingTables:
          description: Number of tables loading in full load
          format: int64
          readOnly: true
          type: integer
        fullLoadQueuedTables:
          description: Number of tables queued in full load
          format: int64
          readOnly: true
          type: integer
        incomingChanges:
          description: Number of incoming changes
          format: int64
          readOnly: true
          type: integer
        initializationCompleted:
          description: Indicates if initial load (full load) has been completed
          readOnly: true
          type: boolean
        latency:
          description: CDC apply latency
          format: int64
          readOnly: true
          type: integer
        migrationState:
          description: Enum of the different state of database level online migration.
          enum:
            - UNDEFINED
            - CONFIGURING
            - INITIALIAZING
            - STARTING
            - RUNNING
            - READY_TO_COMPLETE
            - COMPLETING
            - COMPLETE
            - CANCELLING
            - CANCELLED
            - FAILED
          type: string
          x-ms-enum:
            modelAsString: true
            name: SyncDatabaseMigrationReportingState
        startedOn:
          description: Migration start time
          format: date-time
          readOnly: true
          type: string
      type: object
      x-ms-discriminator-value: DatabaseLevelOutput
    MigrateSqlServerSqlDbSyncTaskOutputError:
      allOf:
        - $ref: "#/components/schemas/MigrateSqlServerSqlDbSyncTaskOutput"
      properties:
        error:
          description: Exception object for all custom exceptions
          properties:
            actionableMessage:
              description: Actionable steps for this exception
              type: string
            filePath:
              description: The path to the file where exception occurred
              readOnly: true
              type: string
            hResult:
              description: Coded numerical value that is assigned to a specific exception
              readOnly: true
              type: integer
            lineNumber:
              description: The line number where exception occurred
              readOnly: true
              type: string
            message:
              description: Error message
              readOnly: true
              type: string
            stackTrace:
              description: Stack trace
              readOnly: true
              type: string
          type: object
      type: object
      x-ms-discriminator-value: ErrorOutput
    MigrateSqlServerSqlDbSyncTaskOutputMigrationLevel:
      allOf:
        - $ref: "#/components/schemas/MigrateSqlServerSqlDbSyncTaskOutput"
      properties:
        databaseCount:
          description: Count of databases
          readOnly: true
          type: integer
        endedOn:
          description: Migration end time
          format: date-time
          readOnly: true
          type: string
        sourceServer:
          description: Source server name
          readOnly: true
          type: string
        sourceServerVersion:
          description: Source server version
          readOnly: true
          type: string
        startedOn:
          description: Migration start time
          format: date-time
          readOnly: true
          type: string
        targetServer:
          description: Target server name
          readOnly: true
          type: string
        targetServerVersion:
          description: Target server version
          readOnly: true
          type: string
      type: object
      x-ms-discriminator-value: MigrationLevelOutput
    MigrateSqlServerSqlDbSyncTaskOutputTableLevel:
      allOf:
        - $ref: "#/components/schemas/MigrateSqlServerSqlDbSyncTaskOutput"
      properties:
        cdcDeleteCounter:
          description: Number of applied deletes
          format: int64
          readOnly: true
          type: integer
        cdcInsertCounter:
          description: Number of applied inserts
          format: int64
          readOnly: true
          type: integer
        cdcUpdateCounter:
          description: Number of applied updates
          format: int64
          readOnly: true
          type: integer
        dataErrorsCounter:
          description: Number of data errors occurred
          format: int64
          readOnly: true
          type: integer
        databaseName:
          description: Name of the database
          readOnly: true
          type: string
        fullLoadEndedOn:
          description: Full load end time
          format: date-time
          readOnly: true
          type: string
        fullLoadEstFinishTime:
          description: Estimate to finish full load
          format: date-time
          readOnly: true
          type: string
        fullLoadStartedOn:
          description: Full load start time
          format: date-time
          readOnly: true
          type: string
        fullLoadTotalRows:
          description: Number of rows applied in full load
          format: int64
          readOnly: true
          type: integer
        lastModifiedTime:
          description: Last modified time on target
          format: date-time
          readOnly: true
          type: string
        state:
          description: Enum of the different state of table level online migration.
          enum:
            - BEFORE_LOAD
            - FULL_LOAD
            - COMPLETED
            - CANCELED
            - ERROR
            - FAILED
          type: string
          x-ms-enum:
            modelAsString: true
            name: SyncTableMigrationState
        tableName:
          description: Name of the table
          readOnly: true
          type: string
        totalChangesApplied:
          description: Total number of applied changes
          format: int64
          readOnly: true
          type: integer
      type: object
      x-ms-discriminator-value: TableLevelOutput
