openapi: 3.0.0
info:
  description: The Admin Subscriptions Management Client.
  title: SubscriptionsManagementClient
  version: 2015-11-01
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/azsadmin/resource-manager/subscriptions/Microsoft.Subscriptions.Admin/preview/2015-11-01/DirectoryTenant.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: azsadmin-DirectoryTenant
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.Subscriptions.Admin/directoryTenants":
    get:
      description: Lists all the directory tenants under the current subscription and given
        resource group name.
      operationId: DirectoryTenants_List
      parameters:
        - description: Subscription credentials which uniquely identify Microsoft Azure
            subscription.The subscription ID forms part of the URI for every
            service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Lists all the directory tenants under the current subscription and given resource group name.:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
        - description: The resource group the resource is located under.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Lists all the directory tenants under the current subscription and given resource group name.:
              value: system.local
        - description: Client Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            default: 2015-11-01
          examples:
            Lists all the directory tenants under the current subscription and given resource group name.:
              value: 2015-11-01
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DirectoryTenantList"
              examples:
                Lists all the directory tenants under the current subscription and given resource group name.:
                  $ref: "#/components/examples/Lists_all_the_directory_tenants_unde\
                    r_the_current_subscription_and_given_resource_group_name."
      tags:
        - DirectoryTenants
      x-ms-pageable:
        nextLinkName: nextLink
  "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.Subscriptions.Admin/directoryTenants/{tenant}":
    delete:
      description: Delete a directory tenant under a resource group.
      operationId: DirectoryTenants_Delete
      parameters:
        - description: Subscription credentials which uniquely identify Microsoft Azure
            subscription.The subscription ID forms part of the URI for every
            service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Delete a directory tenant under a resource group.:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
        - description: The resource group the resource is located under.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Delete a directory tenant under a resource group.:
              value: system.local
        - $ref: "#/components/parameters/DirectoryTenantParameter"
        - description: Client Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            default: 2015-11-01
          examples:
            Delete a directory tenant under a resource group.:
              value: 2015-11-01
      responses:
        "200":
          description: OK
        "204":
          description: No Content
      tags:
        - DirectoryTenants
    get:
      description: Get a directory tenant by name.
      operationId: DirectoryTenants_Get
      parameters:
        - description: Subscription credentials which uniquely identify Microsoft Azure
            subscription.The subscription ID forms part of the URI for every
            service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Get a directory tenant by name.:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
        - description: The resource group the resource is located under.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Get a directory tenant by name.:
              value: system.local
        - $ref: "#/components/parameters/DirectoryTenantParameter"
        - description: Client Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            default: 2015-11-01
          examples:
            Get a directory tenant by name.:
              value: 2015-11-01
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DirectoryTenant"
              examples:
                Get a directory tenant by name.:
                  $ref: "#/components/examples/Get_a_directory_tenant_by_name."
      tags:
        - DirectoryTenants
    put:
      description: Create or updates a directory tenant.
      operationId: DirectoryTenants_CreateOrUpdate
      parameters:
        - description: Subscription credentials which uniquely identify Microsoft Azure
            subscription.The subscription ID forms part of the URI for every
            service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Create or updates a directory tenant.:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
        - description: The resource group the resource is located under.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Create or updates a directory tenant.:
              value: system.local
        - $ref: "#/components/parameters/DirectoryTenantParameter"
        - description: Client Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            default: 2015-11-01
          examples:
            Create or updates a directory tenant.:
              value: 2015-11-01
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DirectoryTenant"
        description: New directory tenant properties.
        required: true
        x-ms-parameter-location: method
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DirectoryTenant"
              examples:
                Create or updates a directory tenant.:
                  $ref: "#/components/examples/Create_or_updates_a_directory_tenant."
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DirectoryTenant"
              examples:
                Create or updates a directory tenant.:
                  $ref: "#/components/examples/Create_or_updates_a_directory_tenant."
      tags:
        - DirectoryTenants
servers:
  - url: https://adminmanagement.local.azurestack.external
components:
  examples:
    Lists_all_the_directory_tenants_under_the_current_subscription_and_given_resource_group_name.:
      value:
        value:
          - id: /subscriptions/8ab2551d-41e5-489b-9273-1cdf1cbc7dc6/resourceGroups/System.local/providers/Microsoft.Subscriptions.Admin/directoryTenants/azurestackci07.onmicrosoft.com
            location: local
            name: azurestackci07.onmicrosoft.com
            properties:
              tenantId: 2b3697e6-a7a2-4cdd-a3d4-f4ef6505cd4f
            type: Microsoft.Subscriptions.Admin/directoryTenants
    Get_a_directory_tenant_by_name.:
      value:
        id: /subscriptions/8ab2551d-41e5-489b-9273-1cdf1cbc7dc6/resourceGroups/System.local/providers/Microsoft.Subscriptions.Admin/directoryTenants/azurestackci07.onmicrosoft.com
        location: local
        name: azurestackci07.onmicrosoft.com
        properties:
          tenantId: 2b3697e6-a7a2-4cdd-a3d4-f4ef6505cd4f
        type: Microsoft.Subscriptions.Admin/directoryTenants
    Create_or_updates_a_directory_tenant.:
      value:
        id: /subscriptions/8158498d-27b1-4ccf-9aa1-de0f925731e6/resourceGroups/System.local/providers/Microsoft.Subscriptions.Admin/directoryTenants/azurestackci05.onmicrosoft.in
        location: local
        name: azurestackci05.onmicrosoft.in
        properties:
          tenantId: eb90516e-65d7-4bf6-8537-8322e9172832
        type: Microsoft.Subscriptions.Admin/directoryTenants
  parameters:
    DirectoryTenantParameter:
      description: Directory tenant name.
      in: path
      name: tenant
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
      examples:
        Delete a directory tenant under a resource group.:
          value: azurestackci07.onmicrosoft.com
        Get a directory tenant by name.:
          value: azurestackci07.onmicrosoft.com
        Create or updates a directory tenant.:
          value: azurestackci05.onmicrosoft.in
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    DirectoryTenant:
      allOf:
        - description: Base Resource Object
          properties:
            id:
              description: URI of the resource.
              readOnly: true
              type: string
            location:
              description: Location of the resource
              type: string
            name:
              description: Name of the resource.
              readOnly: true
              type: string
            tags:
              additionalProperties:
                type: string
              description: List of key-value pairs.
              readOnly: true
              type: object
            type:
              description: Type of resource.
              readOnly: true
              type: string
          type: object
          x-ms-azure-resource: true
      description: Directory tenant.
      properties:
        properties:
          $ref: "#/components/schemas/DirectoryTenantProperties"
      type: object
    DirectoryTenantList:
      description: List of directory tenants.
      properties:
        nextLink:
          description: Continuation token
          type: string
        value:
          description: List of directory tenants.
          items:
            $ref: "#/components/schemas/DirectoryTenant"
          type: array
      type: object
    DirectoryTenantProperties:
      description: Directory tenant.
      properties:
        tenantId:
          description: Tenant unique identifier.
          type: string
      type: object
