openapi: 3.0.0
info:
  description: File containing commonly referenced parameters.
  title: Common Referenced Parameters File
  version: 2017-08-30
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/cognitiveservices/data-plane/Common/Parameters.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: cognitiveservices-Parameters
  x-tags:
    - Azure
    - Microsoft
paths: {}
servers:
  - url: https://azure.local
components:
  parameters:
    GlobalEndpoint:
      description: 'Supported Cognitive Services endpoints (protocol and hostname, for
        example: "https://westus.api.cognitive.microsoft.com",
        "https://api.cognitive.microsoft.com").'
      in: path
      name: Endpoint
      required: true
      x-ms-parameter-location: client
      x-ms-skip-url-encoding: true
      schema:
        type: string
        default: https://api.cognitive.microsoft.com
  schemas:
    ImageUrl:
      properties:
        url:
          description: Publicly reachable URL of an image
          type: string
      required:
        - url
      type: object
