openapi: 3.0.0
info:
  description: API spec for Microsoft.Security (Azure Security Center) resource provider
  title: Security Center
  version: 2017-08-01-preview
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/security/resource-manager/Microsoft.Security/preview/2017-08-01-preview/autoProvisioningSettings.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: security-autoProvisioningSettings
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  "/subscriptions/{subscriptionId}/providers/Microsoft.Security/autoProvisioningSettings":
    get:
      description: Exposes the auto provisioning settings of the subscriptions
      operationId: AutoProvisioningSettings_List
      parameters:
        - description: API version for the operation
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Get auto provisioning settings for subscription:
              value: 2017-08-01-preview
        - description: Azure subscription ID
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
            pattern: ^[0-9A-Fa-f]{8}-([0-9A-Fa-f]{4}-){3}[0-9A-Fa-f]{12}$
          examples:
            Get auto provisioning settings for subscription:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AutoProvisioningSettingList"
              examples:
                Get auto provisioning settings for subscription:
                  $ref: "#/components/examples/Get_auto_provisioning_settings_for_s\
                    ubscription"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response structure.
                properties:
                  error:
                    description: Error details.
                    properties:
                      code:
                        description: An identifier for the error. Codes are invariant and
                          are intended to be consumed programmatically.
                        readOnly: true
                        type: string
                      message:
                        description: A message describing the error, intended to be
                          suitable for display in a user interface.
                        readOnly: true
                        type: string
                    type: object
                    x-ms-external: true
                type: object
                x-ms-external: true
      tags:
        - AutoProvisioningSettings
      x-ms-pageable:
        nextLinkName: nextLink
  "/subscriptions/{subscriptionId}/providers/Microsoft.Security/autoProvisioningSettings/{settingName}":
    get:
      description: Details of a specific setting
      operationId: AutoProvisioningSettings_Get
      parameters:
        - description: API version for the operation
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Get an auto provisioning setting for subscription:
              value: 2017-08-01-preview
        - description: Azure subscription ID
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
            pattern: ^[0-9A-Fa-f]{8}-([0-9A-Fa-f]{4}-){3}[0-9A-Fa-f]{12}$
          examples:
            Get an auto provisioning setting for subscription:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
        - $ref: "#/components/parameters/AutoProvisioningSettingName"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AutoProvisioningSetting"
              examples:
                Get an auto provisioning setting for subscription:
                  $ref: "#/components/examples/Get_an_auto_provisioning_setting_for\
                    _subscription"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response structure.
                properties:
                  error:
                    description: Error details.
                    properties:
                      code:
                        description: An identifier for the error. Codes are invariant and
                          are intended to be consumed programmatically.
                        readOnly: true
                        type: string
                      message:
                        description: A message describing the error, intended to be
                          suitable for display in a user interface.
                        readOnly: true
                        type: string
                    type: object
                    x-ms-external: true
                type: object
                x-ms-external: true
      tags:
        - AutoProvisioningSettings
    put:
      description: Details of a specific setting
      operationId: AutoProvisioningSettings_Create
      parameters:
        - description: API version for the operation
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Create auto provisioning settings for subscription:
              value: 2017-08-01-preview
        - description: Azure subscription ID
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
            pattern: ^[0-9A-Fa-f]{8}-([0-9A-Fa-f]{4}-){3}[0-9A-Fa-f]{12}$
          examples:
            Create auto provisioning settings for subscription:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
        - $ref: "#/components/parameters/AutoProvisioningSettingName"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AutoProvisioningSetting"
        description: Auto provisioning setting key
        required: true
        x-ms-parameter-location: method
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AutoProvisioningSetting"
              examples:
                Create auto provisioning settings for subscription:
                  $ref: "#/components/examples/Create_auto_provisioning_settings_fo\
                    r_subscription"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response structure.
                properties:
                  error:
                    description: Error details.
                    properties:
                      code:
                        description: An identifier for the error. Codes are invariant and
                          are intended to be consumed programmatically.
                        readOnly: true
                        type: string
                      message:
                        description: A message describing the error, intended to be
                          suitable for display in a user interface.
                        readOnly: true
                        type: string
                    type: object
                    x-ms-external: true
                type: object
                x-ms-external: true
      tags:
        - AutoProvisioningSettings
servers:
  - url: https://management.azure.com
components:
  examples:
    Get_auto_provisioning_settings_for_subscription:
      value:
        value:
          - id: /subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23/providers/Microsoft.Security/autoProvisioningSettings/default
            name: default
            properties:
              autoProvision: On
            type: Microsoft.Security/autoProvisioningSettings
    Get_an_auto_provisioning_setting_for_subscription:
      value:
        id: /subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23/providers/Microsoft.Security/autoProvisioningSettings/default
        name: default
        properties:
          autoProvision: On
        type: Microsoft.Security/autoProvisioningSettings
    Create_auto_provisioning_settings_for_subscription:
      value:
        id: /subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23/providers/Microsoft.Security/autoProvisioningSettings/default
        name: default
        properties:
          autoProvision: On
        type: Microsoft.Security/autoProvisioningSettings
  parameters:
    AutoProvisioningSettingName:
      description: Auto provisioning setting key
      in: path
      name: settingName
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
      examples:
        Get an auto provisioning setting for subscription:
          value: default
        Create auto provisioning settings for subscription:
          value: default
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    AutoProvisioningSetting:
      allOf:
        - description: Describes an Azure resource.
          properties:
            id:
              description: Resource Id
              readOnly: true
              type: string
            name:
              description: Resource name
              readOnly: true
              type: string
            type:
              description: Resource type
              readOnly: true
              type: string
          type: object
          x-ms-azure-resource: true
      description: Auto provisioning setting
      properties:
        properties:
          $ref: "#/components/schemas/AutoProvisioningSettingProperties"
      type: object
    AutoProvisioningSettingList:
      description: List of all the auto provisioning settings response
      properties:
        nextLink:
          description: The URI to fetch the next page.
          readOnly: true
          type: string
        value:
          description: List of all the auto provisioning settings
          items:
            $ref: "#/components/schemas/AutoProvisioningSetting"
          type: array
      type: object
    AutoProvisioningSettingProperties:
      description: describes properties of an auto provisioning setting
      properties:
        autoProvision:
          description: Describes what kind of security agent provisioning action to take
          enum:
            - On
            - Off
          type: string
          x-ms-enum:
            modelAsString: true
            name: autoProvision
            values:
              - description: Install missing security agent on VMs automatically
                value: On
              - description: Do not install security agent on the VMs automatically
                value: Off
      required:
        - autoProvision
      type: object
