openapi: 3.0.0
info:
  description: Personalizer Service is an Azure Cognitive Service that makes it easy to
    target content and experiences without complex pre-analysis or cleanup of
    past data. Given a context and featurized content, the Personalizer Service
    returns your content in a ranked list. As rewards are sent in response to
    the ranked list, the reinforcement learning algorithm will improve the model
    and improve performance of future rank calls.
  title: Personalizer Client
  version: v1.0
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/cognitiveservices/data-plane/Personalizer/preview/v1.0/Personalizer.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: cognitiveservices-Personalizer
  x-tags:
    - Azure
    - Microsoft
security:
  - apim_key: []
tags:
  - description: Manages event operations.
    name: Events
  - description: Manages ranking operations.
    name: Rank
paths:
  "/events/{eventId}/activate":
    post:
      operationId: Events_Activate
      parameters:
        - description: The event ID this activation applies to.
          in: path
          name: eventId
          required: true
          schema:
            type: string
            maxLength: 256
          examples:
            Successful Events_Activate request:
              value: id
      responses:
        "204":
          description: Success
        default:
          description: Invalid reward request.
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      summary: Report that the specified event was actually displayed to the user and a
        reward should be expected for it.
      tags:
        - Events
  "/events/{eventId}/reward":
    post:
      operationId: Events_Reward
      parameters:
        - description: The event id this reward applies to.
          in: path
          name: eventId
          required: true
          schema:
            type: string
            maxLength: 256
          examples:
            Successful Events_Reward request:
              value: id
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RewardRequest"
        description: The reward should be a floating point number.
        required: true
      responses:
        "204":
          description: Success
        default:
          description: Invalid reward request.
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      summary: Report reward to allocate to the top ranked action for the specified
        event.
      tags:
        - Events
  /rank:
    post:
      operationId: Rank
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RankRequest"
        description: A Personalizer request.
        required: true
      responses:
        "201":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RankResponse"
              examples:
                Successful Rank request:
                  $ref: "#/components/examples/Successful_Rank_request"
        default:
          description: Invalid rank request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      summary: A Personalizer rank request.
      tags:
        - Rank
servers:
  - url: https://azure.local/personalizer/v1.0
  - url: "{Endpoint}/personalizer/v1.0"
    variables:
      Endpoint:
        description: Supported Cognitive Services endpoint.
        maxLength: 1024
        x-ms-parameter-location: client
        x-ms-skip-url-encoding: true
        default: ""
components:
  examples:
    Successful_Rank_request:
      value:
        eventId: 75269AD0-BFEE-4598-8196-C57383D38E10
        ranking:
          - id: EntertainmentArticle
            probability: 0.8
          - id: SportsArticle
            probability: 0
          - id: NewsArticle
            probability: 0.2
        rewardActionId: EntertainmentArticle
  parameters:
    Endpoint:
      description: Supported Cognitive Services endpoint.
      in: path
      name: Endpoint
      required: true
      x-ms-parameter-location: client
      x-ms-skip-url-encoding: true
      schema:
        type: string
        maxLength: 1024
  securitySchemes:
    apim_key:
      in: header
      name: Ocp-Apim-Subscription-Key
      type: apiKey
  schemas:
    ErrorResponse:
      description: Used to return an error to the client
      properties:
        error:
          $ref: "#/components/schemas/PersonalizerError"
      required:
        - error
      type: object
    InternalError:
      description: An object containing more specific information than the parent object
        about the error.
      properties:
        code:
          description: Detailed error code.
          type: string
        innererror:
          $ref: "#/components/schemas/InternalError"
      type: object
    PersonalizerError:
      description: The error object.
      properties:
        code:
          description: High level error code.
          enum:
            - BadRequest
            - ResourceNotFound
            - InternalServerError
          type: string
          x-ms-enum:
            modelAsString: true
            name: ErrorCode
            values:
              - description: Request could not be understood by the server.
                value: BadRequest
              - description: Requested resource does not exist on the server.
                value: ResourceNotFound
              - description: A generic error has occurred on the server.
                value: InternalServerError
        details:
          description: An array of details about specific errors that led to this reported
            error.
          items:
            $ref: "#/components/schemas/PersonalizerError"
          type: array
        innerError:
          $ref: "#/components/schemas/InternalError"
        message:
          description: A message explaining the error reported by the service.
          type: string
        target:
          description: Error source element.
          type: string
      required:
        - code
        - message
      type: object
    RankRequest:
      description: Request a set of actions to be ranked by the Personalizer service.
      properties:
        actions:
          description: "The set of actions the Personalizer service can pick from.\r

            The set should not contain more than 50 actions.\r

            The order of the actions does not affect the rank result
            but the order\r

            should match the sequence your application would have
            used to display them."
          items:
            $ref: "#/components/schemas/RankableAction"
          type: array
        contextFeatures:
          description: "Features of the context used for Personalizer as a\r

            dictionary of dictionaries. This depends on the
            application, and\r

            typically includes features about the current user,
            their\r

            device, profile information, data about time and date,
            etc."
          items:
            type: object
          type: array
        deferActivation:
          default: false
          description: "Send false if the user will see the rank results, therefore\r

            Personalizer will expect a Reward call, otherwise it
            will assign the default\r

            Reward to the event. Send true if it is possible the
            user will not see the\r

            rank results, because the page is rendering later, or
            the Rank results may be\r

            overridden by code further downstream."
          type: boolean
        eventId:
          description: "Optionally pass an eventId that uniquely identifies this Rank
            event. \r

            If null, the service generates a unique eventId. The
            eventId will be used for\r

            associating this request with its reward, as well as
            seeding the pseudo-random\r

            generator when making a Personalizer call."
          maxLength: 256
          type: string
        excludedActions:
          description: The set of action ids to exclude from ranking.
          items:
            type: string
          type: array
      required:
        - actions
      type: object
    RankResponse:
      description: A resulting ordered list of actions that result from a rank request.
      properties:
        eventId:
          description: The eventId for the round trip from request to response.
          maxLength: 256
          readOnly: true
          type: string
        ranking:
          description: The calculated ranking for the current request.
          items:
            $ref: "#/components/schemas/RankedAction"
          readOnly: true
          type: array
        rewardActionId:
          description: "The action chosen by the Personalizer service. This is the action
            for which to report the reward. This might not be the \r

            first found in 'ranking' if an action in the request in
            first position was part of the excluded ids."
          maxLength: 256
          readOnly: true
          type: string
      type: object
    RankableAction:
      description: An action with it's associated features used for ranking.
      properties:
        features:
          description: List of dictionaries containing features.
          items:
            type: object
          type: array
        id:
          description: Id of the action.
          maxLength: 256
          type: string
      required:
        - id
        - features
      type: object
    RankedAction:
      description: A ranked action with its resulting probability.
      properties:
        id:
          description: Id of the action
          maxLength: 256
          readOnly: true
          type: string
        probability:
          description: Probability of the action
          format: float
          maximum: 1
          minimum: 0
          readOnly: true
          type: number
      type: object
    RewardRequest:
      description: Reward given to a rank response.
      properties:
        value:
          description: Reward to be assigned to an action. Value should be between -1 and 1
            inclusive.
          format: float
          type: number
      required:
        - value
      type: object
