openapi: 3.0.0
info:
  description: API spec for Microsoft.Security (Azure Security Center) resource provider
  title: Security Center
  version: 2015-06-01-preview
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/security/resource-manager/Microsoft.Security/preview/2015-06-01-preview/discoveredSecuritySolutions.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: security-discoveredSecuritySolutions
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  "/subscriptions/{subscriptionId}/providers/Microsoft.Security/discoveredSecuritySolutions":
    get:
      description: Gets a list of discovered Security Solutions for the subscription.
      operationId: DiscoveredSecuritySolutions_List
      parameters:
        - description: Azure subscription ID
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
            pattern: ^[0-9A-Fa-f]{8}-([0-9A-Fa-f]{4}-){3}[0-9A-Fa-f]{12}$
          examples:
            Get discovered security solutions:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
        - description: API version for the operation
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Get discovered security solutions:
              value: 2015-06-01-preview
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DiscoveredSecuritySolutionList"
              examples:
                Get discovered security solutions:
                  $ref: "#/components/examples/Get_discovered_security_solutions"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response structure.
                properties:
                  error:
                    description: Error details.
                    properties:
                      code:
                        description: An identifier for the error. Codes are invariant and
                          are intended to be consumed programmatically.
                        readOnly: true
                        type: string
                      message:
                        description: A message describing the error, intended to be
                          suitable for display in a user interface.
                        readOnly: true
                        type: string
                    type: object
                    x-ms-external: true
                type: object
                x-ms-external: true
      tags:
        - DiscoveredSecuritySolutions
      x-ms-pageable:
        nextLinkName: nextLink
  "/subscriptions/{subscriptionId}/providers/Microsoft.Security/locations/{ascLocation}/discoveredSecuritySolutions":
    get:
      description: Gets a list of discovered Security Solutions for the subscription and
        location.
      operationId: DiscoveredSecuritySolutions_ListByHomeRegion
      parameters:
        - description: Azure subscription ID
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
            pattern: ^[0-9A-Fa-f]{8}-([0-9A-Fa-f]{4}-){3}[0-9A-Fa-f]{12}$
          examples:
            Get discovered security solutions from a security data location:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
        - description: The location where ASC stores the data of the subscription. can be
            retrieved from Get locations
          in: path
          name: ascLocation
          required: true
          x-ms-parameter-location: client
          schema:
            type: string
          examples:
            Get discovered security solutions from a security data location:
              value: centralus
        - description: API version for the operation
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Get discovered security solutions from a security data location:
              value: 2015-06-01-preview
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DiscoveredSecuritySolutionList"
              examples:
                Get discovered security solutions from a security data location:
                  $ref: "#/components/examples/Get_discovered_security_solutions_fr\
                    om_a_security_data_location"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response structure.
                properties:
                  error:
                    description: Error details.
                    properties:
                      code:
                        description: An identifier for the error. Codes are invariant and
                          are intended to be consumed programmatically.
                        readOnly: true
                        type: string
                      message:
                        description: A message describing the error, intended to be
                          suitable for display in a user interface.
                        readOnly: true
                        type: string
                    type: object
                    x-ms-external: true
                type: object
                x-ms-external: true
      tags:
        - DiscoveredSecuritySolutions
      x-ms-pageable:
        nextLinkName: nextLink
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Security/locations/{ascLocation}/discoveredSecuritySolutions/{discoveredSecuritySolutionName}":
    get:
      description: Gets a specific discovered Security Solution.
      operationId: DiscoveredSecuritySolutions_Get
      parameters:
        - description: Azure subscription ID
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
            pattern: ^[0-9A-Fa-f]{8}-([0-9A-Fa-f]{4}-){3}[0-9A-Fa-f]{12}$
          examples:
            Get discovered security solution from a security data location:
              value: 20ff7fc3-e762-44dd-bd96-b71116dcdc23
        - description: The name of the resource group within the user's subscription. The
            name is case insensitive.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._\(\)]+$
          examples:
            Get discovered security solution from a security data location:
              value: myRg2
        - description: The location where ASC stores the data of the subscription. can be
            retrieved from Get locations
          in: path
          name: ascLocation
          required: true
          x-ms-parameter-location: client
          schema:
            type: string
          examples:
            Get discovered security solution from a security data location:
              value: centralus
        - $ref: "#/components/parameters/DiscoveredSecuritySolutionName"
        - description: API version for the operation
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Get discovered security solution from a security data location:
              value: 2015-06-01-preview
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DiscoveredSecuritySolution"
              examples:
                Get discovered security solution from a security data location:
                  $ref: "#/components/examples/Get_discovered_security_solution_fro\
                    m_a_security_data_location"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response structure.
                properties:
                  error:
                    description: Error details.
                    properties:
                      code:
                        description: An identifier for the error. Codes are invariant and
                          are intended to be consumed programmatically.
                        readOnly: true
                        type: string
                      message:
                        description: A message describing the error, intended to be
                          suitable for display in a user interface.
                        readOnly: true
                        type: string
                    type: object
                    x-ms-external: true
                type: object
                x-ms-external: true
      tags:
        - DiscoveredSecuritySolutions
servers:
  - url: https://management.azure.com
components:
  examples:
    Get_discovered_security_solutions:
      value:
        value:
          - id: /subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23/resourceGroups/myRg1/providers/Microsoft.Security/locations/centralus/discoveredSecuritySolutions/CP
            location: eastus
            name: CP
            properties:
              offer: cisco-asav
              publisher: cisco
              securityFamily: Ngfw
              sku: asav-azure-byol
            type: Microsoft.Security/locations/discoveredSecuritySolutions
          - id: /subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23/resourceGroups/myRg2/providers/Microsoft.Security/locations/centralus/discoveredSecuritySolutions/paloalto7
            location: eastus2
            name: paloalto7
            properties:
              offer: vmseries1
              publisher: paloaltonetworks
              securityFamily: Ngfw
              sku: byol
            type: Microsoft.Security/locations/discoveredSecuritySolutions
    Get_discovered_security_solutions_from_a_security_data_location:
      value:
        value:
          - id: /subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23/resourceGroups/myRg1/providers/Microsoft.Security/locations/centralus/discoveredSecuritySolutions/CP
            location: eastus
            name: CP
            properties:
              offer: cisco-asav
              publisher: cisco
              securityFamily: Ngfw
              sku: asav-azure-byol
            type: Microsoft.Security/locations/discoveredSecuritySolutions
          - id: /subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23/resourceGroups/myRg2/providers/Microsoft.Security/locations/centralus/discoveredSecuritySolutions/paloalto7
            location: eastus2
            name: paloalto7
            properties:
              offer: vmseries1
              publisher: paloaltonetworks
              securityFamily: Ngfw
              sku: byol
            type: Microsoft.Security/locations/discoveredSecuritySolutions
    Get_discovered_security_solution_from_a_security_data_location:
      value:
        id: /subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23/resourceGroups/myRg2/providers/Microsoft.Security/locations/centralus/discoveredSecuritySolutions/paloalto7
        location: eastus2
        name: paloalto7
        properties:
          offer: vmseries1
          publisher: paloaltonetworks
          securityFamily: Ngfw
          sku: byol
        type: Microsoft.Security/locations/discoveredSecuritySolutions
  parameters:
    DiscoveredSecuritySolutionName:
      description: Name of a discovered security solution.
      in: path
      name: discoveredSecuritySolutionName
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
      examples:
        Get discovered security solution from a security data location:
          value: paloalto7
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    DiscoveredSecuritySolution:
      allOf:
        - description: Describes an Azure resource.
          properties:
            id:
              description: Resource Id
              readOnly: true
              type: string
            name:
              description: Resource name
              readOnly: true
              type: string
            type:
              description: Resource type
              readOnly: true
              type: string
          type: object
          x-ms-azure-resource: true
        - description: Describes an Azure resource with location
          properties:
            location:
              description: Location where the resource is stored
              readOnly: true
              type: string
          type: object
      properties:
        properties:
          $ref: "#/components/schemas/DiscoveredSecuritySolutionProperties"
      required:
        - properties
      type: object
    DiscoveredSecuritySolutionList:
      properties:
        nextLink:
          description: The URI to fetch the next page.
          readOnly: true
          type: string
        value:
          items:
            $ref: "#/components/schemas/DiscoveredSecuritySolution"
          type: array
      type: object
    DiscoveredSecuritySolutionProperties:
      properties:
        offer:
          description: The security solutions' image offer
          type: string
        publisher:
          description: The security solutions' image publisher
          type: string
        securityFamily:
          description: The security family of the discovered solution
          enum:
            - Waf
            - Ngfw
            - SaasWaf
            - Va
          type: string
          x-ms-enum:
            modelAsString: true
            name: securityFamily
            values:
              - value: Waf
              - value: Ngfw
              - value: SaasWaf
              - value: Va
        sku:
          description: The security solutions' image sku
          type: string
      required:
        - securityFamily
        - offer
        - publisher
        - sku
      type: object
