openapi: 3.0.0
info:
  description: Describes the schema of the Azure EventHub events published to Azure Event
    Grid. This corresponds to the Data property of an EventGridEvent.
  title: Schema of Azure EventHub events published to Azure Event Grid
  version: 2018-01-01
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/eventgrid/data-plane/Microsoft.EventHub/stable/2018-01-01/EventHub.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: eventgrid-EventHub
  x-tags:
    - Azure
    - Microsoft
paths: {}
servers:
  - url: https://azure.local
components:
  schemas:
    EventHubCaptureFileCreatedEventData:
      description: Schema of the Data property of an EventGridEvent for an
        Microsoft.EventHub.CaptureFileCreated event.
      properties:
        eventCount:
          description: The number of events in the file.
          type: integer
        fileType:
          description: The file type of the capture file.
          type: string
        fileurl:
          description: The path to the capture file.
          type: string
        firstEnqueueTime:
          description: The first time from the queue.
          format: date-time
          type: string
        firstSequenceNumber:
          description: The smallest sequence number from the queue.
          type: integer
        lastEnqueueTime:
          description: The last time from the queue.
          format: date-time
          type: string
        lastSequenceNumber:
          description: The last sequence number from the queue.
          type: integer
        partitionId:
          description: The shard ID.
          type: string
        sizeInBytes:
          description: The file size.
          type: integer
      type: object
