openapi: 3.0.0
info:
  description: API to Add/Remove/List Guest Diagnostics Settings Association for Azure
    Resources
  title: Guest Diagnostic Settings Association
  version: 2018-06-01-preview
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-ms-code-generation-settings:
    name: MonitorManagementClient
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/monitor/resource-manager/Microsoft.Insights/preview/2018-06-01-preview/guestDiagnosticSettingsAssociation_API.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: monitor-guestDiagnosticSettingsAssociation_API
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  "/subscriptions/{subscriptionId}/providers/microsoft.insights/guestDiagnosticSettingsAssociations":
    get:
      description: Get a list of all guest diagnostic settings association in a
        subscription.
      operationId: GuestDiagnosticsSettingsAssociation_List
      parameters:
        - $ref: "#/components/parameters/SubscriptionIdParameter"
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: The request succeeded.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GuestDiagnosticSettingsAssociationList"
        default:
          description: An error occurred and the list of guest diagnostic settings
            association could not be retrieved.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      x-ms-pageable: {}
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/microsoft.insights/guestDiagnosticSettingsAssociations":
    get:
      description: Get a list of all guest diagnostic settings association in a resource
        group.
      operationId: GuestDiagnosticsSettingsAssociation_ListByResourceGroup
      parameters:
        - $ref: "#/components/parameters/ResourceGroupNameParameter"
        - $ref: "#/components/parameters/SubscriptionIdParameter"
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: The request succeeded.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GuestDiagnosticSettingsAssociationList"
        default:
          description: An error occurred and the list of guest diagnostic settings
            association could not be retrieved.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      x-ms-pageable: {}
  "/{resourceUri}/providers/microsoft.insights/guestDiagnosticSettingsAssociation/{associationName}":
    delete:
      description: Delete guest diagnostics association settings.
      operationId: GuestDiagnosticsSettingsAssociation_Delete
      parameters:
        - description: The fully qualified ID of the resource, including the resource name
            and resource type.
          in: path
          name: resourceUri
          required: true
          x-ms-skip-url-encoding: true
          schema:
            type: string
          examples:
            Create or update an guest diagnostic settings association:
              value: subscriptions/8498f01b-8064-4e37-856e-318f3c6c685f/resourceGroups/healthsystem/providers/Microsoft.Compute/virtualMachines/eastussojai
        - $ref: "#/components/parameters/DiagnosticSettingsAssociationNameParameter"
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: The diagnostic settings association was successfully deleted.
        "204":
          description: The diagnostic settings association does not exist. It may have
            already been deleted.
        default:
          description: An error occurred and the diagnostic settings association could not
            be deleted.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      tags:
        - GuestDiagnosticsSettingsAssociation
    get:
      description: Gets guest diagnostics association settings.
      operationId: GuestDiagnosticsSettingsAssociation_Get
      parameters:
        - description: The fully qualified ID of the resource, including the resource name
            and resource type.
          in: path
          name: resourceUri
          required: true
          x-ms-skip-url-encoding: true
          schema:
            type: string
          examples:
            Create or update an guest diagnostic settings association:
              value: subscriptions/8498f01b-8064-4e37-856e-318f3c6c685f/resourceGroups/healthsystem/providers/Microsoft.Compute/virtualMachines/eastussojai
        - $ref: "#/components/parameters/DiagnosticSettingsAssociationNameParameter"
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: The request succeeded.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GuestDiagnosticSettingsAssociationResou\
                  rce"
              examples:
                Create or update an guest diagnostic settings association:
                  $ref: "#/components/examples/Create_or_update_an_guest_diagnostic\
                    _settings_association"
        default:
          description: An error occurred and the diagnostic settings association could not
            be retrieved.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      tags:
        - GuestDiagnosticsSettingsAssociation
    patch:
      description: Updates an existing guestDiagnosticsSettingsAssociation Resource. To
        update other fields use the CreateOrUpdate method
      operationId: GuestDiagnosticsSettingsAssociation_Update
      parameters:
        - description: The fully qualified ID of the resource, including the resource name
            and resource type.
          in: path
          name: resourceUri
          required: true
          x-ms-skip-url-encoding: true
          schema:
            type: string
          examples:
            Update a service diagnostic setting:
              value: subscriptions/8498f01b-8064-4e37-856e-318f3c6c685f/resourceGroups/healthsystem/providers/Microsoft.Compute/virtualMachines/eastussojai
        - $ref: "#/components/parameters/ApiVersionParameter"
        - $ref: "#/components/parameters/DiagnosticSettingsAssociationNameParameter"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GuestDiagnosticSettingsAssociationResourc\
                ePatch"
        description: Parameters supplied to the operation.
        required: true
      responses:
        "200":
          description: An existing guest diagnostics setting resource was successfully
            updated.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GuestDiagnosticSettingsAssociationResou\
                  rce"
              examples:
                Update a service diagnostic setting:
                  $ref: "#/components/examples/Update_a_service_diagnostic_setting"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    put:
      description: Creates or updates guest diagnostics settings association.
      operationId: GuestDiagnosticsSettingsAssociation_CreateOrUpdate
      parameters:
        - description: The fully qualified ID of the resource, including the resource name
            and resource type.
          in: path
          name: resourceUri
          required: true
          x-ms-skip-url-encoding: true
          schema:
            type: string
          examples:
            Create or update an guest diagnostic settings association:
              value: subscriptions/8498f01b-8064-4e37-856e-318f3c6c685f/resourceGroups/healthsystem/providers/Microsoft.Compute/virtualMachines/eastussojai
        - $ref: "#/components/parameters/DiagnosticSettingsAssociationNameParameter"
        - $ref: "#/components/parameters/ApiVersionParameter"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GuestDiagnosticSettingsAssociationResource"
        description: The diagnostic settings association to create or update.
        required: true
      responses:
        "200":
          description: An existing guest diagnostic settings association was successfully
            updated.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GuestDiagnosticSettingsAssociationResou\
                  rce"
              examples:
                Create or update an guest diagnostic settings association:
                  $ref: "#/components/examples/Create_or_update_an_guest_diagnostic\
                    _settings_association"
        "201":
          description: A new guest diagnostic settings association was successfully created.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GuestDiagnosticSettingsAssociationResou\
                  rce"
              examples:
                Create or update an guest diagnostic settings association:
                  $ref: "#/components/examples/Create_or_update_an_guest_diagnostic\
                    _settings_association"
        default:
          description: An error occurred and the guest diagnostic settings association
            could not be created or updated.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      tags:
        - GuestDiagnosticsSettingsAssociation
servers:
  - url: https://management.azure.com
components:
  examples:
    Create_or_update_an_guest_diagnostic_settings_association:
      value:
        id: /subscriptions/8498f01b-8064-4e37-856e-318f3c6c685f/resourceGroups/healthsystem/providers/Microsoft.Compute/virtualMachines/eastussojai/providers/microsoft.insights/guestDiagnosticSettingsAssociation/healthSystemMachineConfigAssociation
        location: Global
        name: healthSystemMachineConfigAssociation
        properties:
          guestDiagnosticSettingsName: /subscriptions/187f412d-1758-44d9-b052-169e2564721d/resourceGroups/Default-Association-ResourceGroup/providers/providers/microsoft.insights/guestDiagnosticSettings/vmSettingForSecurity
        tags: {}
        type: Microsoft.Insights/GuestDiagnosticSettingsAssociation
    Update_a_service_diagnostic_setting:
      value:
        id: /subscriptions/8498f01b-8064-4e37-856e-318f3c6c685f/resourceGroups/healthsystem/providers/Microsoft.Compute/virtualMachines/eastussojai/providers/microsoft.insights/guestDiagnosticSettingsAssociation/healthSystemMachineConfigAssociation
        location: Global
        name: healthSystemMachineConfigAssociation
        properties:
          guestDiagnosticSettingsName: /subscriptions/187f412d-1758-44d9-b052-169e2564721d/resourceGroups/Default-Association-ResourceGroup/providers/providers/microsoft.insights/guestDiagnosticSettings/vmSettingForSecurity
        type: Microsoft.Insights/GuestDiagnosticSettingsAssociation
  parameters:
    ApiVersionParameter:
      description: Client Api Version.
      in: query
      name: api-version
      required: true
      schema:
        type: string
      examples:
        Create or update an guest diagnostic settings association:
          value: 2018-06-01-preview
        Update a service diagnostic setting:
          value: 2018-06-01-preview
    DiagnosticSettingsAssociationNameParameter:
      description: The name of the diagnostic settings association.
      in: path
      name: associationName
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
      examples:
        Create or update an guest diagnostic settings association:
          value: healthSystemMachineConfigAssociation
        Update a service diagnostic setting:
          value: healthSystemMachineConfigAssociation
    ResourceGroupNameParameter:
      description: The name of the resource group.
      in: path
      name: resourceGroupName
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
    SubscriptionIdParameter:
      description: The Azure subscription Id.
      in: path
      name: subscriptionId
      required: true
      schema:
        type: string
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    ErrorResponse:
      description: Describes the format of Error response.
      properties:
        code:
          description: Error code
          type: string
        message:
          description: Error message indicating why the operation failed.
          type: string
      type: object
    GuestDiagnosticSettingsAssociation:
      description: A guest diagnostic settings association.
      properties:
        guestDiagnosticSettingsName:
          description: The guest diagnostic settings name.
          type: string
      required:
        - guestDiagnosticSettingsName
    GuestDiagnosticSettingsAssociationList:
      description: A list of guest diagnostic settings association.
      properties:
        nextLink:
          description: Provides the link to retrieve the next set of elements.
          type: string
        value:
          description: The list of guest diagnostic settings association.
          items:
            $ref: "#/components/schemas/GuestDiagnosticSettingsAssociationResource"
          type: array
    GuestDiagnosticSettingsAssociationResource:
      allOf:
        - $ref: "#/components/schemas/Resource"
      description: Virtual machine guest diagnostic settings resource.
      properties:
        properties:
          $ref: "#/components/schemas/GuestDiagnosticSettingsAssociation"
      required:
        - properties
      type: object
    GuestDiagnosticSettingsAssociationResourcePatch:
      description: Guest diagnostic setting resource for patch operations
      properties:
        properties:
          $ref: "#/components/schemas/GuestDiagnosticSettingsAssociation"
        tags:
          additionalProperties:
            type: string
          description: Resource tags
    Resource:
      description: An azure resource object
      properties:
        id:
          description: Azure resource Id
          readOnly: true
          type: string
        location:
          description: Resource location
          type: string
          x-ms-mutability:
            - create
            - read
        name:
          description: Azure resource name
          readOnly: true
          type: string
        tags:
          additionalProperties:
            type: string
          description: Resource tags
        type:
          description: Azure resource type
          readOnly: true
          type: string
      required:
        - location
      x-ms-azure-resource: true
