openapi: 3.0.0
info:
  description: Azure Application Insights client for selecting pricing plans and options.
  title: ApplicationInsightsManagementClient
  version: 2015-05-01
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/applicationinsights/resource-manager/Microsoft.Insights/stable/2015-05-01/componentFeaturesAndPricing_API.json
      version: "2.0"
  x-preferred: false
  x-providerName: azure.com
  x-serviceName: applicationinsights-componentFeaturesAndPricing_API
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Insights/components/{resourceName}/currentbillingfeatures":
    get:
      description: Returns current billing features for an Application Insights component.
      operationId: ComponentCurrentBillingFeatures_Get
      parameters:
        - description: The name of the resource group. The name is case insensitive.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._\(\)]+$
          examples:
            ComponentCurrentBillingFeaturesGet:
              value: my-resource-group
        - description: The API version to use for this operation.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            minLength: 1
          examples:
            ComponentCurrentBillingFeaturesGet:
              value: 2015-05-01
        - description: The ID of the target subscription.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
            minLength: 1
          examples:
            ComponentCurrentBillingFeaturesGet:
              value: subid
        - $ref: "#/components/parameters/ResourceNameParameter"
      responses:
        "200":
          description: An Application Insights component billing features definition.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApplicationInsightsComponentBillingFeat\
                  ures"
              examples:
                ComponentCurrentBillingFeaturesGet:
                  $ref: "#/components/examples/ComponentCurrentBillingFeaturesGet"
    put:
      description: Update current billing features for an Application Insights component.
      operationId: ComponentCurrentBillingFeatures_Update
      parameters:
        - description: The name of the resource group. The name is case insensitive.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._\(\)]+$
          examples:
            ComponentCurrentBillingFeaturesUpdate:
              value: my-resource-group
        - description: The API version to use for this operation.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            minLength: 1
          examples:
            ComponentCurrentBillingFeaturesUpdate:
              value: 2015-05-01
        - description: The ID of the target subscription.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
            minLength: 1
          examples:
            ComponentCurrentBillingFeaturesUpdate:
              value: subid
        - $ref: "#/components/parameters/ResourceNameParameter"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ApplicationInsightsComponentBillingFeatur\
                es"
        description: Properties that need to be specified to update billing features for an
          Application Insights component.
        required: true
      responses:
        "200":
          description: Successful request when updating billing features for an Application
            Insights component. The updated current billing features are
            returned.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApplicationInsightsComponentBillingFeat\
                  ures"
              examples:
                ComponentCurrentBillingFeaturesUpdate:
                  $ref: "#/components/examples/ComponentCurrentBillingFeaturesUpdate"
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Insights/components/{resourceName}/featurecapabilities":
    get:
      description: Returns feature capabilities of the application insights component.
      operationId: ComponentFeatureCapabilities_Get
      parameters:
        - description: The name of the resource group. The name is case insensitive.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._\(\)]+$
          examples:
            ComponentCurrentBillingFeaturesGet:
              value: my-resource-group
        - description: The API version to use for this operation.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            minLength: 1
          examples:
            ComponentCurrentBillingFeaturesGet:
              value: 2015-05-01
        - description: The ID of the target subscription.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
            minLength: 1
          examples:
            ComponentCurrentBillingFeaturesGet:
              value: subid
        - $ref: "#/components/parameters/ResourceNameParameter"
      responses:
        "200":
          description: An Application Insights component feature capabilities definition.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApplicationInsightsComponentFeatureCapa\
                  bilities"
              examples:
                ComponentCurrentBillingFeaturesGet:
                  $ref: "#/components/examples/ComponentCurrentBillingFeaturesGet"
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Insights/components/{resourceName}/getavailablebillingfeatures":
    get:
      description: Returns all available features of the application insights component.
      operationId: ComponentAvailableFeatures_Get
      parameters:
        - description: The name of the resource group. The name is case insensitive.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._\(\)]+$
          examples:
            ComponentCurrentBillingFeaturesGet:
              value: my-resource-group
        - description: The API version to use for this operation.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            minLength: 1
          examples:
            ComponentCurrentBillingFeaturesGet:
              value: 2015-05-01
        - description: The ID of the target subscription.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
            minLength: 1
          examples:
            ComponentCurrentBillingFeaturesGet:
              value: subid
        - $ref: "#/components/parameters/ResourceNameParameter"
      responses:
        "200":
          description: An Application Insights component available features definition.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApplicationInsightsComponentAvailableFe\
                  atures"
              examples:
                ComponentCurrentBillingFeaturesGet:
                  $ref: "#/components/examples/ComponentCurrentBillingFeaturesGet"
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Insights/components/{resourceName}/quotastatus":
    get:
      description: Returns daily data volume cap (quota) status for an Application Insights
        component.
      operationId: ComponentQuotaStatus_Get
      parameters:
        - description: The name of the resource group. The name is case insensitive.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._\(\)]+$
          examples:
            ComponentCurrentBillingFeaturesGet:
              value: my-resource-group
        - description: The API version to use for this operation.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            minLength: 1
          examples:
            ComponentCurrentBillingFeaturesGet:
              value: 2015-05-01
        - description: The ID of the target subscription.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
            minLength: 1
          examples:
            ComponentCurrentBillingFeaturesGet:
              value: subid
        - $ref: "#/components/parameters/ResourceNameParameter"
      responses:
        "200":
          description: An Application Insights component daily data volume cap status
            definition.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApplicationInsightsComponentQuotaStatus"
              examples:
                ComponentCurrentBillingFeaturesGet:
                  $ref: "#/components/examples/ComponentCurrentBillingFeaturesGet"
servers:
  - url: https://management.azure.com
components:
  examples:
    ComponentCurrentBillingFeaturesGet:
      value:
        AppId: 887f4bfd-b5fd-40d7-9fc3-123456789abc
        ExpirationTime: 2017-08-10T05:00:00
        ShouldBeThrottled: true
    ComponentCurrentBillingFeaturesUpdate:
      value:
        CurrentBillingFeatures:
          - Basic
          - Application Insights Enterprise
        DataVolumeCap:
          Cap: 100
          MaxHistoryCap: 500
          ResetTime: 16
          StopSendNotificationWhenHitCap: true
          StopSendNotificationWhenHitThreshold: false
          WarningThreshold: 90
  parameters:
    ResourceNameParameter:
      description: The name of the Application Insights component resource.
      in: path
      name: resourceName
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
      examples:
        ComponentCurrentBillingFeaturesGet:
          value: my-component
        ComponentCurrentBillingFeaturesUpdate:
          value: my-component
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    ApplicationInsightsComponentAvailableFeatures:
      description: An Application Insights component available features.
      properties:
        Result:
          description: A list of Application Insights component feature.
          items:
            $ref: "#/components/schemas/ApplicationInsightsComponentFeature"
          readOnly: true
          type: array
      type: object
    ApplicationInsightsComponentBillingFeatures:
      description: An Application Insights component billing features
      properties:
        CurrentBillingFeatures:
          description: Current enabled pricing plan. When the component is in the
            Enterprise plan, this will list both 'Basic' and 'Application
            Insights Enterprise'.
          items:
            type: string
          type: array
        DataVolumeCap:
          $ref: "#/components/schemas/ApplicationInsightsComponentDataVolumeCap"
      type: object
    ApplicationInsightsComponentDataVolumeCap:
      description: An Application Insights component daily data volume cap
      properties:
        Cap:
          description: Daily data volume cap in GB.
          type: number
        MaxHistoryCap:
          description: Maximum daily data volume cap that the user can set for this
            component.
          readOnly: true
          type: number
        ResetTime:
          description: Daily data volume cap UTC reset hour.
          readOnly: true
          type: integer
        StopSendNotificationWhenHitCap:
          description: Do not send a notification email when the daily data volume cap is
            met.
          type: boolean
        StopSendNotificationWhenHitThreshold:
          description: Reserved, not used for now.
          type: boolean
        WarningThreshold:
          description: Reserved, not used for now.
          type: integer
      type: object
    ApplicationInsightsComponentFeature:
      description: An Application Insights component daily data volume cap status
      properties:
        Capabilities:
          description: A list of Application Insights component feature capability.
          items:
            $ref: "#/components/schemas/ApplicationInsightsComponentFeatureCapabili\
              ty"
          readOnly: true
          type: array
        FeatureName:
          description: The pricing feature name.
          readOnly: true
          type: string
        IsHidden:
          description: Reserved, not used now.
          readOnly: true
          type: boolean
        IsMainFeature:
          description: Whether can apply addon feature on to it.
          readOnly: true
          type: boolean
        MeterId:
          description: The meter id used for the feature.
          readOnly: true
          type: string
        MeterRateFrequency:
          description: The meter rate for the feature's meter.
          readOnly: true
          type: string
        ResouceId:
          description: Reserved, not used now.
          readOnly: true
          type: string
        SupportedAddonFeatures:
          description: The add on features on main feature.
          readOnly: true
          type: string
        Title:
          description: Display name of the feature.
          readOnly: true
          type: string
      type: object
    ApplicationInsightsComponentFeatureCapabilities:
      description: An Application Insights component feature capabilities
      properties:
        AnalyticsIntegration:
          description: Reserved, not used now.
          readOnly: true
          type: boolean
        ApiAccessLevel:
          description: Reserved, not used now.
          readOnly: true
          type: string
        ApplicationMap:
          description: Reserved, not used now.
          readOnly: true
          type: boolean
        BurstThrottlePolicy:
          description: Reserved, not used now.
          readOnly: true
          type: string
        DailyCap:
          description: Daily data volume cap in GB.
          readOnly: true
          type: number
        DailyCapResetTime:
          description: Daily data volume cap UTC reset hour.
          readOnly: true
          type: number
        LiveStreamMetrics:
          description: Reserved, not used now.
          readOnly: true
          type: boolean
        MetadataClass:
          description: Reserved, not used now.
          readOnly: true
          type: string
        MultipleStepWebTest:
          description: Whether allow to use multiple steps web test feature.
          readOnly: true
          type: boolean
        OpenSchema:
          description: Reserved, not used now.
          readOnly: true
          type: boolean
        PowerBIIntegration:
          description: Reserved, not used now.
          readOnly: true
          type: boolean
        ProactiveDetection:
          description: Reserved, not used now.
          readOnly: true
          type: boolean
        SupportExportData:
          description: Whether allow to use continuous export feature.
          readOnly: true
          type: boolean
        ThrottleRate:
          description: Reserved, not used now.
          readOnly: true
          type: number
        TrackingType:
          description: The application insights component used tracking type.
          readOnly: true
          type: string
        WorkItemIntegration:
          description: Whether allow to use work item integration feature.
          readOnly: true
          type: boolean
      type: object
    ApplicationInsightsComponentFeatureCapability:
      description: An Application Insights component feature capability
      properties:
        Description:
          description: The description of the capability.
          readOnly: true
          type: string
        MeterId:
          description: The meter used for the capability.
          readOnly: true
          type: string
        MeterRateFrequency:
          description: The meter rate of the meter.
          readOnly: true
          type: string
        Name:
          description: The name of the capability.
          readOnly: true
          type: string
        Unit:
          description: The unit of the capability.
          readOnly: true
          type: string
        Value:
          description: The value of the capability.
          readOnly: true
          type: string
      type: object
    ApplicationInsightsComponentQuotaStatus:
      description: An Application Insights component daily data volume cap status
      properties:
        AppId:
          description: The Application ID for the Application Insights component.
          readOnly: true
          type: string
        ExpirationTime:
          description: Date and time when the daily data volume cap will be reset, and data
            ingestion will resume.
          readOnly: true
          type: string
        ShouldBeThrottled:
          description: The daily data volume cap is met, and data ingestion will be stopped.
          readOnly: true
          type: boolean
      type: object
