openapi: 3.0.0
info:
  title: AzureStack Azure Bridge Client
  version: 2017-06-01
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/azurestack/resource-manager/Microsoft.AzureStack/stable/2017-06-01/CustomerSubscription.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: azurestack-CustomerSubscription
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.AzureStack/registrations/{registrationName}/customerSubscriptions":
    get:
      description: Returns a list of products.
      operationId: CustomerSubscriptions_List
      parameters:
        - description: Subscription credentials that uniquely identify Microsoft Azure
            subscription. The subscription ID forms part of the URI for every
            service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Returns a list of products.:
              value: dd8597b4-8739-4467-8b10-f8679f62bfbf
        - description: Name of the resource group.
          in: path
          name: resourceGroup
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Returns a list of products.:
              value: azurestack
        - description: Name of the Azure Stack registration.
          in: path
          name: registrationName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Returns a list of products.:
              value: testregistration
        - description: Client API Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            default: 2017-06-01
          examples:
            Returns a list of products.:
              value: 2017-06-01
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerSubscriptionList"
              examples:
                Returns a list of products.:
                  $ref: "#/components/examples/Returns_a_list_of_products."
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response indicates that the service is not able to
                  process the incoming request. The reason is provided in the
                  error message.
                properties:
                  error:
                    description: The details of the error.
                    properties:
                      code:
                        description: Error code.
                        readOnly: true
                        type: string
                      message:
                        description: Error message indicating why the operation failed.
                        readOnly: true
                        type: string
                      target:
                        description: The target of the particular error.
                        readOnly: true
                        type: string
                type: object
      tags:
        - CustomerSubscription
      x-ms-pageable:
        nextLinkName: nextLink
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.AzureStack/registrations/{registrationName}/customerSubscriptions/{customerSubscriptionName}":
    delete:
      description: Deletes a customer subscription under a registration.
      operationId: CustomerSubscriptions_Delete
      parameters:
        - description: Subscription credentials that uniquely identify Microsoft Azure
            subscription. The subscription ID forms part of the URI for every
            service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Deletes a customer subscription under a registration.:
              value: dd8597b4-8739-4467-8b10-f8679f62bfbf
        - description: Name of the resource group.
          in: path
          name: resourceGroup
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Deletes a customer subscription under a registration.:
              value: azurestack
        - description: Name of the Azure Stack registration.
          in: path
          name: registrationName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Deletes a customer subscription under a registration.:
              value: testregistration
        - $ref: "#/components/parameters/CustomerSubscriptionNameParameter"
        - description: Client API Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            default: 2017-06-01
          examples:
            Deletes a customer subscription under a registration.:
              value: 2017-06-01
      responses:
        "200":
          description: OK
        "204":
          description: NO CONTENT
      tags:
        - CustomerSubscription
    get:
      description: Returns the specified product.
      operationId: CustomerSubscriptions_Get
      parameters:
        - description: Subscription credentials that uniquely identify Microsoft Azure
            subscription. The subscription ID forms part of the URI for every
            service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Returns the specified product.:
              value: dd8597b4-8739-4467-8b10-f8679f62bfbf
        - description: Name of the resource group.
          in: path
          name: resourceGroup
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Returns the specified product.:
              value: azurestack
        - description: Name of the Azure Stack registration.
          in: path
          name: registrationName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Returns the specified product.:
              value: testregistration
        - $ref: "#/components/parameters/CustomerSubscriptionNameParameter"
        - description: Client API Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            default: 2017-06-01
          examples:
            Returns the specified product.:
              value: 2017-06-01
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerSubscription"
              examples:
                Returns the specified product.:
                  $ref: "#/components/examples/Returns_the_specified_product."
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response indicates that the service is not able to
                  process the incoming request. The reason is provided in the
                  error message.
                properties:
                  error:
                    description: The details of the error.
                    properties:
                      code:
                        description: Error code.
                        readOnly: true
                        type: string
                      message:
                        description: Error message indicating why the operation failed.
                        readOnly: true
                        type: string
                      target:
                        description: The target of the particular error.
                        readOnly: true
                        type: string
                type: object
      tags:
        - CustomerSubscription
    put:
      description: Creates a new customer subscription under a registration.
      operationId: CustomerSubscriptions_Create
      parameters:
        - description: Subscription credentials that uniquely identify Microsoft Azure
            subscription. The subscription ID forms part of the URI for every
            service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Creates a new customer subscription under a registration.:
              value: dd8597b4-8739-4467-8b10-f8679f62bfbf
        - description: Name of the resource group.
          in: path
          name: resourceGroup
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Creates a new customer subscription under a registration.:
              value: azurestack
        - description: Name of the Azure Stack registration.
          in: path
          name: registrationName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Creates a new customer subscription under a registration.:
              value: testregistration
        - $ref: "#/components/parameters/CustomerSubscriptionNameParameter"
        - description: Client API Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
            default: 2017-06-01
          examples:
            Creates a new customer subscription under a registration.:
              value: 2017-06-01
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CustomerSubscription"
        description: Parameters use to create a customer subscription.
        required: true
        x-ms-parameter-location: method
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerSubscription"
              examples:
                Creates a new customer subscription under a registration.:
                  $ref: "#/components/examples/Creates_a_new_customer_subscription_\
                    under_a_registration."
      tags:
        - CustomerSubscription
servers:
  - url: https://management.azure.com
components:
  examples:
    Returns_a_list_of_products.:
      value:
        value:
          - id: /subscriptions/dd8597b4-8739-4467-8b10-f8679f62bfbf/resourceGroups/azurestack/providers/Microsoft.AzureStack/registrations/testregistration/customerSubscriptions/E09A4E93-29A7-4EBA-A6D4-76202383F07F
            name: testregistration/E09A4E93-29A7-4EBA-A6D4-76202383F07F
            properties:
              tenantId: dbab3982-796f-4d03-9908-044c08aef8a2
            type: Microsoft.AzureStack/registrations/customerSubscriptions
    Returns_the_specified_product.:
      value:
        id: /subscriptions/dd8597b4-8739-4467-8b10-f8679f62bfbf/resourceGroups/azurestack/providers/Microsoft.AzureStack/registrations/testregistration/customerSubscriptions/E09A4E93-29A7-4EBA-A6D4-76202383F07F
        name: testregistration/E09A4E93-29A7-4EBA-A6D4-76202383F07F
        properties:
          tenantId: dbab3982-796f-4d03-9908-044c08aef8a2
        type: Microsoft.AzureStack/registrations/customerSubscriptions
    Creates_a_new_customer_subscription_under_a_registration.:
      value:
        id: ""
        name: ""
        properties:
          tenantId: dbab3982-796f-4d03-9908-044c08aef8a2
        type: ""
  parameters:
    CustomerSubscriptionNameParameter:
      description: Name of the product.
      in: path
      name: customerSubscriptionName
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
      examples:
        Deletes a customer subscription under a registration.:
          value: E09A4E93-29A7-4EBA-A6D4-76202383F07F
        Returns the specified product.:
          value: E09A4E93-29A7-4EBA-A6D4-76202383F07F
        Creates a new customer subscription under a registration.:
          value: E09A4E93-29A7-4EBA-A6D4-76202383F07F
  securitySchemes:
    azure_auth:
      description: Authorization uses an Azure Active Directory OAuth2 flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    CustomerSubscription:
      allOf:
        - description: Base resource object.
          properties:
            etag:
              description: The entity tag used for optimistic concurrency when modifying
                the resource.
              type: string
            id:
              description: ID of the resource.
              readOnly: true
              type: string
            name:
              description: Name of the resource.
              readOnly: true
              type: string
            type:
              description: Type of Resource.
              readOnly: true
              type: string
          type: object
          x-ms-azure-resource: true
      description: Customer subscription.
      properties:
        properties:
          $ref: "#/components/schemas/CustomerSubscriptionProperties"
      type: object
    CustomerSubscriptionList:
      description: Pageable list of customer subscriptions.
      properties:
        nextLink:
          description: URI to the next page.
          type: string
        value:
          description: List of customer subscriptions.
          items:
            $ref: "#/components/schemas/CustomerSubscription"
          type: array
      type: object
    CustomerSubscriptionProperties:
      description: Customer subscription properties.
      properties:
        tenantId:
          description: Tenant Id.
          type: string
      type: object
