openapi: 3.0.0
info:
  description: Provides create, read, update, and delete functionality for Azure SQL
    Database server firewall rules.
  title: Azure SQL Database server firewall rules
  version: 2014-04-01
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/sql/resource-manager/Microsoft.Sql/stable/2014-04-01/firewallRules.json
      version: "2.0"
  x-preferred: false
  x-providerName: azure.com
  x-serviceName: sql-firewallRules
  x-tags:
    - Azure
    - Microsoft
paths:
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}/firewallRules":
    get:
      description: Returns a list of firewall rules.
      operationId: FirewallRules_ListByServer
      parameters:
        - description: The API version to use for the request.
          in: query
          name: api-version
          required: true
          x-ms-parameter-location: client
          schema:
            type: string
          examples:
            List Firewall Rules:
              value: 2014-04-01
        - description: The subscription ID that identifies an Azure subscription.
          in: path
          name: subscriptionId
          required: true
          x-ms-parameter-location: client
          schema:
            type: string
          examples:
            List Firewall Rules:
              value: 00000000-1111-2222-3333-444444444444
        - description: The name of the resource group that contains the resource. You can
            obtain this value from the Azure Resource Manager API or the portal.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            List Firewall Rules:
              value: firewallrulecrudtest-12
        - $ref: "#/components/parameters/ServerNameParameter"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FirewallRuleListResult"
              examples:
                List Firewall Rules:
                  $ref: "#/components/examples/List_Firewall_Rules"
      tags:
        - FirewallRules
      x-ms-pageable: {}
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}/firewallRules/{firewallRuleName}":
    delete:
      description: Deletes a firewall rule.
      operationId: FirewallRules_Delete
      parameters:
        - description: The API version to use for the request.
          in: query
          name: api-version
          required: true
          x-ms-parameter-location: client
          schema:
            type: string
          examples:
            Delete a firewall rule:
              value: 2014-04-01
        - description: The subscription ID that identifies an Azure subscription.
          in: path
          name: subscriptionId
          required: true
          x-ms-parameter-location: client
          schema:
            type: string
          examples:
            Delete a firewall rule:
              value: 00000000-1111-2222-3333-444444444444
        - description: The name of the resource group that contains the resource. You can
            obtain this value from the Azure Resource Manager API or the portal.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Delete a firewall rule:
              value: firewallrulecrudtest-9886
        - $ref: "#/components/parameters/ServerNameParameter"
        - description: The name of the firewall rule.
          in: path
          name: firewallRuleName
          required: true
          schema:
            type: string
          examples:
            Delete a firewall rule:
              value: firewallrulecrudtest-7011
      responses:
        "200":
          description: OK
        "204":
          description: NoContent
      tags:
        - FirewallRules
    get:
      description: Gets a firewall rule.
      operationId: FirewallRules_Get
      parameters:
        - description: The API version to use for the request.
          in: query
          name: api-version
          required: true
          x-ms-parameter-location: client
          schema:
            type: string
          examples:
            Get Firewall Rule:
              value: 2014-04-01
        - description: The subscription ID that identifies an Azure subscription.
          in: path
          name: subscriptionId
          required: true
          x-ms-parameter-location: client
          schema:
            type: string
          examples:
            Get Firewall Rule:
              value: 00000000-1111-2222-3333-444444444444
        - description: The name of the resource group that contains the resource. You can
            obtain this value from the Azure Resource Manager API or the portal.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Get Firewall Rule:
              value: firewallrulecrudtest-12
        - $ref: "#/components/parameters/ServerNameParameter"
        - description: The name of the firewall rule.
          in: path
          name: firewallRuleName
          required: true
          schema:
            type: string
          examples:
            Get Firewall Rule:
              value: firewallrulecrudtest-2304
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FirewallRule"
              examples:
                Get Firewall Rule:
                  $ref: "#/components/examples/Get_Firewall_Rule"
      tags:
        - FirewallRules
    put:
      description: Creates or updates a firewall rule.
      operationId: FirewallRules_CreateOrUpdate
      parameters:
        - description: The API version to use for the request.
          in: query
          name: api-version
          required: true
          x-ms-parameter-location: client
          schema:
            type: string
          examples:
            Create a firewall rule max/min:
              value: 2014-04-01
            Update a firewall rule max/min:
              value: 2014-04-01
        - description: The subscription ID that identifies an Azure subscription.
          in: path
          name: subscriptionId
          required: true
          x-ms-parameter-location: client
          schema:
            type: string
          examples:
            Create a firewall rule max/min:
              value: 00000000-1111-2222-3333-444444444444
            Update a firewall rule max/min:
              value: 00000000-1111-2222-3333-444444444444
        - description: The name of the resource group that contains the resource. You can
            obtain this value from the Azure Resource Manager API or the portal.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Create a firewall rule max/min:
              value: firewallrulecrudtest-12
            Update a firewall rule max/min:
              value: firewallrulecrudtest-12
        - $ref: "#/components/parameters/ServerNameParameter"
        - description: The name of the firewall rule.
          in: path
          name: firewallRuleName
          required: true
          schema:
            type: string
          examples:
            Create a firewall rule max/min:
              value: firewallrulecrudtest-5370
            Update a firewall rule max/min:
              value: firewallrulecrudtest-3927
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FirewallRule"
        description: The required parameters for creating or updating a firewall rule.
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FirewallRule"
              examples:
                Create a firewall rule max/min:
                  $ref: "#/components/examples/Create_a_firewall_rule_max_min"
                Update a firewall rule max/min:
                  $ref: "#/components/examples/Update_a_firewall_rule_max_min"
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FirewallRule"
              examples:
                Create a firewall rule max/min:
                  $ref: "#/components/examples/Create_a_firewall_rule_max_min"
                Update a firewall rule max/min:
                  $ref: "#/components/examples/Update_a_firewall_rule_max_min"
      tags:
        - FirewallRules
servers:
  - url: https://management.azure.com
components:
  examples:
    List_Firewall_Rules:
      value:
        value:
          - id: /subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/firewallrulecrudtest-12/providers/Microsoft.Sql/servers/firewallrulecrudtest-6285/firewallRules/firewallrulecrudtest-2304
            kind: v12.0
            location: Japan East
            name: firewallrulecrudtest-2304
            properties:
              endIpAddress: 0.0.0.0
              startIpAddress: 0.0.0.0
            type: Microsoft.Sql/servers/firewallRules
          - id: /subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/firewallrulecrudtest-12/providers/Microsoft.Sql/servers/firewallrulecrudtest-6285/firewallRules/firewallrulecrudtest-3927
            kind: v12.0
            location: Japan East
            name: firewallrulecrudtest-3927
            properties:
              endIpAddress: 0.0.0.1
              startIpAddress: 0.0.0.1
            type: Microsoft.Sql/servers/firewallRules
          - id: /subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/firewallrulecrudtest-12/providers/Microsoft.Sql/servers/firewallrulecrudtest-6285/firewallRules/firewallrulecrudtest-5370
            kind: v12.0
            location: Japan East
            name: firewallrulecrudtest-5370
            properties:
              endIpAddress: 0.0.0.3
              startIpAddress: 0.0.0.3
            type: Microsoft.Sql/servers/firewallRules
          - id: /subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/firewallrulecrudtest-12/providers/Microsoft.Sql/servers/firewallrulecrudtest-6285/firewallRules/firewallrulecrudtest-5767
            kind: v12.0
            location: Japan East
            name: firewallrulecrudtest-5767
            properties:
              endIpAddress: 0.0.0.2
              startIpAddress: 0.0.0.2
            type: Microsoft.Sql/servers/firewallRules
    Get_Firewall_Rule:
      value:
        id: /subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/firewallrulecrudtest-12/providers/Microsoft.Sql/servers/firewallrulecrudtest-6285/firewallRules/firewallrulecrudtest-2304
        kind: v12.0
        location: Japan East
        name: firewallrulecrudtest-2304
        properties:
          endIpAddress: 0.0.0.0
          startIpAddress: 0.0.0.0
        type: Microsoft.Sql/servers/firewallRules
    Create_a_firewall_rule_max_min:
      value:
        id: /subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/firewallrulecrudtest-12/providers/Microsoft.Sql/servers/firewallrulecrudtest-6285/firewallRules/firewallrulecrudtest-5370
        kind: v12.0
        location: Japan East
        name: firewallrulecrudtest-5370
        properties:
          endIpAddress: 0.0.0.3
          startIpAddress: 0.0.0.3
        type: Microsoft.Sql/servers/firewallRules
    Update_a_firewall_rule_max_min:
      value:
        id: /subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/firewallrulecrudtest-12/providers/Microsoft.Sql/servers/firewallrulecrudtest-6285/firewallRules/firewallrulecrudtest-3927
        kind: v12.0
        location: Japan East
        name: firewallrulecrudtest-3927
        properties:
          endIpAddress: 0.0.0.1
          startIpAddress: 0.0.0.1
        type: Microsoft.Sql/servers/firewallRules
  parameters:
    ServerNameParameter:
      description: The name of the server.
      in: path
      name: serverName
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
      examples:
        List Firewall Rules:
          value: firewallrulecrudtest-6285
        Delete a firewall rule:
          value: firewallrulecrudtest-2368
        Get Firewall Rule:
          value: firewallrulecrudtest-6285
        Create a firewall rule max/min:
          value: firewallrulecrudtest-6285
        Update a firewall rule max/min:
          value: firewallrulecrudtest-6285
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    FirewallRule:
      allOf:
        - allOf:
            - description: ARM resource.
              properties:
                id:
                  description: Resource ID.
                  readOnly: true
                  type: string
                name:
                  description: Resource name.
                  readOnly: true
                  type: string
                type:
                  description: Resource type.
                  readOnly: true
                  type: string
              type: object
              x-ms-azure-resource: true
          description: ARM proxy resource.
          properties: {}
          type: object
      description: Represents a server firewall rule.
      properties:
        kind:
          description: Kind of server that contains this firewall rule.
          readOnly: true
          type: string
        location:
          description: Location of the server that contains this firewall rule.
          readOnly: true
          type: string
        properties:
          $ref: "#/components/schemas/FirewallRuleProperties"
        type:
          description: Type of resource this is.
          readOnly: true
          type: string
    FirewallRuleListResult:
      description: Represents the response to a List Firewall Rules request.
      properties:
        value:
          description: The list of server firewall rules.
          items:
            $ref: "#/components/schemas/FirewallRule"
          type: array
    FirewallRuleProperties:
      description: Represents the properties of a server firewall rule.
      properties:
        endIpAddress:
          description: The end IP address of the firewall rule. Must be IPv4 format. Must
            be greater than or equal to startIpAddress. Use value '0.0.0.0' to
            represent all Azure-internal IP addresses.
          type: string
        startIpAddress:
          description: The start IP address of the firewall rule. Must be IPv4 format. Use
            value '0.0.0.0' to represent all Azure-internal IP addresses.
          type: string
      required:
        - startIpAddress
        - endIpAddress
