openapi: 3.0.0
info:
  description: Describes the schema of the Azure resource events published to Azure Event
    Grid. This corresponds to the Data property of an EventGridEvent.
  title: Schema of Azure resource events published to Azure Event Grid
  version: 2018-01-01
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/eventgrid/data-plane/Microsoft.Resources/stable/2018-01-01/Resources.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: eventgrid-Resources
  x-tags:
    - Azure
    - Microsoft
paths: {}
servers:
  - url: https://azure.local
components:
  schemas:
    ResourceActionCancelData:
      description: Schema of the Data property of an EventGridEvent for an
        Microsoft.Resources.ResourceActionCancel event. This is raised when a
        resource action operation is canceled.
      properties:
        authorization:
          description: The requested authorization for the operation.
          type: string
        claims:
          description: The properties of the claims.
          type: string
        correlationId:
          description: An operation ID used for troubleshooting.
          type: string
        httpRequest:
          description: The details of the operation.
          type: string
        operationName:
          description: The operation that was performed.
          type: string
        resourceGroup:
          description: The resource group of the resource.
          type: string
        resourceProvider:
          description: The resource provider performing the operation.
          type: string
        resourceUri:
          description: The URI of the resource in the operation.
          type: string
        status:
          description: The status of the operation.
          type: string
        subscriptionId:
          description: The subscription ID of the resource.
          type: string
        tenantId:
          description: The tenant ID of the resource.
          type: string
      type: object
    ResourceActionFailureData:
      description: Schema of the Data property of an EventGridEvent for a
        Microsoft.Resources.ResourceActionFailure event. This is raised when a
        resource action operation fails.
      properties:
        authorization:
          description: The requested authorization for the operation.
          type: string
        claims:
          description: The properties of the claims.
          type: string
        correlationId:
          description: An operation ID used for troubleshooting.
          type: string
        httpRequest:
          description: The details of the operation.
          type: string
        operationName:
          description: The operation that was performed.
          type: string
        resourceGroup:
          description: The resource group of the resource.
          type: string
        resourceProvider:
          description: The resource provider performing the operation.
          type: string
        resourceUri:
          description: The URI of the resource in the operation.
          type: string
        status:
          description: The status of the operation.
          type: string
        subscriptionId:
          description: The subscription ID of the resource.
          type: string
        tenantId:
          description: The tenant ID of the resource.
          type: string
      type: object
    ResourceActionSuccessData:
      description: Schema of the Data property of an EventGridEvent for a
        Microsoft.Resources.ResourceActionSuccess event. This is raised when a
        resource action operation succeeds.
      properties:
        authorization:
          description: The requested authorization for the operation.
          type: string
        claims:
          description: The properties of the claims.
          type: string
        correlationId:
          description: An operation ID used for troubleshooting.
          type: string
        httpRequest:
          description: The details of the operation.
          type: string
        operationName:
          description: The operation that was performed.
          type: string
        resourceGroup:
          description: The resource group of the resource.
          type: string
        resourceProvider:
          description: The resource provider performing the operation.
          type: string
        resourceUri:
          description: The URI of the resource in the operation.
          type: string
        status:
          description: The status of the operation.
          type: string
        subscriptionId:
          description: The subscription ID of the resource.
          type: string
        tenantId:
          description: The tenant ID of the resource.
          type: string
      type: object
    ResourceDeleteCancelData:
      description: Schema of the Data property of an EventGridEvent for an
        Microsoft.Resources.ResourceDeleteCancel event. This is raised when a
        resource delete operation is canceled.
      properties:
        authorization:
          description: The requested authorization for the operation.
          type: string
        claims:
          description: The properties of the claims.
          type: string
        correlationId:
          description: An operation ID used for troubleshooting.
          type: string
        httpRequest:
          description: The details of the operation.
          type: string
        operationName:
          description: The operation that was performed.
          type: string
        resourceGroup:
          description: The resource group of the resource.
          type: string
        resourceProvider:
          description: The resource provider performing the operation.
          type: string
        resourceUri:
          description: The URI of the resource in the operation.
          type: string
        status:
          description: The status of the operation.
          type: string
        subscriptionId:
          description: The subscription ID of the resource.
          type: string
        tenantId:
          description: The tenant ID of the resource.
          type: string
      type: object
    ResourceDeleteFailureData:
      description: Schema of the Data property of an EventGridEvent for a
        Microsoft.Resources.ResourceDeleteFailure event. This is raised when a
        resource delete operation fails.
      properties:
        authorization:
          description: The requested authorization for the operation.
          type: string
        claims:
          description: The properties of the claims.
          type: string
        correlationId:
          description: An operation ID used for troubleshooting.
          type: string
        httpRequest:
          description: The details of the operation.
          type: string
        operationName:
          description: The operation that was performed.
          type: string
        resourceGroup:
          description: The resource group of the resource.
          type: string
        resourceProvider:
          description: The resource provider performing the operation.
          type: string
        resourceUri:
          description: The URI of the resource in the operation.
          type: string
        status:
          description: The status of the operation.
          type: string
        subscriptionId:
          description: The subscription ID of the resource.
          type: string
        tenantId:
          description: The tenant ID of the resource.
          type: string
      type: object
    ResourceDeleteSuccessData:
      description: Schema of the Data property of an EventGridEvent for a
        Microsoft.Resources.ResourceDeleteSuccess event. This is raised when a
        resource delete operation succeeds.
      properties:
        authorization:
          description: The requested authorization for the operation.
          type: string
        claims:
          description: The properties of the claims.
          type: string
        correlationId:
          description: An operation ID used for troubleshooting.
          type: string
        httpRequest:
          description: The details of the operation.
          type: string
        operationName:
          description: The operation that was performed.
          type: string
        resourceGroup:
          description: The resource group of the resource.
          type: string
        resourceProvider:
          description: The resource provider performing the operation.
          type: string
        resourceUri:
          description: The URI of the resource in the operation.
          type: string
        status:
          description: The status of the operation.
          type: string
        subscriptionId:
          description: The subscription ID of the resource.
          type: string
        tenantId:
          description: The tenant ID of the resource.
          type: string
      type: object
    ResourceWriteCancelData:
      description: Schema of the Data property of an EventGridEvent for a
        Microsoft.Resources.ResourceWriteCancel event. This is raised when a
        resource create or update operation is canceled.
      properties:
        authorization:
          description: The requested authorization for the operation.
          type: string
        claims:
          description: The properties of the claims.
          type: string
        correlationId:
          description: An operation ID used for troubleshooting.
          type: string
        httpRequest:
          description: The details of the operation.
          type: string
        operationName:
          description: The operation that was performed.
          type: string
        resourceGroup:
          description: The resource group of the resource.
          type: string
        resourceProvider:
          description: The resource provider performing the operation.
          type: string
        resourceUri:
          description: The URI of the resource in the operation.
          type: string
        status:
          description: The status of the operation.
          type: string
        subscriptionId:
          description: The subscription ID of the resource.
          type: string
        tenantId:
          description: The tenant ID of the resource.
          type: string
      type: object
    ResourceWriteFailureData:
      description: Schema of the Data property of an EventGridEvent for a
        Microsoft.Resources.ResourceWriteFailure event. This is raised when a
        resource create or update operation fails.
      properties:
        authorization:
          description: The requested authorization for the operation.
          type: string
        claims:
          description: The properties of the claims.
          type: string
        correlationId:
          description: An operation ID used for troubleshooting.
          type: string
        httpRequest:
          description: The details of the operation.
          type: string
        operationName:
          description: The operation that was performed.
          type: string
        resourceGroup:
          description: The resource group of the resource.
          type: string
        resourceProvider:
          description: The resource provider performing the operation.
          type: string
        resourceUri:
          description: The URI of the resource in the operation.
          type: string
        status:
          description: The status of the operation.
          type: string
        subscriptionId:
          description: The subscription ID of the resource.
          type: string
        tenantId:
          description: The tenant ID of the resource.
          type: string
      type: object
    ResourceWriteSuccessData:
      description: Schema of the Data property of an EventGridEvent for a
        Microsoft.Resources.ResourceWriteSuccess event. This is raised when a
        resource create or update operation succeeds.
      properties:
        authorization:
          description: The requested authorization for the operation.
          type: string
        claims:
          description: The properties of the claims.
          type: string
        correlationId:
          description: An operation ID used for troubleshooting.
          type: string
        httpRequest:
          description: The details of the operation.
          type: string
        operationName:
          description: The operation that was performed.
          type: string
        resourceGroup:
          description: The resource group of the resource.
          type: string
        resourceProvider:
          description: The resource provider performing the operation.
          type: string
        resourceUri:
          description: The URI of the resource in the operation.
          type: string
        status:
          description: The status of the operation.
          type: string
        subscriptionId:
          description: The subscription ID of the resource.
          type: string
        tenantId:
          description: The tenant ID of the resource.
          type: string
      type: object
