openapi: 3.0.0
info:
  description: Use these REST APIs for performing operations on OpenId Connect Provider
    entity associated with your Azure API Management deployment. API Management
    allows you to access APIs secured with token from [OpenID Connect Provider
    ](http://openid.net/connect/) to be accessed from the Developer Console.
  title: ApiManagementClient
  version: 2017-03-01
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/apimanagement/control-plane/Microsoft.ApiManagement/preview/2017-03-01/apimopenidconnectproviders.json
      version: "2.0"
  x-preferred: false
  x-providerName: azure.com
  x-serviceName: apimanagement-apimopenidconnectproviders
  x-tags:
    - Azure
    - Microsoft
security:
  - apim_key: []
paths:
  /openidConnectProviders:
    get:
      description: Lists all OpenID Connect Providers.
      operationId: OpenIdConnectProvider_List
      parameters:
        - description: >-
            | Field | Supported operators    | Supported
            functions                         |

            |-------|------------------------|---------------------------------------------|

            | id    | ge, le, eq, ne, gt, lt | substringof, contains, startswith, endswith |

            | name  | ge, le, eq, ne, gt, lt | substringof, contains, startswith, endswith |
          in: query
          name: $filter
          required: false
          schema:
            type: string
        - description: Number of records to return.
          in: query
          name: $top
          required: false
          x-ms-parameter-location: method
          schema:
            type: integer
            format: int32
            minimum: 1
        - description: Number of records to skip.
          in: query
          name: $skip
          required: false
          x-ms-parameter-location: method
          schema:
            type: integer
            format: int32
            minimum: 0
        - description: Version of the API to be used with the client request.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            ApiManagementListOpenIdConnectProvider:
              value: 2017-03-01
      responses:
        "200":
          description: Lists of all the OpenId Connect Providers.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OpenIdConnectProviderCollection"
              examples:
                ApiManagementListOpenIdConnectProvider:
                  $ref: "#/components/examples/ApiManagementListOpenIdConnectProvid\
                    er"
      tags:
        - OpenIdConnectProviders
      x-ms-odata: "#/components/schemas/OpenidConnectProviderContract"
      x-ms-pageable:
        nextLinkName: nextLink
  "/openidConnectProviders/{opid}":
    delete:
      description: Deletes specific OpenID Connect Provider of the API Management service
        instance.
      operationId: OpenIdConnectProvider_Delete
      parameters:
        - $ref: "#/components/parameters/OpenIdConnectIdParameter"
        - description: The entity state (Etag) version of the OpenID Connect Provider to
            delete. A value of "*" can be used for If-Match to unconditionally
            apply the operation.
          in: header
          name: If-Match
          required: true
          schema:
            type: string
          examples:
            ApiManagementDeleteOpenidconnectproviders:
              value: "*"
        - description: Version of the API to be used with the client request.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            ApiManagementDeleteOpenidconnectproviders:
              value: 2017-03-01
      responses:
        "204":
          description: OpenId Connect Provider was successfully deleted.
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error Body contract.
                properties:
                  code:
                    description: Service-defined error code. This code serves as a
                      sub-status for the HTTP error code specified in the
                      response.
                    type: string
                  details:
                    description: The list of invalid fields send in request, in case of
                      validation error.
                    items:
                      description: Error Field contract.
                      properties:
                        code:
                          description: Property level error code.
                          type: string
                        message:
                          description: Human-readable representation of property-level
                            error.
                          type: string
                        target:
                          description: Property name.
                          type: string
                    type: array
                  message:
                    description: Human-readable representation of the error.
                    type: string
      tags:
        - OpenIdConnectProviders
    get:
      description: Gets specific OpenID Connect Provider.
      operationId: OpenIdConnectProvider_Get
      parameters:
        - $ref: "#/components/parameters/OpenIdConnectIdParameter"
        - description: Version of the API to be used with the client request.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            ApiManagementGetOpenIdConnectProviders:
              value: 2017-03-01
      responses:
        "200":
          description: The response body contains the specified OpenId Connect Provider
            entity.
          headers:
            ETag:
              description: Current entity state version. Should be treated as opaque and
                used to make conditional HTTP requests.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OpenidConnectProviderContract"
              examples:
                ApiManagementGetOpenIdConnectProviders:
                  $ref: "#/components/examples/ApiManagementGetOpenIdConnectProvide\
                    rs"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error Body contract.
                properties:
                  code:
                    description: Service-defined error code. This code serves as a
                      sub-status for the HTTP error code specified in the
                      response.
                    type: string
                  details:
                    description: The list of invalid fields send in request, in case of
                      validation error.
                    items:
                      description: Error Field contract.
                      properties:
                        code:
                          description: Property level error code.
                          type: string
                        message:
                          description: Human-readable representation of property-level
                            error.
                          type: string
                        target:
                          description: Property name.
                          type: string
                    type: array
                  message:
                    description: Human-readable representation of the error.
                    type: string
      tags:
        - OpenIdConnectProviders
    patch:
      description: Updates the specific OpenID Connect Provider.
      operationId: OpenIdConnectProvider_Update
      parameters:
        - $ref: "#/components/parameters/OpenIdConnectIdParameter"
        - description: The entity state (Etag) version of the OpenID Connect Provider to
            update. A value of "*" can be used for If-Match to unconditionally
            apply the operation.
          in: header
          name: If-Match
          required: true
          schema:
            type: string
          examples:
            ApiManagementPatchOpenIdConnectProviders:
              value: "*"
        - description: Version of the API to be used with the client request.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            ApiManagementPatchOpenIdConnectProviders:
              value: 2017-03-01
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OpenidConnectProviderUpdateContract"
        description: Update parameters.
        required: true
      responses:
        "204":
          description: OpenId Connect Provider was successfully updated.
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error Body contract.
                properties:
                  code:
                    description: Service-defined error code. This code serves as a
                      sub-status for the HTTP error code specified in the
                      response.
                    type: string
                  details:
                    description: The list of invalid fields send in request, in case of
                      validation error.
                    items:
                      description: Error Field contract.
                      properties:
                        code:
                          description: Property level error code.
                          type: string
                        message:
                          description: Human-readable representation of property-level
                            error.
                          type: string
                        target:
                          description: Property name.
                          type: string
                    type: array
                  message:
                    description: Human-readable representation of the error.
                    type: string
      tags:
        - OpenIdConnectProviders
    put:
      description: Creates or updates the OpenID Connect Provider.
      operationId: OpenIdConnectProvider_CreateOrUpdate
      parameters:
        - $ref: "#/components/parameters/OpenIdConnectIdParameter"
        - description: Version of the API to be used with the client request.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            ApiManagementPutOpenIdConnectProviders:
              value: 2017-03-01
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OpenidConnectProviderContract"
        description: Create parameters.
        required: true
      responses:
        "200":
          description: OpenIdConnect Provider was successfully updated.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OpenidConnectProviderContract"
              examples:
                ApiManagementPutOpenIdConnectProviders:
                  $ref: "#/components/examples/ApiManagementPutOpenIdConnectProvide\
                    rs"
        "201":
          description: OpenIdConnect Provider was successfully created.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OpenidConnectProviderContract"
              examples:
                ApiManagementPutOpenIdConnectProviders:
                  $ref: "#/components/examples/ApiManagementPutOpenIdConnectProvide\
                    rs"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error Body contract.
                properties:
                  code:
                    description: Service-defined error code. This code serves as a
                      sub-status for the HTTP error code specified in the
                      response.
                    type: string
                  details:
                    description: The list of invalid fields send in request, in case of
                      validation error.
                    items:
                      description: Error Field contract.
                      properties:
                        code:
                          description: Property level error code.
                          type: string
                        message:
                          description: Human-readable representation of property-level
                            error.
                          type: string
                        target:
                          description: Property name.
                          type: string
                    type: array
                  message:
                    description: Human-readable representation of the error.
                    type: string
      tags:
        - OpenIdConnectProviders
servers:
  - url: https://azure.local
  - url: "{apimBaseUrl}"
    variables:
      apimBaseUrl:
        description: The management endpoint of the API Management service, for example
          https://myapimservice.management.azure-api.net.
        x-ms-skip-url-encoding: true
        default: ""
components:
  examples:
    ApiManagementListOpenIdConnectProvider:
      value:
        count: 1
        value:
          - clientId: oidprovidertemplate3
            id: /openidConnectProviders/op1
            metadataEndpoint: https://oidprovider-template3.net
            name: templateoidprovider3
    ApiManagementGetOpenIdConnectProviders:
      value:
        clientId: oidprovidertemplate3
        id: /openidConnectProviders/op1
        metadataEndpoint: https://oidprovider-template3.net
        name: templateoidprovider3
    ApiManagementPutOpenIdConnectProviders:
      value:
        clientId: oidprovidertemplate3
        id: /openidConnectProviders/op1
        metadataEndpoint: https://oidprovider-template3.net
        name: templateoidprovider3
  parameters:
    OpenIdConnectIdParameter:
      description: Identifier of the OpenID Connect Provider.
      in: path
      name: opid
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
        maxLength: 256
        pattern: ^[^*#&+:<>?]+$
      examples:
        ApiManagementDeleteOpenidconnectproviders:
          value: templateOpenIdConnect3
        ApiManagementGetOpenIdConnectProviders:
          value: op1
        ApiManagementPatchOpenIdConnectProviders:
          value: templateOpenIdConnect2
        ApiManagementPutOpenIdConnectProviders:
          value: op1
  securitySchemes:
    apim_key:
      in: header
      name: Authorization
      type: apiKey
  schemas:
    OpenIdConnectProviderCollection:
      description: Paged OpenIdProviders list representation.
      properties:
        count:
          description: Total number of entities
          type: integer
        nextLink:
          description: Next page link if any.
          type: string
        value:
          description: Page values.
          items:
            $ref: "#/components/schemas/OpenidConnectProviderContract"
          type: array
    OpenidConnectProviderContract:
      allOf:
        - $ref: "#/components/schemas/OpenidConnectProviderContractProperties"
      description: OpenId Connect Provider details.
      properties:
        id:
          description: Identifier of the OpenId Connect Provider.
          type: string
    OpenidConnectProviderContractProperties:
      description: OpenID Connect Providers Contract.
      properties:
        clientId:
          description: Client ID of developer console which is the client application.
          type: string
        clientSecret:
          description: Client Secret of developer console which is the client application.
          type: string
        description:
          description: User-friendly description of OpenID Connect Provider.
          type: string
        metadataEndpoint:
          description: Metadata endpoint URI.
          type: string
        name:
          description: User-friendly OpenID Connect Provider name.
          maxLength: 50
          type: string
      required:
        - name
        - metadataEndpoint
        - clientId
    OpenidConnectProviderUpdateContract:
      description: Parameters supplied to the Update OpenID Connect Provider operation.
      properties:
        clientId:
          description: Client ID of developer console which is the client application.
          type: string
        clientSecret:
          description: Client Secret of developer console which is the client application.
          type: string
        description:
          description: User-friendly description of OpenID Connect Provider.
          type: string
        metadataEndpoint:
          description: Metadata endpoint URI.
          type: string
        name:
          description: User-friendly OpenID Connect Provider name.
          maxLength: 50
          type: string
