openapi: 3.0.0
info:
  description: Learn more about home mortgage data, download the data yourself, or build
    new tools using our API.
  title: The Consumer Financial Protection Bureau
  version: "1.0"
  x-apisguru-categories:
    - financial
  x-logo:
    url: http://cfpb.github.io/img/logo_210.png
  x-origin:
    - converter:
        url: https://github.com/lucybot/api-spec-converter
        version: 2.7.11
      format: swagger
      url: https://api.consumerfinance.gov/api-docs
      version: "1.2"
  x-providerName: consumerfinance.gov
externalDocs:
  url: http://cfpb.github.io/api/hmda/
tags:
  - description: Operations about datasets
    name: data
  - description: Operations about LAR data
    name: hmda
paths:
  /data:
    get:
      operationId: getDatasets
      responses:
        "200":
          description: No response was specified
      summary: Get a list of all datasets.
      tags:
        - data
  /data/hmda:
    get:
      operationId: getDatasetHmda
      responses:
        "200":
          description: No response was specified
      summary: Get metadata for this dataset.
      tags:
        - hmda
  "/data/hmda/concept/{concept}":
    get:
      operationId: getConceptHmda
      parameters:
        - description: Name of concept
          in: path
          name: concept
          required: true
          schema:
            type: string
      responses:
        "200":
          description: No response was specified
      summary: Get information about a particular concept in this dataset.
      tags:
        - hmda
  "/data/hmda/slice/{slice}":
    get:
      operationId: querySliceHmda
      parameters:
        - description: Name of slice
          in: path
          name: slice
          required: true
          schema:
            type: string
        - description: Fields to return, separated by commas.
          in: query
          name: $select
          required: false
          schema:
            type: string
        - description: Conditions to search for in the slice, in SQL WHERE style.
          in: query
          name: $where
          required: false
          schema:
            type: string
        - description: Fields to group by, summarizing the data, separated by commas.
          in: query
          name: $group
          required: false
          schema:
            type: string
        - description: Number of records to return, 100 by default. Enter 0 for no limit.
          in: query
          name: $limit
          required: false
          schema:
            type: integer
        - description: Number of records to skip.
          in: query
          name: $offset
          required: false
          schema:
            type: integer
        - description: Fields to order by, separated by commas. ASC and DESC can be used to
            modify the order.
          in: query
          name: $orderBy
          required: false
          schema:
            type: string
        - description: JavaScript callback to invoke. Only useful with JSONP requests.
          in: query
          name: $callback
          required: false
          schema:
            type: string
      responses:
        "200":
          description: No response was specified
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QueryResponse"
            application/xml:
              schema:
                $ref: "#/components/schemas/QueryResponse"
            text/javascript:
              schema:
                $ref: "#/components/schemas/QueryResponse"
            text/csv:
              schema:
                $ref: "#/components/schemas/QueryResponse"
      summary: Query a slice in this dataset.
      tags:
        - hmda
  "/data/hmda/slice/{slice}/metadata":
    get:
      operationId: getSliceMetadataHmda
      parameters:
        - description: Name of slice
          in: path
          name: slice
          required: true
          schema:
            type: string
      responses:
        "200":
          description: No response was specified
      summary: Get the metadata for a slice in this dataset.
      tags:
        - hmda
  "/data/{dataset}":
    get:
      operationId: getDataset
      parameters:
        - description: Name of dataset
          in: path
          name: dataset
          required: true
          schema:
            type: string
      responses:
        "200":
          description: No response was specified
      summary: Get metadata about a dataset.
      tags:
        - data
servers:
  - url: https://api.consumerfinance.gov:443/
components:
  schemas:
    QueryResponse:
      description: Response to a slice query.
      properties:
        size:
          type: integer
        total:
          type: integer
      required:
        - total
        - size
