openapi: 3.0.0
info:
  contact:
    email: michael.binzen@deutschebahn.com
    name: Michael Binzen
  description: >-
    A RESTful webservice to retrieve data about the operational state of public
    elevators and escalators in german railway stations operated by DB
    Station&Service AG. 

    Note: Production and sandbox environments use the same production backend server. 
  license:
    name: CC-BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: http://data.deutschebahn.com/nutzungsbedingungen.html
  title: FaSta-Station_Facilities_Status
  version: v1
  x-apisguru-categories:
    - transport
    - open_data
  x-logo:
    backgroundColor: "#FFFFFF"
    url: https://pbs.twimg.com/profile_images/591140150413025280/Cjcqjl2J.png
  x-origin:
    - format: swagger
      url: https://developer.deutschebahn.com/store/api-docs/DBOpenData/FaSta-Station_Facilities_Status/v1
      version: "2.0"
  x-providerName: deutschebahn.com
  x-serviceName: fasta
security:
  - UserSecurity: []
paths:
  /disruptions:
    get:
      description: Returns information about disruptions of facilities filtered by
        parameters.
      operationId: findDisruptions
      parameters:
        - description: type of the facility to filter by
          in: query
          name: type
          required: false
          style: form
          explode: false
          schema:
            type: array
            items:
              enum:
                - ESCALATOR
                - ELEVATOR
              type: string
            uniqueItems: true
            default:
              - ESCALATOR
              - ELEVATOR
        - description: equipmentnumber of the facility to fetch
          in: query
          name: equipmentnumber
          required: false
          schema:
            type: integer
            format: int64
            minimum: 1
        - description: stationnumber of the station to fetch
          in: query
          name: stationnumber
          required: false
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        "200":
          description: disruption data
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/disruption"
                type: array
        "400":
          description: The given filters contained invalid values.
        "406":
          description: The requested representation format is not available.
        "500":
          description: A processing error has occurred.
        "503":
          description: The service has been disabled temporarily.
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
  "/disruptions/{disruptionnumber}":
    get:
      description: Returns information about a specific disruption of a facility
      operationId: findDisruptionByDisruptionNumber
      parameters:
        - description: disruptionnumber of the disruption to fetch
          in: path
          name: disruptionnumber
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        "200":
          description: disruption data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/disruption"
        "404":
          description: The requested disruption could not be found.
        "406":
          description: Requested representation format is not available.
        "500":
          description: A processing error has occurred.
        "503":
          description: The service has been disabled temporarily.
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
  /facilities:
    get:
      description: Access to public facilities (escalators and elevators) in railway
        stations
      operationId: findFacilities
      parameters:
        - description: type of the facility to filter by
          in: query
          name: type
          required: false
          style: form
          explode: false
          schema:
            type: array
            items:
              enum:
                - ESCALATOR
                - ELEVATOR
              type: string
            uniqueItems: true
            default:
              - ESCALATOR
              - ELEVATOR
        - description: the state of the facility to filter by
          in: query
          name: state
          required: false
          style: form
          explode: false
          schema:
            type: array
            items:
              enum:
                - ACTIVE
                - INACTIVE
              type: string
            uniqueItems: true
            default:
              - ACTIVE
              - INACTIVE
        - description: equipmentnumbers of the facility to filter by
          in: query
          name: equipmentnumbers
          required: false
          style: form
          explode: false
          schema:
            type: array
            items:
              format: int64
              maxItems: 100
              type: integer
            uniqueItems: true
        - description: station number to filter by
          in: query
          name: stationnumber
          required: false
          schema:
            type: integer
            format: int64
            minimum: 1
        - description: "Geo coordinate rectangle in WGS84-format to filter by. Parameters
            must be 4 numbers exactly as follows: longitudeWest, latitudeSouth,
            longitudeEast, latitudeNorth."
          in: query
          name: area
          required: false
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
            minItems: 4
            maxItems: 4
            uniqueItems: false
      responses:
        "200":
          description: facility data
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/facility"
                type: array
        "400":
          description: The given filters contained invalid values.
        "406":
          description: The requested representation format is not available.
        "500":
          description: A processing error has occurred.
        "503":
          description: The service has been disabled temporarily.
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
  "/facilities/{equipmentnumber}":
    get:
      description: Returns the facility identified by its equipmentnumber
      operationId: getFacilityByEquipmentNumber
      parameters:
        - description: equipmentnumber of the facility to fetch
          in: path
          name: equipmentnumber
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        "200":
          description: Facility data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/facility"
        "404":
          description: The requested facility could not be found.
        "406":
          description: The requested representation format is not available.
        "500":
          description: A processing error has occurred.
        "503":
          description: The service has been disabled temporarily.
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
  "/stations/{stationnumber}":
    get:
      description: Returns information about the station and its facilities identified by a
        stationnumber.
      operationId: findStationByStationNumber
      parameters:
        - description: stationnumber of the station to fetch
          in: path
          name: stationnumber
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        "200":
          description: station data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/station"
        "404":
          description: The requested station could not be found.
        "406":
          description: Requested representation format is not available.
        "500":
          description: A processing error has occurred.
        "503":
          description: The service has been disabled temporarily.
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
servers:
  - url: https://api.deutschebahn.com/fasta/v1
  - url: http://api.deutschebahn.com/fasta/v1
components:
  securitySchemes:
    UserSecurity:
      in: header
      name: Authorization
      type: apiKey
  schemas:
    disruption:
      description: A disruption contains information associated with a facility that is
        temporarily not available.
      properties:
        description:
          description: The local conditions of the related facility.
          type: string
        disruptionnumber:
          description: Unique identifier.
          format: int64
          type: integer
        equipmentnumber:
          description: Identifier of the related facility.
          format: int64
          type: integer
        furtherDescription:
          description: Further information of the cause if available.
          type: string
        geographicCoordinates:
          $ref: "#/components/schemas/point"
        lastUpdate:
          description: Last time this disruption has been updated (formatted in ISO-1806).
          format: date-time
          type: string
        outOfServiceOn:
          description: Time specification when the facility will not be available for
            planned maintenance work (formatted in ISO-1806).
          format: date-time
          type: string
        outOfServiceReason:
          description: Cause of the disruption.
          type: string
        outOfServiceTo:
          description: Time specification when the facility will be available again after
            planned maintenance work (formatted in ISO-1806).
          format: date-time
          type: string
        plannedCompletion:
          description: Time specification when the repair is planned to be finished
            (formatted in ISO-1806).
          format: date-time
          type: string
        state:
          description: Actual operational status.
          enum:
            - INACTIVE
          type: string
        stationnumber:
          description: Station number of the related facility.
          format: int64
          type: integer
        type:
          description: The type of the related facility e.g. escalator or elevator.
          enum:
            - ESCALATOR
            - ELEVATOR
          type: string
      required:
        - disruptionnumber
        - equipmentnumber
        - type
        - stationnumber
      type: object
    facility:
      description: Currently a facility provided by this API is either a public elevator or
        escalator in a german railway station operated by Station&Service AG.
      properties:
        description:
          description: The local conditions of the facility.
          type: string
        equipmentnumber:
          description: Unique identifier of the facility.
          format: int64
          type: integer
        geocoordX:
          description: longitude component of geocoordinate in WGS84 format
          format: double
          type: number
        geocoordY:
          description: latitude component of geocoordinate in WGS84 format
          format: double
          type: number
        state:
          description: Actual operational status.
          enum:
            - ACTIVE
            - INACTIVE
          type: string
        stationnumber:
          description: Number of the station where the facility is located.
          format: int64
          type: integer
        type:
          description: Facility type. Currently elevator or escalator.
          enum:
            - ESCALATOR
            - ELEVATOR
          type: string
      required:
        - equipmentnumber
        - type
        - state
        - stationnumber
      type: object
    point:
      description: Representation of a geographical point in GeoJSON format
      properties:
        coordinates:
          description: An array of numbers. First value is longitude, second latitude.
          items:
            format: double
            type: number
          maxItems: 2
          minItems: 2
          type: array
        type:
          default: Point
          type: string
      required:
        - type
        - coordinates
      type: object
    station:
      properties:
        facilities:
          items:
            $ref: "#/components/schemas/facility"
          type: array
        name:
          description: Name of the station.
          type: string
        stationnumber:
          description: Unique identifier of the railway station.
          format: int64
          type: integer
      required:
        - stationnumber
        - name
      type: object
