openapi: 3.0.0
info:
  description: Registered domains search checks the lists of registered domains for names
    containing particular words/phrases/numbers or symbols. Technically it's
    just a GUI interface for domains-index.com database containing more than
    260M of registered domains and 1000+ TLDS including newGTLDs. It's free to
    use and could be helpful domains/marketing research tool. Search results are
    limited to 50 results. You can have up to 100 results via API (link in
    footer) and full list by
  title: domainsdb.info
  version: 1.0.0
  x-apisguru-categories:
    - hosting
  x-logo:
    url: https://pbs.twimg.com/profile_images/769216960504532996/rctG95A0_400x400.jpg
  x-origin:
    - format: swagger
      url: https://domains-index.com/apidomainsdb/swagger.json
      version: "2.0"
  x-providerName: domainsdb.info
tags:
  - description: Search for registered domains
    name: search
paths:
  /search:
    get:
      description: ""
      operationId: addPet
      parameters:
        - description: Search query for registered domains for ex. facebook
          in: query
          name: query
          required: true
          schema:
            type: string
        - description: Search area (cctld|gtld|all)
          in: query
          name: tld
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/domains"
        "405":
          description: Invalid input
      security: []
      summary: Search for registered domains
      tags:
        - search
servers:
  - url: https://api.domainsdb.info/
components:
  securitySchemes:
    api_key:
      in: header
      name: api_key
      type: apiKey
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://petstore.swagger.io/oauth/dialog
          scopes:
            read:pets: read your pets
            write:pets: modify pets in your account
  schemas:
    domains:
      description: Domains data array
      properties:
        domains:
          description: Search results array
          items:
            properties:
              name:
                description: Domains name
                example: google.com, facebook--de.com
                type: string
          type: array
        time:
          description: Request time
          example: "5"
          format: int32
          type: integer
        total:
          description: Total records found
          example: "1235"
          format: int32
          type: integer
      type: object
