openapi: 3.0.0
info:
  contact:
    name: Google
    url: https://google.com
  description: Transfers user data from one user to another.
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Admin Data Transfer
  version: datatransfer_v1
  x-apiClientRegistration:
    url: https://console.developers.google.com
  x-apisguru-categories:
    - analytics
  x-logo:
    url: https://www.gstatic.com/images/icons/material/product/2x/admin_64dp.png
  x-origin:
    - converter:
        url: https://github.com/lucybot/api-spec-converter
        version: 2.7.31
      format: google
      url: https://www.googleapis.com/discovery/v1/apis/admin/datatransfer_v1/rest
      version: v1
  x-preferred: false
  x-providerName: googleapis.com
  x-serviceName: admin
externalDocs:
  url: https://developers.google.com/admin-sdk/data-transfer/
tags:
  - name: applications
  - name: transfers
paths:
  /applications:
    get:
      description: Lists the applications available for data transfer for a customer.
      operationId: datatransfer.applications.list
      parameters:
        - description: Immutable ID of the Google Apps account.
          in: query
          name: customerId
          schema:
            type: string
        - description: Maximum number of results to return. Default is 100.
          in: query
          name: maxResults
          schema:
            type: integer
            minimum: 1
            maximum: 500
        - description: Token to specify next page in the list.
          in: query
          name: pageToken
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/ApplicationsListResponse"
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.datatransfer
          Oauth2c:
            - https://www.googleapis.com/auth/admin.datatransfer
        - Oauth2:
            - https://www.googleapis.com/auth/admin.datatransfer.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.datatransfer.readonly
      tags:
        - applications
    parameters:
      - $ref: "#/components/parameters/alt"
      - $ref: "#/components/parameters/fields"
      - $ref: "#/components/parameters/key"
      - $ref: "#/components/parameters/oauth_token"
      - $ref: "#/components/parameters/prettyPrint"
      - $ref: "#/components/parameters/quotaUser"
      - $ref: "#/components/parameters/userIp"
  "/applications/{applicationId}":
    get:
      description: Retrieves information about an application for the given application ID.
      operationId: datatransfer.applications.get
      parameters:
        - description: ID of the application resource to be retrieved.
          in: path
          name: applicationId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/Application"
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.datatransfer
          Oauth2c:
            - https://www.googleapis.com/auth/admin.datatransfer
        - Oauth2:
            - https://www.googleapis.com/auth/admin.datatransfer.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.datatransfer.readonly
      tags:
        - applications
    parameters:
      - $ref: "#/components/parameters/alt"
      - $ref: "#/components/parameters/fields"
      - $ref: "#/components/parameters/key"
      - $ref: "#/components/parameters/oauth_token"
      - $ref: "#/components/parameters/prettyPrint"
      - $ref: "#/components/parameters/quotaUser"
      - $ref: "#/components/parameters/userIp"
  /transfers:
    get:
      description: Lists the transfers for a customer by source user, destination user, or
        status.
      operationId: datatransfer.transfers.list
      parameters:
        - description: Immutable ID of the Google Apps account.
          in: query
          name: customerId
          schema:
            type: string
        - description: Maximum number of results to return. Default is 100.
          in: query
          name: maxResults
          schema:
            type: integer
            minimum: 1
            maximum: 500
        - description: Destination user's profile ID.
          in: query
          name: newOwnerUserId
          schema:
            type: string
        - description: Source user's profile ID.
          in: query
          name: oldOwnerUserId
          schema:
            type: string
        - description: Token to specify the next page in the list.
          in: query
          name: pageToken
          schema:
            type: string
        - description: Status of the transfer.
          in: query
          name: status
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/DataTransfersListResponse"
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.datatransfer
          Oauth2c:
            - https://www.googleapis.com/auth/admin.datatransfer
        - Oauth2:
            - https://www.googleapis.com/auth/admin.datatransfer.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.datatransfer.readonly
      tags:
        - transfers
    parameters:
      - $ref: "#/components/parameters/alt"
      - $ref: "#/components/parameters/fields"
      - $ref: "#/components/parameters/key"
      - $ref: "#/components/parameters/oauth_token"
      - $ref: "#/components/parameters/prettyPrint"
      - $ref: "#/components/parameters/quotaUser"
      - $ref: "#/components/parameters/userIp"
    post:
      description: Inserts a data transfer request.
      operationId: datatransfer.transfers.insert
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DataTransfer"
      responses:
        "200":
          description: Successful response
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/DataTransfer"
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.datatransfer
          Oauth2c:
            - https://www.googleapis.com/auth/admin.datatransfer
      tags:
        - transfers
  "/transfers/{dataTransferId}":
    get:
      description: Retrieves a data transfer request by its resource ID.
      operationId: datatransfer.transfers.get
      parameters:
        - description: ID of the resource to be retrieved. This is returned in the response
            from the insert method.
          in: path
          name: dataTransferId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/DataTransfer"
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.datatransfer
          Oauth2c:
            - https://www.googleapis.com/auth/admin.datatransfer
        - Oauth2:
            - https://www.googleapis.com/auth/admin.datatransfer.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.datatransfer.readonly
      tags:
        - transfers
    parameters:
      - $ref: "#/components/parameters/alt"
      - $ref: "#/components/parameters/fields"
      - $ref: "#/components/parameters/key"
      - $ref: "#/components/parameters/oauth_token"
      - $ref: "#/components/parameters/prettyPrint"
      - $ref: "#/components/parameters/quotaUser"
      - $ref: "#/components/parameters/userIp"
servers:
  - url: https://www.googleapis.com/admin/datatransfer/v1
components:
  parameters:
    alt:
      description: Data format for the response.
      in: query
      name: alt
      schema:
        type: string
        enum:
          - json
        default: json
    fields:
      description: Selector specifying which fields to include in a partial response.
      in: query
      name: fields
      schema:
        type: string
    key:
      description: API key. Your API key identifies your project and provides you with API
        access, quota, and reports. Required unless you provide an OAuth 2.0
        token.
      in: query
      name: key
      schema:
        type: string
    oauth_token:
      description: OAuth 2.0 token for the current user.
      in: query
      name: oauth_token
      schema:
        type: string
    prettyPrint:
      description: Returns response with indentations and line breaks.
      in: query
      name: prettyPrint
      schema:
        type: boolean
        default: true
    quotaUser:
      description: An opaque string that represents a user for quota purposes. Must not
        exceed 40 characters.
      in: query
      name: quotaUser
      schema:
        type: string
    userIp:
      description: Deprecated. Please use quotaUser instead.
      in: query
      name: userIp
      schema:
        type: string
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/admin.datatransfer: View and manage data transfers between users in your organization
            https://www.googleapis.com/auth/admin.datatransfer.readonly: View data transfers between users in your organization
    Oauth2c:
      description: Oauth 2.0 accessCode authentication
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes:
            https://www.googleapis.com/auth/admin.datatransfer: View and manage data transfers between users in your organization
            https://www.googleapis.com/auth/admin.datatransfer.readonly: View data transfers between users in your organization
  schemas:
    Application:
      description: The JSON template for an Application resource.
      properties:
        etag:
          description: Etag of the resource.
          type: string
        id:
          description: The application's ID.
          format: int64
          type: string
        kind:
          default: admin#datatransfer#ApplicationResource
          description: Identifies the resource as a DataTransfer Application Resource.
          type: string
        name:
          description: The application's name.
          type: string
        transferParams:
          description: The list of all possible transfer parameters for this application.
            These parameters can be used to select the data of the user in this
            application to be transfered.
          items:
            $ref: "#/components/schemas/ApplicationTransferParam"
          type: array
      type: object
    ApplicationDataTransfer:
      description: Template to map fields of ApplicationDataTransfer resource.
      properties:
        applicationId:
          description: The application's ID.
          format: int64
          type: string
        applicationTransferParams:
          description: The transfer parameters for the application. These parameters are
            used to select the data which will get transfered in context of this
            application.
          items:
            $ref: "#/components/schemas/ApplicationTransferParam"
          type: array
        applicationTransferStatus:
          description: Current status of transfer for this application. (Read-only)
          type: string
      type: object
    ApplicationTransferParam:
      description: Template for application transfer parameters.
      properties:
        key:
          description: "The type of the transfer parameter. eg: 'PRIVACY_LEVEL'"
          type: string
        value:
          description: "The value of the coressponding transfer parameter. eg: 'PRIVATE' or
            'SHARED'"
          items:
            type: string
          type: array
      type: object
    ApplicationsListResponse:
      description: Template for a collection of Applications.
      properties:
        applications:
          description: List of applications that support data transfer and are also
            installed for the customer.
          items:
            $ref: "#/components/schemas/Application"
          type: array
        etag:
          description: ETag of the resource.
          type: string
        kind:
          default: admin#datatransfer#applicationsList
          description: Identifies the resource as a collection of Applications.
          type: string
        nextPageToken:
          description: Continuation token which will be used to specify next page in list
            API.
          type: string
      type: object
    DataTransfer:
      description: The JSON template for a DataTransfer resource.
      properties:
        applicationDataTransfers:
          description: List of per application data transfer resources. It contains data
            transfer details of the applications associated with this transfer
            resource. Note that this list is also used to specify the
            applications for which data transfer has to be done at the time of
            the transfer resource creation.
          items:
            $ref: "#/components/schemas/ApplicationDataTransfer"
          type: array
        etag:
          description: ETag of the resource.
          type: string
        id:
          description: The transfer's ID (Read-only).
          type: string
        kind:
          default: admin#datatransfer#DataTransfer
          description: Identifies the resource as a DataTransfer request.
          type: string
        newOwnerUserId:
          description: ID of the user to whom the data is being transfered.
          type: string
        oldOwnerUserId:
          description: ID of the user whose data is being transfered.
          type: string
        overallTransferStatusCode:
          description: Overall transfer status (Read-only).
          type: string
        requestTime:
          description: The time at which the data transfer was requested (Read-only).
          format: date-time
          type: string
      type: object
    DataTransfersListResponse:
      description: Template for a collection of DataTransfer resources.
      properties:
        dataTransfers:
          description: List of data transfer requests.
          items:
            $ref: "#/components/schemas/DataTransfer"
          type: array
        etag:
          description: ETag of the resource.
          type: string
        kind:
          default: admin#datatransfer#dataTransfersList
          description: Identifies the resource as a collection of data transfer requests.
          type: string
        nextPageToken:
          description: Continuation token which will be used to specify next page in list
            API.
          type: string
      type: object
