openapi: 3.0.0
info:
  contact:
    name: Google
    url: https://google.com
  description: Accesses the metadata for all families served by Google Fonts, providing a
    list of families currently available (including available styles and a list
    of supported script subsets).
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Google Fonts Developer
  version: v1
  x-apiClientRegistration:
    url: https://console.developers.google.com
  x-apisguru-categories:
    - developer_tools
  x-logo:
    url: https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
  x-origin:
    - converter:
        url: https://github.com/lucybot/api-spec-converter
        version: 2.7.31
      format: google
      url: https://www.googleapis.com/discovery/v1/apis/webfonts/v1/rest
      version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: webfonts
externalDocs:
  url: https://developers.google.com/fonts/docs/developer_api
tags:
  - name: webfonts
paths:
  /webfonts:
    get:
      description: Retrieves the list of fonts currently served by the Google Fonts
        Developer API
      operationId: webfonts.webfonts.list
      parameters:
        - description: Enables sorting of the list
          in: query
          name: sort
          schema:
            type: string
            enum:
              - alpha
              - date
              - popularity
              - style
              - trending
      responses:
        "200":
          description: Successful response
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/WebfontList"
      tags:
        - webfonts
    parameters:
      - $ref: "#/components/parameters/alt"
      - $ref: "#/components/parameters/fields"
      - $ref: "#/components/parameters/key"
      - $ref: "#/components/parameters/oauth_token"
      - $ref: "#/components/parameters/prettyPrint"
      - $ref: "#/components/parameters/quotaUser"
      - $ref: "#/components/parameters/userIp"
servers:
  - url: https://www.googleapis.com/webfonts/v1
components:
  parameters:
    alt:
      description: Data format for the response.
      in: query
      name: alt
      schema:
        type: string
        enum:
          - json
        default: json
    fields:
      description: Selector specifying which fields to include in a partial response.
      in: query
      name: fields
      schema:
        type: string
    key:
      description: API key. Your API key identifies your project and provides you with API
        access, quota, and reports. Required unless you provide an OAuth 2.0
        token.
      in: query
      name: key
      schema:
        type: string
    oauth_token:
      description: OAuth 2.0 token for the current user.
      in: query
      name: oauth_token
      schema:
        type: string
    prettyPrint:
      description: Returns response with indentations and line breaks.
      in: query
      name: prettyPrint
      schema:
        type: boolean
        default: true
    quotaUser:
      description: An opaque string that represents a user for quota purposes. Must not
        exceed 40 characters.
      in: query
      name: quotaUser
      schema:
        type: string
    userIp:
      description: Deprecated. Please use quotaUser instead.
      in: query
      name: userIp
      schema:
        type: string
  schemas:
    Webfont:
      properties:
        category:
          description: The category of the font.
          type: string
        family:
          description: The name of the font.
          type: string
        files:
          additionalProperties:
            description: The font file URL (value) for an specific variant (key).
            type: string
          description: "The font files (with all supported scripts) for each one of the
            available variants, as a key : value map."
          type: object
        kind:
          default: webfonts#webfont
          description: This kind represents a webfont object in the webfonts service.
          type: string
        lastModified:
          description: The date (format "yyyy-MM-dd") the font was modified for the last
            time.
          format: date
          type: string
        subsets:
          description: The scripts supported by the font.
          items:
            type: string
          type: array
        variants:
          description: The available variants for the font.
          items:
            type: string
          type: array
        version:
          description: The font version.
          type: string
      type: object
    WebfontList:
      properties:
        items:
          description: The list of fonts currently served by the Google Fonts API.
          items:
            $ref: "#/components/schemas/Webfont"
          type: array
        kind:
          default: webfonts#webfontList
          description: This kind represents a list of webfont objects in the webfonts
            service.
          type: string
      type: object
