openapi: 3.0.0
info:
  contact:
    name: Google
    url: https://google.com
  description: Analyzes the performance of a web page and provides tailored suggestions to
    make that page faster.
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: PageSpeed Insights
  version: v5
  x-apiClientRegistration:
    url: https://console.developers.google.com
  x-apisguru-categories:
    - tools
  x-logo:
    url: https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
  x-origin:
    - converter:
        url: https://github.com/lucybot/api-spec-converter
        version: 2.7.31
      format: google
      url: https://www.googleapis.com/discovery/v1/apis/pagespeedonline/v5/rest
      version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: pagespeedonline
externalDocs:
  url: https://developers.google.com/speed/docs/insights/v5/get-started
tags:
  - name: pagespeedapi
paths:
  /runPagespeed:
    get:
      description: Runs PageSpeed analysis on the page at the specified URL, and returns
        PageSpeed scores, a list of suggestions to make that page faster, and
        other information.
      operationId: pagespeedonline.pagespeedapi.runpagespeed
      parameters:
        - description: A Lighthouse category to run; if none are given, only Performance
            category will be run
          in: query
          name: category
          explode: true
          schema:
            type: array
            items:
              enum:
                - accessibility
                - best-practices
                - performance
                - pwa
                - seo
              type: string
        - description: The locale used to localize formatted results
          in: query
          name: locale
          schema:
            type: string
        - description: The analysis strategy (desktop or mobile) to use, and desktop is the
            default
          in: query
          name: strategy
          schema:
            type: string
            enum:
              - desktop
              - mobile
        - description: The URL to fetch and analyze
          in: query
          name: url
          required: true
          schema:
            type: string
        - description: Campaign name for analytics.
          in: query
          name: utm_campaign
          schema:
            type: string
        - description: Campaign source for analytics.
          in: query
          name: utm_source
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/PagespeedApiPagespeedResponseV5"
      tags:
        - pagespeedapi
    parameters:
      - $ref: "#/components/parameters/alt"
      - $ref: "#/components/parameters/fields"
      - $ref: "#/components/parameters/key"
      - $ref: "#/components/parameters/oauth_token"
      - $ref: "#/components/parameters/prettyPrint"
      - $ref: "#/components/parameters/quotaUser"
      - $ref: "#/components/parameters/userIp"
servers:
  - url: https://www.googleapis.com/pagespeedonline/v5
components:
  parameters:
    alt:
      description: Data format for the response.
      in: query
      name: alt
      schema:
        type: string
        enum:
          - json
        default: json
    fields:
      description: Selector specifying which fields to include in a partial response.
      in: query
      name: fields
      schema:
        type: string
    key:
      description: API key. Your API key identifies your project and provides you with API
        access, quota, and reports. Required unless you provide an OAuth 2.0
        token.
      in: query
      name: key
      schema:
        type: string
    oauth_token:
      description: OAuth 2.0 token for the current user.
      in: query
      name: oauth_token
      schema:
        type: string
    prettyPrint:
      description: Returns response with indentations and line breaks.
      in: query
      name: prettyPrint
      schema:
        type: boolean
        default: true
    quotaUser:
      description: An opaque string that represents a user for quota purposes. Must not
        exceed 40 characters.
      in: query
      name: quotaUser
      schema:
        type: string
    userIp:
      description: Deprecated. Please use quotaUser instead.
      in: query
      name: userIp
      schema:
        type: string
  schemas:
    GoogleprotobufListValue:
      items:
        $ref: "#/components/schemas/GoogleprotobufValue"
      type: array
    GoogleprotobufValue: {}
    LighthouseAuditResultV5:
      properties:
        description:
          description: The description of the audit.
          type: string
        details:
          additionalProperties: {}
          description: Freeform details section of the audit.
          type: object
        displayValue:
          description: The value that should be displayed on the UI for this audit.
          type: string
        errorMessage:
          description: An error message from a thrown error inside the audit.
          type: string
        explanation:
          description: An explanation of the errors in the audit.
          type: string
        id:
          description: The audit's id.
          type: string
        score: {}
        scoreDisplayMode:
          description: The enumerated score display mode.
          type: string
        title:
          description: The human readable title.
          type: string
        warnings: {}
      type: object
    LighthouseCategoryV5:
      properties:
        auditRefs:
          description: An array of references to all the audit members of this category.
          items:
            properties:
              group:
                description: The category group that the audit belongs to (optional).
                type: string
              id:
                description: The audit ref id.
                type: string
              weight:
                description: The weight this audit's score has on the overall category
                  score.
                format: double
                type: number
            type: object
          type: array
        description:
          description: A more detailed description of the category and its importance.
          type: string
        id:
          description: The string identifier of the category.
          type: string
        manualDescription:
          description: A description for the manual audits in the category.
          type: string
        score: {}
        title:
          description: The human-friendly name of the category.
          type: string
      type: object
    LighthouseResultV5:
      properties:
        audits:
          additionalProperties:
            $ref: "#/components/schemas/LighthouseAuditResultV5"
          description: Map of audits in the LHR.
          type: object
        categories:
          description: Map of categories in the LHR.
          properties:
            accessibility:
              $ref: "#/components/schemas/LighthouseCategoryV5"
            best-practices:
              $ref: "#/components/schemas/LighthouseCategoryV5"
            performance:
              $ref: "#/components/schemas/LighthouseCategoryV5"
            pwa:
              $ref: "#/components/schemas/LighthouseCategoryV5"
            seo:
              $ref: "#/components/schemas/LighthouseCategoryV5"
          type: object
        categoryGroups:
          additionalProperties:
            description: A grouping contained in a category that groups similar audits
              together.
            properties:
              description:
                description: An optional human readable description of the category group.
                type: string
              title:
                description: The title of the category group.
                type: string
            type: object
          description: Map of category groups in the LHR.
          type: object
        configSettings:
          description: The configuration settings for this LHR.
          properties:
            emulatedFormFactor:
              description: The form factor the emulation should use.
              type: string
            locale:
              description: The locale setting.
              type: string
            onlyCategories: {}
          type: object
        environment:
          description: Environment settings that were used when making this LHR.
          properties:
            benchmarkIndex:
              description: The benchmark index number that indicates rough device class.
              format: double
              type: number
            hostUserAgent:
              description: The user agent string of the version of Chrome used.
              type: string
            networkUserAgent:
              description: The user agent string that was sent over the network.
              type: string
          type: object
        fetchTime:
          description: The time that this run was fetched.
          type: string
        finalUrl:
          description: The final resolved url that was audited.
          type: string
        i18n:
          description: The internationalization strings that are required to render the LHR.
          properties:
            rendererFormattedStrings:
              description: Internationalized strings that are formatted to the locale in
                configSettings.
              properties:
                auditGroupExpandTooltip:
                  description: The tooltip text on an expandable chevron icon.
                  type: string
                crcInitialNavigation:
                  description: The label for the initial request in a critical request
                    chain.
                  type: string
                crcLongestDurationLabel:
                  description: The label for values shown in the summary of critical
                    request chains.
                  type: string
                errorLabel:
                  description: The label shown next to an audit or metric that has had an
                    error.
                  type: string
                errorMissingAuditInfo:
                  description: The error string shown next to an erroring audit.
                  type: string
                labDataTitle:
                  description: The title of the lab data performance category.
                  type: string
                lsPerformanceCategoryDescription:
                  description: The disclaimer shown under performance explaning that the
                    network can vary.
                  type: string
                manualAuditsGroupTitle:
                  description: The heading shown above a list of audits that were not
                    computerd in the run.
                  type: string
                notApplicableAuditsGroupTitle:
                  description: The heading shown above a list of audits that do not apply
                    to a page.
                  type: string
                opportunityResourceColumnLabel:
                  description: The heading for the estimated page load savings opportunity
                    of an audit.
                  type: string
                opportunitySavingsColumnLabel:
                  description: The heading for the estimated page load savings of
                    opportunity audits.
                  type: string
                passedAuditsGroupTitle:
                  description: The heading that is shown above a list of audits that are
                    passing.
                  type: string
                scorescaleLabel:
                  description: The label that explains the score gauges scale (0-49, 50-89,
                    90-100).
                  type: string
                toplevelWarningsMessage:
                  description: The label shown preceding important warnings that may have
                    invalidated an entire report.
                  type: string
                varianceDisclaimer:
                  description: The disclaimer shown below a performance metric value.
                  type: string
                warningHeader:
                  description: The label shown above a bulleted list of warnings.
                  type: string
              type: object
          type: object
        lighthouseVersion:
          description: The lighthouse version that was used to generate this LHR.
          type: string
        requestedUrl:
          description: The original requested url.
          type: string
        runWarnings:
          $ref: "#/components/schemas/GoogleprotobufListValue"
        runtimeError:
          description: A top-level error message that, if present, indicates a serious
            enough problem that this Lighthouse result may need to be discarded.
          properties:
            code:
              description: The enumerated Lighthouse Error code.
              type: string
            message:
              description: A human readable message explaining the error code.
              type: string
          type: object
        stackPacks:
          description: The Stack Pack advice strings.
          items:
            properties:
              descriptions:
                additionalProperties:
                  description: The specific stack pack description.
                  type: string
                description: The stack pack advice strings.
                type: object
              iconDataURL:
                description: The stack pack icon data uri.
                type: string
              id:
                description: The stack pack id.
                type: string
              title:
                description: The stack pack title.
                type: string
            type: object
          type: array
        timing:
          description: Timing information for this LHR.
          properties:
            total:
              description: The total duration of Lighthouse's run.
              format: double
              type: number
          type: object
        userAgent:
          description: The user agent that was used to run this LHR.
          type: string
      type: object
    PagespeedApiLoadingExperienceV5:
      properties:
        id:
          description: The url, pattern or origin which the metrics are on.
          type: string
        initial_url:
          type: string
        metrics:
          additionalProperties:
            description: The type of the metric.
            properties:
              category:
                type: string
              distributions:
                items:
                  properties:
                    max:
                      format: int32
                      type: integer
                    min:
                      format: int32
                      type: integer
                    proportion:
                      format: double
                      type: number
                  type: object
                type: array
              percentile:
                format: int32
                type: integer
            type: object
          type: object
        overall_category:
          type: string
      type: object
    PagespeedApiPagespeedResponseV5:
      properties:
        analysisUTCTimestamp:
          description: The UTC timestamp of this analysis.
          type: string
        captchaResult:
          description: The captcha verify result
          type: string
        id:
          description: Canonicalized and final URL for the document, after following page
            redirects (if any).
          type: string
        kind:
          default: pagespeedonline#result
          description: Kind of result.
          type: string
        lighthouseResult:
          $ref: "#/components/schemas/LighthouseResultV5"
        loadingExperience:
          $ref: "#/components/schemas/PagespeedApiLoadingExperienceV5"
        originLoadingExperience:
          $ref: "#/components/schemas/PagespeedApiLoadingExperienceV5"
        version:
          description: The version of PageSpeed used to generate these results.
          properties:
            major:
              description: The major version number of PageSpeed used to generate these
                results.
              format: int32
              type: integer
            minor:
              description: The minor version number of PageSpeed used to generate these
                results.
              format: int32
              type: integer
          type: object
      type: object
