openapi: 3.0.1
servers:
  - url: https://api.ip2proxy.com
info:
  contact:
    x-twitter: ip2location
  description: IP2Proxy allows instant detection of anonymous proxy, VPN and TOR exit nodes
    and search engine robots (SES) by IP address. Visit
    https://www.ip2location.com/web-service/ip2proxy for further information.
  title: IP2Proxy Proxy Detection
  version: "1.0"
  x-apisguru-categories:
    - location
  x-logo:
    url: https://twitter.com/ip2location/profile_image?size=original
  x-origin:
    - converter:
        url: https://github.com/lucybot/api-spec-converter
        version: 2.7.31
      format: openapi
      url: https://api.swaggerhub.com/apis/ip2location/ip2proxy-proxy-detection/1.0
      version: "3.0"
  x-providerName: ip2proxy.com
paths:
  /:
    get:
      description: Check if an IP address is proxy
      parameters:
        - description: If not present, the web service will assume the PX1 package query.
          in: query
          name: package
          schema:
            type: string
        - description: IP address (IPv4) for lookup purpose. If not present, the server IP
            address will be used for the lookup.
          in: query
          name: ip
          required: true
          schema:
            type: string
        - description: If not present, json format will be returned as the search result.
          in: query
          name: format
          schema:
            enum:
              - json
              - xml
            type: string
        - description: API key.
          in: query
          name: key
          required: true
          schema:
            type: string
      responses:
        "200":
          content:
            text/html; charset=UTF-8:
              examples:
                "0":
                  value: '{"response": "","countryCode": "","countryName":
                    "","regionName": "","cityName": "","isp": "","domain":
                    "","usageType":"","asn":"","as": "","lastSeen":
                    "","proxyType":"","isProxy": ""}'
              schema:
                type: string
          description: Get response from IP2Proxy
