openapi: 3.0.0
info:
  description: Query our database of State and Federal Laws and Incentives for Alternative
    Fuels
  title: Transportation Laws and Incentives
  version: 0.1.0
  x-apisguru-categories:
    - open_data
  x-logo:
    backgroundColor: "#0079C5"
    url: https://twitter.com/NRELdev/profile_image?size=original
  x-origin:
    - converter:
        url: https://github.com/lucybot/api-spec-converter
        version: 2.0.1
      format: swagger
      url: http://developer.nrel.gov/docs/transportation/transportation-incentives-laws-v1/api-docs.json
      version: "1.2"
  x-providerName: nrel.gov
  x-serviceName: transportation-incentives-laws
security:
  - api_key: []
tags:
  - description: Information about laws and incentives
    name: v1
paths:
  "/v1.{output_format}":
    get:
      parameters:
        - description: Response format
          in: path
          name: output_format
          required: true
          schema:
            type: string
            enum:
              - json
              - xml
              - csv
            default: json
        - description: Limit the number of laws returned
          in: query
          name: limit
          schema:
            type: integer
            default: 10
        - description: Return laws for the given Jurisdiction. Jurisdiction must be given
            as a two character state code (eg, 'CO' for Colorado). A single
            jurisdiction, or a comma-separate list of multiple jurisdiction, may
            be given.  Use the code 'US' for federal laws and the code 'DC' for
            Washington D.C.
          in: query
          name: jurisdiction
          schema:
            type: string
        - description: "Search by the technology type. A single type, or a comma-separate
            list of multiple types, may be given. Values and what they stand for
            are as follows: 'BIOD' for Biodiesel, 'ETH' for Ethanol, 'NG' for
            Natural Gas, 'LPG' for Propane (LPG), 'HY' for Hydrogen Fuel Cells,
            'EFFEC' for Fuel Economy / Efficiency, 'IR' for Idle Reduction,
            'ELEC' for EVs, 'HEV' for HEVs, 'PHEV' for PHEVs, 'OTHER' for Other,
            'AFTMKTCONV' for Aftermarket Conversions, and 'NEVS' for NEVs"
          in: query
          name: technology
          schema:
            type: string
        - description: "Search by the incentive type. A single type, or a comma-separate
            list of multiple types, may be given. Values and what they stand for
            are as follows: 'GNT' for Grants, 'TAX' for Tax Incentives, 'LOANS'
            for Loans and Leases, 'RBATE' for Rebates, 'EXEM' for Exemptions,
            and 'OTHER' for Other."
          in: query
          name: incentive_type
          schema:
            type: string
        - description: "Search by the regulation type. A single type, or a comma-separate
            list of multiple types, may be given. Values and what they stand for
            are as follows: 'REGIS' for Registration / Licensing, 'STD' for Fuel
            Production / Quality, 'DREST' for Driving / Idling, 'REQ' for
            Acquisition / Fuel Use, 'FUEL' for Fuel Taxes, 'RFS' for Renewable
            Fuel Standard / Mandate, 'OTHER' for Other, 'AIRQEMISSIONS' for Air
            Quality / Emissions, and 'CCEINIT' for Climate Change / Energy
            Initiatives"
          in: query
          name: regulation_type
          schema:
            type: string
        - description: "Search by the user type. A single type, or a comma-separate list of
            multiple types, may be given. Values and what they stand for are as
            follows: 'IND' for Vehicle Owner/Driver, 'FLEET' for Fleet
            Purchaser/Manager, 'STATION' for Fueling / TSE Infrastructure Owner,
            'AFP' for Alternative Fuel Producer, 'AFS' for Alternative Fuel
            Dealer, 'PURCH' for Alternative Fuel Purchaser, 'MAN' for AFV
            Manufacturer/Retrofitter, and 'OTHER' for Other"
          in: query
          name: user_type
          schema:
            type: string
        - description: Include points of contacts in the return value.
          in: query
          name: poc
          schema:
            type: boolean
            default: false
        - description: Return only recently added or updated laws and incentives
          in: query
          name: recent
          schema:
            type: boolean
            default: false
        - description: Show only expired, repealed or archived laws and incentives.
          in: query
          name: expired
          schema:
            type: boolean
            default: false
        - description: "Search by the law type. A single type, or a comma-separate list of
            multiple types, may be given. Values are as follows: 'STATEINC' for
            State Incentives, 'UPINC ' for Utility/Private Incentives, 'LAWREG'
            for Laws and Regulations, 'INC' for Incentives, 'PROG' for Programs,
            'LUP' for Last Updated, 'OVIEW' for Overview, and 'HILITE' for
            Highlights"
          in: query
          name: law_type
          schema:
            type: string
        - description: Search laws by keyword in title or text.
          in: query
          name: keyword
          schema:
            type: string
        - description: Show only local examples of laws and incentives.
          in: query
          name: local
          schema:
            type: boolean
            default: false
      responses:
        "200":
          description: No response was specified
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/LawsResponse"
      summary: Return a full list of laws and incentives that match your query.
      tags:
        - v1
  "/v1/category-list.{output_format}":
    get:
      parameters:
        - description: Response format
          in: path
          name: output_format
          required: true
          schema:
            type: string
            enum:
              - json
              - xml
            default: json
        - description: Search by the category type.
          in: query
          name: type
          schema:
            type: string
            enum:
              - tech
              - user
              - regulation
              - incentive
      responses:
        "200":
          description: No response was specified
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/CategoryResults"
      summary: Return the law categories for a given category type.
      tags:
        - v1
  "/v1/pocs.{output_format}":
    get:
      parameters:
        - description: Response format
          in: path
          name: output_format
          required: true
          schema:
            type: string
            enum:
              - json
              - xml
            default: json
        - description: Return the points of contact for the given Jurisdiction.
            Jurisdiction must be given as a two character state code (eg, 'CO'
            for Colorado). A single jurisdiction, or a comma-separate list of
            multiple jurisdiction, may be given.  Use the code 'US' for federal
            laws and the code 'DC' for Washington D.C.
          in: query
          name: jurisdiction
          required: true
          schema:
            type: string
      responses:
        "200":
          description: No response was specified
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/PocResults"
      summary: Get the points of contact for a given jurisdiction.
      tags:
        - v1
  "/v1/{id}.{output_format}":
    get:
      parameters:
        - description: Response format
          in: path
          name: output_format
          required: true
          schema:
            type: string
            enum:
              - json
              - xml
            default: json
        - description: The id of the law that you are searching
          in: path
          name: id
          required: true
          schema:
            type: integer
        - description: Include points of contacts in the return value.
          in: query
          name: poc
          schema:
            type: boolean
            default: false
      responses:
        "200":
          description: No response was specified
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/LawResult"
      summary: Fetch the details of a specific law given the law's ID.
      tags:
        - v1
servers:
  - url: https://developer.nrel.gov/api/transportation-incentives-laws
components:
  securitySchemes:
    api_key:
      description: API Key
      in: query
      name: api_key
      type: apiKey
  schemas:
    Category:
      description: A category that the law applies to
      properties:
        category_type:
          description: The type of category. (E.g. tech, incentive, regulation, user)
          type: string
        code:
          description: The code used to identify the category
          type: string
        title:
          description: The full name of the category
          type: string
      required:
        - code
        - title
        - category_type
    CategoryResults:
      properties:
        inputs:
          $ref: "#/components/schemas/Inputs"
        metadata:
          $ref: "#/components/schemas/Metadata"
        result:
          description: The array of law categories returned
          items:
            $ref: "#/components/schemas/FullCategory"
          type: array
      required:
        - metadata
        - inputs
        - result
    FullCategory:
      properties:
        category_type:
          description: The type of category. (E.g. tech, incentive, regulation, user)
          type: string
        code:
          description: The code used to identify the category
          type: string
        help_text:
          description: A short description of what the law category encompasses
          type: string
        sort_order:
          description: The sort order for the categories
          type: string
        title:
          description: The full name of the category
          type: string
      required:
        - code
        - title
        - category_type
        - sort_order
    Inputs:
      description: The parameters that were passed to the API
    Law:
      description: This is a Law
      properties:
        agency:
          description: The agency with primary responsibility for federal
            incentives/regulations.
          type: string
        amended_date:
          description: The date the incentive/law/regulation was updated through new
            legislation or rulemaking.
          format: date-time
          type: string
        archived_date:
          description: The date that an incentive/law/regulation is no longer relevant to
            the database. This may include longstanding Executive Orders or laws
            requiring legislative studies that have been completed.
          format: date-time
          type: string
        categories:
          description: The various law categories that apply to this law
          items:
            $ref: "#/components/schemas/Category"
          type: array
        contacts:
          description: The contacts for the given law, returned only if the parameter poc
            is true
          items:
            $ref: "#/components/schemas/Poc"
          type: array
        enacted_date:
          description: The date the enacting legislation (if applicable) was signed into
            law.
          format: date-time
          type: string
        expired_date:
          description: The date the incentive/law/regulation is set to end.
          format: date-time
          type: string
        id:
          description: A unique identifier for this specific incentive/law/regulation.
          type: integer
        is_recent:
          description: The true or false value used to distinguish between recent federal
            executive actions (TRUE) and active incentives/laws/regulations
            (FALSE).
          type: boolean
        plaintext:
          description: Description of the incentive/law/regulation, including applicable
            legislative references, in <a
            href="https://guides.github.com/features/mastering-markdown/">markdown
            formatting</a>
          type: string
        recent_update_or_new:
          description: An indicator if the last significant update was an update or the
            laws creation.
          type: string
        references:
          description: The URL associated with any bill or legislative reference included
            in the description.
          items:
            $ref: "#/components/schemas/LawReference"
          type: array
        repealed_date:
          description: The date legislation is enacted or a rulemaking is finalized to
            repeal the incentive/law/regulation.
          format: date-time
          type: string
        seq_num:
          description: The numerical value assigned to a description to show the order in
            which it is displayed online within a jurisdiction (state).
          type: integer
        significant_update_date:
          description: When the last significant update to the law was made.
          format: date-time
          type: string
        state:
          description: The state in which the incentive/law/regulation was enacted and is
            active.
          type: string
        text:
          description: Description of the incentive/law/regulation, including applicable
            legislative references, html formated.
          type: string
        title:
          description: The brief title assigned to the incentive/law/regulation description.
          type: string
        topics:
          description: "For local incentive/regulation descriptions, the category that the
            incentive/regulation falls under, described below: Infrastructure
            Requirements, Vehicle Purchase and Infrastructure Development
            Incentives, Fuel Use Incentives, Parking Incentives, Technical
            Assistance, Vehicle Acquisition Requirements, Promotion Initiatives,
            Idle Reduction Requirements, Renewable Fuels Mandates and Standards"
          items:
            $ref: "#/components/schemas/LawTopics"
          type: array
        type:
          description: "The category that the incentive/law/regulation falls under,
            described below: -State Incentives, -Laws and Regulations,
            -Utility/Private Incentives"
          type: string
        types:
          description: The types that apply to this law
          items:
            $ref: "#/components/schemas/LawType"
          type: array
      required:
        - id
        - state
        - title
        - text
        - plaintext
        - type
        - categories
        - types
        - references
        - topics
    LawReference:
      description: The URL associated with any bill or legislative reference included in
        the description.
      properties:
        description:
          description: The context of the reference
          type: string
        url:
          description: The url linking to the reference.
          type: string
      required:
        - description
        - url
    LawResult:
      properties:
        inputs:
          $ref: "#/components/schemas/Inputs"
        metadata:
          $ref: "#/components/schemas/Metadata"
        result:
          $ref: "#/components/schemas/Law"
      required:
        - metadata
        - inputs
        - result
    LawTopics:
      description: "For local incentive/regulation descriptions, the category that the
        incentive/regulation falls under, described below: Infrastructure
        Requirements, Vehicle Purchase and Infrastructure Development
        Incentives, Fuel Use Incentives, Parking Incentives, Technical
        Assistance, Vehicle Acquisition Requirements, Promotion Initiatives,
        Idle Reduction Requirements, Renewable Fuels Mandates and Standards"
      properties:
        id:
          description: The database id of the law topic
          type: integer
        sort_order:
          description: The sort order of the law topic
          type: integer
        title:
          description: The name of the law topic
          type: string
      required:
        - id
        - title
        - sort_order
    LawType:
      description: "The category that the incentive/law/regulation falls under, described
        below: -State Incentives, -Laws and Regulations, -Utility/Private
        Incentives"
      properties:
        code:
          description: The code used to identify the law type
          type: string
        id:
          description: The id of the law type
          type: integer
        title:
          description: The name of the law type
          type: string
      required:
        - id
        - title
        - code
    LawsResponse:
      properties:
        inputs:
          $ref: "#/components/schemas/Inputs"
        metadata:
          $ref: "#/components/schemas/Metadata"
        result:
          description: The array of laws returned
          items:
            $ref: "#/components/schemas/Law"
          type: array
      required:
        - metadata
        - inputs
        - result
    Metadata:
      description: The identifying metadata.
      properties:
        count:
          description: If the request returns an array of results, this is the number of
            results returned in the array
          type: integer
        version:
          description: This is the version of the api
          type: string
      required:
        - version
    Poc:
      properties:
        agency:
          description: The agency that the contact represents
          type: string
        email:
          description: The contacts email address
          type: string
        fax:
          description: The contacts fax number
          type: string
        name:
          description: The name of the contact
          type: string
        state:
          description: The state in which the contact is based ('US' for Federal laws and
            'DC' for the District of Columbia)
          type: string
        telephone:
          description: The contacts phone number
          type: string
        title:
          description: The job title of the contact
          type: string
        web_page:
          description: The contacts webpage
          type: string
      required:
        - name
        - state
    PocResults:
      properties:
        inputs:
          $ref: "#/components/schemas/Inputs"
        metadata:
          $ref: "#/components/schemas/Metadata"
        result:
          description: The array of Points of Contacts for the state requested
          items:
            $ref: "#/components/schemas/Poc"
          type: array
      required:
        - metadata
        - inputs
        - result
