openapi: 3.0.0
info:
  description: "The Buildings Database is a shared resource for the building industry. The
    Database, developed by the U.S. Department of Energy and the National
    Renewable Energy Laboratory (NREL), is a unique central repository of
    in-depth information and data on high-performance, green building projects
    across the United States and abroad.  "
  title: High Performance Building Database
  version: "1.0"
  x-apisguru-categories:
    - open_data
  x-logo:
    backgroundColor: "#0079C5"
    url: https://twitter.com/NRELdev/profile_image?size=original
  x-origin:
    - converter:
        url: https://github.com/lucybot/api-spec-converter
        version: 2.0.1
      format: swagger
      url: http://developer.nrel.gov/docs/buildings/building-case-studies/api-docs.json
      version: "1.2"
  x-providerName: nrel.gov
  x-serviceName: building-case-studies
security:
  - api_key: []
tags:
  - description: API endpoints related to buildings.
    name: project
paths:
  "/project.{output_format}":
    get:
      operationId: project
      parameters:
        - description: Response Format
          in: path
          name: output_format
          required: true
          schema:
            type: string
            enum:
              - json
              - xml
            default: xml
        - description: Search Text
          in: query
          name: search
          required: false
          schema:
            type: string
        - description: Portal ID
          in: query
          name: portal
          required: false
          schema:
            type: string
        - description: Page Number
          in: query
          name: page
          required: false
          schema:
            type: integer
        - description: City
          in: query
          name: city
          required: false
          schema:
            type: string
        - description: "State or Province (ex: 'CO', 'AZ')"
          in: query
          name: province
          required: false
          schema:
            type: string
        - description: "Climate Region.  Use integer from mapping (256: '1A: Very Hot -
            Humid', 257: '1B: Very Hot - Dry', 258: '2A: Hot - Humid', 259: '2B:
            Hot - Dry', 260: '3A: Warm - Humid', 261: '3B: Warm - Dry', 262:
            '3C: Warm - Marine', 263: '4A: Mixed - Humid', 264: '4B: Mixed -
            Dry', 265: '4C: Mixed - Marine', 266: '5A: Cool - Humid', 267: '5B:
            Cool - Dry', 268: '5C: Cool - Marine', 269: '6A: Cold - Humid', 270:
            '6B: Cold - Dry', 271: '7: Very Cold', 272: '8: Subarctic')"
          in: query
          name: region
          required: false
          schema:
            type: string
      responses:
        "200":
          description: No response was specified
      summary: A filterable list of projects.
      tags:
        - project
  "/project/{project_id}.{output_format}":
    get:
      description: This API allows users to request metadata associated with the specific
        Document.
      operationId: document
      parameters:
        - description: Response Format
          in: path
          name: output_format
          required: true
          schema:
            type: string
            enum:
              - json
              - xml
            default: json
        - description: Project ID
          in: path
          name: project_id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: No response was specified
      summary: Project Details
      tags:
        - project
servers:
  - url: https://developer.nrel.gov/api/building-case-studies
components:
  securitySchemes:
    api_key:
      description: API Key
      in: query
      name: api_key
      type: apiKey
