openapi: 3.0.0
info:
  contact:
    email: hello@poemist.com
    name: Poemist Team
    url: https://www.poemist.com
  title: Poemist
  version: "1.0"
  x-apisguru-categories:
    - text
  x-logo:
    url: https://www.poemist.com/images/logo.png
  x-origin:
    - format: swagger
      url: https://www.poemist.com/api-docs.json
      version: "2.0"
  x-providerName: poemist.com
paths:
  /randompoems:
    get:
      operationId: randompoems
      responses:
        "200":
          description: Random poems to be returned
servers:
  - url: https://www.poemist.com/api/v1/
