openapi: 3.0.0
info:
  contact:
    email: info@quicksold.co.uk
    name: Greg Eke
    url: https://quicksold.co.uk
    x-twitter: QuicksoldCoUk
  description: Useful utility APIs.
  license:
    name: License
    url: https://quicksold.co.uk/terms-and-conditions
  termsOfService: https://quicksold.co.uk/terms-and-conditions
  title: Quicksold
  version: "1.0"
  x-apisguru-categories:
    - location
  x-logo:
    url: https://twitter.com/QuicksoldCoUk/profile_image?size=original
  x-origin:
    - format: swagger
      url: https://quicksold.co.uk/v2/api-docs
      version: "2.0"
  x-providerName: quicksold.co.uk
  x-serviceName: location
tags:
  - description: Api Controller
    name: WGS84 to OSGB36
paths:
  "/wgs84ToOsgb36/{latitude}/{longitude}":
    get:
      deprecated: false
      description: Convert a WGS84 latitude and longitude to OSGB36 easting and northing
        (British National Grid).
      operationId: landing2UsingGET
      parameters:
        - description: latitude
          in: path
          name: latitude
          required: true
          schema:
            type: string
        - description: longitude
          in: path
          name: longitude
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
      summary: WGS84 to OSGB36
      tags:
        - WGS84 to OSGB36
servers:
  - url: https://quicksold.co.uk/
components:
  schemas:
    ApiResponse:
      properties:
        data:
          type: object
        error:
          type: string
        errors:
          type: object
        message:
          type: string
        path:
          type: string
        status:
          format: int32
          type: integer
        timestamp:
          format: int64
          type: integer
      title: ApiResponse
      type: object
