openapi: 3.0.0
info:
  contact:
    email: mike.ralphson@gmail.com
    name: Mike Ralphson
    url: https://github.com/mermade/mashery2openapi
  description: Test our API services using I/O Docs.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Rotten Tomatoes
  version: "1.0"
  x-apisguru-categories:
    - media
  x-logo:
    url: https://twitter.com/RottenTomatoes/profile_image?size=original
  x-mashery-id: "1217"
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Mermade/openapi_specifications/master/mashery/api.rottentomatoes.com/Rotten-Tomatoes/1.0/swagger.json
      version: "2.0"
  x-providerName: rottentomatoes.com
  x-unofficialSpec: true
externalDocs:
  description: You can also view our written documentation.
  url: http://developer.rottentomatoes.com/io-docs/docs
security:
  - key: []
tags:
  - name: Movie Lists
  - name: DVD Lists
  - name: Detailed Info
  - name: Search
  - name: Top Level Lists
paths:
  /lists.json:
    get:
      operationId: ListsDirectoryTopLevelLists
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "403":
          description: Forbidden
      summary: ""
      tags:
        - Top Level Lists
  /lists/dvds.json:
    get:
      operationId: DVDListsDirectoryTopLevelLists
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "403":
          description: Forbidden
      summary: ""
      tags:
        - Top Level Lists
  /lists/dvds/current_releases.json:
    get:
      operationId: CurrentReleaseDVDsDVDLists
      parameters:
        - description: The amount of new release dvds to show per page
          in: query
          name: page_limit
          required: false
          schema:
            type: string
            default: "16"
        - description: The selected page of current DVD releases
          in: query
          name: page
          required: false
          schema:
            type: string
            default: "1"
        - description: Provides localized data for the selected country (ISO 3166-1
            alpha-2) if available. Otherwise, returns US data.
          in: query
          name: country
          required: false
          schema:
            type: string
            default: us
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "403":
          description: Forbidden
      summary: ""
      tags:
        - DVD Lists
  /lists/dvds/new_releases.json:
    get:
      operationId: NewReleaseDVDsDVDLists
      parameters:
        - description: The amount of new release dvds to show per page
          in: query
          name: page_limit
          required: false
          schema:
            type: string
            default: "16"
        - description: The selected page of new release DVDs
          in: query
          name: page
          required: false
          schema:
            type: string
            default: "1"
        - description: Provides localized data for the selected country (ISO 3166-1
            alpha-2) if available. Otherwise, returns US data.
          in: query
          name: country
          required: false
          schema:
            type: string
            default: us
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "403":
          description: Forbidden
      summary: ""
      tags:
        - DVD Lists
  /lists/dvds/top_rentals.json:
    get:
      operationId: TopRentalsDVDLists
      parameters:
        - description: Limits the number of top rentals returned
          in: query
          name: limit
          required: false
          schema:
            type: string
            default: "10"
        - description: Provides localized data for the selected country (ISO 3166-1
            alpha-2) if available. Otherwise, returns US data.
          in: query
          name: country
          required: false
          schema:
            type: string
            default: us
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "403":
          description: Forbidden
      summary: ""
      tags:
        - DVD Lists
  /lists/dvds/upcoming.json:
    get:
      operationId: UpcomingDVDsDVDLists
      parameters:
        - description: The amount of upcoming dvds to show per page
          in: query
          name: page_limit
          required: false
          schema:
            type: string
            default: "16"
        - description: The selected page of upcoming DVDs
          in: query
          name: page
          required: false
          schema:
            type: string
            default: "1"
        - description: Provides localized data for the selected country (ISO 3166-1
            alpha-2) if available. Otherwise, returns US data.
          in: query
          name: country
          required: false
          schema:
            type: string
            default: us
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "403":
          description: Forbidden
      summary: ""
      tags:
        - DVD Lists
  /lists/movies.json:
    get:
      operationId: MovieListsDirectoryTopLevelLists
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "403":
          description: Forbidden
      summary: ""
      tags:
        - Top Level Lists
  /lists/movies/box_office.json:
    get:
      operationId: BoxOfficeMovieLists
      parameters:
        - description: Limits the number of movies returned
          in: query
          name: limit
          required: false
          schema:
            type: string
            default: "16"
        - description: Provides localized data for the selected country (ISO 3166-1
            alpha-2) if available. Otherwise, returns US data.
          in: query
          name: country
          required: false
          schema:
            type: string
            default: us
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "403":
          description: Forbidden
      summary: ""
      tags:
        - Movie Lists
  /lists/movies/in_theaters.json:
    get:
      operationId: InTheatersMovieLists
      parameters:
        - description: The amount of movies in theaters to show per page
          in: query
          name: page_limit
          required: false
          schema:
            type: string
            default: "16"
        - description: The selected page of in theaters movies
          in: query
          name: page
          required: false
          schema:
            type: string
            default: "1"
        - description: Provides localized data for the selected country (ISO 3166-1
            alpha-2) if available. Otherwise, returns US data.
          in: query
          name: country
          required: false
          schema:
            type: string
            default: us
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "403":
          description: Forbidden
      summary: ""
      tags:
        - Movie Lists
  /lists/movies/opening.json:
    get:
      operationId: OpeningMoviesMovieLists
      parameters:
        - description: Limits the number of opening movies returned
          in: query
          name: limit
          required: false
          schema:
            type: string
            default: "16"
        - description: Provides localized data for the selected country (ISO 3166-1
            alpha-2) if available. Otherwise, returns US data.
          in: query
          name: country
          required: false
          schema:
            type: string
            default: us
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "403":
          description: Forbidden
      summary: ""
      tags:
        - Movie Lists
  /lists/movies/upcoming.json:
    get:
      operationId: UpcomingMoviesMovieLists
      parameters:
        - description: The amount of upcoming movies to show per page
          in: query
          name: page_limit
          required: false
          schema:
            type: string
            default: "16"
        - description: The selected page of upcoming movies
          in: query
          name: page
          required: false
          schema:
            type: string
            default: "1"
        - description: Provides localized data for the selected country (ISO 3166-1
            alpha-2) if available. Otherwise, returns US data.
          in: query
          name: country
          required: false
          schema:
            type: string
            default: us
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "403":
          description: Forbidden
      summary: ""
      tags:
        - Movie Lists
  /movie_alias.json:
    get:
      operationId: MoviesAliasDetailedInfo
      parameters:
        - description: Movie ID. You can use the movies search endpoint or peruse the lists
            of movies/dvds to get the Movie ID
          in: query
          name: id
          required: false
          schema:
            type: string
            default: 31381
        - description: Only supports imdb lookup at this time
          in: query
          name: type
          required: false
          schema:
            type: string
            default: imdb
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "403":
          description: Forbidden
      summary: ""
      tags:
        - Detailed Info
  /movies.json:
    get:
      operationId: MoviesSearchSearch
      parameters:
        - description: The plain text search query to search for a movie. Remember to URI
            encode this!
          in: query
          name: q
          required: false
          schema:
            type: string
        - description: The amount of movie search results to show per page
          in: query
          name: page_limit
          required: false
          schema:
            type: string
            default: "10"
        - description: The selected page of movie search results
          in: query
          name: page
          required: false
          schema:
            type: string
            default: "1"
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "403":
          description: Forbidden
      summary: ""
      tags:
        - Search
  "/movies/{id}.json":
    get:
      operationId: MoviesInfoDetailedInfo
      parameters:
        - description: Movie ID. You can use the movies search endpoint or peruse the lists
            of movies/dvds to get the Movie ID
          in: path
          name: id
          required: true
          schema:
            type: string
            default: "770672122"
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "403":
          description: Forbidden
      summary: ""
      tags:
        - Detailed Info
  "/movies/{id}/cast.json":
    get:
      operationId: CastInfoDetailedInfo
      parameters:
        - description: Movie ID. You can use the movies search endpoint or peruse the lists
            of movies/dvds to get the Movie ID
          in: path
          name: id
          required: true
          schema:
            type: string
            default: "770672122"
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "403":
          description: Forbidden
      summary: ""
      tags:
        - Detailed Info
  "/movies/{id}/clips.json":
    get:
      operationId: MovieClipsDetailedInfo
      parameters:
        - description: Movie ID. You can use the movies search endpoint or peruse the lists
            of movies/dvds to get the Movie ID
          in: path
          name: id
          required: true
          schema:
            type: string
            default: "770672122"
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "403":
          description: Forbidden
      summary: ""
      tags:
        - Detailed Info
  "/movies/{id}/reviews.json":
    get:
      operationId: MoviesReviewsDetailedInfo
      parameters:
        - description: Movie ID. You can use the movies search endpoint or peruse the lists
            of movies/dvds to get the Movie ID
          in: path
          name: id
          required: true
          schema:
            type: string
            default: "770672122"
        - description: "3 different review types are possible: 'all', 'top_critic' and
            'dvd'. 'top_critic' shows all the Rotten Tomatoes designated top
            critics. 'dvd' pulls the reviews given on the DVD of the movie.
            'all' as the name implies retrieves all reviews."
          in: query
          name: review_type
          required: false
          schema:
            type: string
            default: top_critic
        - description: The number of reviews to show per page
          in: query
          name: page_limit
          required: false
          schema:
            type: string
            default: "20"
        - description: The selected page of reviews
          in: query
          name: page
          required: false
          schema:
            type: string
            default: "1"
        - description: Provides localized data for the selected country (ISO 3166-1
            alpha-2) if available. Otherwise, returns US data.
          in: query
          name: country
          required: false
          schema:
            type: string
            default: us
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "403":
          description: Forbidden
      summary: ""
      tags:
        - Detailed Info
  "/movies/{id}/similar.json":
    get:
      operationId: MoviesSimilarDetailedInfo
      parameters:
        - description: Movie ID. You can use the movies search endpoint or peruse the lists
            of movies/dvds to get the Movie ID
          in: path
          name: id
          required: true
          schema:
            type: string
            default: "770672122"
        - description: Limit the number of similar movies to show
          in: query
          name: limit
          required: false
          schema:
            type: string
            default: "5"
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "403":
          description: Forbidden
      summary: ""
      tags:
        - Detailed Info
servers:
  - url: http://api.rottentomatoes.com/api/public/v1.0
components:
  securitySchemes:
    key:
      in: query
      name: apikey
      type: apiKey
