openapi: 3.0.0
info:
  contact:
    email: contact@tinyuid.com
    name: TinyUID
    url: https://tinyuid.com/feedback
  description: Paste a Long URL link to shorten it
  title: TinyUID.com
  version: 1.0.0
  x-apisguru-categories:
    - developer_tools
  x-origin:
    - format: swagger
      url: https://tinyuid.com/tinyuid-swagger.yaml
      version: "2.0"
  x-providerName: tinyuid.com
externalDocs:
  url: https://tinyuid.com/docs
paths:
  /v1/shorten:
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                url:
                  description: Link
                  type: string
                  format: url
              required:
                - url
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                properties:
                  result_url:
                    description: Short link
                    format: url
                    type: string
                required:
                  - result_url
                type: object
      summary: Create short link
servers:
  - url: https://tinyuid.com/api/
