openapi: 3.0.0
info:
  contact:
    name: partnerapis@walmartlabs.com
    x-twitter: Walmart
  description: Please make sure you use the correct version of the APIs for your use case.
    To find out the appropriate version, go to the API Docs  drop down on the
    menu.
  title: Item
  version: 3.0.1
  x-apisguru-categories:
    - ecommerce
  x-logo:
    url: https://twitter.com/Walmart/profile_image?size=original
  x-origin:
    - format: swagger
      url: https://developer.walmart.com/v1/swaggerProxy?type=item
      version: "2.0"
  x-providerName: walmart.com
  x-serviceName: item
tags:
  - name: Version 3
  - name: Version 2
paths:
  /v2/feeds:
    get:
      description: You can display the status of an item within a feed. Use the feed ID
        returned from the upload an item API.
      operationId: v2getFeedItemStatus
      parameters:
        - description: The feed ID.
          in: query
          name: feedId
          required: false
          schema:
            type: string
        - description: Includes the status details for each item in the feed. Do not set
            this parameter to true as discrepancies may appear between the
            header and the item details (the item details may be incorrect).
            Instead, use the Get a feedItems status.
          in: query
          name: includeDetails
          required: false
          schema:
            type: string
            default: "false"
        - description: The object response to start with, where 0 is the first entity that
            can be requested. It can only be used when includeDetails is set to
            true.
          in: query
          name: offset
          required: false
          schema:
            type: string
            default: "0"
        - description: The number of items to be returned. Cannot be more than 50 items.
            Use it only when the includeDetails is set to true.
          in: query
          name: limit
          required: false
          schema:
            type: string
            default: "50"
        - description: Channel Type
          in: header
          name: WM_CONSUMER.CHANNEL.TYPE
          required: true
          schema:
            type: string
            enum:
              - SWAGGER_CHANNEL_TYPE
            default: SWAGGER_CHANNEL_TYPE
        - description: Your Consumer ID
          in: header
          name: WM_CONSUMER.ID
          required: true
          schema:
            type: string
        - description: Epoch timestamp
          in: header
          name: WM_SEC.TIMESTAMP
          required: true
          schema:
            type: string
            default: Auto populated
        - description: Authentication signature
          in: header
          name: WM_SEC.AUTH_SIGNATURE
          required: true
          schema:
            type: string
            default: Auto populated
        - description: The Service name
          in: header
          name: WM_SVC.NAME
          required: true
          schema:
            type: string
            default: Walmart Marketplace
        - description: A Transaction ID
          in: header
          name: WM_QOS.CORRELATION_ID
          required: true
          schema:
            type: string
            default: 123456abcdef
      responses:
        default:
          description: successful operation
      summary: Get status of an item feed
      tags:
        - Version 2
    post:
      description: You can upload an item feed. If the feed successfully processed, it
        returns a feed ID. Use the returned feed ID to retrieve a feed status.
        You need your Consumer ID and the Private Key to upload an item.
      operationId: v2doPostMultiPart
      parameters:
        - description: Feed Type
          in: query
          name: feedType
          required: false
          schema:
            type: string
            enum:
              - item
            default: item
        - description: Channel Type
          in: header
          name: WM_CONSUMER.CHANNEL.TYPE
          required: true
          schema:
            type: string
            enum:
              - SWAGGER_CHANNEL_TYPE
            default: SWAGGER_CHANNEL_TYPE
        - description: Your Consumer ID
          in: header
          name: WM_CONSUMER.ID
          required: true
          schema:
            type: string
        - description: Epoch timestamp
          in: header
          name: WM_SEC.TIMESTAMP
          required: true
          schema:
            type: string
            default: Auto populated
        - description: Authentication signature
          in: header
          name: WM_SEC.AUTH_SIGNATURE
          required: true
          schema:
            type: string
            default: Auto populated
        - description: The Service name
          in: header
          name: WM_SVC.NAME
          required: true
          schema:
            type: string
            default: Walmart Marketplace
        - description: A Transaction ID
          in: header
          name: WM_QOS.CORRELATION_ID
          required: true
          schema:
            type: string
            default: 123456abcdef
      requestBody:
        $ref: "#/components/requestBodies/v2doPostMultiPart"
      responses:
        default:
          description: successful operation
      summary: Upload an item feed
      tags:
        - Version 2
  "/v2/feeds/{feedId}":
    get:
      description: You can display the status of all items within a feed. Use the feed ID
        returned from the upload an item API.
      operationId: v2getAllItemsStatus
      parameters:
        - description: The feed ID
          in: path
          name: feedId
          required: true
          schema:
            type: string
        - description: Includes details of each entity in the feed. Do not set this
            parameter to true.
          in: query
          name: includeDetails
          required: false
          schema:
            type: string
            default: "false"
        - description: The object response to start with, where 0 is the first entity that
            can be requested. It can only be used when includeDetails is set to
            true.
          in: query
          name: offset
          required: false
          schema:
            type: string
            default: "0"
        - description: The number of entities to be returned. It cannot be more than 50
            entities. Use it only when the includeDetails is set to true.
          in: query
          name: limit
          required: false
          schema:
            type: string
            default: "50"
        - description: Channel Type
          in: header
          name: WM_CONSUMER.CHANNEL.TYPE
          required: true
          schema:
            type: string
            enum:
              - SWAGGER_CHANNEL_TYPE
            default: SWAGGER_CHANNEL_TYPE
        - description: Your Consumer ID
          in: header
          name: WM_CONSUMER.ID
          required: true
          schema:
            type: string
        - description: Epoch timestamp
          in: header
          name: WM_SEC.TIMESTAMP
          required: true
          schema:
            type: string
            default: Auto populated
        - description: Authentication signature
          in: header
          name: WM_SEC.AUTH_SIGNATURE
          required: true
          schema:
            type: string
            default: Auto populated
        - description: The Service name
          in: header
          name: WM_SVC.NAME
          required: true
          schema:
            type: string
            default: Walmart Marketplace
        - description: A Transaction ID
          in: header
          name: WM_QOS.CORRELATION_ID
          required: true
          schema:
            type: string
            default: 123456abcdef
      responses:
        default:
          description: successful operation
      summary: Get status of an item within a feed
      tags:
        - Version 2
  /v3/feeds:
    get:
      description: You can display the status of an item within a feed. Use the feed ID
        returned from the upload an item API.
      operationId: v3getFeedItemStatus
      parameters:
        - description: The feed ID.
          in: query
          name: feedId
          required: false
          schema:
            type: string
        - description: Includes the status details for each item in the feed. Do not set
            this parameter to true as discrepancies may appear between the
            header and the item details (the item details may be incorrect).
            Instead, use the Get a feedItems status.
          in: query
          name: includeDetails
          required: false
          schema:
            type: string
            default: "false"
        - description: The object response to start with, where 0 is the first entity that
            can be requested. It can only be used when includeDetails is set to
            true.
          in: query
          name: offset
          required: false
          schema:
            type: string
            default: "0"
        - description: The number of items to be returned. Cannot be more than 50 items.
            Use it only when the includeDetails is set to true.
          in: query
          name: limit
          required: false
          schema:
            type: string
            default: "50"
        - description: Channel Type
          in: header
          name: WM_CONSUMER.CHANNEL.TYPE
          required: true
          schema:
            type: string
            enum:
              - SWAGGER_CHANNEL_TYPE
            default: SWAGGER_CHANNEL_TYPE
        - description: Your Consumer ID
          in: header
          name: WM_CONSUMER.ID
          required: true
          schema:
            type: string
        - description: Epoch timestamp
          in: header
          name: WM_SEC.TIMESTAMP
          required: true
          schema:
            type: string
            default: Auto populated
        - description: Authentication signature
          in: header
          name: WM_SEC.AUTH_SIGNATURE
          required: true
          schema:
            type: string
            default: Auto populated
        - description: The Service name
          in: header
          name: WM_SVC.NAME
          required: true
          schema:
            type: string
            default: Walmart Marketplace
        - description: A Transaction ID
          in: header
          name: WM_QOS.CORRELATION_ID
          required: true
          schema:
            type: string
            default: 123456abcdef
      responses:
        default:
          description: successful operation
      summary: Get status of an item feed
      tags:
        - Version 3
    post:
      description: You can upload an item feed. If the feed successfully processed, it
        returns a feed ID. Use the returned feed ID to retrieve a feed status.
        You need your Consumer ID and the Private Key to upload an item.
      operationId: v3doPostMultiPart
      parameters:
        - description: Feed Type
          in: query
          name: feedType
          required: false
          schema:
            type: string
            enum:
              - item
              - SUPPLIER_FULL_ITEM
              - CONTENT_PRODUCT
            default: item
        - description: Channel Type
          in: header
          name: WM_CONSUMER.CHANNEL.TYPE
          required: true
          schema:
            type: string
            enum:
              - SWAGGER_CHANNEL_TYPE
            default: SWAGGER_CHANNEL_TYPE
        - description: Your Consumer ID
          in: header
          name: WM_CONSUMER.ID
          required: true
          schema:
            type: string
        - description: Epoch timestamp
          in: header
          name: WM_SEC.TIMESTAMP
          required: true
          schema:
            type: string
            default: Auto populated
        - description: Authentication signature
          in: header
          name: WM_SEC.AUTH_SIGNATURE
          required: true
          schema:
            type: string
            default: Auto populated
        - description: The Service name
          in: header
          name: WM_SVC.NAME
          required: true
          schema:
            type: string
            default: Walmart Marketplace
        - description: A Transaction ID
          in: header
          name: WM_QOS.CORRELATION_ID
          required: true
          schema:
            type: string
            default: 123456abcdef
      requestBody:
        $ref: "#/components/requestBodies/v2doPostMultiPart"
      responses:
        default:
          description: successful operation
      summary: Upload an item feed
      tags:
        - Version 3
  "/v3/feeds/{feedId}":
    get:
      description: You can display the status of all items within a feed. Use the feed ID
        returned from the upload an item API.
      operationId: v3getAllItemsStatus
      parameters:
        - description: The feed ID
          in: path
          name: feedId
          required: true
          schema:
            type: string
        - description: Includes details of each entity in the feed. Do not set this
            parameter to true.
          in: query
          name: includeDetails
          required: false
          schema:
            type: string
            default: "false"
        - description: The object response to start with, where 0 is the first entity that
            can be requested. It can only be used when includeDetails is set to
            true.
          in: query
          name: offset
          required: false
          schema:
            type: string
            default: "0"
        - description: The number of entities to be returned. It cannot be more than 50
            entities. Use it only when the includeDetails is set to true.
          in: query
          name: limit
          required: false
          schema:
            type: string
            default: "50"
        - description: Channel Type
          in: header
          name: WM_CONSUMER.CHANNEL.TYPE
          required: true
          schema:
            type: string
            enum:
              - SWAGGER_CHANNEL_TYPE
            default: SWAGGER_CHANNEL_TYPE
        - description: Your Consumer ID
          in: header
          name: WM_CONSUMER.ID
          required: true
          schema:
            type: string
        - description: Epoch timestamp
          in: header
          name: WM_SEC.TIMESTAMP
          required: true
          schema:
            type: string
            default: Auto populated
        - description: Authentication signature
          in: header
          name: WM_SEC.AUTH_SIGNATURE
          required: true
          schema:
            type: string
            default: Auto populated
        - description: The Service name
          in: header
          name: WM_SVC.NAME
          required: true
          schema:
            type: string
            default: Walmart Marketplace
        - description: A Transaction ID
          in: header
          name: WM_QOS.CORRELATION_ID
          required: true
          schema:
            type: string
            default: 123456abcdef
      responses:
        default:
          description: successful operation
      summary: Get status of an item within a feed
      tags:
        - Version 3
servers:
  - url: https://developer.walmart.com/proxy/item-api-doc-app/rest
components:
  requestBodies:
    v2doPostMultiPart:
      content:
        multipart/form-data:
          schema:
            type: object
            properties:
              file:
                description: Feed File to upload
                type: string
                format: binary
            required:
              - file
