openapi: 3.0.0
info:
  description: The OpenAPI documentation for the RESTful interface of the
    Carl-Maria-von-Weber-Gesamtausgabe. <br/> (No registration, authentication,
    or API key is required) <br/> For feedback or requests about this API please
    contact stadler@weber-gesamtausgabe.de or start the discussion at
    https://github.com/Edirom/WeGA-WebApp
  title: WeGA
  version: 1.0.0
  x-apisguru-categories:
    - open_data
  x-logo:
    backgroundColor: "#FFFFFF"
    url: https://web.archive.org/web/20180313153846im_/https://weber-gesamtausgabe.de/resources/img/logo_weber.png
  x-origin:
    - format: swagger
      url: https://weber-gesamtausgabe.de/api/v1/swagger.json
      version: "2.0"
  x-providerName: weber-gesamtausgabe.de
tags:
  - description: Access to the documents of the WeGA digital edition
    name: Documents
  - description: Access to correspondence related information from the WeGA digital edition
    name: Correspondence
  - description: Access to encoding features
    name: Code Samples
  - description: Access to application settings
    name: Application
paths:
  /application/newID:
    get:
      description: ""
      parameters:
        - $ref: "#/components/parameters/docTypeRequiredParam"
      responses:
        "200":
          description: A single object with a fresh WeGA ID
          content:
            application/json:
              schema:
                properties:
                  docID:
                    description: The WeGA ID
                    pattern: ^A[A-F0-9]{6}$
                    type: string
                  docType:
                    description: The WeGA document type
                    type: string
                type: object
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      summary: Create a new WeGA ID
      tags:
        - Application
  /application/status:
    get:
      description: ""
      responses:
        "200":
          description: A single object with status information
          content:
            application/json:
              schema:
                properties:
                  deployment:
                    description: The datetime of the deployment of the WeGA-WebApp
                    format: date-time
                    type: string
                  status:
                    description: Status (healthy|unhealthy) of the currently running
                      WeGA-WebApp
                    enum:
                      - healthy
                      - unhealthy
                    type: string
                  svnRevision:
                    description: The Subversion revision of the currently installed
                      WeGA-data
                    type: integer
                  version:
                    pattern: ^\d+\.\d+\.\d+$
                    type: string
                type: object
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      summary: Get status information about the running WeGA-WebApp
      tags:
        - Application
  "/code/findByElement/{element}":
    get:
      description: ""
      parameters:
        - description: The XML element to search for
          in: path
          name: element
          required: true
          schema:
            type: string
        - description: The element namespace. Defaults to the TEI namespace
          in: query
          name: namespace
          required: false
          schema:
            type: string
            default: http://www.tei-c.org/ns/1.0
        - $ref: "#/components/parameters/docTypeParam"
        - $ref: "#/components/parameters/offsetParam"
        - $ref: "#/components/parameters/limitParam"
      responses:
        "200":
          description: An array of documents
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/CodeSample"
                type: array
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      summary: Finds code samples by XML element
      tags:
        - Code Samples
  /documents:
    get:
      description: >
        The Documents endpoint returns a list of all documents from the WeGA
        digital edition.
      parameters:
        - $ref: "#/components/parameters/docTypeParam"
        - $ref: "#/components/parameters/offsetParam"
        - $ref: "#/components/parameters/limitParam"
      responses:
        "200":
          description: An array of documents
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Document"
                type: array
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      summary: Lists all documents
      tags:
        - Documents
  "/documents/findByAuthor/{authorID}":
    get:
      description: >
        This endpoint returns a list of documents by a given author – optionally
        filtered by document type 
      parameters:
        - description: >
            The author ID to search for. Accepted ID formats are WeGA, e.g.
            A002068 or http://weber-gesamtausgabe.de/A002068, VIAF, e.g.
            http://viaf.org/viaf/310642461, or  GND, e.g.
            http://d-nb.info/gnd/118629662
          in: path
          name: authorID
          required: true
          schema:
            type: string
            default: A002068
        - $ref: "#/components/parameters/docTypeParam"
        - $ref: "#/components/parameters/offsetParam"
        - $ref: "#/components/parameters/limitParam"
      responses:
        "200":
          description: An array of documents
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Document"
                type: array
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      summary: Finds documents by author
      tags:
        - Documents
  /documents/findByDate:
    get:
      description: >
        This endpoint returns a list of documents related to the given date –
        optionally filtered by document type. 
      parameters:
        - description: The min date to search for
          in: query
          name: fromDate
          required: true
          schema:
            type: string
            format: date
            default: 1786-11-18
        - description: The max date to search for
          in: query
          name: toDate
          required: false
          schema:
            type: string
            format: date
        - $ref: "#/components/parameters/docTypeParam"
        - $ref: "#/components/parameters/offsetParam"
        - $ref: "#/components/parameters/limitParam"
      responses:
        "200":
          description: An array of documents
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Document"
                type: array
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      summary: Finds documents by date
      tags:
        - Documents
  "/documents/findByMention/{docID}":
    get:
      description: >
        This endpoint returns a list of documents that reference a particular
        docID – optionally filtered by document type. 
      parameters:
        - description: >
            The document ID that is to be mentioned. Accepted ID formats are
            WeGA, e.g. A002068 or http://weber-gesamtausgabe.de/A002068, VIAF,
            e.g. http://viaf.org/viaf/310642461, or  GND, e.g.
            http://d-nb.info/gnd/118629662
          in: path
          name: docID
          required: true
          schema:
            type: string
            default: A002068
        - $ref: "#/components/parameters/docTypeParam"
        - $ref: "#/components/parameters/offsetParam"
        - $ref: "#/components/parameters/limitParam"
      responses:
        "200":
          description: An array of documents
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Document"
                type: array
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      summary: Finds documents by reference
      tags:
        - Documents
  "/documents/{docID}":
    get:
      description: >
        This endpoint returns documents, indicated by an ID.
         Accepted ID formats are WeGA, e.g. A002068 or http://weber-gesamtausgabe.de/A002068, VIAF, e.g. http://viaf.org/viaf/310642461, or  GND, e.g. http://d-nb.info/gnd/118629662
      parameters:
        - description: The document identifier to search for
          in: path
          name: docID
          required: true
          schema:
            type: string
            default: A002068
      responses:
        "200":
          description: An array of documents
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Document"
                type: array
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      summary: Returns documents by ID
      tags:
        - Documents
servers:
  - url: https://weber-gesamtausgabe.de/api/v1
components:
  parameters:
    docTypeParam:
      description: The WeGA document type
      in: query
      name: docType
      style: form
      explode: false
      schema:
        type: array
        items:
          enum:
            - biblio
            - diaries
            - documents
            - letters
            - news
            - orgs
            - persons
            - places
            - thematicCommentaries
            - var
            - works
            - writings
          type: string
    docTypeRequiredParam:
      description: The WeGA document type
      in: query
      name: docType
      required: true
      style: form
      explode: false
      schema:
        type: array
        items:
          enum:
            - biblio
            - diaries
            - documents
            - letters
            - news
            - orgs
            - persons
            - places
            - thematicCommentaries
            - var
            - works
            - writings
          type: string
    fromDateParam:
      description: The earliest date
      in: query
      name: fromDate
      schema:
        type: string
        format: date
    limitParam:
      description: Number of items to retrieve (200 max)
      in: query
      name: limit
      schema:
        type: integer
        format: int32
        maximum: 200
        default: 10
    offsetParam:
      description: Position of first item to retrieve (starting from 1)
      in: query
      name: offset
      schema:
        type: integer
        format: int32
        minimum: 1
        default: 1
    toDateParam:
      description: The latest date
      in: query
      name: toDate
      schema:
        type: string
        format: date
  schemas:
    CodeSample:
      properties:
        codeSample:
          description: The code snippet
          type: string
        docID:
          description: The WeGA document identifier representing a specific document
          type: string
        uri:
          description: Unique identifier representing a specific document
          type: string
      type: object
    Document:
      properties:
        docID:
          description: The WeGA document identifier representing a specific document
          type: string
        docType:
          description: The WeGA document type
          type: string
        title:
          description: The title of the document
          type: string
        uri:
          description: Unique identifier representing a specific document
          type: string
      type: object
    Error:
      properties:
        code:
          format: int32
          type: integer
        fields:
          type: string
        message:
          type: string
      type: object
    svnHistoryPatch:
      properties:
        author:
          description: The Subversion commit author
          type: string
        dateTime:
          description: The Subversion commit dateTime
          type: string
        path:
          description: The Subversion path, starting from the repository root
          type: string
        rev:
          description: The Subversion commit revision
          type: integer
        uri:
          description: Unique identifier representing a specific document
          type: string
      type: object
      xml:
        name: patch
